{{ config(
    materialized='incremental',
    database='PROD_SILVER' if target.name == 'prod' else 'DEV_SILVER', schema='SILVER_GC_GRUPO',
    incremental_strategy='append',
    tags=['silver','integ'],
    pre_hook=[
        "{% if is_incremental() %}
        -- (tec_cod_vigencia = 1 --> 0) Marcar como no vigentes registros con match y alguna diferencia. fec_negocio - 1 día (o mismo día si coincide inicio)
        merge into {{ this }} t
        using (
            select
                NO, tec_des_empresa,
                HASH(TIMESTAMP, NO, NAME, SEARCH_NAME, NAME_2, ADDRESS, ADDRESS_2, CITY, CONTACT, PHONE_NO, TELEX_NO, DOCUMENT_SENDING_PROFILE, OUR_ACCOUNT_NO, TERRITORY_CODE, GLOBAL_DIMENSION_1_CODE, GLOBAL_DIMENSION_2_CODE, CHAIN_NAME, BUDGETED_AMOUNT, CREDIT_LIMIT_LCY, CUSTOMER_POSTING_GROUP, CURRENCY_CODE, CUSTOMER_PRICE_GROUP, LANGUAGE_CODE, STATISTICS_GROUP, PAYMENT_TERMS_CODE, FIN_CHARGE_TERMS_CODE, SALESPERSON_CODE, SHIPMENT_METHOD_CODE, SHIPPING_AGENT_CODE, PLACE_OF_EXPORT, INVOICE_DISC_CODE, CUSTOMER_DISC_GROUP, COUNTRY_REGION_CODE, COLLECTION_METHOD, AMOUNT, BLOCKED, INVOICE_COPIES, LAST_STATEMENT_NO, PRINT_STATEMENTS, BILL_TO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, PRIORITY, PAYMENT_METHOD_CODE, LAST_DATE_MODIFIED, LAST_MODIFIED_DATE_TIME, APPLICATION_METHOD, PRICES_INCLUDING_VAT, LOCATION_CODE, FAX_NO, TELEX_ANSWER_BACK, VAT_REGISTRATION_NO, COMBINE_SHIPMENTS, GEN_BUS_POSTING_GROUP, GLN, POST_CODE, COUNTY, E_MAIL, EMAIL, HOME_PAGE, REMINDER_TERMS_CODE, NO_SERIES, TAX_AREA_CODE, TAX_LIABLE, VAT_BUS_POSTING_GROUP, RESERVE, BLOCK_PAYMENT_TOLERANCE, IC_PARTNER_CODE, PREPAYMENT, PARTNER_TYPE, PREFERRED_BANK_ACCOUNT, PRIVACY_BLOCKED, PREFERRED_BANK_ACCOUNT_CODE, IMAGE, CASH_FLOW_PAYMENT_TERMS_CODE, PRIMARY_CONTACT_NO, RESPONSIBILITY_CENTER, SHIPPING_ADVICE, SHIPPING_TIME, CONTACT_TYPE, SHIPPING_AGENT_SERVICE_CODE, SERVICE_ZONE_CODE, ALLOW_LINE_DISC, BASE_CALENDAR_CODE, COPY_SELL_TO_ADDR_TO_QTE_FROM, PAYMENT_DAYS_CODE, NON_PAYMT_PERIODS_CODE, RAPPEL_REFERENCE, NOT_IN_AEAT, COPY_SELLTO_ADDR_TO_QTE_FROM, PRINT_LOTS_IN_INVOICE, ENVIAR_FACTURA_POR_E_MAIL, VALIDATE_EU_VAT_REG_NO, INSURANCE_COMPANY_CONTRACT_NO, COVERAGE_DATE, ID, FACTURA_EN_PAPEL, SECURED_AMOUNT, CURRENCY_ID, AGRUPAR_POR_DIRECCION_ENVIO, COD_CADENA, PAYMENT_TERMS_ID, ANONYMOUS, COMPANY_OWN_RISK, SHIPMENT_METHOD_ID, COD_DTO_LINEA, PROMOCIONES_POR, PAYMENT_METHOD_ID, REQUESTED_RISK_TO_CYC, TIPO_PUNTO_VERDE, TAX_AREA_ID, GRANTED_RISK_CYC, TIPO_RESIDUOS, CONTACT_ID, PUBLIC_RISK, CONTACT_GRAPH_ID, DTO_PP, COD_RUTA, NO_PROVEEDOR_RELACIONADO, RAPPEL_PERC, COMISIONES_POR, NONPAYMT_PERIODS_CODE, IBAN_CODE, FECHA_ALTA, MIG_ACCOUNT_NO, TIPOIVA, DISABLE_SEARCH_BY_NAME, USUARIO_ALTA, SHIPTO_CODE, OBSERVACIONES_ENVIO, GENERAR_SSCC_EN_PALET, COD_IDIOMA_ETIQUETAJE, TIPOFACTURACION, JEFE_DE_VENTAS, COD_IFCO, JEFE_DE_ZONA, PERIODOFACTURACION, HEREDA_COND_GRUPO, ALBARANSGI, HORARIO_ENTREGA, FECHA_CREACION, CERTIFICADOSAE, NATURALEZA_PRODUCTO, PAY_AT_CODE, CODDELISANO, E_MAIL_ENVIO_ALBARAN, E_MAIL_ORDEN_RECOGIDA, PREVISION, FORMA_PAGO_ANTIGUO, OBSERVACIONES_PICKING, PREVISION_FECHA_VENTA, ALBARAN_VALORADO, LOTE_CRECIENTE, EXCLUDE_347, IDPIRPF_IRPF_GROUP, RAPPELS_X_GRUPO, IDPGND_CALCULATION_OF_SIG, ZONA_TRANSPORTE, COD_EUROPOOL, TIPO_DTO_2, IDPVSH_VALUED_SHIPMENT, DEFAULT_SHIP_TO_CODE, TIPO_DTO_3, IF_SAE, TIPO_DTO_4, DOC_TRANSPORTE, IF_SAE_CERTIFICATION, TIPO_DTO_5, IDPCIN_CUST_CLASSIFICAT_CODE, ALBARAN_POR_LOTES, TIPO_CLIENTE, ITEM_CROSS_REFERENCE_CODE, IDPCIN_INSURANCE_CO_CREDIT_LCY, EAN128_ETIQUETA, GROUP_SHIPMENT_TYPE, IDPCIN_COMPANY_CREDIT_LCY, IDPEDI_CONFIG_TEMPLATE_NO, FACTURA_CONTADO_AUTOMATICA, SHIPMENT_FREQUENCY, AIT_BILLING_ADDRESS_CODE, PLAZO_ENTREGA, TIPO_DETALLE_FACTURA, AIT_CREATION_USER, COD_PALET_DEFECTO, DIA_DE_FACTURACION, GRUPO_DE_COMPRA, NO_LOTES_MAX_EN_EXPEDICION, AIT_CREATION_DATETIME, COD_GRUPO_DE_COMPRA, COD_CHEP, IDPSII_DEFAULT_INVOICE_TYPE, EXCLUIR_COBRO_TRAZA_PALETS, IDPSII_DEFAULT_CR_MEMO_TYPE, EXCLUDE_349, IDPSII_VAT_ID_CALCULATION, MEZCLA_PROD_EN_EMBALAJE, UMBRALPAGO, COD_EMBALAJE_DEFECTO, IRPF, IDPSII_OTHER_ID, COD_IRPF, TEC_DES_EMPRESA, NO_COPIAS, COD_ENVIO_FACTURA, NOMBRE_COMERCIAL, TEC_ID_INGESTA, TEC_TS_INGESTA, CYC, CORREO_ELECTRONICO_ADMON, EDI_REF_PEDIDO, EMPRESA_SYMMETRICAL, TEC_TS_STAGING, SUBSET_1, EDI_REF_ALBARAN, TEC_TS_INTEGRACION_B, SUBSET_2, EDI_INF_ADICIONAL_PORTUGAL, EDI_REF_FACTURA, SUBSET_3, SUBSET_4, EDI_REF_PAGO, SUBSET_5, EDI_REF_DEPARTAMENTO, SUBSET_6, EDI_CLIENTE_DEL_GRUPO_ALCAMPO, EDI_PROVEEDOR, SUBSET_7, SUBSET_8, EDI_CLIENTE_UNIDE, EDI_REF_EUROMADI, SUBSET_9, EDI_FRANCIA, SUBSET_10, EDI_CARREFOUR, EFACTURA_AUTOMATICA, EDI_CODIGO_GUVERNAMENTAL, ODS_JOB_TEMPLATE_CODE, EDI_CIP, LIQUIDITY_CODE, SHOW_EXPENSES_ON_TRANSFER, TIPO_FACTURACION, TRANSFER_EXPENSES, BANK_TRANSFER_E_MAIL, FACTURA_POR_ALBARAN, SU_CODIGO, AVERAGE_PAYMENT_PERIOD, SPLIT_SHIP_TO_ADD, CASH_FLOW_CODE, DTO_FACTURA, MOBILE_PRICE_GROUP, PACKING_LIST_REPORT_NO, COD_BANCO, EXPEDITION_LABEL_REP_NO, NOMBRE_CONTACTO_PAGOS, INV_DISCOUNT, COD_CONTACTO_PAGOS, DEFAULT_SHIP_TO_ADDRESS, RESPONSABLE_PAGOS_EMPRESA, COMMISSION_CUSTOMER_GROUP, AUTOINVOICE, AUTOINVOICE_SERIE, SECOND_SALESPERSON_CODE, BANK_ACCOUNT_TO_TRANSFER, INCOME_TAX_RETENTION_CODE, SHIPMET_WITH_PALET_RESUME, INCOME_TAX_RETENTION, INCOME_TAX_RETENTION_KEY, PAPER_INVOICES, PDF_INVOICES, INCOME_TAX_RETENTION_SUBKEY, SIN_CONTROL_PALET_EXPEDICION, RECALCULATE_PRICES_IN_INVOICE, EXPORTAR_TRAZABILIDAD, LOAD_TIME, ENVIAR_PRECIOS_POR_E_MAIL, LOAD_HR, ID_TYPE, E_MAIL_ENVIO_PRECIOS, REGIMEN, ULT_ENVIO_PRECIOS_EMAIL, IMPRIMIR_BULTOS, RETENER_FACTURACION, COD_TRATAMIENTO_COMERCIAL, TOLERANCIA_RECADV, MOSTRAR_SALDO_EMBALAJES, SHIPMENT_ZONE_CODE, EORI_NUMBER, NUM_REGISTRO_ACUERDO_FACT, LOT_COMPLIANCE, NO_CESCE, ERROR_AL_ENVIAR_PRECIOS, SUPLEMENT_NO, ENVIAR_EXCEL_ALBARAN_E_MAIL, E_MAIL_ENVIO_ALBARAN_TRAZ, VAT_DOC_TYPE, OTHER_CUSTOMER, EDI_HORA_ENTREGA, INTRASTAT_EXCLUDED, DATOS_PIE_ALBARAN_1, SII_COUNTRY_CODE, DATOS_PIE_ALBARAN_2, DISABLE_DAYS_MARGIN, EXCLUDE_REMINDER, SCRAP_MANAGER, SUBSET_11, SUBSET_12, SUBSET_13, SUBSET_14, SUBSET_15, SUBSET_16, SUBSET_17, SUBSET_18, SUBSET_19, PREFIJO_EMPRESA_EAN_UCC, SUBSET_20, USE_GLN_IN_ELECTRONIC_DOCUMENT, LAST_ORDER_DATE, DAYS_FOR_SEND_INVOICE, INVOICE_BLOCKED, INVOICE_TO_DAY, ONLY_UPPER_PACKAGE_LEVEL, COMPLETE_BOX, W_PALLET_LABEL, EXTERNAL_DOC_NO_MANDATORY, ONLY_PERSONALIZED_PRICES) AS tec_hash,
                date(tec_ts_ingesta) as tec_fec_inicio
            from {{ ref('clientes_batch') }}
        ) s
        on t.tec_cod_vigencia = 1
            and t.NO is not distinct from s.NO and t.tec_des_empresa is not distinct from s.tec_des_empresa
        when matched and t.tec_hash <> s.tec_hash then
            update set
                tec_cod_vigencia = 0,
                tec_fec_fin = case
                    when s.tec_fec_inicio = t.tec_fec_inicio then s.tec_fec_inicio
                    else dateadd(day, -1, s.tec_fec_inicio)
                end;
        {% endif %}"
    ],
    post_hook=[
        "{%- set log_ref = source('support_param', 'INSERT_LOGS') -%}
{% set src_ref_coopecarn = source('bronze_coopecarn', 'COOPECARN_CUSTOMER') %}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref_coopecarn.database }}')
              and upper(l.schema)     = upper('{{ src_ref_coopecarn.schema }}')
              and upper(l.table_name) = upper('{{ src_ref_coopecarn.identifier }}')
              and exists (
                  select 1
                  from {{ ref('clientes_batch_coopecarn') }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );
{% set src_ref_delisano = source('bronze_delisano', 'V_DL_CLIENTES') %}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref_delisano.database }}')
              and upper(l.schema)     = upper('{{ src_ref_delisano.schema }}')
              and upper(l.table_name) = upper('{{ src_ref_delisano.identifier }}')
              and exists (
                  select 1
                  from {{ ref('clientes_batch_delisano') }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );
{% set src_ref_fricafor = source('bronze_fricafor', 'FRICAFOR_CUSTOMER') %}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref_fricafor.database }}')
              and upper(l.schema)     = upper('{{ src_ref_fricafor.schema }}')
              and upper(l.table_name) = upper('{{ src_ref_fricafor.identifier }}')
              and exists (
                  select 1
                  from {{ ref('clientes_batch_fricafor') }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );"
    ]
) }}

with source as (
    select
        timestamp, 
        no, 
        name, 
        search_name, 
        name_2, 
        address, 
        address_2, 
        city, 
        contact, 
        phone_no, 
        telex_no, 
        document_sending_profile, 
        our_account_no, 
        territory_code, 
        global_dimension_1_code, 
        global_dimension_2_code, 
        chain_name, 
        budgeted_amount, 
        credit_limit_lcy, 
        customer_posting_group, 
        currency_code, 
        customer_price_group, 
        language_code, 
        statistics_group, 
        payment_terms_code, 
        fin_charge_terms_code, 
        salesperson_code, 
        shipment_method_code, 
        shipping_agent_code, 
        place_of_export, 
        invoice_disc_code, 
        customer_disc_group, 
        country_region_code, 
        collection_method, 
        amount, 
        blocked, 
        invoice_copies, 
        last_statement_no, 
        print_statements, 
        bill_to_customer_no, 
        billto_customer_no, 
        priority, 
        payment_method_code, 
        last_date_modified, 
        last_modified_date_time, 
        application_method, 
        prices_including_vat, 
        location_code, 
        fax_no, 
        telex_answer_back, 
        vat_registration_no, 
        combine_shipments, 
        gen_bus_posting_group, 
        gln, 
        post_code, 
        county, 
        e_mail, 
        email, 
        home_page, 
        reminder_terms_code, 
        no_series, 
        tax_area_code, 
        tax_liable, 
        vat_bus_posting_group, 
        reserve, 
        block_payment_tolerance, 
        ic_partner_code, 
        prepayment, 
        partner_type, 
        preferred_bank_account, 
        privacy_blocked, 
        preferred_bank_account_code, 
        image, 
        cash_flow_payment_terms_code, 
        primary_contact_no, 
        responsibility_center, 
        shipping_advice, 
        shipping_time, 
        contact_type, 
        shipping_agent_service_code, 
        service_zone_code, 
        allow_line_disc, 
        base_calendar_code, 
        copy_sell_to_addr_to_qte_from, 
        payment_days_code, 
        non_paymt_periods_code, 
        rappel_reference, 
        not_in_aeat, 
        copy_sellto_addr_to_qte_from, 
        print_lots_in_invoice, 
        enviar_factura_por_e_mail, 
        validate_eu_vat_reg_no, 
        insurance_company_contract_no, 
        coverage_date, 
        id, 
        factura_en_papel, 
        secured_amount, 
        currency_id, 
        agrupar_por_direccion_envio, 
        cod_cadena, 
        payment_terms_id, 
        anonymous, 
        company_own_risk, 
        shipment_method_id, 
        cod_dto_linea, 
        promociones_por, 
        payment_method_id, 
        requested_risk_to_cyc, 
        tipo_punto_verde, 
        tax_area_id, 
        granted_risk_cyc, 
        tipo_residuos, 
        contact_id, 
        public_risk, 
        contact_graph_id, 
        dto_pp, 
        cod_ruta, 
        no_proveedor_relacionado, 
        rappel_perc, 
        comisiones_por, 
        nonpaymt_periods_code, 
        iban_code, 
        fecha_alta, 
        mig_account_no, 
        tipoiva, 
        disable_search_by_name, 
        usuario_alta, 
        shipto_code, 
        observaciones_envio, 
        generar_sscc_en_palet, 
        cod_idioma_etiquetaje, 
        tipofacturacion, 
        jefe_de_ventas, 
        cod_ifco, 
        jefe_de_zona, 
        periodofacturacion, 
        hereda_cond_grupo, 
        albaransgi, 
        horario_entrega, 
        fecha_creacion, 
        certificadosae, 
        naturaleza_producto, 
        pay_at_code, 
        coddelisano, 
        e_mail_envio_albaran, 
        e_mail_orden_recogida, 
        prevision, 
        forma_pago_antiguo, 
        observaciones_picking, 
        prevision_fecha_venta, 
        albaran_valorado, 
        lote_creciente, 
        exclude_347, 
        idpirpf_irpf_group, 
        rappels_x_grupo, 
        idpgnd_calculation_of_sig, 
        zona_transporte, 
        cod_europool, 
        tipo_dto_2, 
        idpvsh_valued_shipment, 
        default_ship_to_code, 
        tipo_dto_3, 
        if_sae, 
        tipo_dto_4, 
        doc_transporte, 
        if_sae_certification, 
        tipo_dto_5, 
        idpcin_cust_classificat_code, 
        albaran_por_lotes, 
        tipo_cliente, 
        item_cross_reference_code, 
        idpcin_insurance_co_credit_lcy, 
        ean128_etiqueta, 
        group_shipment_type, 
        idpcin_company_credit_lcy, 
        idpedi_config_template_no, 
        factura_contado_automatica, 
        shipment_frequency, 
        ait_billing_address_code, 
        plazo_entrega, 
        tipo_detalle_factura, 
        ait_creation_user, 
        cod_palet_defecto, 
        dia_de_facturacion, 
        grupo_de_compra, 
        no_lotes_max_en_expedicion, 
        ait_creation_datetime, 
        cod_grupo_de_compra, 
        cod_chep, 
        idpsii_default_invoice_type, 
        excluir_cobro_traza_palets, 
        idpsii_default_cr_memo_type, 
        exclude_349, 
        idpsii_vat_id_calculation, 
        mezcla_prod_en_embalaje, 
        umbralpago, 
        cod_embalaje_defecto, 
        irpf, 
        idpsii_other_id, 
        cod_irpf, 
        tec_des_empresa, 
        no_copias, 
        cod_envio_factura, 
        nombre_comercial, 
        tec_id_ingesta, 
        tec_ts_ingesta, 
        cyc, 
        correo_electronico_admon, 
        edi_ref_pedido, 
        empresa_symmetrical, 
        tec_ts_staging, 
        subset_1, 
        edi_ref_albaran, 
        tec_ts_integracion_b, 
        subset_2, 
        edi_inf_adicional_portugal, 
        edi_ref_factura, 
        subset_3, 
        subset_4, 
        edi_ref_pago, 
        subset_5, 
        edi_ref_departamento, 
        subset_6, 
        edi_cliente_del_grupo_alcampo, 
        edi_proveedor, 
        subset_7, 
        subset_8, 
        edi_cliente_unide, 
        edi_ref_euromadi, 
        subset_9, 
        edi_francia, 
        subset_10, 
        edi_carrefour, 
        efactura_automatica, 
        edi_codigo_guvernamental, 
        ods_job_template_code, 
        edi_cip, 
        liquidity_code, 
        show_expenses_on_transfer, 
        tipo_facturacion, 
        transfer_expenses, 
        bank_transfer_e_mail, 
        factura_por_albaran, 
        su_codigo, 
        average_payment_period, 
        split_ship_to_add, 
        cash_flow_code, 
        dto_factura, 
        mobile_price_group, 
        packing_list_report_no, 
        cod_banco, 
        expedition_label_rep_no, 
        nombre_contacto_pagos, 
        inv_discount, 
        cod_contacto_pagos, 
        default_ship_to_address, 
        responsable_pagos_empresa, 
        commission_customer_group, 
        autoinvoice, 
        autoinvoice_serie, 
        second_salesperson_code, 
        bank_account_to_transfer, 
        income_tax_retention_code, 
        shipmet_with_palet_resume, 
        income_tax_retention, 
        income_tax_retention_key, 
        paper_invoices, 
        pdf_invoices, 
        income_tax_retention_subkey, 
        sin_control_palet_expedicion, 
        recalculate_prices_in_invoice, 
        exportar_trazabilidad, 
        load_time, 
        enviar_precios_por_e_mail, 
        load_hr, 
        id_type, 
        e_mail_envio_precios, 
        regimen, 
        ult_envio_precios_email, 
        imprimir_bultos, 
        retener_facturacion, 
        cod_tratamiento_comercial, 
        tolerancia_recadv, 
        mostrar_saldo_embalajes, 
        shipment_zone_code, 
        eori_number, 
        num_registro_acuerdo_fact, 
        lot_compliance, 
        no_cesce, 
        error_al_enviar_precios, 
        suplement_no, 
        enviar_excel_albaran_e_mail, 
        e_mail_envio_albaran_traz, 
        vat_doc_type, 
        other_customer, 
        edi_hora_entrega, 
        intrastat_excluded, 
        datos_pie_albaran_1, 
        sii_country_code, 
        datos_pie_albaran_2, 
        disable_days_margin, 
        exclude_reminder, 
        scrap_manager, 
        subset_11, 
        subset_12, 
        subset_13, 
        subset_14, 
        subset_15, 
        subset_16, 
        subset_17, 
        subset_18, 
        subset_19, 
        prefijo_empresa_ean_ucc, 
        subset_20, 
        use_gln_in_electronic_document, 
        last_order_date, 
        days_for_send_invoice, 
        invoice_blocked, 
        invoice_to_day, 
        only_upper_package_level, 
        complete_box, 
        w_pallet_label, 
        external_doc_no_mandatory, 
        only_personalized_prices, 
        tec_des_cod_siglas, 
        tec_des_empresa, 
        tec_id_ingesta, 
        tec_ts_ingesta, 
        HASH(TIMESTAMP, NO, NAME, SEARCH_NAME, NAME_2, ADDRESS, ADDRESS_2, CITY, CONTACT, PHONE_NO, TELEX_NO, DOCUMENT_SENDING_PROFILE, OUR_ACCOUNT_NO, TERRITORY_CODE, GLOBAL_DIMENSION_1_CODE, GLOBAL_DIMENSION_2_CODE, CHAIN_NAME, BUDGETED_AMOUNT, CREDIT_LIMIT_LCY, CUSTOMER_POSTING_GROUP, CURRENCY_CODE, CUSTOMER_PRICE_GROUP, LANGUAGE_CODE, STATISTICS_GROUP, PAYMENT_TERMS_CODE, FIN_CHARGE_TERMS_CODE, SALESPERSON_CODE, SHIPMENT_METHOD_CODE, SHIPPING_AGENT_CODE, PLACE_OF_EXPORT, INVOICE_DISC_CODE, CUSTOMER_DISC_GROUP, COUNTRY_REGION_CODE, COLLECTION_METHOD, AMOUNT, BLOCKED, INVOICE_COPIES, LAST_STATEMENT_NO, PRINT_STATEMENTS, BILL_TO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, PRIORITY, PAYMENT_METHOD_CODE, LAST_DATE_MODIFIED, LAST_MODIFIED_DATE_TIME, APPLICATION_METHOD, PRICES_INCLUDING_VAT, LOCATION_CODE, FAX_NO, TELEX_ANSWER_BACK, VAT_REGISTRATION_NO, COMBINE_SHIPMENTS, GEN_BUS_POSTING_GROUP, GLN, POST_CODE, COUNTY, E_MAIL, EMAIL, HOME_PAGE, REMINDER_TERMS_CODE, NO_SERIES, TAX_AREA_CODE, TAX_LIABLE, VAT_BUS_POSTING_GROUP, RESERVE, BLOCK_PAYMENT_TOLERANCE, IC_PARTNER_CODE, PREPAYMENT, PARTNER_TYPE, PREFERRED_BANK_ACCOUNT, PRIVACY_BLOCKED, PREFERRED_BANK_ACCOUNT_CODE, IMAGE, CASH_FLOW_PAYMENT_TERMS_CODE, PRIMARY_CONTACT_NO, RESPONSIBILITY_CENTER, SHIPPING_ADVICE, SHIPPING_TIME, CONTACT_TYPE, SHIPPING_AGENT_SERVICE_CODE, SERVICE_ZONE_CODE, ALLOW_LINE_DISC, BASE_CALENDAR_CODE, COPY_SELL_TO_ADDR_TO_QTE_FROM, PAYMENT_DAYS_CODE, NON_PAYMT_PERIODS_CODE, RAPPEL_REFERENCE, NOT_IN_AEAT, COPY_SELLTO_ADDR_TO_QTE_FROM, PRINT_LOTS_IN_INVOICE, ENVIAR_FACTURA_POR_E_MAIL, VALIDATE_EU_VAT_REG_NO, INSURANCE_COMPANY_CONTRACT_NO, COVERAGE_DATE, ID, FACTURA_EN_PAPEL, SECURED_AMOUNT, CURRENCY_ID, AGRUPAR_POR_DIRECCION_ENVIO, COD_CADENA, PAYMENT_TERMS_ID, ANONYMOUS, COMPANY_OWN_RISK, SHIPMENT_METHOD_ID, COD_DTO_LINEA, PROMOCIONES_POR, PAYMENT_METHOD_ID, REQUESTED_RISK_TO_CYC, TIPO_PUNTO_VERDE, TAX_AREA_ID, GRANTED_RISK_CYC, TIPO_RESIDUOS, CONTACT_ID, PUBLIC_RISK, CONTACT_GRAPH_ID, DTO_PP, COD_RUTA, NO_PROVEEDOR_RELACIONADO, RAPPEL_PERC, COMISIONES_POR, NONPAYMT_PERIODS_CODE, IBAN_CODE, FECHA_ALTA, MIG_ACCOUNT_NO, TIPOIVA, DISABLE_SEARCH_BY_NAME, USUARIO_ALTA, SHIPTO_CODE, OBSERVACIONES_ENVIO, GENERAR_SSCC_EN_PALET, COD_IDIOMA_ETIQUETAJE, TIPOFACTURACION, JEFE_DE_VENTAS, COD_IFCO, JEFE_DE_ZONA, PERIODOFACTURACION, HEREDA_COND_GRUPO, ALBARANSGI, HORARIO_ENTREGA, FECHA_CREACION, CERTIFICADOSAE, NATURALEZA_PRODUCTO, PAY_AT_CODE, CODDELISANO, E_MAIL_ENVIO_ALBARAN, E_MAIL_ORDEN_RECOGIDA, PREVISION, FORMA_PAGO_ANTIGUO, OBSERVACIONES_PICKING, PREVISION_FECHA_VENTA, ALBARAN_VALORADO, LOTE_CRECIENTE, EXCLUDE_347, IDPIRPF_IRPF_GROUP, RAPPELS_X_GRUPO, IDPGND_CALCULATION_OF_SIG, ZONA_TRANSPORTE, COD_EUROPOOL, TIPO_DTO_2, IDPVSH_VALUED_SHIPMENT, DEFAULT_SHIP_TO_CODE, TIPO_DTO_3, IF_SAE, TIPO_DTO_4, DOC_TRANSPORTE, IF_SAE_CERTIFICATION, TIPO_DTO_5, IDPCIN_CUST_CLASSIFICAT_CODE, ALBARAN_POR_LOTES, TIPO_CLIENTE, ITEM_CROSS_REFERENCE_CODE, IDPCIN_INSURANCE_CO_CREDIT_LCY, EAN128_ETIQUETA, GROUP_SHIPMENT_TYPE, IDPCIN_COMPANY_CREDIT_LCY, IDPEDI_CONFIG_TEMPLATE_NO, FACTURA_CONTADO_AUTOMATICA, SHIPMENT_FREQUENCY, AIT_BILLING_ADDRESS_CODE, PLAZO_ENTREGA, TIPO_DETALLE_FACTURA, AIT_CREATION_USER, COD_PALET_DEFECTO, DIA_DE_FACTURACION, GRUPO_DE_COMPRA, NO_LOTES_MAX_EN_EXPEDICION, AIT_CREATION_DATETIME, COD_GRUPO_DE_COMPRA, COD_CHEP, IDPSII_DEFAULT_INVOICE_TYPE, EXCLUIR_COBRO_TRAZA_PALETS, IDPSII_DEFAULT_CR_MEMO_TYPE, EXCLUDE_349, IDPSII_VAT_ID_CALCULATION, MEZCLA_PROD_EN_EMBALAJE, UMBRALPAGO, COD_EMBALAJE_DEFECTO, IRPF, IDPSII_OTHER_ID, COD_IRPF, TEC_DES_EMPRESA, NO_COPIAS, COD_ENVIO_FACTURA, NOMBRE_COMERCIAL, TEC_ID_INGESTA, TEC_TS_INGESTA, CYC, CORREO_ELECTRONICO_ADMON, EDI_REF_PEDIDO, EMPRESA_SYMMETRICAL, TEC_TS_STAGING, SUBSET_1, EDI_REF_ALBARAN, TEC_TS_INTEGRACION_B, SUBSET_2, EDI_INF_ADICIONAL_PORTUGAL, EDI_REF_FACTURA, SUBSET_3, SUBSET_4, EDI_REF_PAGO, SUBSET_5, EDI_REF_DEPARTAMENTO, SUBSET_6, EDI_CLIENTE_DEL_GRUPO_ALCAMPO, EDI_PROVEEDOR, SUBSET_7, SUBSET_8, EDI_CLIENTE_UNIDE, EDI_REF_EUROMADI, SUBSET_9, EDI_FRANCIA, SUBSET_10, EDI_CARREFOUR, EFACTURA_AUTOMATICA, EDI_CODIGO_GUVERNAMENTAL, ODS_JOB_TEMPLATE_CODE, EDI_CIP, LIQUIDITY_CODE, SHOW_EXPENSES_ON_TRANSFER, TIPO_FACTURACION, TRANSFER_EXPENSES, BANK_TRANSFER_E_MAIL, FACTURA_POR_ALBARAN, SU_CODIGO, AVERAGE_PAYMENT_PERIOD, SPLIT_SHIP_TO_ADD, CASH_FLOW_CODE, DTO_FACTURA, MOBILE_PRICE_GROUP, PACKING_LIST_REPORT_NO, COD_BANCO, EXPEDITION_LABEL_REP_NO, NOMBRE_CONTACTO_PAGOS, INV_DISCOUNT, COD_CONTACTO_PAGOS, DEFAULT_SHIP_TO_ADDRESS, RESPONSABLE_PAGOS_EMPRESA, COMMISSION_CUSTOMER_GROUP, AUTOINVOICE, AUTOINVOICE_SERIE, SECOND_SALESPERSON_CODE, BANK_ACCOUNT_TO_TRANSFER, INCOME_TAX_RETENTION_CODE, SHIPMET_WITH_PALET_RESUME, INCOME_TAX_RETENTION, INCOME_TAX_RETENTION_KEY, PAPER_INVOICES, PDF_INVOICES, INCOME_TAX_RETENTION_SUBKEY, SIN_CONTROL_PALET_EXPEDICION, RECALCULATE_PRICES_IN_INVOICE, EXPORTAR_TRAZABILIDAD, LOAD_TIME, ENVIAR_PRECIOS_POR_E_MAIL, LOAD_HR, ID_TYPE, E_MAIL_ENVIO_PRECIOS, REGIMEN, ULT_ENVIO_PRECIOS_EMAIL, IMPRIMIR_BULTOS, RETENER_FACTURACION, COD_TRATAMIENTO_COMERCIAL, TOLERANCIA_RECADV, MOSTRAR_SALDO_EMBALAJES, SHIPMENT_ZONE_CODE, EORI_NUMBER, NUM_REGISTRO_ACUERDO_FACT, LOT_COMPLIANCE, NO_CESCE, ERROR_AL_ENVIAR_PRECIOS, SUPLEMENT_NO, ENVIAR_EXCEL_ALBARAN_E_MAIL, E_MAIL_ENVIO_ALBARAN_TRAZ, VAT_DOC_TYPE, OTHER_CUSTOMER, EDI_HORA_ENTREGA, INTRASTAT_EXCLUDED, DATOS_PIE_ALBARAN_1, SII_COUNTRY_CODE, DATOS_PIE_ALBARAN_2, DISABLE_DAYS_MARGIN, EXCLUDE_REMINDER, SCRAP_MANAGER, SUBSET_11, SUBSET_12, SUBSET_13, SUBSET_14, SUBSET_15, SUBSET_16, SUBSET_17, SUBSET_18, SUBSET_19, PREFIJO_EMPRESA_EAN_UCC, SUBSET_20, USE_GLN_IN_ELECTRONIC_DOCUMENT, LAST_ORDER_DATE, DAYS_FOR_SEND_INVOICE, INVOICE_BLOCKED, INVOICE_TO_DAY, ONLY_UPPER_PACKAGE_LEVEL, COMPLETE_BOX, W_PALLET_LABEL, EXTERNAL_DOC_NO_MANDATORY, ONLY_PERSONALIZED_PRICES) AS tec_hash, 
        date(tec_ts_ingesta) as tec_fec_inicio
    from {{ ref('clientes_batch') }}
)
select
    s.*,
    to_date('2999-12-31')             as tec_fec_fin,
    1                                 as tec_cod_vigencia,
    current_timestamp()               as tec_ts_integracion_s
from source s
{% if is_incremental() %}
left join {{ this }} t
    on  t.NO is not distinct from s.NO and t.tec_des_empresa is not distinct from s.tec_des_empresa
    and t.tec_cod_vigencia    = 1
where t.NO is null
    or t.tec_hash <> s.tec_hash
{% endif %}
