{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_ITEM_VARIANT') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"ITEM_NO_"', 'VARCHAR') }}                                as ITEM_NO,
        {{ std_cast('"CODE"', 'VARCHAR') }}                                    as CODE,
        {{ std_cast('"DESCRIPTION"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"DESCRIPTION_2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"SALES_UNIT_OF_MEASURE"', 'VARCHAR') }}                   as SALES_UNIT_OF_MEASURE,
        {{ std_cast('"CHECKED"', 'INTEGER') }}                                 as CHECKED,
        {{ std_cast('"INTERNAL_REVIEW_DATE"', 'TIMESTAMP_NTZ') }}              as INTERNAL_REVIEW_DATE,
        {{ std_cast('"PRODUCTION_LABEL_REPORT_NO_"', 'INTEGER') }}             as PRODUCTION_LABEL_REPORT_NO,
        {{ std_cast('"INJECTION_MANAGEMENT"', 'INTEGER') }}                    as INJECTION_MANAGEMENT,
        {{ std_cast('"GL19"', 'VARCHAR') }}                                    as GL19,
        {{ std_cast('"GL1A_BOX"', 'VARCHAR') }}                                as GL1A_BOX,
        {{ std_cast('"GL1A_PIECE"', 'VARCHAR') }}                              as GL1A_PIECE,
        {{ std_cast('"COMMERTIAL_DESCRIPTION"', 'VARCHAR') }}                  as COMMERTIAL_DESCRIPTION,
        {{ std_cast('"LANGUAGE_1"', 'VARCHAR') }}                              as LANGUAGE_1,
        {{ std_cast('"LANGUAGE_2"', 'VARCHAR') }}                              as LANGUAGE_2,
        {{ std_cast('"LANGUAGE_3"', 'VARCHAR') }}                              as LANGUAGE_3,
        {{ std_cast('"LANGUAGE_4"', 'VARCHAR') }}                              as LANGUAGE_4,
        {{ std_cast('"LANGUAGE_5"', 'VARCHAR') }}                              as LANGUAGE_5,
        {{ std_cast('"EXCEL_LANGUAGE"', 'VARCHAR') }}                          as EXCEL_LANGUAGE,
        {{ std_cast('"TRADERMARK_CODE"', 'VARCHAR') }}                         as TRADERMARK_CODE,
        {{ std_cast('"TECNICAL_CARD"', 'VARCHAR') }}                           as TECNICAL_CARD,
        {{ std_cast('"PIECE_LABEL_CODE"', 'VARCHAR') }}                        as PIECE_LABEL_CODE,
        {{ std_cast('"BOX_LABEL_CODE"', 'VARCHAR') }}                          as BOX_LABEL_CODE,
        {{ std_cast('"PALET_LABEL_CODE"', 'VARCHAR') }}                        as PALET_LABEL_CODE,
        {{ std_cast('"PRINT_LABEL_DATE"', 'TIMESTAMP_NTZ') }}                  as PRINT_LABEL_DATE,
        {{ std_cast('"PRINT_LABEL_USER"', 'VARCHAR') }}                        as PRINT_LABEL_USER,
        {{ std_cast('"SHORT_DESC_LANGUAGE_1"', 'VARCHAR') }}                   as SHORT_DESC_LANGUAGE_1,
        {{ std_cast('"SHORT_DESC_LANGUAGE_2"', 'VARCHAR') }}                   as SHORT_DESC_LANGUAGE_2,
        {{ std_cast('"SHORT_DESC_LANGUAGE_3"', 'VARCHAR') }}                   as SHORT_DESC_LANGUAGE_3,
        {{ std_cast('"SHORT_DESC_LANGUAGE_4"', 'VARCHAR') }}                   as SHORT_DESC_LANGUAGE_4,
        {{ std_cast('"SHORT_DESC_LANGUAGE_5"', 'VARCHAR') }}                   as SHORT_DESC_LANGUAGE_5,
        {{ std_cast('"DESC_LANGUAGE_1"', 'VARCHAR') }}                         as DESC_LANGUAGE_1,
        {{ std_cast('"DESC_LANGUAGE_2"', 'VARCHAR') }}                         as DESC_LANGUAGE_2,
        {{ std_cast('"DESC_LANGUAGE_3"', 'VARCHAR') }}                         as DESC_LANGUAGE_3,
        {{ std_cast('"DESC_LANGUAGE_4"', 'VARCHAR') }}                         as DESC_LANGUAGE_4,
        {{ std_cast('"DESC_LANGUAGE_5"', 'VARCHAR') }}                         as DESC_LANGUAGE_5,
        {{ std_cast('"INGR_LANGUAGE_1"', 'VARCHAR') }}                         as INGR_LANGUAGE_1,
        {{ std_cast('"INGR_LANGUAGE_2"', 'VARCHAR') }}                         as INGR_LANGUAGE_2,
        {{ std_cast('"INGR_LANGUAGE_3"', 'VARCHAR') }}                         as INGR_LANGUAGE_3,
        {{ std_cast('"INGR_LANGUAGE_4"', 'VARCHAR') }}                         as INGR_LANGUAGE_4,
        {{ std_cast('"INGR_LANGUAGE_5"', 'VARCHAR') }}                         as INGR_LANGUAGE_5,
        {{ std_cast('"ROUTING_NO_"', 'VARCHAR') }}                             as ROUTING_NO,
        {{ std_cast('"PACKING_BOM"', 'VARCHAR') }}                             as PACKING_BOM,
        {{ std_cast('"MAQUILA"', 'INTEGER') }}                                 as MAQUILA,
        {{ std_cast('"OLD_ITEM_NO_"', 'VARCHAR') }}                            as OLD_ITEM_NO,
        {{ std_cast('"DECLARED_INJECTION_"', 'NUMBER(38,5)') }}                as DECLARED_INJECTION,
        {{ std_cast('"FIXED_WEIGHT"', 'INTEGER') }}                            as FIXED_WEIGHT,
        {{ std_cast('"BOX_CODE"', 'VARCHAR') }}                                as BOX_CODE,
        {{ std_cast('"KG_BOX"', 'NUMBER(38,5)') }}                             as KG_BOX,
        {{ std_cast('"BOX_ROW"', 'INTEGER') }}                                 as BOX_ROW,
        {{ std_cast('"ROWS_PALET"', 'INTEGER') }}                              as ROWS_PALET,
        {{ std_cast('"BOX_PALET"', 'INTEGER') }}                               as BOX_PALET,
        {{ std_cast('"KG_PALET"', 'NUMBER(38,5)') }}                           as KG_PALET,
        {{ std_cast('"UNITS_BOX"', 'INTEGER') }}                               as UNITS_BOX,
        {{ std_cast('"UNITS_PACKAGE"', 'INTEGER') }}                           as UNITS_PACKAGE,
        {{ std_cast('"PACKAGES_BOX"', 'INTEGER') }}                            as PACKAGES_BOX,
        {{ std_cast('"UNITS_BOX_TXT"', 'VARCHAR') }}                           as UNITS_BOX_TXT,
        {{ std_cast('"UNITS_PACKAGE_TXT"', 'VARCHAR') }}                       as UNITS_PACKAGE_TXT,
        {{ std_cast('"PACKAGES_BOX_TXT"', 'VARCHAR') }}                        as PACKAGES_BOX_TXT,
        {{ std_cast('"UNITS_CONTAINER_TXT"', 'VARCHAR') }}                     as UNITS_CONTAINER_TXT,
        {{ std_cast('"LABEL_CODE"', 'VARCHAR') }}                              as LABEL_CODE,
        {{ std_cast('"PRODUCT_MANUF_INSTRUCTION"', 'VARCHAR') }}               as PRODUCT_MANUF_INSTRUCTION,
        {{ std_cast('"SHIPMENT_REMARKS"', 'VARCHAR') }}                        as SHIPMENT_REMARKS,
        {{ std_cast('"TARIFF_NO_"', 'VARCHAR') }}                              as TARIFF_NO,
        {{ std_cast('"SALES_BLOCKED"', 'INTEGER') }}                           as SALES_BLOCKED,
        {{ std_cast('"GTIN"', 'VARCHAR') }}                                    as GTIN,
        {{ std_cast('"PALLET_CODE"', 'VARCHAR') }}                             as PALLET_CODE,
        {{ std_cast('"JAIL_CODE"', 'VARCHAR') }}                               as JAIL_CODE,
        {{ std_cast('"BUCKET_CODE"', 'VARCHAR') }}                             as BUCKET_CODE,
        {{ std_cast('"PLATE_MANDATORY"', 'INTEGER') }}                         as PLATE_MANDATORY,
        {{ std_cast('"PLATE_CODE"', 'VARCHAR') }}                              as PLATE_CODE,
        {{ std_cast('"PLATES_BOX"', 'INTEGER') }}                              as PLATES_BOX,
        {{ std_cast('"PLATES_PALLET"', 'INTEGER') }}                           as PLATES_PALLET,
        {{ std_cast('"PLATE_WEIGHT"', 'NUMBER(38,5)') }}                       as PLATE_WEIGHT,
        {{ std_cast('"PLATES_TO_CREATE_ORDER"', 'NUMBER(38,5)') }}             as PLATES_TO_CREATE_ORDER,
        {{ std_cast('"MANUFACTUING_DATE"', 'TIMESTAMP_NTZ') }}                 as MANUFACTUING_DATE,
        {{ std_cast('"QUANTITY_TO_CREATE_ORDER"', 'NUMBER(38,5)') }}           as QUANTITY_TO_CREATE_ORDER,
        {{ std_cast('"QUANTITY_TO_CONSUME"', 'NUMBER(38,5)') }}                as QUANTITY_TO_CONSUME,
        {{ std_cast('"EAN_TEMPLATE_BOX_1"', 'VARCHAR') }}                      as EAN_TEMPLATE_BOX_1,
        {{ std_cast('"EAN_TEMPLATE_BOX_2"', 'VARCHAR') }}                      as EAN_TEMPLATE_BOX_2,
        {{ std_cast('"EAN_TEMPLATE_PIECE_1"', 'VARCHAR') }}                    as EAN_TEMPLATE_PIECE_1,
        {{ std_cast('"EAN_TEMPLATE_PIECE_2"', 'VARCHAR') }}                    as EAN_TEMPLATE_PIECE_2,
        {{ std_cast('"EAN_CODE_BOX_1"', 'VARCHAR') }}                          as EAN_CODE_BOX_1,
        {{ std_cast('"EAN_CODE_BOX_2"', 'VARCHAR') }}                          as EAN_CODE_BOX_2,
        {{ std_cast('"EAN_CODE_PIECE_1"', 'VARCHAR') }}                        as EAN_CODE_PIECE_1,
        {{ std_cast('"EAN_CODE_PIECE_2"', 'VARCHAR') }}                        as EAN_CODE_PIECE_2,
        {{ std_cast('"EAN_TYPE_BOX_1"', 'INTEGER') }}                          as EAN_TYPE_BOX_1,
        {{ std_cast('"EAN_TYPE_BOX_2"', 'INTEGER') }}                          as EAN_TYPE_BOX_2,
        {{ std_cast('"EAN_TYPE_PIECE_1"', 'INTEGER') }}                        as EAN_TYPE_PIECE_1,
        {{ std_cast('"EAN_TYPE_PIECE_2"', 'INTEGER') }}                        as EAN_TYPE_PIECE_2,
        {{ std_cast('"PRINT_WEIGHT_PIECE"', 'INTEGER') }}                      as PRINT_WEIGHT_PIECE,
        {{ std_cast('"UNIT_PRICE"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"MANUFACTURED_BY"', 'INTEGER') }}                         as MANUFACTURED_BY,
        {{ std_cast('"MEAT_PREPARATION"', 'INTEGER') }}                        as MEAT_PREPARATION,
        {{ std_cast('"WATER_ADDED"', 'INTEGER') }}                             as WATER_ADDED,
        {{ std_cast('"MEAT_ORIGIN"', 'INTEGER') }}                             as MEAT_ORIGIN,
        {{ std_cast('"CUSTOMER_NO_"', 'VARCHAR') }}                            as CUSTOMER_NO,
        {{ std_cast('"CUSTOMER_ITEM_NO_"', 'VARCHAR') }}                       as CUSTOMER_ITEM_NO,
        {{ std_cast('"PRINT_CUSTOMER_ITEM_NO_"', 'INTEGER') }}                 as PRINT_CUSTOMER_ITEM_NO,
        {{ std_cast('"PRINT_CUST_LOT_NO_"', 'INTEGER') }}                      as PRINT_CUST_LOT_NO,
        {{ std_cast('"PRINT_CUSTOMER_INFORMATION"', 'INTEGER') }}              as PRINT_CUSTOMER_INFORMATION,
        {{ std_cast('"MANUFACTURED_FOR"', 'VARCHAR') }}                        as MANUFACTURED_FOR,
        {{ std_cast('"RM_CODE"', 'VARCHAR') }}                                 as RM_CODE,
        {{ std_cast('"KG_MP_TN"', 'NUMBER(38,5)') }}                           as KG_MP_TN,
        {{ std_cast('"SALT_CODE"', 'VARCHAR') }}                               as SALT_CODE,
        {{ std_cast('"KG_SALT_TN"', 'NUMBER(38,5)') }}                         as KG_SALT_TN,
        {{ std_cast('"PACKAGING_WEIGHT"', 'NUMBER(38,5)') }}                   as PACKAGING_WEIGHT,
        {{ std_cast('"PLASTIC_WEIGHT_GR"', 'NUMBER(38,5)') }}                  as PLASTIC_WEIGHT_GR,
        {{ std_cast('"PRESENTATION"', 'VARCHAR') }}                            as PRESENTATION,
        {{ std_cast('"TECNICAL_CARD_VERSION"', 'VARCHAR') }}                   as TECNICAL_CARD_VERSION,
        {{ std_cast('"TECNICAL_CARD_VERSION_DATE"', 'TIMESTAMP_NTZ') }}        as TECNICAL_CARD_VERSION_DATE,
        {{ std_cast('"WEIGHT_PIECE"', 'NUMBER(38,5)') }}                       as WEIGHT_PIECE,
        {{ std_cast('"THICK_PIECE"', 'NUMBER(38,5)') }}                        as THICK_PIECE,
        {{ std_cast('"EXPIRATION_CALCULATION"', 'VARCHAR') }}                  as EXPIRATION_CALCULATION,
        {{ std_cast('"ENFORCE_PLANNING"', 'INTEGER') }}                        as ENFORCE_PLANNING,
        {{ std_cast('"BOLD"', 'INTEGER') }}                                    as BOLD,
        {{ std_cast('"BLOCK_VARIANT"', 'INTEGER') }}                           as BLOCK_VARIANT,
        {{ std_cast('"BLOCK_PURCHASE_PRODUCTION"', 'INTEGER') }}               as BLOCK_PURCHASE_PRODUCTION,
        {{ std_cast('"CONTROL_CAJAS_EXPEDICION"', 'INTEGER') }}                as CONTROL_CAJAS_EXPEDICION,
        {{ std_cast('"SUBSET_1"', 'VARCHAR') }}                                as SUBSET_1,
        {{ std_cast('"SUBSET_2"', 'VARCHAR') }}                                as SUBSET_2,
        {{ std_cast('"SUBSET_3"', 'VARCHAR') }}                                as SUBSET_3,
        {{ std_cast('"SUBSET_4"', 'VARCHAR') }}                                as SUBSET_4,
        {{ std_cast('"SUBSET_5"', 'VARCHAR') }}                                as SUBSET_5,
        {{ std_cast('"RM_FIELD_1"', 'NUMBER(38,5)') }}                         as RM_FIELD_1,
        {{ std_cast('"RM_FIELD_2"', 'NUMBER(38,5)') }}                         as RM_FIELD_2,
        {{ std_cast('"RM_FIELD_3"', 'NUMBER(38,5)') }}                         as RM_FIELD_3,
        {{ std_cast('"RM_COST_DISTR_"', 'NUMBER(38,5)') }}                     as RM_COST_DISTR,
        {{ std_cast('"PVP"', 'NUMBER(38,5)') }}                                as PVP,
        {{ std_cast('"R"', 'INTEGER') }}                                       as R,
        {{ std_cast('"FCP"', 'INTEGER') }}                                     as FCP,
        {{ std_cast('"_TOLERANCIA_EXCESO_PESO"', 'NUMBER(38,5)') }}            as TOLERANCIA_EXCESO_PESO,
        {{ std_cast('"FCP_LOCATION"', 'VARCHAR') }}                            as FCP_LOCATION,
        {{ std_cast('"_TOLERANCIA_CARGA_EXPEDICION"', 'NUMBER(38,5)') }}       as TOLERANCIA_CARGA_EXPEDICION,
        {{ std_cast('"CONTROL_FABRICACION_MERCADONA"', 'INTEGER') }}           as CONTROL_FABRICACION_MERCADONA,
        {{ std_cast('"FILM_TOP"', 'VARCHAR') }}                                as FILM_TOP,
        {{ std_cast('"FILM_BOTTOM"', 'VARCHAR') }}                             as FILM_BOTTOM,
        {{ std_cast('"BAG"', 'VARCHAR') }}                                     as BAG,
        {{ std_cast('"LABEL"', 'VARCHAR') }}                                   as LABEL,
        {{ std_cast('"BOX_PALET_MERCADONA"', 'INTEGER') }}                     as BOX_PALET_MERCADONA,
        {{ std_cast('"PRODUCTION_GROUPED"', 'INTEGER') }}                      as PRODUCTION_GROUPED,
        {{ std_cast('"GL19_PIECE"', 'VARCHAR') }}                              as GL19_PIECE,
        {{ std_cast('"SCRAP_CATEGORY"', 'VARCHAR') }}                          as SCRAP_CATEGORY,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'COO'                                                                     as tec_des_cod_siglas,
        'COOPECARN'                                                            as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src