{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_SALES_LINES') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"timestamp"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"Document Type"', 'INTEGER') }}                           as DOCUMENT_TYPE,
        {{ std_cast('"Document No_"', 'VARCHAR') }}                            as DOCUMENT_NO,
        {{ std_cast('"Line No_"', 'INTEGER') }}                                as LINE_NO,
        {{ std_cast('"Sell-to Customer No_"', 'VARCHAR') }}                    as SELLTO_CUSTOMER_NO,
        {{ std_cast('"Type"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Posting Group"', 'VARCHAR') }}                           as POSTING_GROUP,
        {{ std_cast('"Shipment Date"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"Description"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"Description 2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"Unit of Measure"', 'VARCHAR') }}                         as UNIT_OF_MEASURE,
        {{ std_cast('"Quantity"', 'NUMBER(38,5)') }}                           as QUANTITY,
        {{ std_cast('"Outstanding Quantity"', 'NUMBER(38,5)') }}               as OUTSTANDING_QUANTITY,
        {{ std_cast('"Qty_ to Invoice"', 'NUMBER(38,5)') }}                    as QTY_TO_INVOICE,
        {{ std_cast('"Qty_ to Ship"', 'NUMBER(38,5)') }}                       as QTY_TO_SHIP,
        {{ std_cast('"Unit Price"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"Unit Cost (LCY)"', 'NUMBER(38,5)') }}                    as UNIT_COST_LCY,
        {{ std_cast('"VAT _"', 'NUMBER(38,5)') }}                              as VAT,
        {{ std_cast('"Line Discount _"', 'NUMBER(38,5)') }}                    as LINE_DISCOUNT,
        {{ std_cast('"Line Discount Amount"', 'NUMBER(38,5)') }}               as LINE_DISCOUNT_AMOUNT,
        {{ std_cast('"Amount"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"Amount Including VAT"', 'NUMBER(38,5)') }}               as AMOUNT_INCLUDING_VAT,
        {{ std_cast('"Allow Invoice Disc_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"Gross Weight"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"Net Weight"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"Units per Parcel"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"Unit Volume"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"Appl_-to Item Entry"', 'INTEGER') }}                     as APPL_TO_ITEM_ENTRY,
        {{ std_cast('"Shortcut Dimension 1 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"Shortcut Dimension 2 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Job No_"', 'VARCHAR') }}                                 as JOB_NO,
        {{ std_cast('"Work Type Code"', 'VARCHAR') }}                          as WORK_TYPE_CODE,
        {{ std_cast('"Recalculate Invoice Disc_"', 'INTEGER') }}               as RECALCULATE_INVOICE_DISC,
        {{ std_cast('"Outstanding Amount"', 'NUMBER(38,5)') }}                 as OUTSTANDING_AMOUNT,
        {{ std_cast('"Qty_ Shipped Not Invoiced"', 'NUMBER(38,5)') }}          as QTY_SHIPPED_NOT_INVOICED,
        {{ std_cast('"Shipped Not Invoiced"', 'NUMBER(38,5)') }}               as SHIPPED_NOT_INVOICED,
        {{ std_cast('"Quantity Shipped"', 'NUMBER(38,5)') }}                   as QUANTITY_SHIPPED,
        {{ std_cast('"Quantity Invoiced"', 'NUMBER(38,5)') }}                  as QUANTITY_INVOICED,
        {{ std_cast('"Shipment No_"', 'VARCHAR') }}                            as SHIPMENT_NO,
        {{ std_cast('"Shipment Line No_"', 'INTEGER') }}                       as SHIPMENT_LINE_NO,
        {{ std_cast('"Profit _"', 'NUMBER(38,5)') }}                           as PROFIT,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"Inv_ Discount Amount"', 'NUMBER(38,5)') }}               as INV_DISCOUNT_AMOUNT,
        {{ std_cast('"Purchase Order No_"', 'VARCHAR') }}                      as PURCHASE_ORDER_NO,
        {{ std_cast('"Purch_ Order Line No_"', 'INTEGER') }}                   as PURCH_ORDER_LINE_NO,
        {{ std_cast('"Drop Shipment"', 'INTEGER') }}                           as DROP_SHIPMENT,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"Gen_ Prod_ Posting Group"', 'VARCHAR') }}                as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"VAT Calculation Type"', 'INTEGER') }}                    as VAT_CALCULATION_TYPE,
        {{ std_cast('"Transaction Type"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"Transport Method"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"Attached to Line No_"', 'INTEGER') }}                    as ATTACHED_TO_LINE_NO,
        {{ std_cast('"Exit Point"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"Area"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"Transaction Specification"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"Tax Category"', 'VARCHAR') }}                            as TAX_CATEGORY,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"Tax Group Code"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT Clause Code"', 'VARCHAR') }}                         as VAT_CLAUSE_CODE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT Prod_ Posting Group"', 'VARCHAR') }}                 as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"Currency Code"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"Outstanding Amount (LCY)"', 'NUMBER(38,5)') }}           as OUTSTANDING_AMOUNT_LCY,
        {{ std_cast('"Shipped Not Invoiced (LCY)"', 'NUMBER(38,5)') }}         as SHIPPED_NOT_INVOICED_LCY,
        {{ std_cast('"Shipped Not Inv_ (LCY) No VAT"', 'NUMBER(38,5)') }}      as SHIPPED_NOT_INV_LCY_NO_VAT,
        {{ std_cast('"Reserve"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"Blanket Order No_"', 'VARCHAR') }}                       as BLANKET_ORDER_NO,
        {{ std_cast('"Blanket Order Line No_"', 'INTEGER') }}                  as BLANKET_ORDER_LINE_NO,
        {{ std_cast('"VAT Base Amount"', 'NUMBER(38,5)') }}                    as VAT_BASE_AMOUNT,
        {{ std_cast('"Unit Cost"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"System-Created Entry"', 'INTEGER') }}                    as SYSTEMCREATED_ENTRY,
        {{ std_cast('"Line Amount"', 'NUMBER(38,5)') }}                        as LINE_AMOUNT,
        {{ std_cast('"VAT Difference"', 'NUMBER(38,5)') }}                     as VAT_DIFFERENCE,
        {{ std_cast('"Inv_ Disc_ Amount to Invoice"', 'NUMBER(38,5)') }}       as INV_DISC_AMOUNT_TO_INVOICE,
        {{ std_cast('"VAT Identifier"', 'VARCHAR') }}                          as VAT_IDENTIFIER,
        {{ std_cast('"IC Partner Ref_ Type"', 'INTEGER') }}                    as IC_PARTNER_REF_TYPE,
        {{ std_cast('"IC Partner Reference"', 'VARCHAR') }}                    as IC_PARTNER_REFERENCE,
        {{ std_cast('"Prepayment _"', 'NUMBER(38,5)') }}                       as PREPAYMENT,
        {{ std_cast('"Prepmt_ Line Amount"', 'NUMBER(38,5)') }}                as PREPMT_LINE_AMOUNT,
        {{ std_cast('"Prepmt_ Amt_ Inv_"', 'NUMBER(38,5)') }}                  as PREPMT_AMT_INV,
        {{ std_cast('"Prepmt_ Amt_ Incl_ VAT"', 'NUMBER(38,5)') }}             as PREPMT_AMT_INCL_VAT,
        {{ std_cast('"Prepayment Amount"', 'NUMBER(38,5)') }}                  as PREPAYMENT_AMOUNT,
        {{ std_cast('"Prepmt_ VAT Base Amt_"', 'NUMBER(38,5)') }}              as PREPMT_VAT_BASE_AMT,
        {{ std_cast('"Prepayment VAT _"', 'NUMBER(38,5)') }}                   as PREPAYMENT_VAT,
        {{ std_cast('"Prepmt_ VAT Calc_ Type"', 'INTEGER') }}                  as PREPMT_VAT_CALC_TYPE,
        {{ std_cast('"Prepayment VAT Identifier"', 'VARCHAR') }}               as PREPAYMENT_VAT_IDENTIFIER,
        {{ std_cast('"Prepayment Tax Area Code"', 'VARCHAR') }}                as PREPAYMENT_TAX_AREA_CODE,
        {{ std_cast('"Prepayment Tax Liable"', 'INTEGER') }}                   as PREPAYMENT_TAX_LIABLE,
        {{ std_cast('"Prepayment Tax Group Code"', 'VARCHAR') }}               as PREPAYMENT_TAX_GROUP_CODE,
        {{ std_cast('"Prepmt Amt to Deduct"', 'NUMBER(38,5)') }}               as PREPMT_AMT_TO_DEDUCT,
        {{ std_cast('"Prepmt Amt Deducted"', 'NUMBER(38,5)') }}                as PREPMT_AMT_DEDUCTED,
        {{ std_cast('"Prepayment Line"', 'INTEGER') }}                         as PREPAYMENT_LINE,
        {{ std_cast('"Prepmt_ Amount Inv_ Incl_ VAT"', 'NUMBER(38,5)') }}      as PREPMT_AMOUNT_INV_INCL_VAT,
        {{ std_cast('"Prepmt_ Amount Inv_ (LCY)"', 'NUMBER(38,5)') }}          as PREPMT_AMOUNT_INV_LCY,
        {{ std_cast('"IC Partner Code"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"Prepmt_ VAT Amount Inv_ (LCY)"', 'NUMBER(38,5)') }}      as PREPMT_VAT_AMOUNT_INV_LCY,
        {{ std_cast('"Prepayment VAT Difference"', 'NUMBER(38,5)') }}          as PREPAYMENT_VAT_DIFFERENCE,
        {{ std_cast('"Prepmt VAT Diff_ to Deduct"', 'NUMBER(38,5)') }}         as PREPMT_VAT_DIFF_TO_DEDUCT,
        {{ std_cast('"Prepmt VAT Diff_ Deducted"', 'NUMBER(38,5)') }}          as PREPMT_VAT_DIFF_DEDUCTED,
        {{ std_cast('"Pmt_ Discount Amount"', 'NUMBER(38,5)') }}               as PMT_DISCOUNT_AMOUNT,
        {{ std_cast('"Line Discount Calculation"', 'INTEGER') }}               as LINE_DISCOUNT_CALCULATION,
        {{ std_cast('"Dimension Set ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"Qty_ to Assemble to Order"', 'NUMBER(38,5)') }}          as QTY_TO_ASSEMBLE_TO_ORDER,
        {{ std_cast('"Qty_ to Asm_ to Order (Base)"', 'NUMBER(38,5)') }}       as QTY_TO_ASM_TO_ORDER_BASE,
        {{ std_cast('"Job Task No_"', 'VARCHAR') }}                            as JOB_TASK_NO,
        {{ std_cast('"Job Contract Entry No_"', 'INTEGER') }}                  as JOB_CONTRACT_ENTRY_NO,
        {{ std_cast('"Deferral Code"', 'VARCHAR') }}                           as DEFERRAL_CODE,
        {{ std_cast('"Returns Deferral Start Date"', 'TIMESTAMP_NTZ') }}       as RETURNS_DEFERRAL_START_DATE,
        {{ std_cast('"Variant Code"', 'VARCHAR') }}                            as VARIANT_CODE,
        {{ std_cast('"Bin Code"', 'VARCHAR') }}                                as BIN_CODE,
        {{ std_cast('"Qty_ per Unit of Measure"', 'NUMBER(38,5)') }}           as QTY_PER_UNIT_OF_MEASURE,
        {{ std_cast('"Planned"', 'INTEGER') }}                                 as PLANNED,
        {{ std_cast('"Unit of Measure Code"', 'VARCHAR') }}                    as UNIT_OF_MEASURE_CODE,
        {{ std_cast('"Quantity (Base)"', 'NUMBER(38,5)') }}                    as QUANTITY_BASE,
        {{ std_cast('"Outstanding Qty_ (Base)"', 'NUMBER(38,5)') }}            as OUTSTANDING_QTY_BASE,
        {{ std_cast('"Qty_ to Invoice (Base)"', 'NUMBER(38,5)') }}             as QTY_TO_INVOICE_BASE,
        {{ std_cast('"Qty_ to Ship (Base)"', 'NUMBER(38,5)') }}                as QTY_TO_SHIP_BASE,
        {{ std_cast('"Qty_ Shipped Not Invd_ (Base)"', 'NUMBER(38,5)') }}      as QTY_SHIPPED_NOT_INVD_BASE,
        {{ std_cast('"Qty_ Shipped (Base)"', 'NUMBER(38,5)') }}                as QTY_SHIPPED_BASE,
        {{ std_cast('"Qty_ Invoiced (Base)"', 'NUMBER(38,5)') }}               as QTY_INVOICED_BASE,
        {{ std_cast('"FA Posting Date"', 'TIMESTAMP_NTZ') }}                   as FA_POSTING_DATE,
        {{ std_cast('"Depreciation Book Code"', 'VARCHAR') }}                  as DEPRECIATION_BOOK_CODE,
        {{ std_cast('"Depr_ until FA Posting Date"', 'INTEGER') }}             as DEPR_UNTIL_FA_POSTING_DATE,
        {{ std_cast('"Duplicate in Depreciation Book"', 'VARCHAR') }}          as DUPLICATE_IN_DEPRECIATION_BOOK,
        {{ std_cast('"Use Duplication List"', 'INTEGER') }}                    as USE_DUPLICATION_LIST,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"Out-of-Stock Substitution"', 'INTEGER') }}               as OUTOFSTOCK_SUBSTITUTION,
        {{ std_cast('"Originally Ordered No_"', 'VARCHAR') }}                  as ORIGINALLY_ORDERED_NO,
        {{ std_cast('"Originally Ordered Var_ Code"', 'VARCHAR') }}            as ORIGINALLY_ORDERED_VAR_CODE,
        {{ std_cast('"Cross-Reference No_"', 'VARCHAR') }}                     as CROSSREFERENCE_NO,
        {{ std_cast('"Unit of Measure (Cross Ref_)"', 'VARCHAR') }}            as UNIT_OF_MEASURE_CROSS_REF,
        {{ std_cast('"Cross-Reference Type"', 'INTEGER') }}                    as CROSSREFERENCE_TYPE,
        {{ std_cast('"Cross-Reference Type No_"', 'VARCHAR') }}                as CROSSREFERENCE_TYPE_NO,
        {{ std_cast('"Item Category Code"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"Nonstock"', 'INTEGER') }}                                as NONSTOCK,
        {{ std_cast('"Purchasing Code"', 'VARCHAR') }}                         as PURCHASING_CODE,
        {{ std_cast('"Product Group Code"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"Special Order"', 'INTEGER') }}                           as SPECIAL_ORDER,
        {{ std_cast('"Special Order Purchase No_"', 'VARCHAR') }}              as SPECIAL_ORDER_PURCHASE_NO,
        {{ std_cast('"Special Order Purch_ Line No_"', 'INTEGER') }}           as SPECIAL_ORDER_PURCH_LINE_NO,
        {{ std_cast('"Completely Shipped"', 'INTEGER') }}                      as COMPLETELY_SHIPPED,
        {{ std_cast('"Requested Delivery Date"', 'TIMESTAMP_NTZ') }}           as REQUESTED_DELIVERY_DATE,
        {{ std_cast('"Promised Delivery Date"', 'TIMESTAMP_NTZ') }}            as PROMISED_DELIVERY_DATE,
        {{ std_cast('"Shipping Time"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"Outbound Whse_ Handling Time"', 'VARCHAR') }}            as OUTBOUND_WHSE_HANDLING_TIME,
        {{ std_cast('"Planned Delivery Date"', 'TIMESTAMP_NTZ') }}             as PLANNED_DELIVERY_DATE,
        {{ std_cast('"Planned Shipment Date"', 'TIMESTAMP_NTZ') }}             as PLANNED_SHIPMENT_DATE,
        {{ std_cast('"Shipping Agent Code"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"Shipping Agent Service Code"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"Allow Item Charge Assignment"', 'INTEGER') }}            as ALLOW_ITEM_CHARGE_ASSIGNMENT,
        {{ std_cast('"Return Qty_ to Receive"', 'NUMBER(38,5)') }}             as RETURN_QTY_TO_RECEIVE,
        {{ std_cast('"Return Qty_ to Receive (Base)"', 'NUMBER(38,5)') }}      as RETURN_QTY_TO_RECEIVE_BASE,
        {{ std_cast('"Return Qty_ Rcd_ Not Invd_"', 'NUMBER(38,5)') }}         as RETURN_QTY_RCD_NOT_INVD,
        {{ std_cast('"Ret_ Qty_ Rcd_ Not Invd_(Base)"', 'NUMBER(38,5)') }}     as RET_QTY_RCD_NOT_INVD_BASE,
        {{ std_cast('"Return Rcd_ Not Invd_"', 'NUMBER(38,5)') }}              as RETURN_RCD_NOT_INVD,
        {{ std_cast('"Return Rcd_ Not Invd_ (LCY)"', 'NUMBER(38,5)') }}        as RETURN_RCD_NOT_INVD_LCY,
        {{ std_cast('"Return Qty_ Received"', 'NUMBER(38,5)') }}               as RETURN_QTY_RECEIVED,
        {{ std_cast('"Return Qty_ Received (Base)"', 'NUMBER(38,5)') }}        as RETURN_QTY_RECEIVED_BASE,
        {{ std_cast('"Appl_-from Item Entry"', 'INTEGER') }}                   as APPL_FROM_ITEM_ENTRY,
        {{ std_cast('"BOM Item No_"', 'VARCHAR') }}                            as BOM_ITEM_NO,
        {{ std_cast('"Return Receipt No_"', 'VARCHAR') }}                      as RETURN_RECEIPT_NO,
        {{ std_cast('"Return Receipt Line No_"', 'INTEGER') }}                 as RETURN_RECEIPT_LINE_NO,
        {{ std_cast('"Return Reason Code"', 'VARCHAR') }}                      as RETURN_REASON_CODE,
        {{ std_cast('"Copied From Posted Doc_"', 'INTEGER') }}                 as COPIED_FROM_POSTED_DOC,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        {{ std_cast('"Subtype"', 'INTEGER') }}                                 as SUBTYPE,
        {{ std_cast('"Price description"', 'VARCHAR') }}                       as PRICE_DESCRIPTION,
        {{ std_cast('"Pmt_ Disc_ Given Amount (Old)"', 'NUMBER(38,5)') }}      as PMT_DISC_GIVEN_AMOUNT_OLD,
        {{ std_cast('"EC _"', 'NUMBER(38,5)') }}                               as EC,
        {{ std_cast('"EC Difference"', 'NUMBER(38,5)') }}                      as EC_DIFFERENCE,
        {{ std_cast('"Prepayment EC _"', 'NUMBER(38,5)') }}                    as PREPAYMENT_EC,
        {{ std_cast('"IDPIRPF IRPF Group"', 'VARCHAR') }}                      as IDPIRPF_IRPF_GROUP,
        {{ std_cast('"IDPIRPF IRPF Amount"', 'NUMBER(38,5)') }}                as IDPIRPF_IRPF_AMOUNT,
        {{ std_cast('"IDPIRPF IRPF _"', 'NUMBER(38,5)') }}                     as IDPIRPF_IRPF,
        {{ std_cast('"IDPIRPF IRPF Base Amount"', 'NUMBER(38,5)') }}           as IDPIRPF_IRPF_BASE_AMOUNT,
        {{ std_cast('"IDPIRPF Amount incl_ IRPF"', 'NUMBER(38,5)') }}          as IDPIRPF_AMOUNT_INCL_IRPF,
        {{ std_cast('"IDPIRPF IRPF"', 'INTEGER') }}                            as IDPIRPF_IRPF,
        {{ std_cast('"IDPVUM Quantity"', 'NUMBER(38,5)') }}                    as IDPVUM_QUANTITY,
        {{ std_cast('"IDPVUM Unit of Measure Code"', 'VARCHAR') }}             as IDPVUM_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"IDPVUM Unit Price"', 'NUMBER(38,5)') }}                  as IDPVUM_UNIT_PRICE,
        {{ std_cast('"IDPVUM Price in VUM"', 'INTEGER') }}                     as IDPVUM_PRICE_IN_VUM,
        {{ std_cast('"IDPVUM VUM Per Unit"', 'NUMBER(38,5)') }}                as IDPVUM_VUM_PER_UNIT,
        {{ std_cast('"IDPVUM Outstanding Qty_"', 'NUMBER(38,5)') }}            as IDPVUM_OUTSTANDING_QTY,
        {{ std_cast('"IDPVUM Qty_ to Invoice"', 'NUMBER(38,5)') }}             as IDPVUM_QTY_TO_INVOICE,
        {{ std_cast('"IDPVUM Qty_ to Ship"', 'NUMBER(38,5)') }}                as IDPVUM_QTY_TO_SHIP,
        {{ std_cast('"IDPVUM Qty_ Shipped Not Inv_"', 'NUMBER(38,5)') }}       as IDPVUM_QTY_SHIPPED_NOT_INV,
        {{ std_cast('"IDPVUM Quantity Shipped"', 'NUMBER(38,5)') }}            as IDPVUM_QUANTITY_SHIPPED,
        {{ std_cast('"IDPVUM Quantity Invoiced"', 'NUMBER(38,5)') }}           as IDPVUM_QUANTITY_INVOICED,
        {{ std_cast('"IDPVUM Qty_ to Assble_ Order"', 'NUMBER(38,5)') }}       as IDPVUM_QTY_TO_ASSBLE_ORDER,
        {{ std_cast('"IDPVUM Return Qty_ to Receive"', 'NUMBER(38,5)') }}      as IDPVUM_RETURN_QTY_TO_RECEIVE,
        {{ std_cast('"IDPVUM Retn_ Qty_ Rd_ Not Inv_"', 'NUMBER(38,5)') }}     as IDPVUM_RETN_QTY_RD_NOT_INV,
        {{ std_cast('"IDPVUM Return Qty_ Received"', 'NUMBER(38,5)') }}        as IDPVUM_RETURN_QTY_RECEIVED,
        {{ std_cast('"IDPVUM Update Source"', 'INTEGER') }}                    as IDPVUM_UPDATE_SOURCE,
        {{ std_cast('"IDPGND SIG Amount"', 'NUMBER(38,5)') }}                  as IDPGND_SIG_AMOUNT,
        {{ std_cast('"IDPGND SIG Rate"', 'NUMBER(38,5)') }}                    as IDPGND_SIG_RATE,
        {{ std_cast('"IDPGND SIG"', 'INTEGER') }}                              as IDPGND_SIG,
        {{ std_cast('"IDPGND Posting Date Shipment"', 'TIMESTAMP_NTZ') }}      as IDPGND_POSTING_DATE_SHIPMENT,
        {{ std_cast('"IDPGND Shipment Date Shipment"', 'TIMESTAMP_NTZ') }}     as IDPGND_SHIPMENT_DATE_SHIPMENT,
        {{ std_cast('"IDPGND Req_ Del_ Date Shipment"', 'TIMESTAMP_NTZ') }}    as IDPGND_REQ_DEL_DATE_SHIPMENT,
        {{ std_cast('"IF_OR_TYPE"', 'VARCHAR') }}                              as IF_OR_TYPE,
        {{ std_cast('"IF_UNIT_PRICE_CODE"', 'VARCHAR') }}                      as IF_UNIT_PRICE_CODE,
        {{ std_cast('"IF_NUM_BOXES_NEEDED"', 'NUMBER(38,5)') }}                as IF_NUM_BOXES_NEEDED,
        {{ std_cast('"IF_NUM_CONT_NEEDED"', 'NUMBER(38,5)') }}                 as IF_NUM_CONT_NEEDED,
        {{ std_cast('"IF_DUN14"', 'VARCHAR') }}                                as IF_DUN14,
        {{ std_cast('"Sales Date"', 'TIMESTAMP_NTZ') }}                        as SALES_DATE,
        {{ std_cast('"Cerrado"', 'INTEGER') }}                                 as CERRADO,
        {{ std_cast('"TempQty"', 'NUMBER(38,5)') }}                            as TEMPQTY,
        {{ std_cast('"Original Quantity"', 'NUMBER(38,5)') }}                  as ORIGINAL_QUANTITY,
        {{ std_cast('"Original Quantity UMV"', 'NUMBER(38,5)') }}              as ORIGINAL_QUANTITY_UMV,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'DLS'                                                                     as tec_des_cod_siglas,
        'DELISANO'                                                             as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src