{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_SALES_SHIPMENT_HEADER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"Sell-to Customer No_"', 'VARCHAR') }}                    as SELLTO_CUSTOMER_NO,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"Bill-to Name"', 'VARCHAR') }}                            as BILLTO_NAME,
        {{ std_cast('"Bill-to Name 2"', 'VARCHAR') }}                          as BILLTO_NAME_2,
        {{ std_cast('"Bill-to Address"', 'VARCHAR') }}                         as BILLTO_ADDRESS,
        {{ std_cast('"Bill-to Address 2"', 'VARCHAR') }}                       as BILLTO_ADDRESS_2,
        {{ std_cast('"Bill-to City"', 'VARCHAR') }}                            as BILLTO_CITY,
        {{ std_cast('"Bill-to Contact"', 'VARCHAR') }}                         as BILLTO_CONTACT,
        {{ std_cast('"Your Reference"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        {{ std_cast('"Ship-to Code"', 'VARCHAR') }}                            as SHIPTO_CODE,
        {{ std_cast('"Ship-to Name"', 'VARCHAR') }}                            as SHIPTO_NAME,
        {{ std_cast('"Ship-to Name 2"', 'VARCHAR') }}                          as SHIPTO_NAME_2,
        {{ std_cast('"Ship-to Address"', 'VARCHAR') }}                         as SHIPTO_ADDRESS,
        {{ std_cast('"Ship-to Address 2"', 'VARCHAR') }}                       as SHIPTO_ADDRESS_2,
        {{ std_cast('"Ship-to City"', 'VARCHAR') }}                            as SHIPTO_CITY,
        {{ std_cast('"Ship-to Contact"', 'VARCHAR') }}                         as SHIPTO_CONTACT,
        {{ std_cast('"Order Date"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"Posting Date"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"Shipment Date"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"Posting Description"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"Payment Terms Code"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"Due Date"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"Payment Discount _"', 'NUMBER(38,5)') }}                 as PAYMENT_DISCOUNT,
        {{ std_cast('"Pmt_ Discount Date"', 'TIMESTAMP_NTZ') }}                as PMT_DISCOUNT_DATE,
        {{ std_cast('"Shipment Method Code"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Shortcut Dimension 1 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"Shortcut Dimension 2 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"Customer Posting Group"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"Currency Code"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"Currency Factor"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Prices Including VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"Invoice Disc_ Code"', 'VARCHAR') }}                      as INVOICE_DISC_CODE,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        {{ std_cast('"Language Code"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"Salesperson Code"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"Order No_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"No_ Printed"', 'INTEGER') }}                             as NO_PRINTED,
        {{ std_cast('"On Hold"', 'VARCHAR') }}                                 as ON_HOLD,
        {{ std_cast('"Applies-to Doc_ Type"', 'INTEGER') }}                    as APPLIESTO_DOC_TYPE,
        {{ std_cast('"Applies-to Doc_ No_"', 'VARCHAR') }}                     as APPLIESTO_DOC_NO,
        {{ std_cast('"Bal_ Account No_"', 'VARCHAR') }}                        as BAL_ACCOUNT_NO,
        {{ std_cast('"VAT Registration No_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"Reason Code"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"EU 3-Party Trade"', 'INTEGER') }}                        as EU_3PARTY_TRADE,
        {{ std_cast('"Transaction Type"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"Transport Method"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT Country_Region Code"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        {{ std_cast('"Sell-to Customer Name"', 'VARCHAR') }}                   as SELLTO_CUSTOMER_NAME,
        {{ std_cast('"Sell-to Customer Name 2"', 'VARCHAR') }}                 as SELLTO_CUSTOMER_NAME_2,
        {{ std_cast('"Sell-to Address"', 'VARCHAR') }}                         as SELLTO_ADDRESS,
        {{ std_cast('"Sell-to Address 2"', 'VARCHAR') }}                       as SELLTO_ADDRESS_2,
        {{ std_cast('"Sell-to City"', 'VARCHAR') }}                            as SELLTO_CITY,
        {{ std_cast('"Sell-to Contact"', 'VARCHAR') }}                         as SELLTO_CONTACT,
        {{ std_cast('"Bill-to Post Code"', 'VARCHAR') }}                       as BILLTO_POST_CODE,
        {{ std_cast('"Bill-to County"', 'VARCHAR') }}                          as BILLTO_COUNTY,
        {{ std_cast('"Bill-to Country_Region Code"', 'VARCHAR') }}             as BILLTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Sell-to Post Code"', 'VARCHAR') }}                       as SELLTO_POST_CODE,
        {{ std_cast('"Sell-to County"', 'VARCHAR') }}                          as SELLTO_COUNTY,
        {{ std_cast('"Sell-to Country_Region Code"', 'VARCHAR') }}             as SELLTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Ship-to Post Code"', 'VARCHAR') }}                       as SHIPTO_POST_CODE,
        {{ std_cast('"Ship-to County"', 'VARCHAR') }}                          as SHIPTO_COUNTY,
        {{ std_cast('"Ship-to Country_Region Code"', 'VARCHAR') }}             as SHIPTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Bal_ Account Type"', 'INTEGER') }}                       as BAL_ACCOUNT_TYPE,
        {{ std_cast('"Exit Point"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"Correction"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"Document Date"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"External Document No_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"Area"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"Transaction Specification"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"Payment Method Code"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"Shipping Agent Code"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"Package Tracking No_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        {{ std_cast('"No_ Series"', 'VARCHAR') }}                              as NO_SERIES,
        {{ std_cast('"Order No_ Series"', 'VARCHAR') }}                        as ORDER_NO_SERIES,
        {{ std_cast('"User ID"', 'VARCHAR') }}                                 as USER_ID,
        {{ std_cast('"Source Code"', 'VARCHAR') }}                             as SOURCE_CODE,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT Base Discount _"', 'NUMBER(38,5)') }}                as VAT_BASE_DISCOUNT,
        {{ std_cast('"Quote No_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"Dimension Set ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"Campaign No_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        {{ std_cast('"Sell-to Contact No_"', 'VARCHAR') }}                     as SELLTO_CONTACT_NO,
        {{ std_cast('"Bill-to Contact No_"', 'VARCHAR') }}                     as BILLTO_CONTACT_NO,
        {{ std_cast('"Opportunity No_"', 'VARCHAR') }}                         as OPPORTUNITY_NO,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"Requested Delivery Date"', 'TIMESTAMP_NTZ') }}           as REQUESTED_DELIVERY_DATE,
        {{ std_cast('"Promised Delivery Date"', 'TIMESTAMP_NTZ') }}            as PROMISED_DELIVERY_DATE,
        {{ std_cast('"Shipping Time"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"Outbound Whse_ Handling Time"', 'VARCHAR') }}            as OUTBOUND_WHSE_HANDLING_TIME,
        {{ std_cast('"Shipping Agent Service Code"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Applies-to Bill No_"', 'VARCHAR') }}                     as APPLIESTO_BILL_NO,
        {{ std_cast('"Cust_ Bank Acc_ Code"', 'VARCHAR') }}                    as CUST_BANK_ACC_CODE,
        {{ std_cast('"Pay-at Code"', 'VARCHAR') }}                             as PAYAT_CODE,
        {{ std_cast('"Sell-to Phone No_"', 'VARCHAR') }}                       as SELLTO_PHONE_NO,
        {{ std_cast('"Sell-to E-Mail"', 'VARCHAR') }}                          as SELLTO_EMAIL,
        {{ std_cast('"IDPGND Ship-to Excl_ SIG Rate"', 'INTEGER') }}           as IDPGND_SHIPTO_EXCL_SIG_RATE,
        {{ std_cast('"IDPVSH Invoice Discount Value"', 'NUMBER(38,5)') }}      as IDPVSH_INVOICE_DISCOUNT_VALUE,
        {{ std_cast('"IF_OR_TYPE"', 'VARCHAR') }}                              as IF_OR_TYPE,
        {{ std_cast('"IF_DATA_1"', 'VARCHAR') }}                               as IF_DATA_1,
        {{ std_cast('"IF_DATA_2"', 'VARCHAR') }}                               as IF_DATA_2,
        {{ std_cast('"IF_DATA_3"', 'VARCHAR') }}                               as IF_DATA_3,
        {{ std_cast('"IF_DATA_4"', 'VARCHAR') }}                               as IF_DATA_4,
        {{ std_cast('"IF_DATA_5"', 'VARCHAR') }}                               as IF_DATA_5,
        {{ std_cast('"IF_ML_TIME"', 'TIMESTAMP_NTZ') }}                        as IF_ML_TIME,
        {{ std_cast('"IF_SAE_CERTIFICATION"', 'VARCHAR') }}                    as IF_SAE_CERTIFICATION,
        {{ std_cast('"CO_ID_CONT"', 'VARCHAR') }}                              as CO_ID_CONT,
        {{ std_cast('"CO_ID_PREC"', 'VARCHAR') }}                              as CO_ID_PREC,
        {{ std_cast('"TotalNetWeight"', 'NUMBER(38,5)') }}                     as TOTALNETWEIGHT,
        {{ std_cast('"TotalGrossWeight"', 'NUMBER(38,5)') }}                   as TOTALGROSSWEIGHT,
        {{ std_cast('"PackagesPalletNumber"', 'INTEGER') }}                    as PACKAGESPALLETNUMBER,
        {{ std_cast('"PackagesNumber"', 'INTEGER') }}                          as PACKAGESNUMBER,
        {{ std_cast('"Cerrado"', 'INTEGER') }}                                 as CERRADO,
        {{ std_cast('"AIT Billing Address Code"', 'VARCHAR') }}                as AIT_BILLING_ADDRESS_CODE,
        {{ std_cast('"AIT Creation User"', 'VARCHAR') }}                       as AIT_CREATION_USER,
        {{ std_cast('"AIT Creation Datetime"', 'TIMESTAMP_NTZ') }}             as AIT_CREATION_DATETIME,
        {{ std_cast('"IDPEDI DESADV"', 'INTEGER') }}                           as IDPEDI_DESADV,
        {{ std_cast('"IDPEDI DESADV Sent"', 'INTEGER') }}                      as IDPEDI_DESADV_SENT,
        {{ std_cast('"IDPEDI RECADV"', 'INTEGER') }}                           as IDPEDI_RECADV,
        {{ std_cast('"IDPEDI RECADV Accepted"', 'INTEGER') }}                  as IDPEDI_RECADV_ACCEPTED,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'DLS'                                                                     as tec_des_cod_siglas,
        'DELISANO'                                                             as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src