{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_CUSTOMER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"NAME"', 'VARCHAR') }}                                    as NAME,
        {{ std_cast('"SEARCH_NAME"', 'VARCHAR') }}                             as SEARCH_NAME,
        {{ std_cast('"NAME_2"', 'VARCHAR') }}                                  as NAME_2,
        {{ std_cast('"ADDRESS"', 'VARCHAR') }}                                 as ADDRESS,
        {{ std_cast('"ADDRESS_2"', 'VARCHAR') }}                               as ADDRESS_2,
        {{ std_cast('"CITY"', 'VARCHAR') }}                                    as CITY,
        {{ std_cast('"CONTACT"', 'VARCHAR') }}                                 as CONTACT,
        {{ std_cast('"PHONE_NO_"', 'VARCHAR') }}                               as PHONE_NO,
        {{ std_cast('"TELEX_NO_"', 'VARCHAR') }}                               as TELEX_NO,
        {{ std_cast('"DOCUMENT_SENDING_PROFILE"', 'VARCHAR') }}                as DOCUMENT_SENDING_PROFILE,
        {{ std_cast('"OUR_ACCOUNT_NO_"', 'VARCHAR') }}                         as OUR_ACCOUNT_NO,
        {{ std_cast('"TERRITORY_CODE"', 'VARCHAR') }}                          as TERRITORY_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_1_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_2_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"CHAIN_NAME"', 'VARCHAR') }}                              as CHAIN_NAME,
        {{ std_cast('"BUDGETED_AMOUNT"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"CREDIT_LIMIT_LCY"', 'NUMBER(38,5)') }}                   as CREDIT_LIMIT_LCY,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"STATISTICS_GROUP"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"FIN_CHARGE_TERMS_CODE"', 'VARCHAR') }}                   as FIN_CHARGE_TERMS_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PLACE_OF_EXPORT"', 'VARCHAR') }}                         as PLACE_OF_EXPORT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"COUNTRY_REGION_CODE"', 'VARCHAR') }}                     as COUNTRY_REGION_CODE,
        {{ std_cast('"COLLECTION_METHOD"', 'VARCHAR') }}                       as COLLECTION_METHOD,
        {{ std_cast('"AMOUNT"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"BLOCKED"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"INVOICE_COPIES"', 'INTEGER') }}                          as INVOICE_COPIES,
        {{ std_cast('"LAST_STATEMENT_NO_"', 'INTEGER') }}                      as LAST_STATEMENT_NO,
        {{ std_cast('"PRINT_STATEMENTS"', 'INTEGER') }}                        as PRINT_STATEMENTS,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"PRIORITY"', 'INTEGER') }}                                as PRIORITY,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"LAST_DATE_MODIFIED"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"APPLICATION_METHOD"', 'INTEGER') }}                      as APPLICATION_METHOD,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"FAX_NO_"', 'VARCHAR') }}                                 as FAX_NO,
        {{ std_cast('"TELEX_ANSWER_BACK"', 'VARCHAR') }}                       as TELEX_ANSWER_BACK,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"COMBINE_SHIPMENTS"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GLN"', 'VARCHAR') }}                                     as GLN,
        {{ std_cast('"POST_CODE"', 'VARCHAR') }}                               as POST_CODE,
        {{ std_cast('"COUNTY"', 'VARCHAR') }}                                  as COUNTY,
        {{ std_cast('"E_MAIL"', 'VARCHAR') }}                                  as E_MAIL,
        {{ std_cast('"HOME_PAGE"', 'VARCHAR') }}                               as HOME_PAGE,
        {{ std_cast('"REMINDER_TERMS_CODE"', 'VARCHAR') }}                     as REMINDER_TERMS_CODE,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"BLOCK_PAYMENT_TOLERANCE"', 'INTEGER') }}                 as BLOCK_PAYMENT_TOLERANCE,
        {{ std_cast('"IC_PARTNER_CODE"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"PREPAYMENT_"', 'NUMBER(38,5)') }}                        as PREPAYMENT,
        {{ std_cast('"PARTNER_TYPE"', 'INTEGER') }}                            as PARTNER_TYPE,
        {{ std_cast('"PRIVACY_BLOCKED"', 'INTEGER') }}                         as PRIVACY_BLOCKED,
        {{ std_cast('"PREFERRED_BANK_ACCOUNT_CODE"', 'VARCHAR') }}             as PREFERRED_BANK_ACCOUNT_CODE,
        {{ std_cast('"CASH_FLOW_PAYMENT_TERMS_CODE"', 'VARCHAR') }}            as CASH_FLOW_PAYMENT_TERMS_CODE,
        {{ std_cast('"PRIMARY_CONTACT_NO_"', 'VARCHAR') }}                     as PRIMARY_CONTACT_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"SHIPPING_ADVICE"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"SHIPPING_TIME"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"SHIPPING_AGENT_SERVICE_CODE"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"SERVICE_ZONE_CODE"', 'VARCHAR') }}                       as SERVICE_ZONE_CODE,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"BASE_CALENDAR_CODE"', 'VARCHAR') }}                      as BASE_CALENDAR_CODE,
        {{ std_cast('"COPY_SELL_TO_ADDR_TO_QTE_FROM"', 'INTEGER') }}           as COPY_SELL_TO_ADDR_TO_QTE_FROM,
        {{ std_cast('"PAYMENT_DAYS_CODE"', 'VARCHAR') }}                       as PAYMENT_DAYS_CODE,
        {{ std_cast('"NON_PAYMT_PERIODS_CODE"', 'VARCHAR') }}                  as NON_PAYMT_PERIODS_CODE,
        {{ std_cast('"NOT_IN_AEAT"', 'INTEGER') }}                             as NOT_IN_AEAT,
        {{ std_cast('"ENVIAR_FACTURA_POR_E_MAIL"', 'INTEGER') }}               as ENVIAR_FACTURA_POR_E_MAIL,
        {{ std_cast('"FACTURA_EN_PAPEL"', 'INTEGER') }}                        as FACTURA_EN_PAPEL,
        {{ std_cast('"AGRUPAR_POR_DIRECCION_ENVIO"', 'INTEGER') }}             as AGRUPAR_POR_DIRECCION_ENVIO,
        {{ std_cast('"COD_CADENA"', 'VARCHAR') }}                              as COD_CADENA,
        {{ std_cast('"COD_DTO_LINEA"', 'VARCHAR') }}                           as COD_DTO_LINEA,
        {{ std_cast('"PROMOCIONES_POR"', 'INTEGER') }}                         as PROMOCIONES_POR,
        {{ std_cast('"TIPO_PUNTO_VERDE"', 'INTEGER') }}                        as TIPO_PUNTO_VERDE,
        {{ std_cast('"TIPO_RESIDUOS"', 'INTEGER') }}                           as TIPO_RESIDUOS,
        {{ std_cast('"COD_RUTA"', 'VARCHAR') }}                                as COD_RUTA,
        {{ std_cast('"NO_PROVEEDOR_RELACIONADO"', 'VARCHAR') }}                as NO_PROVEEDOR_RELACIONADO,
        {{ std_cast('"COMISIONES_POR"', 'INTEGER') }}                          as COMISIONES_POR,
        {{ std_cast('"FECHA_ALTA"', 'TIMESTAMP_NTZ') }}                        as FECHA_ALTA,
        {{ std_cast('"USUARIO_ALTA"', 'VARCHAR') }}                            as USUARIO_ALTA,
        {{ std_cast('"GENERAR_SSCC_EN_PALET"', 'INTEGER') }}                   as GENERAR_SSCC_EN_PALET,
        {{ std_cast('"COD_IDIOMA_ETIQUETAJE"', 'VARCHAR') }}                   as COD_IDIOMA_ETIQUETAJE,
        {{ std_cast('"COD_IFCO"', 'VARCHAR') }}                                as COD_IFCO,
        {{ std_cast('"HORARIO_ENTREGA"', 'VARCHAR') }}                         as HORARIO_ENTREGA,
        {{ std_cast('"NATURALEZA_PRODUCTO"', 'VARCHAR') }}                     as NATURALEZA_PRODUCTO,
        {{ std_cast('"E_MAIL_ENVIO_ALBARAN"', 'VARCHAR') }}                    as E_MAIL_ENVIO_ALBARAN,
        {{ std_cast('"E_MAIL_ORDEN_RECOGIDA"', 'VARCHAR') }}                   as E_MAIL_ORDEN_RECOGIDA,
        {{ std_cast('"OBSERVACIONES_PICKING"', 'VARCHAR') }}                   as OBSERVACIONES_PICKING,
        {{ std_cast('"LOTE_CRECIENTE"', 'INTEGER') }}                          as LOTE_CRECIENTE,
        {{ std_cast('"ZONA_TRANSPORTE"', 'VARCHAR') }}                         as ZONA_TRANSPORTE,
        {{ std_cast('"COD_EUROPOOL"', 'VARCHAR') }}                            as COD_EUROPOOL,
        {{ std_cast('"DEFAULT_SHIP_TO_CODE"', 'VARCHAR') }}                    as DEFAULT_SHIP_TO_CODE,
        {{ std_cast('"DOC_TRANSPORTE"', 'INTEGER') }}                          as DOC_TRANSPORTE,
        {{ std_cast('"ALBARAN_POR_LOTES"', 'INTEGER') }}                       as ALBARAN_POR_LOTES,
        {{ std_cast('"TIPO_CLIENTE"', 'INTEGER') }}                            as TIPO_CLIENTE,
        {{ std_cast('"EAN128_ETIQUETA"', 'VARCHAR') }}                         as EAN128_ETIQUETA,
        {{ std_cast('"FACTURA_CONTADO_AUTOMATICA"', 'INTEGER') }}              as FACTURA_CONTADO_AUTOMATICA,
        {{ std_cast('"PLAZO_ENTREGA"', 'VARCHAR') }}                           as PLAZO_ENTREGA,
        {{ std_cast('"COD_PALET_DEFECTO"', 'VARCHAR') }}                       as COD_PALET_DEFECTO,
        {{ std_cast('"NO_LOTES_MAX_EN_EXPEDICION"', 'INTEGER') }}              as NO_LOTES_MAX_EN_EXPEDICION,
        {{ std_cast('"COD_CHEP"', 'VARCHAR') }}                                as COD_CHEP,
        {{ std_cast('"EXCLUIR_COBRO_TRAZA_PALETS"', 'INTEGER') }}              as EXCLUIR_COBRO_TRAZA_PALETS,
        {{ std_cast('"MEZCLA_PROD_EN_EMBALAJE"', 'INTEGER') }}                 as MEZCLA_PROD_EN_EMBALAJE,
        {{ std_cast('"COD_EMBALAJE_DEFECTO"', 'VARCHAR') }}                    as COD_EMBALAJE_DEFECTO,
        {{ std_cast('"NO_COPIAS"', 'INTEGER') }}                               as NO_COPIAS,
        {{ std_cast('"NOMBRE_COMERCIAL"', 'VARCHAR') }}                        as NOMBRE_COMERCIAL,
        {{ std_cast('"CYC"', 'INTEGER') }}                                     as CYC,
        {{ std_cast('"EDI_REF_PEDIDO"', 'VARCHAR') }}                          as EDI_REF_PEDIDO,
        {{ std_cast('"EDI_REF_ALBARAN"', 'VARCHAR') }}                         as EDI_REF_ALBARAN,
        {{ std_cast('"EDI_INF_ADICIONAL_PORTUGAL"', 'INTEGER') }}              as EDI_INF_ADICIONAL_PORTUGAL,
        {{ std_cast('"EDI_REF_FACTURA"', 'VARCHAR') }}                         as EDI_REF_FACTURA,
        {{ std_cast('"EDI_REF_PAGO"', 'VARCHAR') }}                            as EDI_REF_PAGO,
        {{ std_cast('"EDI_REF_DEPARTAMENTO"', 'VARCHAR') }}                    as EDI_REF_DEPARTAMENTO,
        {{ std_cast('"EDI_CLIENTE_DEL_GRUPO_ALCAMPO"', 'INTEGER') }}           as EDI_CLIENTE_DEL_GRUPO_ALCAMPO,
        {{ std_cast('"EDI_PROVEEDOR"', 'VARCHAR') }}                           as EDI_PROVEEDOR,
        {{ std_cast('"EDI_CLIENTE_UNIDE"', 'INTEGER') }}                       as EDI_CLIENTE_UNIDE,
        {{ std_cast('"EDI_REF_EUROMADI"', 'VARCHAR') }}                        as EDI_REF_EUROMADI,
        {{ std_cast('"EDI_FRANCIA"', 'INTEGER') }}                             as EDI_FRANCIA,
        {{ std_cast('"EDI_CARREFOUR"', 'INTEGER') }}                           as EDI_CARREFOUR,
        {{ std_cast('"EDI_CODIGO_GUVERNAMENTAL"', 'VARCHAR') }}                as EDI_CODIGO_GUVERNAMENTAL,
        {{ std_cast('"EDI_CIP"', 'VARCHAR') }}                                 as EDI_CIP,
        {{ std_cast('"ALBARAN_VALORADO"', 'INTEGER') }}                        as ALBARAN_VALORADO,
        {{ std_cast('"TIPO_FACTURACION"', 'INTEGER') }}                        as TIPO_FACTURACION,
        {{ std_cast('"FACTURA_POR_ALBARAN"', 'INTEGER') }}                     as FACTURA_POR_ALBARAN,
        {{ std_cast('"SU_CODIGO"', 'VARCHAR') }}                               as SU_CODIGO,
        {{ std_cast('"SPLIT_SHIP_TO_ADD_"', 'INTEGER') }}                      as SPLIT_SHIP_TO_ADD,
        {{ std_cast('"_DTO_FACTURA"', 'NUMBER(38,5)') }}                       as DTO_FACTURA,
        {{ std_cast('"COD_BANCO"', 'VARCHAR') }}                               as COD_BANCO,
        {{ std_cast('"NOMBRE_CONTACTO_PAGOS"', 'VARCHAR') }}                   as NOMBRE_CONTACTO_PAGOS,
        {{ std_cast('"COD_CONTACTO_PAGOS"', 'VARCHAR') }}                      as COD_CONTACTO_PAGOS,
        {{ std_cast('"RESPONSABLE_PAGOS_EMPRESA"', 'VARCHAR') }}               as RESPONSABLE_PAGOS_EMPRESA,
        {{ std_cast('"COMMISSION_CUSTOMER_GROUP"', 'VARCHAR') }}               as COMMISSION_CUSTOMER_GROUP,
        {{ std_cast('"SECOND_SALESPERSON_CODE"', 'VARCHAR') }}                 as SECOND_SALESPERSON_CODE,
        {{ std_cast('"INCOME_TAX_RETENTION_CODE"', 'VARCHAR') }}               as INCOME_TAX_RETENTION_CODE,
        {{ std_cast('"INCOME_TAX_RETENTION_"', 'NUMBER(38,5)') }}              as INCOME_TAX_RETENTION,
        {{ std_cast('"INCOME_TAX_RETENTION_KEY"', 'VARCHAR') }}                as INCOME_TAX_RETENTION_KEY,
        {{ std_cast('"INCOME_TAX_RETENTION_SUBKEY"', 'VARCHAR') }}             as INCOME_TAX_RETENTION_SUBKEY,
        {{ std_cast('"SIN_CONTROL_PALET_EXPEDICION"', 'INTEGER') }}            as SIN_CONTROL_PALET_EXPEDICION,
        {{ std_cast('"EXPORTAR_TRAZABILIDAD"', 'INTEGER') }}                   as EXPORTAR_TRAZABILIDAD,
        {{ std_cast('"ENVIAR_PRECIOS_POR_E_MAIL"', 'INTEGER') }}               as ENVIAR_PRECIOS_POR_E_MAIL,
        {{ std_cast('"E_MAIL_ENVIO_PRECIOS"', 'VARCHAR') }}                    as E_MAIL_ENVIO_PRECIOS,
        {{ std_cast('"ULT_ENVIO_PRECIOS_EMAIL"', 'TIMESTAMP_NTZ') }}           as ULT_ENVIO_PRECIOS_EMAIL,
        {{ std_cast('"IMPRIMIR_BULTOS"', 'INTEGER') }}                         as IMPRIMIR_BULTOS,
        {{ std_cast('"COD_TRATAMIENTO_COMERCIAL"', 'VARCHAR') }}               as COD_TRATAMIENTO_COMERCIAL,
        {{ std_cast('"MOSTRAR_SALDO_EMBALAJES"', 'INTEGER') }}                 as MOSTRAR_SALDO_EMBALAJES,
        {{ std_cast('"EORI_NUMBER"', 'VARCHAR') }}                             as EORI_NUMBER,
        {{ std_cast('"NO_CESCE"', 'VARCHAR') }}                                as NO_CESCE,
        {{ std_cast('"ERROR_AL_ENVIAR_PRECIOS"', 'INTEGER') }}                 as ERROR_AL_ENVIAR_PRECIOS,
        {{ std_cast('"ENVIAR_EXCEL_ALBARAN_E_MAIL"', 'INTEGER') }}             as ENVIAR_EXCEL_ALBARAN_E_MAIL,
        {{ std_cast('"E_MAIL_ENVIO_ALBARAN_TRAZ"', 'VARCHAR') }}               as E_MAIL_ENVIO_ALBARAN_TRAZ,
        {{ std_cast('"EDI_HORA_ENTREGA"', 'TIMESTAMP_NTZ') }}                  as EDI_HORA_ENTREGA,
        {{ std_cast('"DATOS_PIE_ALBARAN_1"', 'VARCHAR') }}                     as DATOS_PIE_ALBARAN_1,
        {{ std_cast('"DATOS_PIE_ALBARAN_2"', 'VARCHAR') }}                     as DATOS_PIE_ALBARAN_2,
        {{ std_cast('"DISABLE_DAYS_MARGIN"', 'INTEGER') }}                     as DISABLE_DAYS_MARGIN,
        {{ std_cast('"SUBSET_1"', 'VARCHAR') }}                                as SUBSET_1,
        {{ std_cast('"SUBSET_2"', 'VARCHAR') }}                                as SUBSET_2,
        {{ std_cast('"SUBSET_3"', 'VARCHAR') }}                                as SUBSET_3,
        {{ std_cast('"SUBSET_4"', 'VARCHAR') }}                                as SUBSET_4,
        {{ std_cast('"SUBSET_5"', 'VARCHAR') }}                                as SUBSET_5,
        {{ std_cast('"SUBSET_6"', 'VARCHAR') }}                                as SUBSET_6,
        {{ std_cast('"SUBSET_7"', 'VARCHAR') }}                                as SUBSET_7,
        {{ std_cast('"SUBSET_8"', 'VARCHAR') }}                                as SUBSET_8,
        {{ std_cast('"SUBSET_9"', 'VARCHAR') }}                                as SUBSET_9,
        {{ std_cast('"SUBSET_10"', 'VARCHAR') }}                               as SUBSET_10,
        {{ std_cast('"PREFIJO_EMPRESA_EAN_UCC"', 'VARCHAR') }}                 as PREFIJO_EMPRESA_EAN_UCC,
        {{ std_cast('"USE_GLN_IN_ELECTRONIC_DOCUMENT"', 'INTEGER') }}          as USE_GLN_IN_ELECTRONIC_DOCUMENT,
        {{ std_cast('"DAYS_FOR_SEND_INVOICE"', 'INTEGER') }}                   as DAYS_FOR_SEND_INVOICE,
        {{ std_cast('"VAT_DOC_TYPE"', 'INTEGER') }}                            as VAT_DOC_TYPE,
        {{ std_cast('"SII_COUNTRY_CODE"', 'VARCHAR') }}                        as SII_COUNTRY_CODE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        {{ std_cast('"INVOICE_BLOCKED"', 'INTEGER') }}                         as INVOICE_BLOCKED,
        {{ std_cast('"INVOICE_TO_DAY"', 'INTEGER') }}                          as INVOICE_TO_DAY,
        {{ std_cast('"ONLY_UPPER_PACKAGE_LEVEL"', 'INTEGER') }}                as ONLY_UPPER_PACKAGE_LEVEL,
        {{ std_cast('"COMPLETE_BOX"', 'INTEGER') }}                            as COMPLETE_BOX,
        {{ std_cast('"W_PALLET_LABEL"', 'INTEGER') }}                          as W_PALLET_LABEL,
        {{ std_cast('"EXTERNAL_DOC_NO_MANDATORY"', 'INTEGER') }}               as EXTERNAL_DOC_NO_MANDATORY,
        {{ std_cast('"ONLY_PERSONALIZED_PRICES"', 'INTEGER') }}                as ONLY_PERSONALIZED_PRICES,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'FRI'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
