{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_CLIENTES') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"timestamp"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"Name"', 'VARCHAR') }}                                    as NAME,
        {{ std_cast('"Search Name"', 'VARCHAR') }}                             as SEARCH_NAME,
        {{ std_cast('"Name 2"', 'VARCHAR') }}                                  as NAME_2,
        {{ std_cast('"Address"', 'VARCHAR') }}                                 as ADDRESS,
        {{ std_cast('"Address 2"', 'VARCHAR') }}                               as ADDRESS_2,
        {{ std_cast('"City"', 'VARCHAR') }}                                    as CITY,
        {{ std_cast('"Contact"', 'VARCHAR') }}                                 as CONTACT,
        {{ std_cast('"Phone No_"', 'VARCHAR') }}                               as PHONE_NO,
        {{ std_cast('"Telex No_"', 'VARCHAR') }}                               as TELEX_NO,
        {{ std_cast('"Document Sending Profile"', 'VARCHAR') }}                as DOCUMENT_SENDING_PROFILE,
        {{ std_cast('"Our Account No_"', 'VARCHAR') }}                         as OUR_ACCOUNT_NO,
        {{ std_cast('"Territory Code"', 'VARCHAR') }}                          as TERRITORY_CODE,
        {{ std_cast('"Global Dimension 1 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"Global Dimension 2 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"Chain Name"', 'VARCHAR') }}                              as CHAIN_NAME,
        {{ std_cast('"Budgeted Amount"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"Credit Limit (LCY)"', 'NUMBER(38,5)') }}                 as CREDIT_LIMIT_LCY,
        {{ std_cast('"Customer Posting Group"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"Currency Code"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Language Code"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"Statistics Group"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"Payment Terms Code"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"Fin_ Charge Terms Code"', 'VARCHAR') }}                  as FIN_CHARGE_TERMS_CODE,
        {{ std_cast('"Salesperson Code"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"Shipment Method Code"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"Shipping Agent Code"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"Place of Export"', 'VARCHAR') }}                         as PLACE_OF_EXPORT,
        {{ std_cast('"Invoice Disc_ Code"', 'VARCHAR') }}                      as INVOICE_DISC_CODE,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        {{ std_cast('"Country_Region Code"', 'VARCHAR') }}                     as COUNTRY_REGION_CODE,
        {{ std_cast('"Collection Method"', 'VARCHAR') }}                       as COLLECTION_METHOD,
        {{ std_cast('"Amount"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"Blocked"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"Invoice Copies"', 'INTEGER') }}                          as INVOICE_COPIES,
        {{ std_cast('"Last Statement No_"', 'INTEGER') }}                      as LAST_STATEMENT_NO,
        {{ std_cast('"Print Statements"', 'INTEGER') }}                        as PRINT_STATEMENTS,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"Priority"', 'INTEGER') }}                                as PRIORITY,
        {{ std_cast('"Payment Method Code"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"Last Modified Date Time"', 'TIMESTAMP_NTZ') }}           as LAST_MODIFIED_DATE_TIME,
        {{ std_cast('"Last Date Modified"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"Application Method"', 'INTEGER') }}                      as APPLICATION_METHOD,
        {{ std_cast('"Prices Including VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Fax No_"', 'VARCHAR') }}                                 as FAX_NO,
        {{ std_cast('"Telex Answer Back"', 'VARCHAR') }}                       as TELEX_ANSWER_BACK,
        {{ std_cast('"VAT Registration No_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"Combine Shipments"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GLN"', 'VARCHAR') }}                                     as GLN,
        {{ std_cast('"Post Code"', 'VARCHAR') }}                               as POST_CODE,
        {{ std_cast('"County"', 'VARCHAR') }}                                  as COUNTY,
        {{ std_cast('"E-Mail"', 'VARCHAR') }}                                  as EMAIL,
        {{ std_cast('"Home Page"', 'VARCHAR') }}                               as HOME_PAGE,
        {{ std_cast('"Reminder Terms Code"', 'VARCHAR') }}                     as REMINDER_TERMS_CODE,
        {{ std_cast('"No_ Series"', 'VARCHAR') }}                              as NO_SERIES,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"Reserve"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"Block Payment Tolerance"', 'INTEGER') }}                 as BLOCK_PAYMENT_TOLERANCE,
        {{ std_cast('"IC Partner Code"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"Prepayment _"', 'NUMBER(38,5)') }}                       as PREPAYMENT,
        {{ std_cast('"Partner Type"', 'INTEGER') }}                            as PARTNER_TYPE,
        {{ std_cast('"Image"', 'VARCHAR') }}                                   as IMAGE,
        {{ std_cast('"Privacy Blocked"', 'INTEGER') }}                         as PRIVACY_BLOCKED,
        {{ std_cast('"Preferred Bank Account Code"', 'VARCHAR') }}             as PREFERRED_BANK_ACCOUNT_CODE,
        {{ std_cast('"Cash Flow Payment Terms Code"', 'VARCHAR') }}            as CASH_FLOW_PAYMENT_TERMS_CODE,
        {{ std_cast('"Primary Contact No_"', 'VARCHAR') }}                     as PRIMARY_CONTACT_NO,
        {{ std_cast('"Contact Type"', 'INTEGER') }}                            as CONTACT_TYPE,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"Shipping Advice"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"Shipping Time"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"Shipping Agent Service Code"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"Service Zone Code"', 'VARCHAR') }}                       as SERVICE_ZONE_CODE,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Base Calendar Code"', 'VARCHAR') }}                      as BASE_CALENDAR_CODE,
        {{ std_cast('"Copy Sell-to Addr_ to Qte From"', 'INTEGER') }}          as COPY_SELLTO_ADDR_TO_QTE_FROM,
        {{ std_cast('"Validate EU Vat Reg_ No_"', 'INTEGER') }}                as VALIDATE_EU_VAT_REG_NO,
        {{ std_cast('"Id"', 'VARCHAR') }}                                      as ID,
        {{ std_cast('"Currency Id"', 'VARCHAR') }}                             as CURRENCY_ID,
        {{ std_cast('"Payment Terms Id"', 'VARCHAR') }}                        as PAYMENT_TERMS_ID,
        {{ std_cast('"Shipment Method Id"', 'VARCHAR') }}                      as SHIPMENT_METHOD_ID,
        {{ std_cast('"Payment Method Id"', 'VARCHAR') }}                       as PAYMENT_METHOD_ID,
        {{ std_cast('"Tax Area ID"', 'VARCHAR') }}                             as TAX_AREA_ID,
        {{ std_cast('"Contact ID"', 'VARCHAR') }}                              as CONTACT_ID,
        {{ std_cast('"Contact Graph Id"', 'VARCHAR') }}                        as CONTACT_GRAPH_ID,
        {{ std_cast('"Payment Days Code"', 'VARCHAR') }}                       as PAYMENT_DAYS_CODE,
        {{ std_cast('"Non-Paymt_ Periods Code"', 'VARCHAR') }}                 as NONPAYMT_PERIODS_CODE,
        {{ std_cast('"Not in AEAT"', 'INTEGER') }}                             as NOT_IN_AEAT,
        {{ std_cast('"Disable Search by Name"', 'INTEGER') }}                  as DISABLE_SEARCH_BY_NAME,
        {{ std_cast('"Ship-to Code"', 'VARCHAR') }}                            as SHIPTO_CODE,
        {{ std_cast('"TipoFacturacion"', 'INTEGER') }}                         as TIPOFACTURACION,
        {{ std_cast('"PeriodoFacturacion"', 'INTEGER') }}                      as PERIODOFACTURACION,
        {{ std_cast('"AlbaranSGI"', 'INTEGER') }}                              as ALBARANSGI,
        {{ std_cast('"CertificadoSAE"', 'INTEGER') }}                          as CERTIFICADOSAE,
        {{ std_cast('"CodDelisano"', 'VARCHAR') }}                             as CODDELISANO,
        {{ std_cast('"Prevision"', 'INTEGER') }}                               as PREVISION,
        {{ std_cast('"Prevision_Fecha_Venta"', 'INTEGER') }}                   as PREVISION_FECHA_VENTA,
        {{ std_cast('"IDPIRPF IRPF Group"', 'VARCHAR') }}                      as IDPIRPF_IRPF_GROUP,
        {{ std_cast('"IDPGND Calculation of SIG"', 'INTEGER') }}               as IDPGND_CALCULATION_OF_SIG,
        {{ std_cast('"IDPVSH Valued Shipment"', 'INTEGER') }}                  as IDPVSH_VALUED_SHIPMENT,
        {{ std_cast('"IF_SAE"', 'INTEGER') }}                                  as IF_SAE,
        {{ std_cast('"IF_SAE_CERTIFICATION"', 'VARCHAR') }}                    as IF_SAE_CERTIFICATION,
        {{ std_cast('"IDPCIN Cust_ Classificat_ Code"', 'VARCHAR') }}          as IDPCIN_CUST_CLASSIFICAT_CODE,
        {{ std_cast('"IDPCIN Insurance Co_Credit LCY"', 'NUMBER(38,5)') }}     as IDPCIN_INSURANCE_CO_CREDIT_LCY,
        {{ std_cast('"IDPCIN Company Credit (LCY)"', 'NUMBER(38,5)') }}        as IDPCIN_COMPANY_CREDIT_LCY,
        {{ std_cast('"IDPEDI Config_ Template No_"', 'VARCHAR') }}             as IDPEDI_CONFIG_TEMPLATE_NO,
        {{ std_cast('"AIT Billing Address Code"', 'VARCHAR') }}                as AIT_BILLING_ADDRESS_CODE,
        {{ std_cast('"AIT Creation User"', 'VARCHAR') }}                       as AIT_CREATION_USER,
        {{ std_cast('"AIT Creation Datetime"', 'TIMESTAMP_NTZ') }}             as AIT_CREATION_DATETIME,
        {{ std_cast('"IDPSII Default Invoice Type"', 'VARCHAR') }}             as IDPSII_DEFAULT_INVOICE_TYPE,
        {{ std_cast('"IDPSII Default Cr_ Memo Type"', 'VARCHAR') }}            as IDPSII_DEFAULT_CR_MEMO_TYPE,
        {{ std_cast('"IDPSII VAT ID Calculation"', 'INTEGER') }}               as IDPSII_VAT_ID_CALCULATION,
        {{ std_cast('"IDPSII Other Id"', 'VARCHAR') }}                         as IDPSII_OTHER_ID,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'DLS'                                                                     as tec_des_cod_siglas,
        'DELISANO'                                                             as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
