{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_CLIENTES') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"timestamp"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"Name"', 'VARCHAR') }}                                    as NAME,
        {{ std_cast('"Search Name"', 'VARCHAR') }}                             as SEARCH_NAME,
        {{ std_cast('"Name 2"', 'VARCHAR') }}                                  as NAME_2,
        {{ std_cast('"Address"', 'VARCHAR') }}                                 as ADDRESS,
        {{ std_cast('"Address 2"', 'VARCHAR') }}                               as ADDRESS_2,
        {{ std_cast('"City"', 'VARCHAR') }}                                    as CITY,
        {{ std_cast('"Contact"', 'VARCHAR') }}                                 as CONTACT,
        {{ std_cast('"Phone No_"', 'VARCHAR') }}                               as PHONE_NO,
        {{ std_cast('"Telex No_"', 'VARCHAR') }}                               as TELEX_NO,
        {{ std_cast('"Document Sending Profile"', 'VARCHAR') }}                as DOCUMENT_SENDING_PROFILE,
        {{ std_cast('"Our Account No_"', 'VARCHAR') }}                         as OUR_ACCOUNT_NO,
        {{ std_cast('"Territory Code"', 'VARCHAR') }}                          as TERRITORY_CODE,
        {{ std_cast('"Global Dimension 1 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"Global Dimension 2 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"Chain Name"', 'VARCHAR') }}                              as CHAIN_NAME,
        {{ std_cast('"Budgeted Amount"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"Credit Limit (LCY)"', 'NUMBER(38,5)') }}                 as CREDIT_LIMIT_LCY,
        {{ std_cast('"Customer Posting Group"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"Currency Code"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Language Code"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"Statistics Group"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"Payment Terms Code"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"Fin_ Charge Terms Code"', 'VARCHAR') }}                  as FIN_CHARGE_TERMS_CODE,
        {{ std_cast('"Salesperson Code"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"Shipment Method Code"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"Shipping Agent Code"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"Place of Export"', 'VARCHAR') }}                         as PLACE_OF_EXPORT,
        {{ std_cast('"Invoice Disc_ Code"', 'VARCHAR') }}                      as INVOICE_DISC_CODE,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        {{ std_cast('"Country_Region Code"', 'VARCHAR') }}                     as COUNTRY_REGION_CODE,
        {{ std_cast('"Collection Method"', 'VARCHAR') }}                       as COLLECTION_METHOD,
        {{ std_cast('"Amount"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"Blocked"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"Invoice Copies"', 'INTEGER') }}                          as INVOICE_COPIES,
        {{ std_cast('"Last Statement No_"', 'INTEGER') }}                      as LAST_STATEMENT_NO,
        {{ std_cast('"Print Statements"', 'INTEGER') }}                        as PRINT_STATEMENTS,
        NULL                                                                   as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"Priority"', 'INTEGER') }}                                as PRIORITY,
        {{ std_cast('"Payment Method Code"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"Last Date Modified"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"Application Method"', 'INTEGER') }}                      as APPLICATION_METHOD,
        {{ std_cast('"Prices Including VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Fax No_"', 'VARCHAR') }}                                 as FAX_NO,
        {{ std_cast('"Telex Answer Back"', 'VARCHAR') }}                       as TELEX_ANSWER_BACK,
        {{ std_cast('"VAT Registration No_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"Combine Shipments"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GLN"', 'VARCHAR') }}                                     as GLN,
        {{ std_cast('"Post Code"', 'VARCHAR') }}                               as POST_CODE,
        {{ std_cast('"County"', 'VARCHAR') }}                                  as COUNTY,
        NULL                                                                   as E_MAIL,
        {{ std_cast('"Home Page"', 'VARCHAR') }}                               as HOME_PAGE,
        {{ std_cast('"Reminder Terms Code"', 'VARCHAR') }}                     as REMINDER_TERMS_CODE,
        {{ std_cast('"No_ Series"', 'VARCHAR') }}                              as NO_SERIES,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"Reserve"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"Block Payment Tolerance"', 'INTEGER') }}                 as BLOCK_PAYMENT_TOLERANCE,
        {{ std_cast('"IC Partner Code"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"Prepayment _"', 'NUMBER(38,5)') }}                       as PREPAYMENT,
        {{ std_cast('"Partner Type"', 'INTEGER') }}                            as PARTNER_TYPE,
        NULL                                                                   as PREFERRED_BANK_ACCOUNT,
        {{ std_cast('"Cash Flow Payment Terms Code"', 'VARCHAR') }}            as CASH_FLOW_PAYMENT_TERMS_CODE,
        {{ std_cast('"Primary Contact No_"', 'VARCHAR') }}                     as PRIMARY_CONTACT_NO,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"Shipping Advice"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"Shipping Time"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"Shipping Agent Service Code"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"Service Zone Code"', 'VARCHAR') }}                       as SERVICE_ZONE_CODE,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Base Calendar Code"', 'VARCHAR') }}                      as BASE_CALENDAR_CODE,
        NULL                                                                   as COPY_SELL_TO_ADDR_TO_QTE_FROM,
        {{ std_cast('"Payment Days Code"', 'VARCHAR') }}                       as PAYMENT_DAYS_CODE,
        NULL                                                                   as NON_PAYMT_PERIODS_CODE,
        NULL                                                                   as RAPPEL_REFERENCE,
        NULL                                                                   as PRINT_LOTS_IN_INVOICE,
        NULL                                                                   as INSURANCE_COMPANY_CONTRACT_NO,
        NULL                                                                   as COVERAGE_DATE,
        NULL                                                                   as SECURED_AMOUNT,
        NULL                                                                   as ANONYMOUS,
        NULL                                                                   as COMPANY_OWN_RISK,
        NULL                                                                   as REQUESTED_RISK_TO_CYC,
        NULL                                                                   as GRANTED_RISK_CYC,
        NULL                                                                   as PUBLIC_RISK,
        NULL                                                                   as DTO_PP,
        NULL                                                                   as RAPPEL_PERC,
        NULL                                                                   as IBAN_CODE,
        NULL                                                                   as MIG_ACCOUNT_NO,
        NULL                                                                   as TIPOIVA,
        NULL                                                                   as OBSERVACIONES_ENVIO,
        NULL                                                                   as JEFE_DE_VENTAS,
        NULL                                                                   as JEFE_DE_ZONA,
        NULL                                                                   as HEREDA_COND_GRUPO,
        NULL                                                                   as FECHA_CREACION,
        NULL                                                                   as PAY_AT_CODE,
        NULL                                                                   as FORMA_PAGO_ANTIGUO,
        NULL                                                                   as ALBARAN_VALORADO,
        NULL                                                                   as EXCLUDE_347,
        NULL                                                                   as RAPPELS_X_GRUPO,
        NULL                                                                   as TIPO_DTO_2,
        NULL                                                                   as TIPO_DTO_3,
        NULL                                                                   as TIPO_DTO_4,
        NULL                                                                   as TIPO_DTO_5,
        NULL                                                                   as ITEM_CROSS_REFERENCE_CODE,
        NULL                                                                   as GROUP_SHIPMENT_TYPE,
        NULL                                                                   as SHIPMENT_FREQUENCY,
        NULL                                                                   as TIPO_DETALLE_FACTURA,
        NULL                                                                   as DIA_DE_FACTURACION,
        NULL                                                                   as GRUPO_DE_COMPRA,
        NULL                                                                   as COD_GRUPO_DE_COMPRA,
        NULL                                                                   as EXCLUDE_349,
        NULL                                                                   as UMBRALPAGO,
        NULL                                                                   as IRPF,
        NULL                                                                   as COD_IRPF,
        NULL                                                                   as COD_ENVIO_FACTURA,
        NULL                                                                   as CORREO_ELECTRONICO_ADMON,
        NULL                                                                   as EMPRESA_SYMMETRICAL,
        NULL                                                                   as SUBSET_1,
        NULL                                                                   as SUBSET_2,
        NULL                                                                   as SUBSET_3,
        NULL                                                                   as SUBSET_4,
        NULL                                                                   as SUBSET_5,
        NULL                                                                   as SUBSET_6,
        NULL                                                                   as SUBSET_7,
        NULL                                                                   as SUBSET_8,
        NULL                                                                   as SUBSET_9,
        NULL                                                                   as SUBSET_10,
        NULL                                                                   as EFACTURA_AUTOMATICA,
        NULL                                                                   as ODS_JOB_TEMPLATE_CODE,
        NULL                                                                   as LIQUIDITY_CODE,
        NULL                                                                   as SHOW_EXPENSES_ON_TRANSFER,
        NULL                                                                   as TRANSFER_EXPENSES,
        NULL                                                                   as BANK_TRANSFER_E_MAIL,
        NULL                                                                   as AVERAGE_PAYMENT_PERIOD,
        NULL                                                                   as CASH_FLOW_CODE,
        NULL                                                                   as MOBILE_PRICE_GROUP,
        NULL                                                                   as PACKING_LIST_REPORT_NO,
        NULL                                                                   as EXPEDITION_LABEL_REP_NO,
        NULL                                                                   as INV_DISCOUNT,
        NULL                                                                   as DEFAULT_SHIP_TO_ADDRESS,
        NULL                                                                   as AUTOINVOICE,
        NULL                                                                   as AUTOINVOICE_SERIE,
        NULL                                                                   as BANK_ACCOUNT_TO_TRANSFER,
        NULL                                                                   as SHIPMET_WITH_PALET_RESUME,
        NULL                                                                   as PAPER_INVOICES,
        NULL                                                                   as PDF_INVOICES,
        NULL                                                                   as RECALCULATE_PRICES_IN_INVOICE,
        NULL                                                                   as LOAD_TIME,
        NULL                                                                   as LOAD_HR,
        NULL                                                                   as ID_TYPE,
        NULL                                                                   as REGIMEN,
        NULL                                                                   as RETENER_FACTURACION,
        NULL                                                                   as TOLERANCIA_RECADV,
        NULL                                                                   as SHIPMENT_ZONE_CODE,
        NULL                                                                   as NUM_REGISTRO_ACUERDO_FACT,
        NULL                                                                   as LOT_COMPLIANCE,
        NULL                                                                   as EORI_NUMBER,
        NULL                                                                   as SUPLEMENT_NO,
        NULL                                                                   as VAT_DOC_TYPE,
        NULL                                                                   as OTHER_CUSTOMER,
        NULL                                                                   as INTRASTAT_EXCLUDED,
        NULL                                                                   as SII_COUNTRY_CODE,
        NULL                                                                   as EXCLUDE_REMINDER,
        NULL                                                                   as SCRAP_MANAGER,
        NULL                                                                   as SUBSET_11,
        NULL                                                                   as SUBSET_12,
        NULL                                                                   as SUBSET_13,
        NULL                                                                   as SUBSET_14,
        NULL                                                                   as SUBSET_15,
        NULL                                                                   as SUBSET_16,
        NULL                                                                   as SUBSET_17,
        NULL                                                                   as SUBSET_18,
        NULL                                                                   as SUBSET_19,
        NULL                                                                   as SUBSET_20,
        NULL                                                                   as LAST_ORDER_DATE,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"Last Modified Date Time"', 'TIMESTAMP_NTZ') }}           as LAST_MODIFIED_DATE_TIME,
        {{ std_cast('"E-Mail"', 'VARCHAR') }}                                  as EMAIL,
        {{ std_cast('"Image"', 'VARCHAR') }}                                   as IMAGE,
        {{ std_cast('"Privacy Blocked"', 'INTEGER') }}                         as PRIVACY_BLOCKED,
        {{ std_cast('"Preferred Bank Account Code"', 'VARCHAR') }}             as PREFERRED_BANK_ACCOUNT_CODE,
        {{ std_cast('"Contact Type"', 'INTEGER') }}                            as CONTACT_TYPE,
        {{ std_cast('"Copy Sell-to Addr_ to Qte From"', 'INTEGER') }}          as COPY_SELLTO_ADDR_TO_QTE_FROM,
        {{ std_cast('"Validate EU Vat Reg_ No_"', 'INTEGER') }}                as VALIDATE_EU_VAT_REG_NO,
        {{ std_cast('"Id"', 'VARCHAR') }}                                      as ID,
        {{ std_cast('"Currency Id"', 'VARCHAR') }}                             as CURRENCY_ID,
        {{ std_cast('"Payment Terms Id"', 'VARCHAR') }}                        as PAYMENT_TERMS_ID,
        {{ std_cast('"Shipment Method Id"', 'VARCHAR') }}                      as SHIPMENT_METHOD_ID,
        {{ std_cast('"Payment Method Id"', 'VARCHAR') }}                       as PAYMENT_METHOD_ID,
        {{ std_cast('"Tax Area ID"', 'VARCHAR') }}                             as TAX_AREA_ID,
        {{ std_cast('"Contact ID"', 'VARCHAR') }}                              as CONTACT_ID,
        {{ std_cast('"Contact Graph Id"', 'VARCHAR') }}                        as CONTACT_GRAPH_ID,
        {{ std_cast('"Non-Paymt_ Periods Code"', 'VARCHAR') }}                 as NONPAYMT_PERIODS_CODE,
        {{ std_cast('"Not in AEAT"', 'INTEGER') }}                             as NOT_IN_AEAT,
        {{ std_cast('"Disable Search by Name"', 'INTEGER') }}                  as DISABLE_SEARCH_BY_NAME,
        {{ std_cast('"Ship-to Code"', 'VARCHAR') }}                            as SHIPTO_CODE,
        {{ std_cast('"TipoFacturacion"', 'INTEGER') }}                         as TIPOFACTURACION,
        {{ std_cast('"PeriodoFacturacion"', 'INTEGER') }}                      as PERIODOFACTURACION,
        {{ std_cast('"AlbaranSGI"', 'INTEGER') }}                              as ALBARANSGI,
        {{ std_cast('"CertificadoSAE"', 'INTEGER') }}                          as CERTIFICADOSAE,
        {{ std_cast('"CodDelisano"', 'VARCHAR') }}                             as CODDELISANO,
        {{ std_cast('"Prevision"', 'INTEGER') }}                               as PREVISION,
        {{ std_cast('"Prevision_Fecha_Venta"', 'INTEGER') }}                   as PREVISION_FECHA_VENTA,
        {{ std_cast('"IDPIRPF IRPF Group"', 'VARCHAR') }}                      as IDPIRPF_IRPF_GROUP,
        {{ std_cast('"IDPGND Calculation of SIG"', 'INTEGER') }}               as IDPGND_CALCULATION_OF_SIG,
        {{ std_cast('"IDPVSH Valued Shipment"', 'INTEGER') }}                  as IDPVSH_VALUED_SHIPMENT,
        {{ std_cast('"IF_SAE"', 'INTEGER') }}                                  as IF_SAE,
        {{ std_cast('"IF_SAE_CERTIFICATION"', 'VARCHAR') }}                    as IF_SAE_CERTIFICATION,
        {{ std_cast('"IDPCIN Cust_ Classificat_ Code"', 'VARCHAR') }}          as IDPCIN_CUST_CLASSIFICAT_CODE,
        {{ std_cast('"IDPCIN Insurance Co_Credit LCY"', 'NUMBER(38,5)') }}     as IDPCIN_INSURANCE_CO_CREDIT_LCY,
        {{ std_cast('"IDPCIN Company Credit (LCY)"', 'NUMBER(38,5)') }}        as IDPCIN_COMPANY_CREDIT_LCY,
        {{ std_cast('"IDPEDI Config_ Template No_"', 'VARCHAR') }}             as IDPEDI_CONFIG_TEMPLATE_NO,
        {{ std_cast('"AIT Billing Address Code"', 'VARCHAR') }}                as AIT_BILLING_ADDRESS_CODE,
        {{ std_cast('"AIT Creation User"', 'VARCHAR') }}                       as AIT_CREATION_USER,
        {{ std_cast('"AIT Creation Datetime"', 'TIMESTAMP_NTZ') }}             as AIT_CREATION_DATETIME,
        {{ std_cast('"IDPSII Default Invoice Type"', 'VARCHAR') }}             as IDPSII_DEFAULT_INVOICE_TYPE,
        {{ std_cast('"IDPSII Default Cr_ Memo Type"', 'VARCHAR') }}            as IDPSII_DEFAULT_CR_MEMO_TYPE,
        {{ std_cast('"IDPSII VAT ID Calculation"', 'INTEGER') }}               as IDPSII_VAT_ID_CALCULATION,
        {{ std_cast('"IDPSII Other Id"', 'VARCHAR') }}                         as IDPSII_OTHER_ID,
        NULL                                                                   as ENVIAR_FACTURA_POR_E_MAIL,
        NULL                                                                   as FACTURA_EN_PAPEL,
        NULL                                                                   as AGRUPAR_POR_DIRECCION_ENVIO,
        NULL                                                                   as COD_CADENA,
        NULL                                                                   as COD_DTO_LINEA,
        NULL                                                                   as PROMOCIONES_POR,
        NULL                                                                   as TIPO_PUNTO_VERDE,
        NULL                                                                   as TIPO_RESIDUOS,
        NULL                                                                   as COD_RUTA,
        NULL                                                                   as NO_PROVEEDOR_RELACIONADO,
        NULL                                                                   as COMISIONES_POR,
        NULL                                                                   as FECHA_ALTA,
        NULL                                                                   as USUARIO_ALTA,
        NULL                                                                   as GENERAR_SSCC_EN_PALET,
        NULL                                                                   as COD_IDIOMA_ETIQUETAJE,
        NULL                                                                   as COD_IFCO,
        NULL                                                                   as HORARIO_ENTREGA,
        NULL                                                                   as NATURALEZA_PRODUCTO,
        NULL                                                                   as E_MAIL_ENVIO_ALBARAN,
        NULL                                                                   as E_MAIL_ORDEN_RECOGIDA,
        NULL                                                                   as OBSERVACIONES_PICKING,
        NULL                                                                   as LOTE_CRECIENTE,
        NULL                                                                   as ZONA_TRANSPORTE,
        NULL                                                                   as COD_EUROPOOL,
        NULL                                                                   as DEFAULT_SHIP_TO_CODE,
        NULL                                                                   as DOC_TRANSPORTE,
        NULL                                                                   as ALBARAN_POR_LOTES,
        NULL                                                                   as TIPO_CLIENTE,
        NULL                                                                   as EAN128_ETIQUETA,
        NULL                                                                   as FACTURA_CONTADO_AUTOMATICA,
        NULL                                                                   as PLAZO_ENTREGA,
        NULL                                                                   as COD_PALET_DEFECTO,
        NULL                                                                   as NO_LOTES_MAX_EN_EXPEDICION,
        NULL                                                                   as COD_CHEP,
        NULL                                                                   as EXCLUIR_COBRO_TRAZA_PALETS,
        NULL                                                                   as MEZCLA_PROD_EN_EMBALAJE,
        NULL                                                                   as COD_EMBALAJE_DEFECTO,
        NULL                                                                   as NO_COPIAS,
        NULL                                                                   as NOMBRE_COMERCIAL,
        NULL                                                                   as CYC,
        NULL                                                                   as EDI_REF_PEDIDO,
        NULL                                                                   as EDI_REF_ALBARAN,
        NULL                                                                   as EDI_INF_ADICIONAL_PORTUGAL,
        NULL                                                                   as EDI_REF_FACTURA,
        NULL                                                                   as EDI_REF_PAGO,
        NULL                                                                   as EDI_REF_DEPARTAMENTO,
        NULL                                                                   as EDI_CLIENTE_DEL_GRUPO_ALCAMPO,
        NULL                                                                   as EDI_PROVEEDOR,
        NULL                                                                   as EDI_CLIENTE_UNIDE,
        NULL                                                                   as EDI_REF_EUROMADI,
        NULL                                                                   as EDI_FRANCIA,
        NULL                                                                   as EDI_CARREFOUR,
        NULL                                                                   as EDI_CODIGO_GUVERNAMENTAL,
        NULL                                                                   as EDI_CIP,
        NULL                                                                   as TIPO_FACTURACION,
        NULL                                                                   as FACTURA_POR_ALBARAN,
        NULL                                                                   as SU_CODIGO,
        NULL                                                                   as SPLIT_SHIP_TO_ADD,
        NULL                                                                   as DTO_FACTURA,
        NULL                                                                   as COD_BANCO,
        NULL                                                                   as NOMBRE_CONTACTO_PAGOS,
        NULL                                                                   as COD_CONTACTO_PAGOS,
        NULL                                                                   as RESPONSABLE_PAGOS_EMPRESA,
        NULL                                                                   as COMMISSION_CUSTOMER_GROUP,
        NULL                                                                   as SECOND_SALESPERSON_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION,
        NULL                                                                   as INCOME_TAX_RETENTION_KEY,
        NULL                                                                   as INCOME_TAX_RETENTION_SUBKEY,
        NULL                                                                   as SIN_CONTROL_PALET_EXPEDICION,
        NULL                                                                   as EXPORTAR_TRAZABILIDAD,
        NULL                                                                   as ENVIAR_PRECIOS_POR_E_MAIL,
        NULL                                                                   as E_MAIL_ENVIO_PRECIOS,
        NULL                                                                   as ULT_ENVIO_PRECIOS_EMAIL,
        NULL                                                                   as IMPRIMIR_BULTOS,
        NULL                                                                   as COD_TRATAMIENTO_COMERCIAL,
        NULL                                                                   as MOSTRAR_SALDO_EMBALAJES,
        NULL                                                                   as NO_CESCE,
        NULL                                                                   as ERROR_AL_ENVIAR_PRECIOS,
        NULL                                                                   as ENVIAR_EXCEL_ALBARAN_E_MAIL,
        NULL                                                                   as E_MAIL_ENVIO_ALBARAN_TRAZ,
        NULL                                                                   as EDI_HORA_ENTREGA,
        NULL                                                                   as DATOS_PIE_ALBARAN_1,
        NULL                                                                   as DATOS_PIE_ALBARAN_2,
        NULL                                                                   as DISABLE_DAYS_MARGIN,
        NULL                                                                   as PREFIJO_EMPRESA_EAN_UCC,
        NULL                                                                   as USE_GLN_IN_ELECTRONIC_DOCUMENT,
        NULL                                                                   as DAYS_FOR_SEND_INVOICE,
        NULL                                                                   as INVOICE_BLOCKED,
        NULL                                                                   as INVOICE_TO_DAY,
        NULL                                                                   as ONLY_UPPER_PACKAGE_LEVEL,
        NULL                                                                   as COMPLETE_BOX,
        NULL                                                                   as W_PALLET_LABEL,
        NULL                                                                   as EXTERNAL_DOC_NO_MANDATORY,
        NULL                                                                   as ONLY_PERSONALIZED_PRICES,
        'DLS'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
