{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_CUSTOMER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"NAME"', 'VARCHAR') }}                                    as NAME,
        {{ std_cast('"SEARCH_NAME"', 'VARCHAR') }}                             as SEARCH_NAME,
        {{ std_cast('"NAME_2"', 'VARCHAR') }}                                  as NAME_2,
        {{ std_cast('"ADDRESS"', 'VARCHAR') }}                                 as ADDRESS,
        {{ std_cast('"ADDRESS_2"', 'VARCHAR') }}                               as ADDRESS_2,
        {{ std_cast('"CITY"', 'VARCHAR') }}                                    as CITY,
        {{ std_cast('"CONTACT"', 'VARCHAR') }}                                 as CONTACT,
        {{ std_cast('"PHONE_NO_"', 'VARCHAR') }}                               as PHONE_NO,
        {{ std_cast('"TELEX_NO_"', 'VARCHAR') }}                               as TELEX_NO,
        {{ std_cast('"DOCUMENT_SENDING_PROFILE"', 'VARCHAR') }}                as DOCUMENT_SENDING_PROFILE,
        {{ std_cast('"OUR_ACCOUNT_NO_"', 'VARCHAR') }}                         as OUR_ACCOUNT_NO,
        {{ std_cast('"TERRITORY_CODE"', 'VARCHAR') }}                          as TERRITORY_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_1_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_2_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"CHAIN_NAME"', 'VARCHAR') }}                              as CHAIN_NAME,
        {{ std_cast('"BUDGETED_AMOUNT"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"CREDIT_LIMIT_LCY"', 'NUMBER(38,5)') }}                   as CREDIT_LIMIT_LCY,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"STATISTICS_GROUP"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"FIN_CHARGE_TERMS_CODE"', 'VARCHAR') }}                   as FIN_CHARGE_TERMS_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PLACE_OF_EXPORT"', 'VARCHAR') }}                         as PLACE_OF_EXPORT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"COUNTRY_REGION_CODE"', 'VARCHAR') }}                     as COUNTRY_REGION_CODE,
        {{ std_cast('"COLLECTION_METHOD"', 'VARCHAR') }}                       as COLLECTION_METHOD,
        {{ std_cast('"AMOUNT"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"BLOCKED"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"INVOICE_COPIES"', 'INTEGER') }}                          as INVOICE_COPIES,
        {{ std_cast('"LAST_STATEMENT_NO_"', 'INTEGER') }}                      as LAST_STATEMENT_NO,
        {{ std_cast('"PRINT_STATEMENTS"', 'INTEGER') }}                        as PRINT_STATEMENTS,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"PRIORITY"', 'INTEGER') }}                                as PRIORITY,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"LAST_DATE_MODIFIED"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"APPLICATION_METHOD"', 'INTEGER') }}                      as APPLICATION_METHOD,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"FAX_NO_"', 'VARCHAR') }}                                 as FAX_NO,
        {{ std_cast('"TELEX_ANSWER_BACK"', 'VARCHAR') }}                       as TELEX_ANSWER_BACK,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"COMBINE_SHIPMENTS"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GLN"', 'VARCHAR') }}                                     as GLN,
        {{ std_cast('"POST_CODE"', 'VARCHAR') }}                               as POST_CODE,
        {{ std_cast('"COUNTY"', 'VARCHAR') }}                                  as COUNTY,
        {{ std_cast('"E_MAIL"', 'VARCHAR') }}                                  as E_MAIL,
        {{ std_cast('"HOME_PAGE"', 'VARCHAR') }}                               as HOME_PAGE,
        {{ std_cast('"REMINDER_TERMS_CODE"', 'VARCHAR') }}                     as REMINDER_TERMS_CODE,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"BLOCK_PAYMENT_TOLERANCE"', 'INTEGER') }}                 as BLOCK_PAYMENT_TOLERANCE,
        {{ std_cast('"IC_PARTNER_CODE"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"PREPAYMENT_"', 'NUMBER(38,5)') }}                        as PREPAYMENT,
        {{ std_cast('"PARTNER_TYPE"', 'INTEGER') }}                            as PARTNER_TYPE,
        {{ std_cast('"PREFERRED_BANK_ACCOUNT"', 'VARCHAR') }}                  as PREFERRED_BANK_ACCOUNT,
        {{ std_cast('"CASH_FLOW_PAYMENT_TERMS_CODE"', 'VARCHAR') }}            as CASH_FLOW_PAYMENT_TERMS_CODE,
        {{ std_cast('"PRIMARY_CONTACT_NO_"', 'VARCHAR') }}                     as PRIMARY_CONTACT_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"SHIPPING_ADVICE"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"SHIPPING_TIME"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"SHIPPING_AGENT_SERVICE_CODE"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"SERVICE_ZONE_CODE"', 'VARCHAR') }}                       as SERVICE_ZONE_CODE,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"BASE_CALENDAR_CODE"', 'VARCHAR') }}                      as BASE_CALENDAR_CODE,
        {{ std_cast('"COPY_SELL_TO_ADDR_TO_QTE_FROM"', 'INTEGER') }}           as COPY_SELL_TO_ADDR_TO_QTE_FROM,
        {{ std_cast('"PAYMENT_DAYS_CODE"', 'VARCHAR') }}                       as PAYMENT_DAYS_CODE,
        {{ std_cast('"NON_PAYMT_PERIODS_CODE"', 'VARCHAR') }}                  as NON_PAYMT_PERIODS_CODE,
        {{ std_cast('"RAPPEL_REFERENCE_"', 'NUMBER(38,5)') }}                  as RAPPEL_REFERENCE,
        {{ std_cast('"PRINT_LOTS_IN_INVOICE"', 'INTEGER') }}                   as PRINT_LOTS_IN_INVOICE,
        {{ std_cast('"INSURANCE_COMPANY_CONTRACT_NO_"', 'VARCHAR') }}          as INSURANCE_COMPANY_CONTRACT_NO,
        {{ std_cast('"COVERAGE_DATE"', 'TIMESTAMP_NTZ') }}                     as COVERAGE_DATE,
        {{ std_cast('"SECURED_AMOUNT"', 'NUMBER(38,5)') }}                     as SECURED_AMOUNT,
        {{ std_cast('"ANONYMOUS"', 'INTEGER') }}                               as ANONYMOUS,
        {{ std_cast('"COMPANY_OWN_RISK"', 'NUMBER(38,5)') }}                   as COMPANY_OWN_RISK,
        {{ std_cast('"REQUESTED_RISK_TO_CYC"', 'NUMBER(38,5)') }}              as REQUESTED_RISK_TO_CYC,
        {{ std_cast('"GRANTED_RISK_CYC"', 'NUMBER(38,5)') }}                   as GRANTED_RISK_CYC,
        {{ std_cast('"PUBLIC_RISK"', 'NUMBER(38,5)') }}                        as PUBLIC_RISK,
        {{ std_cast('"DTO_PP"', 'NUMBER(38,5)') }}                             as DTO_PP,
        {{ std_cast('"RAPPEL_PERC"', 'NUMBER(38,5)') }}                        as RAPPEL_PERC,
        {{ std_cast('"IBAN_CODE"', 'VARCHAR') }}                               as IBAN_CODE,
        {{ std_cast('"MIG_ACCOUNT_NO_"', 'VARCHAR') }}                         as MIG_ACCOUNT_NO,
        {{ std_cast('"TIPOIVA"', 'VARCHAR') }}                                 as TIPOIVA,
        {{ std_cast('"OBSERVACIONES_ENVIO"', 'VARCHAR') }}                     as OBSERVACIONES_ENVIO,
        {{ std_cast('"JEFE_DE_VENTAS"', 'VARCHAR') }}                          as JEFE_DE_VENTAS,
        {{ std_cast('"JEFE_DE_ZONA"', 'VARCHAR') }}                            as JEFE_DE_ZONA,
        {{ std_cast('"HEREDA_COND_GRUPO"', 'INTEGER') }}                       as HEREDA_COND_GRUPO,
        {{ std_cast('"FECHA_CREACION"', 'TIMESTAMP_NTZ') }}                    as FECHA_CREACION,
        {{ std_cast('"PAY_AT_CODE"', 'VARCHAR') }}                             as PAY_AT_CODE,
        {{ std_cast('"FORMA_PAGO_ANTIGUO"', 'VARCHAR') }}                      as FORMA_PAGO_ANTIGUO,
        {{ std_cast('"ALBARAN_VALORADO"', 'INTEGER') }}                        as ALBARAN_VALORADO,
        {{ std_cast('"EXCLUDE_347"', 'INTEGER') }}                             as EXCLUDE_347,
        {{ std_cast('"RAPPELS_X_GRUPO"', 'INTEGER') }}                         as RAPPELS_X_GRUPO,
        {{ std_cast('"TIPO_DTO_2"', 'INTEGER') }}                              as TIPO_DTO_2,
        {{ std_cast('"TIPO_DTO_3"', 'INTEGER') }}                              as TIPO_DTO_3,
        {{ std_cast('"TIPO_DTO_4"', 'INTEGER') }}                              as TIPO_DTO_4,
        {{ std_cast('"TIPO_DTO_5"', 'INTEGER') }}                              as TIPO_DTO_5,
        {{ std_cast('"ITEM_CROSS_REFERENCE_CODE"', 'VARCHAR') }}               as ITEM_CROSS_REFERENCE_CODE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        {{ std_cast('"TIPO_DETALLE_FACTURA"', 'INTEGER') }}                    as TIPO_DETALLE_FACTURA,
        {{ std_cast('"DIA_DE_FACTURACION"', 'INTEGER') }}                      as DIA_DE_FACTURACION,
        {{ std_cast('"GRUPO_DE_COMPRA"', 'INTEGER') }}                         as GRUPO_DE_COMPRA,
        {{ std_cast('"COD_GRUPO_DE_COMPRA"', 'VARCHAR') }}                     as COD_GRUPO_DE_COMPRA,
        {{ std_cast('"EXCLUDE_349"', 'INTEGER') }}                             as EXCLUDE_349,
        {{ std_cast('"UMBRALPAGO"', 'NUMBER(38,5)') }}                         as UMBRALPAGO,
        {{ std_cast('"_IRPF"', 'NUMBER(38,5)') }}                              as IRPF,
        {{ std_cast('"COD_IRPF"', 'VARCHAR') }}                                as COD_IRPF,
        {{ std_cast('"COD_ENVIO_FACTURA"', 'VARCHAR') }}                       as COD_ENVIO_FACTURA,
        {{ std_cast('"CORREO_ELECTRONICO_ADMON_"', 'VARCHAR') }}               as CORREO_ELECTRONICO_ADMON,
        {{ std_cast('"EMPRESA_SYMMETRICAL"', 'VARCHAR') }}                     as EMPRESA_SYMMETRICAL,
        {{ std_cast('"SUBSET_1"', 'VARCHAR') }}                                as SUBSET_1,
        {{ std_cast('"SUBSET_2"', 'VARCHAR') }}                                as SUBSET_2,
        {{ std_cast('"SUBSET_3"', 'VARCHAR') }}                                as SUBSET_3,
        {{ std_cast('"SUBSET_4"', 'VARCHAR') }}                                as SUBSET_4,
        {{ std_cast('"SUBSET_5"', 'VARCHAR') }}                                as SUBSET_5,
        {{ std_cast('"SUBSET_6"', 'VARCHAR') }}                                as SUBSET_6,
        {{ std_cast('"SUBSET_7"', 'VARCHAR') }}                                as SUBSET_7,
        {{ std_cast('"SUBSET_8"', 'VARCHAR') }}                                as SUBSET_8,
        {{ std_cast('"SUBSET_9"', 'VARCHAR') }}                                as SUBSET_9,
        {{ std_cast('"SUBSET_10"', 'VARCHAR') }}                               as SUBSET_10,
        {{ std_cast('"EFACTURA_AUTOMATICA"', 'INTEGER') }}                     as EFACTURA_AUTOMATICA,
        {{ std_cast('"ODS_JOB_TEMPLATE_CODE"', 'VARCHAR') }}                   as ODS_JOB_TEMPLATE_CODE,
        {{ std_cast('"LIQUIDITY_CODE"', 'VARCHAR') }}                          as LIQUIDITY_CODE,
        {{ std_cast('"SHOW_EXPENSES_ON_TRANSFER"', 'INTEGER') }}               as SHOW_EXPENSES_ON_TRANSFER,
        {{ std_cast('"TRANSFER_EXPENSES"', 'INTEGER') }}                       as TRANSFER_EXPENSES,
        {{ std_cast('"BANK_TRANSFER_E_MAIL"', 'VARCHAR') }}                    as BANK_TRANSFER_E_MAIL,
        {{ std_cast('"AVERAGE_PAYMENT_PERIOD"', 'INTEGER') }}                  as AVERAGE_PAYMENT_PERIOD,
        {{ std_cast('"CASH_FLOW_CODE"', 'VARCHAR') }}                          as CASH_FLOW_CODE,
        {{ std_cast('"MOBILE_PRICE_GROUP"', 'VARCHAR') }}                      as MOBILE_PRICE_GROUP,
        {{ std_cast('"PACKING_LIST_REPORT_NO_"', 'INTEGER') }}                 as PACKING_LIST_REPORT_NO,
        {{ std_cast('"EXPEDITION_LABEL_REP_NO_"', 'INTEGER') }}                as EXPEDITION_LABEL_REP_NO,
        {{ std_cast('"INV_DISCOUNT"', 'NUMBER(38,5)') }}                       as INV_DISCOUNT,
        {{ std_cast('"DEFAULT_SHIP_TO_ADDRESS"', 'VARCHAR') }}                 as DEFAULT_SHIP_TO_ADDRESS,
        {{ std_cast('"AUTOINVOICE"', 'INTEGER') }}                             as AUTOINVOICE,
        {{ std_cast('"AUTOINVOICE_SERIE"', 'VARCHAR') }}                       as AUTOINVOICE_SERIE,
        {{ std_cast('"BANK_ACCOUNT_TO_TRANSFER"', 'VARCHAR') }}                as BANK_ACCOUNT_TO_TRANSFER,
        {{ std_cast('"SHIPMET_WITH_PALET_RESUME"', 'INTEGER') }}               as SHIPMET_WITH_PALET_RESUME,
        {{ std_cast('"PAPER_INVOICES"', 'INTEGER') }}                          as PAPER_INVOICES,
        {{ std_cast('"PDF_INVOICES"', 'INTEGER') }}                            as PDF_INVOICES,
        {{ std_cast('"RECALCULATE_PRICES_IN_INVOICE"', 'INTEGER') }}           as RECALCULATE_PRICES_IN_INVOICE,
        {{ std_cast('"LOAD_TIME"', 'VARCHAR') }}                               as LOAD_TIME,
        {{ std_cast('"LOAD_HR_"', 'TIMESTAMP_NTZ') }}                          as LOAD_HR,
        {{ std_cast('"ID_TYPE"', 'VARCHAR') }}                                 as ID_TYPE,
        {{ std_cast('"REGIMEN"', 'VARCHAR') }}                                 as REGIMEN,
        {{ std_cast('"RETENER_FACTURACION"', 'INTEGER') }}                     as RETENER_FACTURACION,
        {{ std_cast('"TOLERANCIA_RECADV"', 'NUMBER(38,5)') }}                  as TOLERANCIA_RECADV,
        {{ std_cast('"SHIPMENT_ZONE_CODE"', 'VARCHAR') }}                      as SHIPMENT_ZONE_CODE,
        {{ std_cast('"NUM_REGISTRO_ACUERDO_FACT_"', 'VARCHAR') }}              as NUM_REGISTRO_ACUERDO_FACT,
        {{ std_cast('"_LOT_COMPLIANCE"', 'NUMBER(38,5)') }}                    as LOT_COMPLIANCE,
        {{ std_cast('"EORI_NUMBER"', 'VARCHAR') }}                             as EORI_NUMBER,
        {{ std_cast('"SUPLEMENT_NO_"', 'VARCHAR') }}                           as SUPLEMENT_NO,
        {{ std_cast('"VAT_DOC_TYPE"', 'INTEGER') }}                            as VAT_DOC_TYPE,
        {{ std_cast('"OTHER_CUSTOMER"', 'INTEGER') }}                          as OTHER_CUSTOMER,
        {{ std_cast('"INTRASTAT_EXCLUDED"', 'INTEGER') }}                      as INTRASTAT_EXCLUDED,
        {{ std_cast('"SII_COUNTRY_CODE"', 'VARCHAR') }}                        as SII_COUNTRY_CODE,
        {{ std_cast('"EXCLUDE_REMINDER"', 'INTEGER') }}                        as EXCLUDE_REMINDER,
        {{ std_cast('"SCRAP_MANAGER"', 'INTEGER') }}                           as SCRAP_MANAGER,
        {{ std_cast('"SUBSET_11"', 'VARCHAR') }}                               as SUBSET_11,
        {{ std_cast('"SUBSET_12"', 'VARCHAR') }}                               as SUBSET_12,
        {{ std_cast('"SUBSET_13"', 'VARCHAR') }}                               as SUBSET_13,
        {{ std_cast('"SUBSET_14"', 'VARCHAR') }}                               as SUBSET_14,
        {{ std_cast('"SUBSET_15"', 'VARCHAR') }}                               as SUBSET_15,
        {{ std_cast('"SUBSET_16"', 'VARCHAR') }}                               as SUBSET_16,
        {{ std_cast('"SUBSET_17"', 'VARCHAR') }}                               as SUBSET_17,
        {{ std_cast('"SUBSET_18"', 'VARCHAR') }}                               as SUBSET_18,
        {{ std_cast('"SUBSET_19"', 'VARCHAR') }}                               as SUBSET_19,
        {{ std_cast('"SUBSET_20"', 'VARCHAR') }}                               as SUBSET_20,
        {{ std_cast('"LAST_ORDER_DATE"', 'TIMESTAMP_NTZ') }}                   as LAST_ORDER_DATE,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'COO'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
