{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_PRODUCTOS') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"No_ 2"', 'VARCHAR') }}                                   as NO_2,
        {{ std_cast('"Description"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"Search Description"', 'VARCHAR') }}                      as SEARCH_DESCRIPTION,
        {{ std_cast('"Description 2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"Base Unit of Measure"', 'VARCHAR') }}                    as BASE_UNIT_OF_MEASURE,
        {{ std_cast('"Price Unit Conversion"', 'INTEGER') }}                   as PRICE_UNIT_CONVERSION,
        {{ std_cast('"Type"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"Inventory Posting Group"', 'VARCHAR') }}                 as INVENTORY_POSTING_GROUP,
        {{ std_cast('"Shelf No_"', 'VARCHAR') }}                               as SHELF_NO,
        {{ std_cast('"Item Disc_ Group"', 'VARCHAR') }}                        as ITEM_DISC_GROUP,
        {{ std_cast('"Allow Invoice Disc_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"Statistics Group"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"Commission Group"', 'INTEGER') }}                        as COMMISSION_GROUP,
        {{ std_cast('"Unit Price"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"Price_Profit Calculation"', 'INTEGER') }}                as PRICE_PROFIT_CALCULATION,
        {{ std_cast('"Profit _"', 'NUMBER(38,5)') }}                           as PROFIT,
        {{ std_cast('"Costing Method"', 'INTEGER') }}                          as COSTING_METHOD,
        {{ std_cast('"Unit Cost"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"Standard Cost"', 'NUMBER(38,5)') }}                      as STANDARD_COST,
        {{ std_cast('"Last Direct Cost"', 'NUMBER(38,5)') }}                   as LAST_DIRECT_COST,
        {{ std_cast('"Indirect Cost _"', 'NUMBER(38,5)') }}                    as INDIRECT_COST,
        {{ std_cast('"Cost is Adjusted"', 'INTEGER') }}                        as COST_IS_ADJUSTED,
        {{ std_cast('"Allow Online Adjustment"', 'INTEGER') }}                 as ALLOW_ONLINE_ADJUSTMENT,
        {{ std_cast('"Vendor No_"', 'VARCHAR') }}                              as VENDOR_NO,
        {{ std_cast('"Vendor Item No_"', 'VARCHAR') }}                         as VENDOR_ITEM_NO,
        {{ std_cast('"Lead Time Calculation"', 'VARCHAR') }}                   as LEAD_TIME_CALCULATION,
        {{ std_cast('"Reorder Point"', 'NUMBER(38,5)') }}                      as REORDER_POINT,
        {{ std_cast('"Maximum Inventory"', 'NUMBER(38,5)') }}                  as MAXIMUM_INVENTORY,
        {{ std_cast('"Reorder Quantity"', 'NUMBER(38,5)') }}                   as REORDER_QUANTITY,
        {{ std_cast('"Alternative Item No_"', 'VARCHAR') }}                    as ALTERNATIVE_ITEM_NO,
        {{ std_cast('"Unit List Price"', 'NUMBER(38,5)') }}                    as UNIT_LIST_PRICE,
        {{ std_cast('"Duty Due _"', 'NUMBER(38,5)') }}                         as DUTY_DUE,
        {{ std_cast('"Duty Code"', 'VARCHAR') }}                               as DUTY_CODE,
        {{ std_cast('"Gross Weight"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"Net Weight"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"Units per Parcel"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"Unit Volume"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"Durability"', 'VARCHAR') }}                              as DURABILITY,
        {{ std_cast('"Freight Type"', 'VARCHAR') }}                            as FREIGHT_TYPE,
        {{ std_cast('"Tariff No_"', 'VARCHAR') }}                              as TARIFF_NO,
        {{ std_cast('"Duty Unit Conversion"', 'NUMBER(38,5)') }}               as DUTY_UNIT_CONVERSION,
        {{ std_cast('"Country_Region Purchased Code"', 'VARCHAR') }}           as COUNTRY_REGION_PURCHASED_CODE,
        {{ std_cast('"Budget Quantity"', 'NUMBER(38,5)') }}                    as BUDGET_QUANTITY,
        {{ std_cast('"Budgeted Amount"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"Budget Profit"', 'NUMBER(38,5)') }}                      as BUDGET_PROFIT,
        {{ std_cast('"Blocked"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"Last Date Modified"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"Price Includes VAT"', 'INTEGER') }}                      as PRICE_INCLUDES_VAT,
        {{ std_cast('"VAT Bus_ Posting Gr_ (Price)"', 'VARCHAR') }}            as VAT_BUS_POSTING_GR_PRICE,
        {{ std_cast('"Gen_ Prod_ Posting Group"', 'VARCHAR') }}                as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"Country_Region of Origin Code"', 'VARCHAR') }}           as COUNTRY_REGION_OF_ORIGIN_CODE,
        {{ std_cast('"Automatic Ext_ Texts"', 'INTEGER') }}                    as AUTOMATIC_EXT_TEXTS,
        {{ std_cast('"No_ Series"', 'VARCHAR') }}                              as NO_SERIES,
        {{ std_cast('"Tax Group Code"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT Prod_ Posting Group"', 'VARCHAR') }}                 as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"Reserve"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"Global Dimension 1 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"Global Dimension 2 Code"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"Stockout Warning"', 'INTEGER') }}                        as STOCKOUT_WARNING,
        {{ std_cast('"Prevent Negative Inventory"', 'INTEGER') }}              as PREVENT_NEGATIVE_INVENTORY,
        {{ std_cast('"Application Wksh_ User ID"', 'VARCHAR') }}               as APPLICATION_WKSH_USER_ID,
        {{ std_cast('"Assembly Policy"', 'INTEGER') }}                         as ASSEMBLY_POLICY,
        {{ std_cast('"GTIN"', 'VARCHAR') }}                                    as GTIN,
        {{ std_cast('"Default Deferral Template Code"', 'VARCHAR') }}          as DEFAULT_DEFERRAL_TEMPLATE_CODE,
        NULL                                                                   as LOW_LEVEL_CODE,
        {{ std_cast('"Lot Size"', 'NUMBER(38,5)') }}                           as LOT_SIZE,
        {{ std_cast('"Serial Nos_"', 'VARCHAR') }}                             as SERIAL_NOS,
        {{ std_cast('"Last Unit Cost Calc_ Date"', 'TIMESTAMP_NTZ') }}         as LAST_UNIT_COST_CALC_DATE,
        NULL                                                                   as ROLLED_UP_MATERIAL_COST,
        NULL                                                                   as ROLLED_UP_CAPACITY_COST,
        {{ std_cast('"Scrap _"', 'NUMBER(38,5)') }}                            as SCRAP,
        {{ std_cast('"Inventory Value Zero"', 'INTEGER') }}                    as INVENTORY_VALUE_ZERO,
        {{ std_cast('"Discrete Order Quantity"', 'INTEGER') }}                 as DISCRETE_ORDER_QUANTITY,
        {{ std_cast('"Minimum Order Quantity"', 'NUMBER(38,5)') }}             as MINIMUM_ORDER_QUANTITY,
        {{ std_cast('"Maximum Order Quantity"', 'NUMBER(38,5)') }}             as MAXIMUM_ORDER_QUANTITY,
        {{ std_cast('"Safety Stock Quantity"', 'NUMBER(38,5)') }}              as SAFETY_STOCK_QUANTITY,
        {{ std_cast('"Order Multiple"', 'NUMBER(38,5)') }}                     as ORDER_MULTIPLE,
        {{ std_cast('"Safety Lead Time"', 'VARCHAR') }}                        as SAFETY_LEAD_TIME,
        {{ std_cast('"Flushing Method"', 'INTEGER') }}                         as FLUSHING_METHOD,
        {{ std_cast('"Replenishment System"', 'INTEGER') }}                    as REPLENISHMENT_SYSTEM,
        {{ std_cast('"Rounding Precision"', 'NUMBER(38,5)') }}                 as ROUNDING_PRECISION,
        {{ std_cast('"Sales Unit of Measure"', 'VARCHAR') }}                   as SALES_UNIT_OF_MEASURE,
        {{ std_cast('"Purch_ Unit of Measure"', 'VARCHAR') }}                  as PURCH_UNIT_OF_MEASURE,
        {{ std_cast('"Time Bucket"', 'VARCHAR') }}                             as TIME_BUCKET,
        {{ std_cast('"Reordering Policy"', 'INTEGER') }}                       as REORDERING_POLICY,
        {{ std_cast('"Include Inventory"', 'INTEGER') }}                       as INCLUDE_INVENTORY,
        {{ std_cast('"Manufacturing Policy"', 'INTEGER') }}                    as MANUFACTURING_POLICY,
        {{ std_cast('"Rescheduling Period"', 'VARCHAR') }}                     as RESCHEDULING_PERIOD,
        {{ std_cast('"Lot Accumulation Period"', 'VARCHAR') }}                 as LOT_ACCUMULATION_PERIOD,
        {{ std_cast('"Dampener Period"', 'VARCHAR') }}                         as DAMPENER_PERIOD,
        {{ std_cast('"Dampener Quantity"', 'NUMBER(38,5)') }}                  as DAMPENER_QUANTITY,
        {{ std_cast('"Overflow Level"', 'NUMBER(38,5)') }}                     as OVERFLOW_LEVEL,
        {{ std_cast('"Manufacturer Code"', 'VARCHAR') }}                       as MANUFACTURER_CODE,
        {{ std_cast('"Item Category Code"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"Created From Nonstock Item"', 'INTEGER') }}              as CREATED_FROM_NONSTOCK_ITEM,
        {{ std_cast('"Product Group Code"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"Service Item Group"', 'VARCHAR') }}                      as SERVICE_ITEM_GROUP,
        {{ std_cast('"Item Tracking Code"', 'VARCHAR') }}                      as ITEM_TRACKING_CODE,
        {{ std_cast('"Lot Nos_"', 'VARCHAR') }}                                as LOT_NOS,
        {{ std_cast('"Expiration Calculation"', 'VARCHAR') }}                  as EXPIRATION_CALCULATION,
        {{ std_cast('"Special Equipment Code"', 'VARCHAR') }}                  as SPECIAL_EQUIPMENT_CODE,
        NULL                                                                   as PUT_AWAY_TEMPLATE_CODE,
        NULL                                                                   as PUT_AWAY_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"Phys Invt Counting Period Code"', 'VARCHAR') }}          as PHYS_INVT_COUNTING_PERIOD_CODE,
        {{ std_cast('"Last Counting Period Update"', 'TIMESTAMP_NTZ') }}       as LAST_COUNTING_PERIOD_UPDATE,
        NULL                                                                   as USE_CROSS_DOCKING,
        {{ std_cast('"Next Counting Start Date"', 'TIMESTAMP_NTZ') }}          as NEXT_COUNTING_START_DATE,
        {{ std_cast('"Next Counting End Date"', 'TIMESTAMP_NTZ') }}            as NEXT_COUNTING_END_DATE,
        {{ std_cast('"Cost Regulation _"', 'NUMBER(38,5)') }}                  as COST_REGULATION,
        NULL                                                                   as COMMENTS_TO_PURCH_ORDER,
        NULL                                                                   as ITEM_AREA,
        NULL                                                                   as TRADERMARK_CODE,
        NULL                                                                   as MOLD,
        NULL                                                                   as FIXED_WEIGHT,
        NULL                                                                   as ANIMAL,
        NULL                                                                   as STORAGE_CONDITIONS,
        NULL                                                                   as MIN_EXPIRY_ON_RECEPCION,
        NULL                                                                   as MIN_EXPIRY_ON_MANUFACTURING,
        NULL                                                                   as INJECTION,
        NULL                                                                   as WATER_LITERS,
        NULL                                                                   as SALT_CODE,
        NULL                                                                   as PRODUCT_IF,
        NULL                                                                   as ADITIVE_CODE,
        NULL                                                                   as RM_CODE,
        NULL                                                                   as COMMERCIAL_DESCRIPTION,
        NULL                                                                   as TARIFF_NO_CANARY_ISLAND,
        NULL                                                                   as MAQUILA,
        NULL                                                                   as KG_RM_TN,
        NULL                                                                   as KG_BRINE_TN,
        NULL                                                                   as COOP_PRODUCT_TYPE,
        NULL                                                                   as PACKAGING_TYPE,
        NULL                                                                   as BOX_X_JAIL,
        NULL                                                                   as UNITS_X_BOX,
        NULL                                                                   as QUANTITY_TO_CREATE_ORDER,
        NULL                                                                   as TOLERANCE_GR,
        NULL                                                                   as TEMPERATURE,
        NULL                                                                   as CREATE_ORDER_TO_VENDOR_NO,
        NULL                                                                   as TOTAL_ENEGETIC_VALUE_KCAL,
        NULL                                                                   as TOTAL_FAT_G,
        NULL                                                                   as OF_WITHCH_SATURADES_G,
        NULL                                                                   as CARBOHYDRATES_G,
        NULL                                                                   as OF_WITH_SUGARS_G,
        NULL                                                                   as PROTEIN_G,
        NULL                                                                   as SALT_G,
        NULL                                                                   as MOISTURE_FQ,
        NULL                                                                   as PROTEIN_FQ,
        NULL                                                                   as CARBOHYDRATES_FQ,
        NULL                                                                   as SUGARS_FQ,
        NULL                                                                   as HYDROXYPROLINE_FQ,
        NULL                                                                   as ASHES_FQ,
        NULL                                                                   as SALT_MG_FQ,
        NULL                                                                   as ALIMENTARY_FIBRE_FQ,
        NULL                                                                   as FAT_FQ,
        NULL                                                                   as FAT_SATURADES_FQ,
        NULL                                                                   as TOTAL_ENEGETIC_KCAL_100G,
        NULL                                                                   as PROTEIN_KCAL_100G,
        NULL                                                                   as FAT_KCAL_100G,
        NULL                                                                   as CARBOHYDRATES_KCAL_100G,
        NULL                                                                   as TOTAL_ENEGETIC_KJUL_100G,
        NULL                                                                   as OBSERVACIONES_SALMORRA,
        NULL                                                                   as BRINE_LOT,
        NULL                                                                   as BRINE_NO,
        NULL                                                                   as ALERGEN_CODE,
        NULL                                                                   as USE_INSTRUCTIONS_CODE,
        NULL                                                                   as MICROBIOLOGICAL_CONDITIONS,
        NULL                                                                   as MAINTENANCE,
        NULL                                                                   as PLAN_NO,
        NULL                                                                   as RECLASSIF_CODE,
        NULL                                                                   as REPROCESS_ROUTING_NO,
        NULL                                                                   as REPROCESS_BOM_NO,
        NULL                                                                   as NO_QUALITY_CONTROL,
        NULL                                                                   as QUAL_ROUNDING_PRECISION,
        NULL                                                                   as MANUFACTURER_MANDATORY,
        NULL                                                                   as REACTIVE,
        NULL                                                                   as NATURE,
        NULL                                                                   as CREATION_DATE,
        NULL                                                                   as DESCRIPCION_AMPLIADA,
        NULL                                                                   as SUBSET_1,
        NULL                                                                   as SUBSET_2,
        NULL                                                                   as SUBSET_3,
        NULL                                                                   as SUBSET_4,
        NULL                                                                   as SUBSET_5,
        NULL                                                                   as SUBSET_6,
        NULL                                                                   as SUBSET_7,
        NULL                                                                   as SUBSET_8,
        NULL                                                                   as SUBSET_9,
        NULL                                                                   as SUBSET_10,
        NULL                                                                   as WIDTH,
        NULL                                                                   as LENGTH,
        NULL                                                                   as TALL,
        NULL                                                                   as RM_FIELD_1,
        NULL                                                                   as RM_FIELD_2,
        NULL                                                                   as RM_FIELD_3,
        NULL                                                                   as RM_FIELD_4,
        NULL                                                                   as RM_FIELD_5,
        NULL                                                                   as MANUF_FIELD_1,
        NULL                                                                   as MANUF_FIELD_2,
        NULL                                                                   as MANUF_FIELD_3,
        NULL                                                                   as MANUF_FIELD_4,
        NULL                                                                   as MANUF_FIELD_5,
        NULL                                                                   as MANUF_FIELD_6,
        NULL                                                                   as MANUF_FIELD_7,
        NULL                                                                   as MANUF_FIELD_8,
        NULL                                                                   as MANUF_FIELD_9,
        NULL                                                                   as MANUF_FIELD_10,
        NULL                                                                   as RM_FIELD_1_DISTR,
        NULL                                                                   as RM_FIELD_2_DISTR,
        NULL                                                                   as RM_FIELD_3_DISTR,
        NULL                                                                   as RM_FIELD_4_DISTR,
        NULL                                                                   as RM_FIELD_5_DISTR,
        NULL                                                                   as MANUF_FIELD_1_DISTR,
        NULL                                                                   as MANUF_FIELD_2_DISTR,
        NULL                                                                   as MANUF_FIELD_3_DISTR,
        NULL                                                                   as MANUF_FIELD_4_DISTR,
        NULL                                                                   as MANUF_FIELD_5_DISTR,
        NULL                                                                   as MANUF_FIELD_6_DISTR,
        NULL                                                                   as MANUF_FIELD_7_DISTR,
        NULL                                                                   as MANUF_FIELD_8_DISTR,
        NULL                                                                   as MANUF_FIELD_9_DISTR,
        NULL                                                                   as MANUF_FIELD_10_DISTR,
        NULL                                                                   as WAREHOUSING_EXPENSES,
        NULL                                                                   as STRUCTURE_EXPENSES,
        NULL                                                                   as STRUCTURE_EXPENSES_DISTR,
        NULL                                                                   as KUBIC_COST,
        NULL                                                                   as RM_WEEKLY_COST,
        {{ std_cast('"Routing No_"', 'VARCHAR') }}                             as ROUTING_NO,
        {{ std_cast('"Production BOM No_"', 'VARCHAR') }}                      as PRODUCTION_BOM_NO,
        NULL                                                                   as SINGLE_LEVEL_MATERIAL_COST,
        NULL                                                                   as SINGLE_LEVEL_CAPACITY_COST,
        NULL                                                                   as SINGLE_LEVEL_SUBCONTRD_COST,
        NULL                                                                   as SINGLE_LEVEL_CAP_OVHD_COST,
        NULL                                                                   as SINGLE_LEVEL_MFG_OVHD_COST,
        {{ std_cast('"Overhead Rate"', 'NUMBER(38,5)') }}                      as OVERHEAD_RATE,
        NULL                                                                   as ROLLED_UP_SUBCONTRACTED_COST,
        NULL                                                                   as ROLLED_UP_MFG_OVHD_COST,
        NULL                                                                   as ROLLED_UP_CAP_OVERHEAD_COST,
        {{ std_cast('"Order Tracking Policy"', 'INTEGER') }}                   as ORDER_TRACKING_POLICY,
        {{ std_cast('"Critical"', 'INTEGER') }}                                as CRITICAL,
        {{ std_cast('"Common Item No_"', 'VARCHAR') }}                         as COMMON_ITEM_NO,
        NULL                                                                   as CONSUMO_SEMANAL_PREVISTO,
        NULL                                                                   as CADASTRAL_REFERENCE,
        NULL                                                                   as PROPERTY_SITUATION,
        NULL                                                                   as CONSUMIR_AL_EXPEDIR,
        NULL                                                                   as MCD_ITEM_NO,
        NULL                                                                   as OBSOLESCENDE_DATE,
        NULL                                                                   as KUBIC_FIXED_PRICE,
        NULL                                                                   as WITHOUT_CONSUMPTION,
        NULL                                                                   as LOCATION_BRINNE_PLANNING,
        NULL                                                                   as NOT_TO_INCLUDE_TRACK_MCD,
        NULL                                                                   as PRODUCTION_DATE,
        NULL                                                                   as EXPEDITION_DATE,
        NULL                                                                   as ECO,
        NULL                                                                   as DIAMETER,
        NULL                                                                   as BASE_GR,
        NULL                                                                   as PACKING_TYPE,
        NULL                                                                   as TESDIR_PRODUCT_TYPE,
        NULL                                                                   as CONTROL_SACO_COMPLETO,
        NULL                                                                   as MANUAL_COMSUMPTION,
        NULL                                                                   as RESP_CENTRE,
        NULL                                                                   as REPLENISHMENT_LOCATION_CODE,
        NULL                                                                   as GAMA_GC,
        NULL                                                                   as SUBGAMA_GC,
        NULL                                                                   as FAMILA_GC,
        NULL                                                                   as FORMATO_GC,
        NULL                                                                   as LOT_ANALYTICAL_MANDATORY,
        NULL                                                                   as HYDRATION,
        NULL                                                                   as KG_MP,
        NULL                                                                   as DEPOSITO_SALMORRA,
        NULL                                                                   as PACKAGE_ITEM_NO,
        NULL                                                                   as PERMITIR_CERRAR_OP_A_0,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        {{ std_cast('"Block Reason"', 'VARCHAR') }}                            as BLOCK_REASON,
        {{ std_cast('"Last DateTime Modified"', 'TIMESTAMP_NTZ') }}            as LAST_DATETIME_MODIFIED,
        {{ std_cast('"Last Time Modified"', 'TIMESTAMP_NTZ') }}                as LAST_TIME_MODIFIED,
        {{ std_cast('"Picture"', 'VARCHAR') }}                                 as PICTURE,
        {{ std_cast('"Low-Level Code"', 'INTEGER') }}                          as LOWLEVEL_CODE,
        {{ std_cast('"Rolled-up Material Cost"', 'NUMBER(38,5)') }}            as ROLLEDUP_MATERIAL_COST,
        {{ std_cast('"Rolled-up Capacity Cost"', 'NUMBER(38,5)') }}            as ROLLEDUP_CAPACITY_COST,
        {{ std_cast('"Warehouse Class Code"', 'VARCHAR') }}                    as WAREHOUSE_CLASS_CODE,
        {{ std_cast('"Put-away Template Code"', 'VARCHAR') }}                  as PUTAWAY_TEMPLATE_CODE,
        {{ std_cast('"Put-away Unit of Measure Code"', 'VARCHAR') }}           as PUTAWAY_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"Use Cross-Docking"', 'INTEGER') }}                       as USE_CROSSDOCKING,
        {{ std_cast('"Id"', 'VARCHAR') }}                                      as ID,
        {{ std_cast('"Unit of Measure Id"', 'VARCHAR') }}                      as UNIT_OF_MEASURE_ID,
        {{ std_cast('"Tax Group Id"', 'VARCHAR') }}                            as TAX_GROUP_ID,
        {{ std_cast('"Sales Blocked"', 'INTEGER') }}                           as SALES_BLOCKED,
        {{ std_cast('"Purchasing Blocked"', 'INTEGER') }}                      as PURCHASING_BLOCKED,
        {{ std_cast('"Item Category Id"', 'VARCHAR') }}                        as ITEM_CATEGORY_ID,
        {{ std_cast('"Single-Level Material Cost"', 'NUMBER(38,5)') }}         as SINGLELEVEL_MATERIAL_COST,
        {{ std_cast('"Single-Level Capacity Cost"', 'NUMBER(38,5)') }}         as SINGLELEVEL_CAPACITY_COST,
        {{ std_cast('"Single-Level Subcontrd_ Cost"', 'NUMBER(38,5)') }}       as SINGLELEVEL_SUBCONTRD_COST,
        {{ std_cast('"Single-Level Cap_ Ovhd Cost"', 'NUMBER(38,5)') }}        as SINGLELEVEL_CAP_OVHD_COST,
        {{ std_cast('"Single-Level Mfg_ Ovhd Cost"', 'NUMBER(38,5)') }}        as SINGLELEVEL_MFG_OVHD_COST,
        {{ std_cast('"Rolled-up Subcontracted Cost"', 'NUMBER(38,5)') }}       as ROLLEDUP_SUBCONTRACTED_COST,
        {{ std_cast('"Rolled-up Mfg_ Ovhd Cost"', 'NUMBER(38,5)') }}           as ROLLEDUP_MFG_OVHD_COST,
        {{ std_cast('"Rolled-up Cap_ Overhead Cost"', 'NUMBER(38,5)') }}       as ROLLEDUP_CAP_OVERHEAD_COST,
        {{ std_cast('"INVENTARIO"', 'NUMBER(38,5)') }}                         as INVENTARIO,
        {{ std_cast('"INVENTARIO_VUM"', 'NUMBER(38,5)') }}                     as INVENTARIO_VUM,
        {{ std_cast('"IF_RD_TYPE"', 'VARCHAR') }}                              as IF_RD_TYPE,
        {{ std_cast('"IF_FIXED_WEIGHT"', 'NUMBER(38,5)') }}                    as IF_FIXED_WEIGHT,
        {{ std_cast('"IF_MIN_TMP"', 'NUMBER(38,5)') }}                         as IF_MIN_TMP,
        {{ std_cast('"IF_MAX_TMP"', 'NUMBER(38,5)') }}                         as IF_MAX_TMP,
        {{ std_cast('"IF_ERR_WEIGHT"', 'NUMBER(38,5)') }}                      as IF_ERR_WEIGHT,
        {{ std_cast('"IF_PRODUCT_UOM_CONTROL"', 'INTEGER') }}                  as IF_PRODUCT_UOM_CONTROL,
        {{ std_cast('"IF_CL_CODE_TYPE"', 'INTEGER') }}                         as IF_CL_CODE_TYPE,
        {{ std_cast('"IF_CL_CODE_EAN14"', 'VARCHAR') }}                        as IF_CL_CODE_EAN14,
        {{ std_cast('"IF_TRAY_TARE"', 'NUMBER(38,5)') }}                       as IF_TRAY_TARE,
        {{ std_cast('"IF_BOX_TARE"', 'NUMBER(38,5)') }}                        as IF_BOX_TARE,
        {{ std_cast('"IF_TRAYS_IN_BOX"', 'INTEGER') }}                         as IF_TRAYS_IN_BOX,
        {{ std_cast('"IF_BOXES_IN_PALLET"', 'INTEGER') }}                      as IF_BOXES_IN_PALLET,
        {{ std_cast('"IF_RET_DAYS"', 'VARCHAR') }}                             as IF_RET_DAYS,
        {{ std_cast('"IF_BOX_PACK"', 'VARCHAR') }}                             as IF_BOX_PACK,
        {{ std_cast('"IF_MIN_WEIGHT"', 'NUMBER(38,5)') }}                      as IF_MIN_WEIGHT,
        {{ std_cast('"IF_MAX_WEIGHT"', 'NUMBER(38,5)') }}                      as IF_MAX_WEIGHT,
        {{ std_cast('"IF_ERR_WEIGHT_DOWN"', 'NUMBER(38,5)') }}                 as IF_ERR_WEIGHT_DOWN,
        {{ std_cast('"RD_INTERNAL"', 'INTEGER') }}                             as RD_INTERNAL,
        {{ std_cast('"IF_GRASA_INFERIOR"', 'NUMBER(38,5)') }}                  as IF_GRASA_INFERIOR,
        {{ std_cast('"IF_GRASA_SUPERIOR"', 'NUMBER(38,5)') }}                  as IF_GRASA_SUPERIOR,
        {{ std_cast('"IF_PD_ID"', 'VARCHAR') }}                                as IF_PD_ID,
        {{ std_cast('"IF_PD_TYPE"', 'INTEGER') }}                              as IF_PD_TYPE,
        {{ std_cast('"AIT Dias en tienda"', 'VARCHAR') }}                      as AIT_DIAS_EN_TIENDA,
        {{ std_cast('"DimensionesBolsa"', 'VARCHAR') }}                        as DIMENSIONESBOLSA,
        {{ std_cast('"AIT Owner"', 'VARCHAR') }}                               as AIT_OWNER,
        {{ std_cast('"EAN14BOX"', 'VARCHAR') }}                                as EAN14BOX,
        {{ std_cast('"DL_MachineCode"', 'VARCHAR') }}                          as DL_MACHINECODE,
        {{ std_cast('"Has Sales Forecast"', 'INTEGER') }}                      as HAS_SALES_FORECAST,
        {{ std_cast('"Delay days"', 'VARCHAR') }}                              as DELAY_DAYS,
        {{ std_cast('"IDPVUM Variable Unit Measure"', 'VARCHAR') }}            as IDPVUM_VARIABLE_UNIT_MEASURE,
        {{ std_cast('"IDPVUM Price in VUM"', 'INTEGER') }}                     as IDPVUM_PRICE_IN_VUM,
        {{ std_cast('"IDPVUM Cost in VUM"', 'INTEGER') }}                      as IDPVUM_COST_IN_VUM,
        {{ std_cast('"IDPVUM Automatic Decrease"', 'INTEGER') }}               as IDPVUM_AUTOMATIC_DECREASE,
        {{ std_cast('"IDPVUM Decrease of Deviation"', 'INTEGER') }}            as IDPVUM_DECREASE_OF_DEVIATION,
        {{ std_cast('"IDPVUM Decrease of Adjust"', 'INTEGER') }}               as IDPVUM_DECREASE_OF_ADJUST,
        {{ std_cast('"IDPVUM Decrease of Liquidation"', 'INTEGER') }}          as IDPVUM_DECREASE_OF_LIQUIDATION,
        {{ std_cast('"IDPVUM Manual Decrease"', 'INTEGER') }}                  as IDPVUM_MANUAL_DECREASE,
        {{ std_cast('"IDPVUM Upd_ Sales Doc_ (Qty_)"', 'INTEGER') }}           as IDPVUM_UPD_SALES_DOC_QTY,
        {{ std_cast('"IDPVUM Sales Rounding Prec_"', 'NUMBER(38,5)') }}        as IDPVUM_SALES_ROUNDING_PREC,
        {{ std_cast('"IDPVUM Sales Rounding Type"', 'INTEGER') }}              as IDPVUM_SALES_ROUNDING_TYPE,
        {{ std_cast('"IDPVUM Upd_ Pch_ Doc_ (Qty_)"', 'INTEGER') }}            as IDPVUM_UPD_PCH_DOC_QTY,
        {{ std_cast('"IDPVUM Purch_ Rounding Prec_"', 'NUMBER(38,5)') }}       as IDPVUM_PURCH_ROUNDING_PREC,
        {{ std_cast('"IDPVUM Purch_ Rounding Type"', 'INTEGER') }}             as IDPVUM_PURCH_ROUNDING_TYPE,
        {{ std_cast('"AIT Vendor Posting Gr"', 'VARCHAR') }}                   as AIT_VENDOR_POSTING_GR,
        {{ std_cast('"AIT Creation User"', 'VARCHAR') }}                       as AIT_CREATION_USER,
        {{ std_cast('"AIT Creation Datetime"', 'TIMESTAMP_NTZ') }}             as AIT_CREATION_DATETIME,
        {{ std_cast('"product_group"', 'VARCHAR') }}                           as PRODUCT_GROUP,
        {{ std_cast('"product_class"', 'VARCHAR') }}                           as PRODUCT_CLASS,
        {{ std_cast('"product_component"', 'VARCHAR') }}                       as PRODUCT_COMPONENT,
        {{ std_cast('"ALERGENOS"', 'VARCHAR') }}                               as ALERGENOS,
        {{ std_cast('"ES CARNE"', 'VARCHAR') }}                                as ES_CARNE,
        {{ std_cast('"CONGELADO"', 'VARCHAR') }}                               as CONGELADO,
        {{ std_cast('"CRITICO"', 'VARCHAR') }}                                 as CRITICO,
        {{ std_cast('"DEMORA-SOLO CARGA"', 'VARCHAR') }}                       as DEMORASOLO_CARGA,
        {{ std_cast('"DIAS EN TIENDA"', 'VARCHAR') }}                          as DIAS_EN_TIENDA,
        {{ std_cast('"DET LUNES"', 'VARCHAR') }}                               as DET_LUNES,
        {{ std_cast('"DET MARTES"', 'VARCHAR') }}                              as DET_MARTES,
        {{ std_cast('"DET MIERCOLES"', 'VARCHAR') }}                           as DET_MIERCOLES,
        {{ std_cast('"DET JUEVES"', 'VARCHAR') }}                              as DET_JUEVES,
        {{ std_cast('"DET VIERNES"', 'VARCHAR') }}                             as DET_VIERNES,
        {{ std_cast('"DET SABADO"', 'VARCHAR') }}                              as DET_SABADO,
        {{ std_cast('"DET DOMINGO"', 'VARCHAR') }}                             as DET_DOMINGO,
        {{ std_cast('"DIAS VIDA MAX. USO"', 'VARCHAR') }}                      as DIAS_VIDA_MAX_USO,
        {{ std_cast('"FECHA SACRIFICIO"', 'VARCHAR') }}                        as FECHA_SACRIFICIO,
        {{ std_cast('"GARGANES"', 'VARCHAR') }}                                as GARGANES,
        {{ std_cast('"GERENTE MDONA"', 'VARCHAR') }}                           as GERENTE_MDONA,
        {{ std_cast('"CAJA LOGIFRUIT"', 'VARCHAR') }}                          as CAJA_LOGIFRUIT,
        {{ std_cast('"MARCA"', 'VARCHAR') }}                                   as MARCA,
        {{ std_cast('"MODELO"', 'VARCHAR') }}                                  as MODELO,
        {{ std_cast('"REFERENCIA"', 'VARCHAR') }}                              as REFERENCIA,
        {{ std_cast('"REPARABILIDAD"', 'VARCHAR') }}                           as REPARABILIDAD,
        {{ std_cast('"CERTIF.SAE"', 'VARCHAR') }}                              as CERTIFSAE,
        {{ std_cast('"SIN TRAZAB VACUNO"', 'VARCHAR') }}                       as SIN_TRAZAB_VACUNO,
        {{ std_cast('"SIN VALORACION STOCK"', 'VARCHAR') }}                    as SIN_VALORACION_STOCK,
        {{ std_cast('"SUMINISTRADOR"', 'VARCHAR') }}                           as SUMINISTRADOR,
        {{ std_cast('"LOTES VACUNO"', 'VARCHAR') }}                            as LOTES_VACUNO,
        {{ std_cast('"IGIC"', 'VARCHAR') }}                                    as IGIC,
        {{ std_cast('"SUBSEMI"', 'VARCHAR') }}                                 as SUBSEMI,
        {{ std_cast('"FECHA DESPIECE"', 'VARCHAR') }}                          as FECHA_DESPIECE,
        {{ std_cast('"LOTE 10"', 'VARCHAR') }}                                 as LOTE_10,
        {{ std_cast('"JAPON"', 'VARCHAR') }}                                   as JAPON,
        {{ std_cast('"ENCOLADO FECHA PRODUCCION"', 'VARCHAR') }}               as ENCOLADO_FECHA_PRODUCCION,
        {{ std_cast('"COMEDOR"', 'VARCHAR') }}                                 as COMEDOR,
        {{ std_cast('"PACKINGLIST CADUCIDAD"', 'VARCHAR') }}                   as PACKINGLIST_CADUCIDAD,
        {{ std_cast('"FVENTA ES FCADUCIDAD"', 'VARCHAR') }}                    as FVENTA_ES_FCADUCIDAD,
        {{ std_cast('"HEURA"', 'VARCHAR') }}                                   as HEURA,
        {{ std_cast('"ES PACK"', 'VARCHAR') }}                                 as ES_PACK,
        {{ std_cast('"HONGKONG"', 'VARCHAR') }}                                as HONGKONG,
        {{ std_cast('"SINGAPUR"', 'VARCHAR') }}                                as SINGAPUR,
        {{ std_cast('"MUESTRAS"', 'VARCHAR') }}                                as MUESTRAS,
        {{ std_cast('"COD_FABRICANTE"', 'VARCHAR') }}                          as COD_FABRICANTE,
        {{ std_cast('"PORPLA"', 'VARCHAR') }}                                  as PORPLA,
        {{ std_cast('"PEDIDO_KG_MDONA"', 'VARCHAR') }}                         as PEDIDO_KG_MDONA,
        {{ std_cast('"CANARIAS"', 'VARCHAR') }}                                as CANARIAS,
        {{ std_cast('"FRICAFOR"', 'VARCHAR') }}                                as FRICAFOR,
        {{ std_cast('"CROQUETAS"', 'VARCHAR') }}                               as CROQUETAS,
        {{ std_cast('"REFRIGERADO"', 'VARCHAR') }}                             as REFRIGERADO,
        NULL                                                                   as MANTENIMIENTO,
        NULL                                                                   as COD_RAPPEL_VENTAS,
        NULL                                                                   as COD_RAPPEL_COMPRAS,
        NULL                                                                   as NO_PRESENTACION,
        NULL                                                                   as CODIGO_EMBALAJE,
        NULL                                                                   as CONTROL_DIB,
        NULL                                                                   as PRECIO_PUNTO_VERDE_CDAD_DL,
        NULL                                                                   as UNIDAD_MEDIDA_PUNTO_VERDE,
        NULL                                                                   as GRUPO_RESIDUOS,
        NULL                                                                   as AUTOCOMPLETAR_EMBALAJE,
        NULL                                                                   as ANS_CADUCIDAD_RECEP,
        NULL                                                                   as ANS_CADUCIDAD_EXPED,
        NULL                                                                   as LIQUIDACION_POR_EMBALAJE,
        NULL                                                                   as PESO_FIJO,
        NULL                                                                   as LIQUIDACION_POR_PESADA,
        NULL                                                                   as NOMBRE_ABREVIADO,
        NULL                                                                   as CANT_ALTERNATIVA_OBLIGATORIA,
        NULL                                                                   as CODIGO_PLU,
        NULL                                                                   as REGISTRO_SANITARIO,
        NULL                                                                   as COD_EMBALAJE_COMPRA,
        NULL                                                                   as COD_PALET_DEFECTO,
        NULL                                                                   as TIPO_PALETIZACION,
        NULL                                                                   as PALET_POR_DEFECTO,
        NULL                                                                   as PESADA_POR_PRODUCTO_LOTE,
        NULL                                                                   as PRODUCTO_DE_VENTA,
        NULL                                                                   as PLAZO_CONSUMO_PREFERENTE,
        NULL                                                                   as FECHA_ALTA,
        NULL                                                                   as USUARIO_ALTA,
        NULL                                                                   as PESO_FIJO_EN_VENTA,
        NULL                                                                   as PRODUCTO_IBERICO,
        NULL                                                                   as STOCK_SEGURIDAD_PRODUCCION,
        NULL                                                                   as NATURALEZA_PRODUCTO,
        NULL                                                                   as TEMPERATURA_MINIMA,
        NULL                                                                   as TEMPERATURA_MAXIMA,
        NULL                                                                   as BLOQUEAR_AJUSTE_AUT_COSTE,
        NULL                                                                   as MERMA_TEORICA,
        NULL                                                                   as PLAZO_OP_FABRIC,
        NULL                                                                   as PRODUCTO_ORIGEN,
        NULL                                                                   as COSTES_POR_CANTIDAD,
        NULL                                                                   as UNIDADES_POR_CAJA,
        NULL                                                                   as CAJAS_POR_PALET,
        NULL                                                                   as PESO_MIN_UNIDAD,
        NULL                                                                   as PESO_MAX_UNIDAD,
        NULL                                                                   as TOLERANCIA,
        NULL                                                                   as PRESENCIA_OGM,
        NULL                                                                   as PAIS_PROCEDENCIA,
        NULL                                                                   as CERTIFICADO_NO_OGM,
        NULL                                                                   as TEXTO_ETIQUETA,
        NULL                                                                   as ORIGEN,
        NULL                                                                   as COD_PLANTILLA,
        NULL                                                                   as TIEMPO_REPOSO,
        NULL                                                                   as LOCATION_CODE,
        NULL                                                                   as PERMITIR_RECLASIFICACION_OC,
        NULL                                                                   as AVISO_CALIDAD,
        NULL                                                                   as EMB_ETIQUETA,
        NULL                                                                   as PRODUCTO_A_CURAR,
        NULL                                                                   as PALETIZACION_AUTOMATICA,
        NULL                                                                   as EDI_CODIGO_EAN,
        NULL                                                                   as PRECIO_MATADERO,
        NULL                                                                   as COD_ESPECIE,
        NULL                                                                   as CONTROL_POR,
        NULL                                                                   as NO_PLANTILLA_OT_MATADERO,
        NULL                                                                   as NO_PLANTILLA_OT_DESPIECE,
        NULL                                                                   as COD_GRUPO_INGREDIENTES,
        NULL                                                                   as CALCULO_FECHA_RETIRADA,
        NULL                                                                   as NO_PRODUCTO_KAIS,
        NULL                                                                   as CONTROLAR_PESO_MIN_MAX,
        NULL                                                                   as CONTROL_CADUCIDAD_EXPEDICION,
        NULL                                                                   as DESCRIPCION_INTERNA,
        NULL                                                                   as RECADV_DISABLED,
        'DLS'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
