{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_ITEM') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"NO_2"', 'VARCHAR') }}                                    as NO_2,
        {{ std_cast('"DESCRIPTION"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"SEARCH_DESCRIPTION"', 'VARCHAR') }}                      as SEARCH_DESCRIPTION,
        {{ std_cast('"DESCRIPTION_2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"BASE_UNIT_OF_MEASURE"', 'VARCHAR') }}                    as BASE_UNIT_OF_MEASURE,
        {{ std_cast('"PRICE_UNIT_CONVERSION"', 'INTEGER') }}                   as PRICE_UNIT_CONVERSION,
        {{ std_cast('"TYPE"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"INVENTORY_POSTING_GROUP"', 'VARCHAR') }}                 as INVENTORY_POSTING_GROUP,
        {{ std_cast('"SHELF_NO_"', 'VARCHAR') }}                               as SHELF_NO,
        {{ std_cast('"ITEM_DISC_GROUP"', 'VARCHAR') }}                         as ITEM_DISC_GROUP,
        {{ std_cast('"ALLOW_INVOICE_DISC_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"STATISTICS_GROUP"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"COMMISSION_GROUP"', 'INTEGER') }}                        as COMMISSION_GROUP,
        {{ std_cast('"UNIT_PRICE"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"PRICE_PROFIT_CALCULATION"', 'INTEGER') }}                as PRICE_PROFIT_CALCULATION,
        {{ std_cast('"PROFIT_"', 'NUMBER(38,5)') }}                            as PROFIT,
        {{ std_cast('"COSTING_METHOD"', 'INTEGER') }}                          as COSTING_METHOD,
        {{ std_cast('"UNIT_COST"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"STANDARD_COST"', 'NUMBER(38,5)') }}                      as STANDARD_COST,
        {{ std_cast('"LAST_DIRECT_COST"', 'NUMBER(38,5)') }}                   as LAST_DIRECT_COST,
        {{ std_cast('"INDIRECT_COST_"', 'NUMBER(38,5)') }}                     as INDIRECT_COST,
        {{ std_cast('"COST_IS_ADJUSTED"', 'INTEGER') }}                        as COST_IS_ADJUSTED,
        {{ std_cast('"ALLOW_ONLINE_ADJUSTMENT"', 'INTEGER') }}                 as ALLOW_ONLINE_ADJUSTMENT,
        {{ std_cast('"VENDOR_NO_"', 'VARCHAR') }}                              as VENDOR_NO,
        {{ std_cast('"VENDOR_ITEM_NO_"', 'VARCHAR') }}                         as VENDOR_ITEM_NO,
        {{ std_cast('"LEAD_TIME_CALCULATION"', 'VARCHAR') }}                   as LEAD_TIME_CALCULATION,
        {{ std_cast('"REORDER_POINT"', 'NUMBER(38,5)') }}                      as REORDER_POINT,
        {{ std_cast('"MAXIMUM_INVENTORY"', 'NUMBER(38,5)') }}                  as MAXIMUM_INVENTORY,
        {{ std_cast('"REORDER_QUANTITY"', 'NUMBER(38,5)') }}                   as REORDER_QUANTITY,
        {{ std_cast('"ALTERNATIVE_ITEM_NO_"', 'VARCHAR') }}                    as ALTERNATIVE_ITEM_NO,
        {{ std_cast('"UNIT_LIST_PRICE"', 'NUMBER(38,5)') }}                    as UNIT_LIST_PRICE,
        {{ std_cast('"DUTY_DUE_"', 'NUMBER(38,5)') }}                          as DUTY_DUE,
        {{ std_cast('"DUTY_CODE"', 'VARCHAR') }}                               as DUTY_CODE,
        {{ std_cast('"GROSS_WEIGHT"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"NET_WEIGHT"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"UNITS_PER_PARCEL"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"UNIT_VOLUME"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"DURABILITY"', 'VARCHAR') }}                              as DURABILITY,
        {{ std_cast('"FREIGHT_TYPE"', 'VARCHAR') }}                            as FREIGHT_TYPE,
        {{ std_cast('"TARIFF_NO_"', 'VARCHAR') }}                              as TARIFF_NO,
        {{ std_cast('"DUTY_UNIT_CONVERSION"', 'NUMBER(38,5)') }}               as DUTY_UNIT_CONVERSION,
        {{ std_cast('"COUNTRY_REGION_PURCHASED_CODE"', 'VARCHAR') }}           as COUNTRY_REGION_PURCHASED_CODE,
        {{ std_cast('"BUDGET_QUANTITY"', 'NUMBER(38,5)') }}                    as BUDGET_QUANTITY,
        {{ std_cast('"BUDGETED_AMOUNT"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"BUDGET_PROFIT"', 'NUMBER(38,5)') }}                      as BUDGET_PROFIT,
        {{ std_cast('"BLOCKED"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"LAST_DATE_MODIFIED"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"PRICE_INCLUDES_VAT"', 'INTEGER') }}                      as PRICE_INCLUDES_VAT,
        {{ std_cast('"VAT_BUS_POSTING_GR_PRICE"', 'VARCHAR') }}                as VAT_BUS_POSTING_GR_PRICE,
        {{ std_cast('"GEN_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"COUNTRY_REGION_OF_ORIGIN_CODE"', 'VARCHAR') }}           as COUNTRY_REGION_OF_ORIGIN_CODE,
        {{ std_cast('"AUTOMATIC_EXT_TEXTS"', 'INTEGER') }}                     as AUTOMATIC_EXT_TEXTS,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"TAX_GROUP_CODE"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"GLOBAL_DIMENSION_1_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_2_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"STOCKOUT_WARNING"', 'INTEGER') }}                        as STOCKOUT_WARNING,
        {{ std_cast('"PREVENT_NEGATIVE_INVENTORY"', 'INTEGER') }}              as PREVENT_NEGATIVE_INVENTORY,
        {{ std_cast('"APPLICATION_WKSH_USER_ID"', 'VARCHAR') }}                as APPLICATION_WKSH_USER_ID,
        {{ std_cast('"ASSEMBLY_POLICY"', 'INTEGER') }}                         as ASSEMBLY_POLICY,
        {{ std_cast('"GTIN"', 'VARCHAR') }}                                    as GTIN,
        {{ std_cast('"DEFAULT_DEFERRAL_TEMPLATE_CODE"', 'VARCHAR') }}          as DEFAULT_DEFERRAL_TEMPLATE_CODE,
        {{ std_cast('"LOW_LEVEL_CODE"', 'INTEGER') }}                          as LOW_LEVEL_CODE,
        {{ std_cast('"LOT_SIZE"', 'NUMBER(38,5)') }}                           as LOT_SIZE,
        {{ std_cast('"SERIAL_NOS_"', 'VARCHAR') }}                             as SERIAL_NOS,
        {{ std_cast('"LAST_UNIT_COST_CALC_DATE"', 'TIMESTAMP_NTZ') }}          as LAST_UNIT_COST_CALC_DATE,
        {{ std_cast('"ROLLED_UP_MATERIAL_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_MATERIAL_COST,
        {{ std_cast('"ROLLED_UP_CAPACITY_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_CAPACITY_COST,
        {{ std_cast('"SCRAP_"', 'NUMBER(38,5)') }}                             as SCRAP,
        {{ std_cast('"INVENTORY_VALUE_ZERO"', 'INTEGER') }}                    as INVENTORY_VALUE_ZERO,
        {{ std_cast('"DISCRETE_ORDER_QUANTITY"', 'INTEGER') }}                 as DISCRETE_ORDER_QUANTITY,
        {{ std_cast('"MINIMUM_ORDER_QUANTITY"', 'NUMBER(38,5)') }}             as MINIMUM_ORDER_QUANTITY,
        {{ std_cast('"MAXIMUM_ORDER_QUANTITY"', 'NUMBER(38,5)') }}             as MAXIMUM_ORDER_QUANTITY,
        {{ std_cast('"SAFETY_STOCK_QUANTITY"', 'NUMBER(38,5)') }}              as SAFETY_STOCK_QUANTITY,
        {{ std_cast('"ORDER_MULTIPLE"', 'NUMBER(38,5)') }}                     as ORDER_MULTIPLE,
        {{ std_cast('"SAFETY_LEAD_TIME"', 'VARCHAR') }}                        as SAFETY_LEAD_TIME,
        {{ std_cast('"FLUSHING_METHOD"', 'INTEGER') }}                         as FLUSHING_METHOD,
        {{ std_cast('"REPLENISHMENT_SYSTEM"', 'INTEGER') }}                    as REPLENISHMENT_SYSTEM,
        {{ std_cast('"ROUNDING_PRECISION"', 'NUMBER(38,5)') }}                 as ROUNDING_PRECISION,
        {{ std_cast('"SALES_UNIT_OF_MEASURE"', 'VARCHAR') }}                   as SALES_UNIT_OF_MEASURE,
        {{ std_cast('"PURCH_UNIT_OF_MEASURE"', 'VARCHAR') }}                   as PURCH_UNIT_OF_MEASURE,
        {{ std_cast('"TIME_BUCKET"', 'VARCHAR') }}                             as TIME_BUCKET,
        {{ std_cast('"REORDERING_POLICY"', 'INTEGER') }}                       as REORDERING_POLICY,
        {{ std_cast('"INCLUDE_INVENTORY"', 'INTEGER') }}                       as INCLUDE_INVENTORY,
        {{ std_cast('"MANUFACTURING_POLICY"', 'INTEGER') }}                    as MANUFACTURING_POLICY,
        {{ std_cast('"RESCHEDULING_PERIOD"', 'VARCHAR') }}                     as RESCHEDULING_PERIOD,
        {{ std_cast('"LOT_ACCUMULATION_PERIOD"', 'VARCHAR') }}                 as LOT_ACCUMULATION_PERIOD,
        {{ std_cast('"DAMPENER_PERIOD"', 'VARCHAR') }}                         as DAMPENER_PERIOD,
        {{ std_cast('"DAMPENER_QUANTITY"', 'NUMBER(38,5)') }}                  as DAMPENER_QUANTITY,
        {{ std_cast('"OVERFLOW_LEVEL"', 'NUMBER(38,5)') }}                     as OVERFLOW_LEVEL,
        {{ std_cast('"MANUFACTURER_CODE"', 'VARCHAR') }}                       as MANUFACTURER_CODE,
        {{ std_cast('"ITEM_CATEGORY_CODE"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"CREATED_FROM_NONSTOCK_ITEM"', 'INTEGER') }}              as CREATED_FROM_NONSTOCK_ITEM,
        {{ std_cast('"PRODUCT_GROUP_CODE"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"SERVICE_ITEM_GROUP"', 'VARCHAR') }}                      as SERVICE_ITEM_GROUP,
        {{ std_cast('"ITEM_TRACKING_CODE"', 'VARCHAR') }}                      as ITEM_TRACKING_CODE,
        {{ std_cast('"LOT_NOS_"', 'VARCHAR') }}                                as LOT_NOS,
        {{ std_cast('"EXPIRATION_CALCULATION"', 'VARCHAR') }}                  as EXPIRATION_CALCULATION,
        {{ std_cast('"SPECIAL_EQUIPMENT_CODE"', 'VARCHAR') }}                  as SPECIAL_EQUIPMENT_CODE,
        {{ std_cast('"PUT_AWAY_TEMPLATE_CODE"', 'VARCHAR') }}                  as PUT_AWAY_TEMPLATE_CODE,
        {{ std_cast('"PUT_AWAY_UNIT_OF_MEASURE_CODE"', 'VARCHAR') }}           as PUT_AWAY_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"PHYS_INVT_COUNTING_PERIOD_CODE"', 'VARCHAR') }}          as PHYS_INVT_COUNTING_PERIOD_CODE,
        {{ std_cast('"LAST_COUNTING_PERIOD_UPDATE"', 'TIMESTAMP_NTZ') }}       as LAST_COUNTING_PERIOD_UPDATE,
        {{ std_cast('"USE_CROSS_DOCKING"', 'INTEGER') }}                       as USE_CROSS_DOCKING,
        {{ std_cast('"NEXT_COUNTING_START_DATE"', 'TIMESTAMP_NTZ') }}          as NEXT_COUNTING_START_DATE,
        {{ std_cast('"NEXT_COUNTING_END_DATE"', 'TIMESTAMP_NTZ') }}            as NEXT_COUNTING_END_DATE,
        {{ std_cast('"COST_REGULATION_"', 'NUMBER(38,5)') }}                   as COST_REGULATION,
        {{ std_cast('"COMMENTS_TO_PURCH_ORDER"', 'VARCHAR') }}                 as COMMENTS_TO_PURCH_ORDER,
        {{ std_cast('"ITEM_AREA"', 'INTEGER') }}                               as ITEM_AREA,
        {{ std_cast('"TRADERMARK_CODE"', 'VARCHAR') }}                         as TRADERMARK_CODE,
        {{ std_cast('"MOLD"', 'VARCHAR') }}                                    as MOLD,
        {{ std_cast('"FIXED_WEIGHT"', 'INTEGER') }}                            as FIXED_WEIGHT,
        {{ std_cast('"ANIMAL"', 'VARCHAR') }}                                  as ANIMAL,
        {{ std_cast('"STORAGE_CONDITIONS"', 'VARCHAR') }}                      as STORAGE_CONDITIONS,
        {{ std_cast('"MIN_EXPIRY_ON_RECEPCION"', 'INTEGER') }}                 as MIN_EXPIRY_ON_RECEPCION,
        {{ std_cast('"MIN_EXPIRY_ON_MANUFACTURING"', 'INTEGER') }}             as MIN_EXPIRY_ON_MANUFACTURING,
        {{ std_cast('"INJECTION_"', 'NUMBER(38,5)') }}                         as INJECTION,
        {{ std_cast('"WATER_LITERS"', 'NUMBER(38,5)') }}                       as WATER_LITERS,
        {{ std_cast('"SALT_CODE"', 'VARCHAR') }}                               as SALT_CODE,
        {{ std_cast('"PRODUCT_IF"', 'VARCHAR') }}                              as PRODUCT_IF,
        {{ std_cast('"ADITIVE_CODE"', 'VARCHAR') }}                            as ADITIVE_CODE,
        {{ std_cast('"RM_CODE"', 'VARCHAR') }}                                 as RM_CODE,
        {{ std_cast('"COMMERCIAL_DESCRIPTION"', 'VARCHAR') }}                  as COMMERCIAL_DESCRIPTION,
        {{ std_cast('"TARIFF_NO_CANARY_ISLAND"', 'VARCHAR') }}                 as TARIFF_NO_CANARY_ISLAND,
        {{ std_cast('"MAQUILA"', 'INTEGER') }}                                 as MAQUILA,
        {{ std_cast('"KG_RM_TN"', 'NUMBER(38,5)') }}                           as KG_RM_TN,
        {{ std_cast('"KG_BRINE_TN"', 'NUMBER(38,5)') }}                        as KG_BRINE_TN,
        {{ std_cast('"COOP_PRODUCT_TYPE"', 'INTEGER') }}                       as COOP_PRODUCT_TYPE,
        {{ std_cast('"PACKAGING_TYPE"', 'INTEGER') }}                          as PACKAGING_TYPE,
        {{ std_cast('"BOX_X_JAIL"', 'INTEGER') }}                              as BOX_X_JAIL,
        {{ std_cast('"UNITS_X_BOX"', 'INTEGER') }}                             as UNITS_X_BOX,
        {{ std_cast('"QUANTITY_TO_CREATE_ORDER"', 'NUMBER(38,5)') }}           as QUANTITY_TO_CREATE_ORDER,
        {{ std_cast('"TOLERANCE_GR"', 'NUMBER(38,5)') }}                       as TOLERANCE_GR,
        {{ std_cast('"TEMPERATURE"', 'INTEGER') }}                             as TEMPERATURE,
        {{ std_cast('"CREATE_ORDER_TO_VENDOR_NO_"', 'VARCHAR') }}              as CREATE_ORDER_TO_VENDOR_NO,
        {{ std_cast('"TOTAL_ENEGETIC_VALUE_KCAL"', 'NUMBER(38,5)') }}          as TOTAL_ENEGETIC_VALUE_KCAL,
        {{ std_cast('"TOTAL_FAT_G"', 'NUMBER(38,5)') }}                        as TOTAL_FAT_G,
        {{ std_cast('"OF_WITHCH_SATURADES_G"', 'NUMBER(38,5)') }}              as OF_WITHCH_SATURADES_G,
        {{ std_cast('"CARBOHYDRATES_G"', 'NUMBER(38,5)') }}                    as CARBOHYDRATES_G,
        {{ std_cast('"OF_WITH_SUGARS_G"', 'NUMBER(38,5)') }}                   as OF_WITH_SUGARS_G,
        {{ std_cast('"PROTEIN_G"', 'NUMBER(38,5)') }}                          as PROTEIN_G,
        {{ std_cast('"SALT_G"', 'NUMBER(38,5)') }}                             as SALT_G,
        {{ std_cast('"MOISTURE_FQ"', 'NUMBER(38,5)') }}                        as MOISTURE_FQ,
        {{ std_cast('"PROTEIN_FQ"', 'NUMBER(38,5)') }}                         as PROTEIN_FQ,
        {{ std_cast('"CARBOHYDRATES_FQ"', 'NUMBER(38,5)') }}                   as CARBOHYDRATES_FQ,
        {{ std_cast('"SUGARS_FQ"', 'NUMBER(38,5)') }}                          as SUGARS_FQ,
        {{ std_cast('"HYDROXYPROLINE_FQ"', 'NUMBER(38,5)') }}                  as HYDROXYPROLINE_FQ,
        {{ std_cast('"ASHES_FQ"', 'NUMBER(38,5)') }}                           as ASHES_FQ,
        {{ std_cast('"SALT_MG_FQ"', 'NUMBER(38,5)') }}                         as SALT_MG_FQ,
        {{ std_cast('"ALIMENTARY_FIBRE_FQ"', 'NUMBER(38,5)') }}                as ALIMENTARY_FIBRE_FQ,
        {{ std_cast('"FAT_FQ"', 'NUMBER(38,5)') }}                             as FAT_FQ,
        {{ std_cast('"FAT_SATURADES_FQ"', 'NUMBER(38,5)') }}                   as FAT_SATURADES_FQ,
        {{ std_cast('"TOTAL_ENEGETIC_KCAL_100G"', 'NUMBER(38,5)') }}           as TOTAL_ENEGETIC_KCAL_100G,
        {{ std_cast('"PROTEIN_KCAL_100G"', 'NUMBER(38,5)') }}                  as PROTEIN_KCAL_100G,
        {{ std_cast('"FAT_KCAL_100G"', 'NUMBER(38,5)') }}                      as FAT_KCAL_100G,
        {{ std_cast('"CARBOHYDRATES_KCAL_100G"', 'NUMBER(38,5)') }}            as CARBOHYDRATES_KCAL_100G,
        {{ std_cast('"TOTAL_ENEGETIC_KJUL_100G"', 'NUMBER(38,5)') }}           as TOTAL_ENEGETIC_KJUL_100G,
        {{ std_cast('"OBSERVACIONES_SALMORRA"', 'VARCHAR') }}                  as OBSERVACIONES_SALMORRA,
        {{ std_cast('"BRINE_LOT"', 'NUMBER(38,5)') }}                          as BRINE_LOT,
        {{ std_cast('"BRINE_NO_"', 'INTEGER') }}                               as BRINE_NO,
        {{ std_cast('"ALERGEN_CODE"', 'VARCHAR') }}                            as ALERGEN_CODE,
        {{ std_cast('"USE_INSTRUCTIONS_CODE"', 'VARCHAR') }}                   as USE_INSTRUCTIONS_CODE,
        {{ std_cast('"MICROBIOLOGICAL_CONDITIONS"', 'VARCHAR') }}              as MICROBIOLOGICAL_CONDITIONS,
        {{ std_cast('"MAINTENANCE"', 'INTEGER') }}                             as MAINTENANCE,
        {{ std_cast('"PLAN_NO_"', 'VARCHAR') }}                                as PLAN_NO,
        {{ std_cast('"RECLASSIF_CODE"', 'VARCHAR') }}                          as RECLASSIF_CODE,
        {{ std_cast('"REPROCESS_ROUTING_NO_"', 'VARCHAR') }}                   as REPROCESS_ROUTING_NO,
        {{ std_cast('"REPROCESS_BOM_NO_"', 'VARCHAR') }}                       as REPROCESS_BOM_NO,
        {{ std_cast('"NO_QUALITY_CONTROL"', 'INTEGER') }}                      as NO_QUALITY_CONTROL,
        {{ std_cast('"QUAL_ROUNDING_PRECISION"', 'NUMBER(38,5)') }}            as QUAL_ROUNDING_PRECISION,
        {{ std_cast('"MANUFACTURER_MANDATORY"', 'INTEGER') }}                  as MANUFACTURER_MANDATORY,
        {{ std_cast('"REACTIVE"', 'INTEGER') }}                                as REACTIVE,
        {{ std_cast('"NATURE"', 'INTEGER') }}                                  as NATURE,
        {{ std_cast('"CREATION_DATE"', 'TIMESTAMP_NTZ') }}                     as CREATION_DATE,
        {{ std_cast('"DESCRIPCION_AMPLIADA"', 'VARCHAR') }}                    as DESCRIPCION_AMPLIADA,
        {{ std_cast('"SUBSET_1"', 'VARCHAR') }}                                as SUBSET_1,
        {{ std_cast('"SUBSET_2"', 'VARCHAR') }}                                as SUBSET_2,
        {{ std_cast('"SUBSET_3"', 'VARCHAR') }}                                as SUBSET_3,
        {{ std_cast('"SUBSET_4"', 'VARCHAR') }}                                as SUBSET_4,
        {{ std_cast('"SUBSET_5"', 'VARCHAR') }}                                as SUBSET_5,
        {{ std_cast('"SUBSET_6"', 'VARCHAR') }}                                as SUBSET_6,
        {{ std_cast('"SUBSET_7"', 'VARCHAR') }}                                as SUBSET_7,
        {{ std_cast('"SUBSET_8"', 'VARCHAR') }}                                as SUBSET_8,
        {{ std_cast('"SUBSET_9"', 'VARCHAR') }}                                as SUBSET_9,
        {{ std_cast('"SUBSET_10"', 'VARCHAR') }}                               as SUBSET_10,
        {{ std_cast('"WIDTH"', 'NUMBER(38,5)') }}                              as WIDTH,
        {{ std_cast('"LENGTH"', 'NUMBER(38,5)') }}                             as LENGTH,
        {{ std_cast('"TALL"', 'NUMBER(38,5)') }}                               as TALL,
        {{ std_cast('"RM_FIELD_1"', 'NUMBER(38,5)') }}                         as RM_FIELD_1,
        {{ std_cast('"RM_FIELD_2"', 'NUMBER(38,5)') }}                         as RM_FIELD_2,
        {{ std_cast('"RM_FIELD_3"', 'NUMBER(38,5)') }}                         as RM_FIELD_3,
        {{ std_cast('"RM_FIELD_4"', 'NUMBER(38,5)') }}                         as RM_FIELD_4,
        {{ std_cast('"RM_FIELD_5"', 'NUMBER(38,5)') }}                         as RM_FIELD_5,
        {{ std_cast('"MANUF_FIELD_1"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_1,
        {{ std_cast('"MANUF_FIELD_2"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_2,
        {{ std_cast('"MANUF_FIELD_3"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_3,
        {{ std_cast('"MANUF_FIELD_4"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_4,
        {{ std_cast('"MANUF_FIELD_5"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_5,
        {{ std_cast('"MANUF_FIELD_6"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_6,
        {{ std_cast('"MANUF_FIELD_7"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_7,
        {{ std_cast('"MANUF_FIELD_8"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_8,
        {{ std_cast('"MANUF_FIELD_9"', 'NUMBER(38,5)') }}                      as MANUF_FIELD_9,
        {{ std_cast('"MANUF_FIELD_10"', 'NUMBER(38,5)') }}                     as MANUF_FIELD_10,
        {{ std_cast('"RM_FIELD_1_DISTR_"', 'NUMBER(38,5)') }}                  as RM_FIELD_1_DISTR,
        {{ std_cast('"RM_FIELD_2_DISTR_"', 'NUMBER(38,5)') }}                  as RM_FIELD_2_DISTR,
        {{ std_cast('"RM_FIELD_3_DISTR_"', 'NUMBER(38,5)') }}                  as RM_FIELD_3_DISTR,
        {{ std_cast('"RM_FIELD_4_DISTR_"', 'NUMBER(38,5)') }}                  as RM_FIELD_4_DISTR,
        {{ std_cast('"RM_FIELD_5_DISTR_"', 'NUMBER(38,5)') }}                  as RM_FIELD_5_DISTR,
        {{ std_cast('"MANUF_FIELD_1_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_1_DISTR,
        {{ std_cast('"MANUF_FIELD_2_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_2_DISTR,
        {{ std_cast('"MANUF_FIELD_3_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_3_DISTR,
        {{ std_cast('"MANUF_FIELD_4_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_4_DISTR,
        {{ std_cast('"MANUF_FIELD_5_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_5_DISTR,
        {{ std_cast('"MANUF_FIELD_6_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_6_DISTR,
        {{ std_cast('"MANUF_FIELD_7_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_7_DISTR,
        {{ std_cast('"MANUF_FIELD_8_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_8_DISTR,
        {{ std_cast('"MANUF_FIELD_9_DISTR_"', 'NUMBER(38,5)') }}               as MANUF_FIELD_9_DISTR,
        {{ std_cast('"MANUF_FIELD_10_DISTR_"', 'NUMBER(38,5)') }}              as MANUF_FIELD_10_DISTR,
        {{ std_cast('"WAREHOUSING_EXPENSES"', 'NUMBER(38,5)') }}               as WAREHOUSING_EXPENSES,
        {{ std_cast('"STRUCTURE_EXPENSES"', 'NUMBER(38,5)') }}                 as STRUCTURE_EXPENSES,
        {{ std_cast('"STRUCTURE_EXPENSES_DISTR_"', 'NUMBER(38,5)') }}          as STRUCTURE_EXPENSES_DISTR,
        {{ std_cast('"KUBIC_COST"', 'NUMBER(38,5)') }}                         as KUBIC_COST,
        {{ std_cast('"RM_WEEKLY_COST"', 'NUMBER(38,5)') }}                     as RM_WEEKLY_COST,
        {{ std_cast('"ROUTING_NO_"', 'VARCHAR') }}                             as ROUTING_NO,
        {{ std_cast('"PRODUCTION_BOM_NO_"', 'VARCHAR') }}                      as PRODUCTION_BOM_NO,
        {{ std_cast('"SINGLE_LEVEL_MATERIAL_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_MATERIAL_COST,
        {{ std_cast('"SINGLE_LEVEL_CAPACITY_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_CAPACITY_COST,
        {{ std_cast('"SINGLE_LEVEL_SUBCONTRD_COST"', 'NUMBER(38,5)') }}        as SINGLE_LEVEL_SUBCONTRD_COST,
        {{ std_cast('"SINGLE_LEVEL_CAP_OVHD_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_CAP_OVHD_COST,
        {{ std_cast('"SINGLE_LEVEL_MFG_OVHD_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_MFG_OVHD_COST,
        {{ std_cast('"OVERHEAD_RATE"', 'NUMBER(38,5)') }}                      as OVERHEAD_RATE,
        {{ std_cast('"ROLLED_UP_SUBCONTRACTED_COST"', 'NUMBER(38,5)') }}       as ROLLED_UP_SUBCONTRACTED_COST,
        {{ std_cast('"ROLLED_UP_MFG_OVHD_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_MFG_OVHD_COST,
        {{ std_cast('"ROLLED_UP_CAP_OVERHEAD_COST"', 'NUMBER(38,5)') }}        as ROLLED_UP_CAP_OVERHEAD_COST,
        {{ std_cast('"ORDER_TRACKING_POLICY"', 'INTEGER') }}                   as ORDER_TRACKING_POLICY,
        {{ std_cast('"CRITICAL"', 'INTEGER') }}                                as CRITICAL,
        {{ std_cast('"COMMON_ITEM_NO_"', 'VARCHAR') }}                         as COMMON_ITEM_NO,
        {{ std_cast('"CONSUMO_SEMANAL_PREVISTO"', 'NUMBER(38,5)') }}           as CONSUMO_SEMANAL_PREVISTO,
        {{ std_cast('"CADASTRAL_REFERENCE"', 'VARCHAR') }}                     as CADASTRAL_REFERENCE,
        {{ std_cast('"PROPERTY_SITUATION"', 'INTEGER') }}                      as PROPERTY_SITUATION,
        {{ std_cast('"CONSUMIR_AL_EXPEDIR"', 'INTEGER') }}                     as CONSUMIR_AL_EXPEDIR,
        {{ std_cast('"MCD_ITEM_NO_"', 'VARCHAR') }}                            as MCD_ITEM_NO,
        {{ std_cast('"OBSOLESCENDE_DATE"', 'TIMESTAMP_NTZ') }}                 as OBSOLESCENDE_DATE,
        {{ std_cast('"KUBIC_FIXED_PRICE"', 'NUMBER(38,5)') }}                  as KUBIC_FIXED_PRICE,
        {{ std_cast('"WITHOUT_CONSUMPTION"', 'INTEGER') }}                     as WITHOUT_CONSUMPTION,
        {{ std_cast('"LOCATION_BRINNE_PLANNING"', 'VARCHAR') }}                as LOCATION_BRINNE_PLANNING,
        {{ std_cast('"NOT_TO_INCLUDE_TRACK_MCD"', 'INTEGER') }}                as NOT_TO_INCLUDE_TRACK_MCD,
        {{ std_cast('"PRODUCTION_DATE"', 'TIMESTAMP_NTZ') }}                   as PRODUCTION_DATE,
        {{ std_cast('"EXPEDITION_DATE"', 'TIMESTAMP_NTZ') }}                   as EXPEDITION_DATE,
        {{ std_cast('"ECO"', 'INTEGER') }}                                     as ECO,
        {{ std_cast('"DIAMETER"', 'NUMBER(38,5)') }}                           as DIAMETER,
        {{ std_cast('"BASE_GR"', 'NUMBER(38,5)') }}                            as BASE_GR,
        {{ std_cast('"PACKING_TYPE"', 'INTEGER') }}                            as PACKING_TYPE,
        {{ std_cast('"TESDIR_PRODUCT_TYPE"', 'INTEGER') }}                     as TESDIR_PRODUCT_TYPE,
        {{ std_cast('"CONTROL_SACO_COMPLETO"', 'INTEGER') }}                   as CONTROL_SACO_COMPLETO,
        {{ std_cast('"MANUAL_COMSUMPTION"', 'INTEGER') }}                      as MANUAL_COMSUMPTION,
        {{ std_cast('"RESP_CENTRE"', 'VARCHAR') }}                             as RESP_CENTRE,
        {{ std_cast('"REPLENISHMENT_LOCATION_CODE"', 'VARCHAR') }}             as REPLENISHMENT_LOCATION_CODE,
        {{ std_cast('"GAMA_GC"', 'VARCHAR') }}                                 as GAMA_GC,
        {{ std_cast('"SUBGAMA_GC"', 'VARCHAR') }}                              as SUBGAMA_GC,
        {{ std_cast('"FAMILA_GC"', 'VARCHAR') }}                               as FAMILA_GC,
        {{ std_cast('"FORMATO_GC"', 'VARCHAR') }}                              as FORMATO_GC,
        {{ std_cast('"LOT_ANALYTICAL_MANDATORY"', 'INTEGER') }}                as LOT_ANALYTICAL_MANDATORY,
        {{ std_cast('"HYDRATION"', 'INTEGER') }}                               as HYDRATION,
        {{ std_cast('"KG_MP"', 'NUMBER(38,5)') }}                              as KG_MP,
        {{ std_cast('"DEPOSITO_SALMORRA"', 'NUMBER(38,5)') }}                  as DEPOSITO_SALMORRA,
        {{ std_cast('"PACKAGE_ITEM_NO_"', 'VARCHAR') }}                        as PACKAGE_ITEM_NO,
        {{ std_cast('"PERMITIR_CERRAR_OP_A_0"', 'INTEGER') }}                  as PERMITIR_CERRAR_OP_A_0,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        NULL                                                                   as BLOCK_REASON,
        NULL                                                                   as LAST_DATETIME_MODIFIED,
        NULL                                                                   as LAST_TIME_MODIFIED,
        NULL                                                                   as PICTURE,
        NULL                                                                   as LOWLEVEL_CODE,
        NULL                                                                   as ROLLEDUP_MATERIAL_COST,
        NULL                                                                   as ROLLEDUP_CAPACITY_COST,
        NULL                                                                   as WAREHOUSE_CLASS_CODE,
        NULL                                                                   as PUTAWAY_TEMPLATE_CODE,
        NULL                                                                   as PUTAWAY_UNIT_OF_MEASURE_CODE,
        NULL                                                                   as USE_CROSSDOCKING,
        NULL                                                                   as ID,
        NULL                                                                   as UNIT_OF_MEASURE_ID,
        NULL                                                                   as TAX_GROUP_ID,
        NULL                                                                   as SALES_BLOCKED,
        NULL                                                                   as PURCHASING_BLOCKED,
        NULL                                                                   as ITEM_CATEGORY_ID,
        NULL                                                                   as SINGLELEVEL_MATERIAL_COST,
        NULL                                                                   as SINGLELEVEL_CAPACITY_COST,
        NULL                                                                   as SINGLELEVEL_SUBCONTRD_COST,
        NULL                                                                   as SINGLELEVEL_CAP_OVHD_COST,
        NULL                                                                   as SINGLELEVEL_MFG_OVHD_COST,
        NULL                                                                   as ROLLEDUP_SUBCONTRACTED_COST,
        NULL                                                                   as ROLLEDUP_MFG_OVHD_COST,
        NULL                                                                   as ROLLEDUP_CAP_OVERHEAD_COST,
        NULL                                                                   as INVENTARIO,
        NULL                                                                   as INVENTARIO_VUM,
        NULL                                                                   as IF_RD_TYPE,
        NULL                                                                   as IF_FIXED_WEIGHT,
        NULL                                                                   as IF_MIN_TMP,
        NULL                                                                   as IF_MAX_TMP,
        NULL                                                                   as IF_ERR_WEIGHT,
        NULL                                                                   as IF_PRODUCT_UOM_CONTROL,
        NULL                                                                   as IF_CL_CODE_TYPE,
        NULL                                                                   as IF_CL_CODE_EAN14,
        NULL                                                                   as IF_TRAY_TARE,
        NULL                                                                   as IF_BOX_TARE,
        NULL                                                                   as IF_TRAYS_IN_BOX,
        NULL                                                                   as IF_BOXES_IN_PALLET,
        NULL                                                                   as IF_RET_DAYS,
        NULL                                                                   as IF_BOX_PACK,
        NULL                                                                   as IF_MIN_WEIGHT,
        NULL                                                                   as IF_MAX_WEIGHT,
        NULL                                                                   as IF_ERR_WEIGHT_DOWN,
        NULL                                                                   as RD_INTERNAL,
        NULL                                                                   as IF_GRASA_INFERIOR,
        NULL                                                                   as IF_GRASA_SUPERIOR,
        NULL                                                                   as IF_PD_ID,
        NULL                                                                   as IF_PD_TYPE,
        NULL                                                                   as AIT_DIAS_EN_TIENDA,
        NULL                                                                   as DIMENSIONESBOLSA,
        NULL                                                                   as AIT_OWNER,
        NULL                                                                   as EAN14BOX,
        NULL                                                                   as DL_MACHINECODE,
        NULL                                                                   as HAS_SALES_FORECAST,
        NULL                                                                   as DELAY_DAYS,
        NULL                                                                   as IDPVUM_VARIABLE_UNIT_MEASURE,
        NULL                                                                   as IDPVUM_PRICE_IN_VUM,
        NULL                                                                   as IDPVUM_COST_IN_VUM,
        NULL                                                                   as IDPVUM_AUTOMATIC_DECREASE,
        NULL                                                                   as IDPVUM_DECREASE_OF_DEVIATION,
        NULL                                                                   as IDPVUM_DECREASE_OF_ADJUST,
        NULL                                                                   as IDPVUM_DECREASE_OF_LIQUIDATION,
        NULL                                                                   as IDPVUM_MANUAL_DECREASE,
        NULL                                                                   as IDPVUM_UPD_SALES_DOC_QTY,
        NULL                                                                   as IDPVUM_SALES_ROUNDING_PREC,
        NULL                                                                   as IDPVUM_SALES_ROUNDING_TYPE,
        NULL                                                                   as IDPVUM_UPD_PCH_DOC_QTY,
        NULL                                                                   as IDPVUM_PURCH_ROUNDING_PREC,
        NULL                                                                   as IDPVUM_PURCH_ROUNDING_TYPE,
        NULL                                                                   as AIT_VENDOR_POSTING_GR,
        NULL                                                                   as AIT_CREATION_USER,
        NULL                                                                   as AIT_CREATION_DATETIME,
        NULL                                                                   as PRODUCT_GROUP,
        NULL                                                                   as PRODUCT_CLASS,
        NULL                                                                   as PRODUCT_COMPONENT,
        NULL                                                                   as ALERGENOS,
        NULL                                                                   as ES_CARNE,
        NULL                                                                   as CONGELADO,
        NULL                                                                   as CRITICO,
        NULL                                                                   as DEMORASOLO_CARGA,
        NULL                                                                   as DIAS_EN_TIENDA,
        NULL                                                                   as DET_LUNES,
        NULL                                                                   as DET_MARTES,
        NULL                                                                   as DET_MIERCOLES,
        NULL                                                                   as DET_JUEVES,
        NULL                                                                   as DET_VIERNES,
        NULL                                                                   as DET_SABADO,
        NULL                                                                   as DET_DOMINGO,
        NULL                                                                   as DIAS_VIDA_MAX_USO,
        NULL                                                                   as FECHA_SACRIFICIO,
        NULL                                                                   as GARGANES,
        NULL                                                                   as GERENTE_MDONA,
        NULL                                                                   as CAJA_LOGIFRUIT,
        NULL                                                                   as MARCA,
        NULL                                                                   as MODELO,
        NULL                                                                   as REFERENCIA,
        NULL                                                                   as REPARABILIDAD,
        NULL                                                                   as CERTIFSAE,
        NULL                                                                   as SIN_TRAZAB_VACUNO,
        NULL                                                                   as SIN_VALORACION_STOCK,
        NULL                                                                   as SUMINISTRADOR,
        NULL                                                                   as LOTES_VACUNO,
        NULL                                                                   as IGIC,
        NULL                                                                   as SUBSEMI,
        NULL                                                                   as FECHA_DESPIECE,
        NULL                                                                   as LOTE_10,
        NULL                                                                   as JAPON,
        NULL                                                                   as ENCOLADO_FECHA_PRODUCCION,
        NULL                                                                   as COMEDOR,
        NULL                                                                   as PACKINGLIST_CADUCIDAD,
        NULL                                                                   as FVENTA_ES_FCADUCIDAD,
        NULL                                                                   as HEURA,
        NULL                                                                   as ES_PACK,
        NULL                                                                   as HONGKONG,
        NULL                                                                   as SINGAPUR,
        NULL                                                                   as MUESTRAS,
        NULL                                                                   as COD_FABRICANTE,
        NULL                                                                   as PORPLA,
        NULL                                                                   as PEDIDO_KG_MDONA,
        NULL                                                                   as CANARIAS,
        NULL                                                                   as FRICAFOR,
        NULL                                                                   as CROQUETAS,
        NULL                                                                   as REFRIGERADO,
        NULL                                                                   as MANTENIMIENTO,
        NULL                                                                   as COD_RAPPEL_VENTAS,
        NULL                                                                   as COD_RAPPEL_COMPRAS,
        NULL                                                                   as NO_PRESENTACION,
        NULL                                                                   as CODIGO_EMBALAJE,
        NULL                                                                   as CONTROL_DIB,
        NULL                                                                   as PRECIO_PUNTO_VERDE_CDAD_DL,
        NULL                                                                   as UNIDAD_MEDIDA_PUNTO_VERDE,
        NULL                                                                   as GRUPO_RESIDUOS,
        NULL                                                                   as AUTOCOMPLETAR_EMBALAJE,
        NULL                                                                   as ANS_CADUCIDAD_RECEP,
        NULL                                                                   as ANS_CADUCIDAD_EXPED,
        NULL                                                                   as LIQUIDACION_POR_EMBALAJE,
        NULL                                                                   as PESO_FIJO,
        NULL                                                                   as LIQUIDACION_POR_PESADA,
        NULL                                                                   as NOMBRE_ABREVIADO,
        NULL                                                                   as CANT_ALTERNATIVA_OBLIGATORIA,
        NULL                                                                   as CODIGO_PLU,
        NULL                                                                   as REGISTRO_SANITARIO,
        NULL                                                                   as COD_EMBALAJE_COMPRA,
        NULL                                                                   as COD_PALET_DEFECTO,
        NULL                                                                   as TIPO_PALETIZACION,
        NULL                                                                   as PALET_POR_DEFECTO,
        NULL                                                                   as PESADA_POR_PRODUCTO_LOTE,
        NULL                                                                   as PRODUCTO_DE_VENTA,
        NULL                                                                   as PLAZO_CONSUMO_PREFERENTE,
        NULL                                                                   as FECHA_ALTA,
        NULL                                                                   as USUARIO_ALTA,
        NULL                                                                   as PESO_FIJO_EN_VENTA,
        NULL                                                                   as PRODUCTO_IBERICO,
        NULL                                                                   as STOCK_SEGURIDAD_PRODUCCION,
        NULL                                                                   as NATURALEZA_PRODUCTO,
        NULL                                                                   as TEMPERATURA_MINIMA,
        NULL                                                                   as TEMPERATURA_MAXIMA,
        NULL                                                                   as BLOQUEAR_AJUSTE_AUT_COSTE,
        NULL                                                                   as MERMA_TEORICA,
        NULL                                                                   as PLAZO_OP_FABRIC,
        NULL                                                                   as PRODUCTO_ORIGEN,
        NULL                                                                   as COSTES_POR_CANTIDAD,
        NULL                                                                   as UNIDADES_POR_CAJA,
        NULL                                                                   as CAJAS_POR_PALET,
        NULL                                                                   as PESO_MIN_UNIDAD,
        NULL                                                                   as PESO_MAX_UNIDAD,
        NULL                                                                   as TOLERANCIA,
        NULL                                                                   as PRESENCIA_OGM,
        NULL                                                                   as PAIS_PROCEDENCIA,
        NULL                                                                   as CERTIFICADO_NO_OGM,
        NULL                                                                   as TEXTO_ETIQUETA,
        NULL                                                                   as ORIGEN,
        NULL                                                                   as COD_PLANTILLA,
        NULL                                                                   as TIEMPO_REPOSO,
        NULL                                                                   as LOCATION_CODE,
        NULL                                                                   as PERMITIR_RECLASIFICACION_OC,
        NULL                                                                   as AVISO_CALIDAD,
        NULL                                                                   as EMB_ETIQUETA,
        NULL                                                                   as PRODUCTO_A_CURAR,
        NULL                                                                   as PALETIZACION_AUTOMATICA,
        NULL                                                                   as EDI_CODIGO_EAN,
        NULL                                                                   as PRECIO_MATADERO,
        NULL                                                                   as COD_ESPECIE,
        NULL                                                                   as CONTROL_POR,
        NULL                                                                   as NO_PLANTILLA_OT_MATADERO,
        NULL                                                                   as NO_PLANTILLA_OT_DESPIECE,
        NULL                                                                   as COD_GRUPO_INGREDIENTES,
        NULL                                                                   as CALCULO_FECHA_RETIRADA,
        NULL                                                                   as NO_PRODUCTO_KAIS,
        NULL                                                                   as CONTROLAR_PESO_MIN_MAX,
        NULL                                                                   as CONTROL_CADUCIDAD_EXPEDICION,
        NULL                                                                   as DESCRIPCION_INTERNA,
        NULL                                                                   as RECADV_DISABLED,
        'COO'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
