{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_ITEM') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"NO_2"', 'VARCHAR') }}                                    as NO_2,
        {{ std_cast('"DESCRIPTION"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"SEARCH_DESCRIPTION"', 'VARCHAR') }}                      as SEARCH_DESCRIPTION,
        {{ std_cast('"DESCRIPTION_2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"BASE_UNIT_OF_MEASURE"', 'VARCHAR') }}                    as BASE_UNIT_OF_MEASURE,
        {{ std_cast('"PRICE_UNIT_CONVERSION"', 'INTEGER') }}                   as PRICE_UNIT_CONVERSION,
        {{ std_cast('"TYPE"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"INVENTORY_POSTING_GROUP"', 'VARCHAR') }}                 as INVENTORY_POSTING_GROUP,
        {{ std_cast('"SHELF_NO_"', 'VARCHAR') }}                               as SHELF_NO,
        {{ std_cast('"ITEM_DISC_GROUP"', 'VARCHAR') }}                         as ITEM_DISC_GROUP,
        {{ std_cast('"ALLOW_INVOICE_DISC_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"STATISTICS_GROUP"', 'INTEGER') }}                        as STATISTICS_GROUP,
        {{ std_cast('"COMMISSION_GROUP"', 'INTEGER') }}                        as COMMISSION_GROUP,
        {{ std_cast('"UNIT_PRICE"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"PRICE_PROFIT_CALCULATION"', 'INTEGER') }}                as PRICE_PROFIT_CALCULATION,
        {{ std_cast('"PROFIT_"', 'NUMBER(38,5)') }}                            as PROFIT,
        {{ std_cast('"COSTING_METHOD"', 'INTEGER') }}                          as COSTING_METHOD,
        {{ std_cast('"UNIT_COST"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"STANDARD_COST"', 'NUMBER(38,5)') }}                      as STANDARD_COST,
        {{ std_cast('"LAST_DIRECT_COST"', 'NUMBER(38,5)') }}                   as LAST_DIRECT_COST,
        {{ std_cast('"INDIRECT_COST_"', 'NUMBER(38,5)') }}                     as INDIRECT_COST,
        {{ std_cast('"COST_IS_ADJUSTED"', 'INTEGER') }}                        as COST_IS_ADJUSTED,
        {{ std_cast('"ALLOW_ONLINE_ADJUSTMENT"', 'INTEGER') }}                 as ALLOW_ONLINE_ADJUSTMENT,
        {{ std_cast('"VENDOR_NO_"', 'VARCHAR') }}                              as VENDOR_NO,
        {{ std_cast('"VENDOR_ITEM_NO_"', 'VARCHAR') }}                         as VENDOR_ITEM_NO,
        {{ std_cast('"LEAD_TIME_CALCULATION"', 'VARCHAR') }}                   as LEAD_TIME_CALCULATION,
        {{ std_cast('"REORDER_POINT"', 'NUMBER(38,5)') }}                      as REORDER_POINT,
        {{ std_cast('"MAXIMUM_INVENTORY"', 'NUMBER(38,5)') }}                  as MAXIMUM_INVENTORY,
        {{ std_cast('"REORDER_QUANTITY"', 'NUMBER(38,5)') }}                   as REORDER_QUANTITY,
        {{ std_cast('"ALTERNATIVE_ITEM_NO_"', 'VARCHAR') }}                    as ALTERNATIVE_ITEM_NO,
        {{ std_cast('"UNIT_LIST_PRICE"', 'NUMBER(38,5)') }}                    as UNIT_LIST_PRICE,
        {{ std_cast('"DUTY_DUE_"', 'NUMBER(38,5)') }}                          as DUTY_DUE,
        {{ std_cast('"DUTY_CODE"', 'VARCHAR') }}                               as DUTY_CODE,
        {{ std_cast('"GROSS_WEIGHT"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"NET_WEIGHT"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"UNITS_PER_PARCEL"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"UNIT_VOLUME"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"DURABILITY"', 'VARCHAR') }}                              as DURABILITY,
        {{ std_cast('"FREIGHT_TYPE"', 'VARCHAR') }}                            as FREIGHT_TYPE,
        {{ std_cast('"TARIFF_NO_"', 'VARCHAR') }}                              as TARIFF_NO,
        {{ std_cast('"DUTY_UNIT_CONVERSION"', 'NUMBER(38,5)') }}               as DUTY_UNIT_CONVERSION,
        {{ std_cast('"COUNTRY_REGION_PURCHASED_CODE"', 'VARCHAR') }}           as COUNTRY_REGION_PURCHASED_CODE,
        {{ std_cast('"BUDGET_QUANTITY"', 'NUMBER(38,5)') }}                    as BUDGET_QUANTITY,
        {{ std_cast('"BUDGETED_AMOUNT"', 'NUMBER(38,5)') }}                    as BUDGETED_AMOUNT,
        {{ std_cast('"BUDGET_PROFIT"', 'NUMBER(38,5)') }}                      as BUDGET_PROFIT,
        {{ std_cast('"BLOCKED"', 'INTEGER') }}                                 as BLOCKED,
        {{ std_cast('"LAST_DATE_MODIFIED"', 'TIMESTAMP_NTZ') }}                as LAST_DATE_MODIFIED,
        {{ std_cast('"PRICE_INCLUDES_VAT"', 'INTEGER') }}                      as PRICE_INCLUDES_VAT,
        {{ std_cast('"VAT_BUS_POSTING_GR_PRICE"', 'VARCHAR') }}                as VAT_BUS_POSTING_GR_PRICE,
        {{ std_cast('"GEN_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"COUNTRY_REGION_OF_ORIGIN_CODE"', 'VARCHAR') }}           as COUNTRY_REGION_OF_ORIGIN_CODE,
        {{ std_cast('"AUTOMATIC_EXT_TEXTS"', 'INTEGER') }}                     as AUTOMATIC_EXT_TEXTS,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"TAX_GROUP_CODE"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"GLOBAL_DIMENSION_1_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_1_CODE,
        {{ std_cast('"GLOBAL_DIMENSION_2_CODE"', 'VARCHAR') }}                 as GLOBAL_DIMENSION_2_CODE,
        {{ std_cast('"STOCKOUT_WARNING"', 'INTEGER') }}                        as STOCKOUT_WARNING,
        {{ std_cast('"PREVENT_NEGATIVE_INVENTORY"', 'INTEGER') }}              as PREVENT_NEGATIVE_INVENTORY,
        {{ std_cast('"APPLICATION_WKSH_USER_ID"', 'VARCHAR') }}                as APPLICATION_WKSH_USER_ID,
        {{ std_cast('"ASSEMBLY_POLICY"', 'INTEGER') }}                         as ASSEMBLY_POLICY,
        {{ std_cast('"GTIN"', 'VARCHAR') }}                                    as GTIN,
        {{ std_cast('"DEFAULT_DEFERRAL_TEMPLATE_CODE"', 'VARCHAR') }}          as DEFAULT_DEFERRAL_TEMPLATE_CODE,
        {{ std_cast('"LOW_LEVEL_CODE"', 'INTEGER') }}                          as LOW_LEVEL_CODE,
        {{ std_cast('"LOT_SIZE"', 'NUMBER(38,5)') }}                           as LOT_SIZE,
        {{ std_cast('"SERIAL_NOS_"', 'VARCHAR') }}                             as SERIAL_NOS,
        {{ std_cast('"LAST_UNIT_COST_CALC_DATE"', 'TIMESTAMP_NTZ') }}          as LAST_UNIT_COST_CALC_DATE,
        {{ std_cast('"ROLLED_UP_MATERIAL_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_MATERIAL_COST,
        {{ std_cast('"ROLLED_UP_CAPACITY_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_CAPACITY_COST,
        {{ std_cast('"SCRAP_"', 'NUMBER(38,5)') }}                             as SCRAP,
        {{ std_cast('"INVENTORY_VALUE_ZERO"', 'INTEGER') }}                    as INVENTORY_VALUE_ZERO,
        {{ std_cast('"DISCRETE_ORDER_QUANTITY"', 'INTEGER') }}                 as DISCRETE_ORDER_QUANTITY,
        {{ std_cast('"MINIMUM_ORDER_QUANTITY"', 'NUMBER(38,5)') }}             as MINIMUM_ORDER_QUANTITY,
        {{ std_cast('"MAXIMUM_ORDER_QUANTITY"', 'NUMBER(38,5)') }}             as MAXIMUM_ORDER_QUANTITY,
        {{ std_cast('"SAFETY_STOCK_QUANTITY"', 'NUMBER(38,5)') }}              as SAFETY_STOCK_QUANTITY,
        {{ std_cast('"ORDER_MULTIPLE"', 'NUMBER(38,5)') }}                     as ORDER_MULTIPLE,
        {{ std_cast('"SAFETY_LEAD_TIME"', 'VARCHAR') }}                        as SAFETY_LEAD_TIME,
        {{ std_cast('"FLUSHING_METHOD"', 'INTEGER') }}                         as FLUSHING_METHOD,
        {{ std_cast('"REPLENISHMENT_SYSTEM"', 'INTEGER') }}                    as REPLENISHMENT_SYSTEM,
        {{ std_cast('"ROUNDING_PRECISION"', 'NUMBER(38,5)') }}                 as ROUNDING_PRECISION,
        {{ std_cast('"SALES_UNIT_OF_MEASURE"', 'VARCHAR') }}                   as SALES_UNIT_OF_MEASURE,
        {{ std_cast('"PURCH_UNIT_OF_MEASURE"', 'VARCHAR') }}                   as PURCH_UNIT_OF_MEASURE,
        {{ std_cast('"TIME_BUCKET"', 'VARCHAR') }}                             as TIME_BUCKET,
        {{ std_cast('"REORDERING_POLICY"', 'INTEGER') }}                       as REORDERING_POLICY,
        {{ std_cast('"INCLUDE_INVENTORY"', 'INTEGER') }}                       as INCLUDE_INVENTORY,
        {{ std_cast('"MANUFACTURING_POLICY"', 'INTEGER') }}                    as MANUFACTURING_POLICY,
        {{ std_cast('"RESCHEDULING_PERIOD"', 'VARCHAR') }}                     as RESCHEDULING_PERIOD,
        {{ std_cast('"LOT_ACCUMULATION_PERIOD"', 'VARCHAR') }}                 as LOT_ACCUMULATION_PERIOD,
        {{ std_cast('"DAMPENER_PERIOD"', 'VARCHAR') }}                         as DAMPENER_PERIOD,
        {{ std_cast('"DAMPENER_QUANTITY"', 'NUMBER(38,5)') }}                  as DAMPENER_QUANTITY,
        {{ std_cast('"OVERFLOW_LEVEL"', 'NUMBER(38,5)') }}                     as OVERFLOW_LEVEL,
        {{ std_cast('"MANUFACTURER_CODE"', 'VARCHAR') }}                       as MANUFACTURER_CODE,
        {{ std_cast('"ITEM_CATEGORY_CODE"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"CREATED_FROM_NONSTOCK_ITEM"', 'INTEGER') }}              as CREATED_FROM_NONSTOCK_ITEM,
        {{ std_cast('"PRODUCT_GROUP_CODE"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"SERVICE_ITEM_GROUP"', 'VARCHAR') }}                      as SERVICE_ITEM_GROUP,
        {{ std_cast('"ITEM_TRACKING_CODE"', 'VARCHAR') }}                      as ITEM_TRACKING_CODE,
        {{ std_cast('"LOT_NOS_"', 'VARCHAR') }}                                as LOT_NOS,
        {{ std_cast('"EXPIRATION_CALCULATION"', 'VARCHAR') }}                  as EXPIRATION_CALCULATION,
        {{ std_cast('"SPECIAL_EQUIPMENT_CODE"', 'VARCHAR') }}                  as SPECIAL_EQUIPMENT_CODE,
        {{ std_cast('"PUT_AWAY_TEMPLATE_CODE"', 'VARCHAR') }}                  as PUT_AWAY_TEMPLATE_CODE,
        {{ std_cast('"PUT_AWAY_UNIT_OF_MEASURE_CODE"', 'VARCHAR') }}           as PUT_AWAY_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"PHYS_INVT_COUNTING_PERIOD_CODE"', 'VARCHAR') }}          as PHYS_INVT_COUNTING_PERIOD_CODE,
        {{ std_cast('"LAST_COUNTING_PERIOD_UPDATE"', 'TIMESTAMP_NTZ') }}       as LAST_COUNTING_PERIOD_UPDATE,
        {{ std_cast('"USE_CROSS_DOCKING"', 'INTEGER') }}                       as USE_CROSS_DOCKING,
        {{ std_cast('"NEXT_COUNTING_START_DATE"', 'TIMESTAMP_NTZ') }}          as NEXT_COUNTING_START_DATE,
        {{ std_cast('"NEXT_COUNTING_END_DATE"', 'TIMESTAMP_NTZ') }}            as NEXT_COUNTING_END_DATE,
        {{ std_cast('"COST_REGULATION_"', 'NUMBER(38,5)') }}                   as COST_REGULATION,
        {{ std_cast('"COMMENTS_TO_PURCH_ORDER"', 'VARCHAR') }}                 as COMMENTS_TO_PURCH_ORDER,
        NULL                                                                   as ITEM_AREA,
        NULL                                                                   as TRADERMARK_CODE,
        NULL                                                                   as MOLD,
        NULL                                                                   as FIXED_WEIGHT,
        NULL                                                                   as ANIMAL,
        NULL                                                                   as STORAGE_CONDITIONS,
        NULL                                                                   as MIN_EXPIRY_ON_RECEPCION,
        NULL                                                                   as MIN_EXPIRY_ON_MANUFACTURING,
        NULL                                                                   as INJECTION,
        NULL                                                                   as WATER_LITERS,
        NULL                                                                   as SALT_CODE,
        NULL                                                                   as PRODUCT_IF,
        NULL                                                                   as ADITIVE_CODE,
        NULL                                                                   as RM_CODE,
        NULL                                                                   as COMMERCIAL_DESCRIPTION,
        NULL                                                                   as TARIFF_NO_CANARY_ISLAND,
        NULL                                                                   as MAQUILA,
        NULL                                                                   as KG_RM_TN,
        NULL                                                                   as KG_BRINE_TN,
        NULL                                                                   as COOP_PRODUCT_TYPE,
        NULL                                                                   as PACKAGING_TYPE,
        NULL                                                                   as BOX_X_JAIL,
        NULL                                                                   as UNITS_X_BOX,
        {{ std_cast('"QUANTITY_TO_CREATE_ORDER"', 'NUMBER(38,5)') }}           as QUANTITY_TO_CREATE_ORDER,
        NULL                                                                   as TOLERANCE_GR,
        NULL                                                                   as TEMPERATURE,
        {{ std_cast('"CREATE_ORDER_TO_VENDOR_NO_"', 'VARCHAR') }}              as CREATE_ORDER_TO_VENDOR_NO,
        NULL                                                                   as TOTAL_ENEGETIC_VALUE_KCAL,
        NULL                                                                   as TOTAL_FAT_G,
        NULL                                                                   as OF_WITHCH_SATURADES_G,
        NULL                                                                   as CARBOHYDRATES_G,
        NULL                                                                   as OF_WITH_SUGARS_G,
        NULL                                                                   as PROTEIN_G,
        NULL                                                                   as SALT_G,
        NULL                                                                   as MOISTURE_FQ,
        NULL                                                                   as PROTEIN_FQ,
        NULL                                                                   as CARBOHYDRATES_FQ,
        NULL                                                                   as SUGARS_FQ,
        NULL                                                                   as HYDROXYPROLINE_FQ,
        NULL                                                                   as ASHES_FQ,
        NULL                                                                   as SALT_MG_FQ,
        NULL                                                                   as ALIMENTARY_FIBRE_FQ,
        NULL                                                                   as FAT_FQ,
        NULL                                                                   as FAT_SATURADES_FQ,
        NULL                                                                   as TOTAL_ENEGETIC_KCAL_100G,
        NULL                                                                   as PROTEIN_KCAL_100G,
        NULL                                                                   as FAT_KCAL_100G,
        NULL                                                                   as CARBOHYDRATES_KCAL_100G,
        NULL                                                                   as TOTAL_ENEGETIC_KJUL_100G,
        NULL                                                                   as OBSERVACIONES_SALMORRA,
        NULL                                                                   as BRINE_LOT,
        NULL                                                                   as BRINE_NO,
        NULL                                                                   as ALERGEN_CODE,
        NULL                                                                   as USE_INSTRUCTIONS_CODE,
        NULL                                                                   as MICROBIOLOGICAL_CONDITIONS,
        NULL                                                                   as MAINTENANCE,
        NULL                                                                   as PLAN_NO,
        NULL                                                                   as RECLASSIF_CODE,
        NULL                                                                   as REPROCESS_ROUTING_NO,
        NULL                                                                   as REPROCESS_BOM_NO,
        NULL                                                                   as NO_QUALITY_CONTROL,
        NULL                                                                   as QUAL_ROUNDING_PRECISION,
        NULL                                                                   as MANUFACTURER_MANDATORY,
        NULL                                                                   as REACTIVE,
        NULL                                                                   as NATURE,
        NULL                                                                   as CREATION_DATE,
        NULL                                                                   as DESCRIPCION_AMPLIADA,
        {{ std_cast('"SUBSET_1"', 'VARCHAR') }}                                as SUBSET_1,
        {{ std_cast('"SUBSET_2"', 'VARCHAR') }}                                as SUBSET_2,
        {{ std_cast('"SUBSET_3"', 'VARCHAR') }}                                as SUBSET_3,
        {{ std_cast('"SUBSET_4"', 'VARCHAR') }}                                as SUBSET_4,
        {{ std_cast('"SUBSET_5"', 'VARCHAR') }}                                as SUBSET_5,
        {{ std_cast('"SUBSET_6"', 'VARCHAR') }}                                as SUBSET_6,
        {{ std_cast('"SUBSET_7"', 'VARCHAR') }}                                as SUBSET_7,
        {{ std_cast('"SUBSET_8"', 'VARCHAR') }}                                as SUBSET_8,
        {{ std_cast('"SUBSET_9"', 'VARCHAR') }}                                as SUBSET_9,
        {{ std_cast('"SUBSET_10"', 'VARCHAR') }}                               as SUBSET_10,
        NULL                                                                   as WIDTH,
        NULL                                                                   as LENGTH,
        NULL                                                                   as TALL,
        NULL                                                                   as RM_FIELD_1,
        NULL                                                                   as RM_FIELD_2,
        NULL                                                                   as RM_FIELD_3,
        NULL                                                                   as RM_FIELD_4,
        NULL                                                                   as RM_FIELD_5,
        NULL                                                                   as MANUF_FIELD_1,
        NULL                                                                   as MANUF_FIELD_2,
        NULL                                                                   as MANUF_FIELD_3,
        NULL                                                                   as MANUF_FIELD_4,
        NULL                                                                   as MANUF_FIELD_5,
        NULL                                                                   as MANUF_FIELD_6,
        NULL                                                                   as MANUF_FIELD_7,
        NULL                                                                   as MANUF_FIELD_8,
        NULL                                                                   as MANUF_FIELD_9,
        NULL                                                                   as MANUF_FIELD_10,
        NULL                                                                   as RM_FIELD_1_DISTR,
        NULL                                                                   as RM_FIELD_2_DISTR,
        NULL                                                                   as RM_FIELD_3_DISTR,
        NULL                                                                   as RM_FIELD_4_DISTR,
        NULL                                                                   as RM_FIELD_5_DISTR,
        NULL                                                                   as MANUF_FIELD_1_DISTR,
        NULL                                                                   as MANUF_FIELD_2_DISTR,
        NULL                                                                   as MANUF_FIELD_3_DISTR,
        NULL                                                                   as MANUF_FIELD_4_DISTR,
        NULL                                                                   as MANUF_FIELD_5_DISTR,
        NULL                                                                   as MANUF_FIELD_6_DISTR,
        NULL                                                                   as MANUF_FIELD_7_DISTR,
        NULL                                                                   as MANUF_FIELD_8_DISTR,
        NULL                                                                   as MANUF_FIELD_9_DISTR,
        NULL                                                                   as MANUF_FIELD_10_DISTR,
        NULL                                                                   as WAREHOUSING_EXPENSES,
        NULL                                                                   as STRUCTURE_EXPENSES,
        NULL                                                                   as STRUCTURE_EXPENSES_DISTR,
        NULL                                                                   as KUBIC_COST,
        NULL                                                                   as RM_WEEKLY_COST,
        {{ std_cast('"ROUTING_NO_"', 'VARCHAR') }}                             as ROUTING_NO,
        {{ std_cast('"PRODUCTION_BOM_NO_"', 'VARCHAR') }}                      as PRODUCTION_BOM_NO,
        {{ std_cast('"SINGLE_LEVEL_MATERIAL_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_MATERIAL_COST,
        {{ std_cast('"SINGLE_LEVEL_CAPACITY_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_CAPACITY_COST,
        {{ std_cast('"SINGLE_LEVEL_SUBCONTRD_COST"', 'NUMBER(38,5)') }}        as SINGLE_LEVEL_SUBCONTRD_COST,
        {{ std_cast('"SINGLE_LEVEL_CAP_OVHD_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_CAP_OVHD_COST,
        {{ std_cast('"SINGLE_LEVEL_MFG_OVHD_COST"', 'NUMBER(38,5)') }}         as SINGLE_LEVEL_MFG_OVHD_COST,
        {{ std_cast('"OVERHEAD_RATE"', 'NUMBER(38,5)') }}                      as OVERHEAD_RATE,
        {{ std_cast('"ROLLED_UP_SUBCONTRACTED_COST"', 'NUMBER(38,5)') }}       as ROLLED_UP_SUBCONTRACTED_COST,
        {{ std_cast('"ROLLED_UP_MFG_OVHD_COST"', 'NUMBER(38,5)') }}            as ROLLED_UP_MFG_OVHD_COST,
        {{ std_cast('"ROLLED_UP_CAP_OVERHEAD_COST"', 'NUMBER(38,5)') }}        as ROLLED_UP_CAP_OVERHEAD_COST,
        {{ std_cast('"ORDER_TRACKING_POLICY"', 'INTEGER') }}                   as ORDER_TRACKING_POLICY,
        {{ std_cast('"CRITICAL"', 'INTEGER') }}                                as CRITICAL,
        {{ std_cast('"COMMON_ITEM_NO_"', 'VARCHAR') }}                         as COMMON_ITEM_NO,
        {{ std_cast('"CONSUMO_SEMANAL_PREVISTO"', 'NUMBER(38,5)') }}           as CONSUMO_SEMANAL_PREVISTO,
        NULL                                                                   as CADASTRAL_REFERENCE,
        NULL                                                                   as PROPERTY_SITUATION,
        NULL                                                                   as CONSUMIR_AL_EXPEDIR,
        NULL                                                                   as MCD_ITEM_NO,
        NULL                                                                   as OBSOLESCENDE_DATE,
        NULL                                                                   as KUBIC_FIXED_PRICE,
        NULL                                                                   as WITHOUT_CONSUMPTION,
        NULL                                                                   as LOCATION_BRINNE_PLANNING,
        NULL                                                                   as NOT_TO_INCLUDE_TRACK_MCD,
        NULL                                                                   as PRODUCTION_DATE,
        NULL                                                                   as EXPEDITION_DATE,
        NULL                                                                   as ECO,
        NULL                                                                   as DIAMETER,
        NULL                                                                   as BASE_GR,
        NULL                                                                   as PACKING_TYPE,
        NULL                                                                   as TESDIR_PRODUCT_TYPE,
        NULL                                                                   as CONTROL_SACO_COMPLETO,
        NULL                                                                   as MANUAL_COMSUMPTION,
        NULL                                                                   as RESP_CENTRE,
        NULL                                                                   as REPLENISHMENT_LOCATION_CODE,
        NULL                                                                   as GAMA_GC,
        NULL                                                                   as SUBGAMA_GC,
        NULL                                                                   as FAMILA_GC,
        NULL                                                                   as FORMATO_GC,
        NULL                                                                   as LOT_ANALYTICAL_MANDATORY,
        NULL                                                                   as HYDRATION,
        NULL                                                                   as KG_MP,
        NULL                                                                   as DEPOSITO_SALMORRA,
        NULL                                                                   as PACKAGE_ITEM_NO,
        NULL                                                                   as PERMITIR_CERRAR_OP_A_0,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        NULL                                                                   as BLOCK_REASON,
        NULL                                                                   as LAST_DATETIME_MODIFIED,
        {{ std_cast('"LAST_TIME_MODIFIED"', 'TIMESTAMP_NTZ') }}                as LAST_TIME_MODIFIED,
        NULL                                                                   as PICTURE,
        NULL                                                                   as LOWLEVEL_CODE,
        NULL                                                                   as ROLLEDUP_MATERIAL_COST,
        NULL                                                                   as ROLLEDUP_CAPACITY_COST,
        {{ std_cast('"WAREHOUSE_CLASS_CODE"', 'VARCHAR') }}                    as WAREHOUSE_CLASS_CODE,
        NULL                                                                   as PUTAWAY_TEMPLATE_CODE,
        NULL                                                                   as PUTAWAY_UNIT_OF_MEASURE_CODE,
        NULL                                                                   as USE_CROSSDOCKING,
        NULL                                                                   as ID,
        NULL                                                                   as UNIT_OF_MEASURE_ID,
        NULL                                                                   as TAX_GROUP_ID,
        NULL                                                                   as SALES_BLOCKED,
        NULL                                                                   as PURCHASING_BLOCKED,
        NULL                                                                   as ITEM_CATEGORY_ID,
        NULL                                                                   as SINGLELEVEL_MATERIAL_COST,
        NULL                                                                   as SINGLELEVEL_CAPACITY_COST,
        NULL                                                                   as SINGLELEVEL_SUBCONTRD_COST,
        NULL                                                                   as SINGLELEVEL_CAP_OVHD_COST,
        NULL                                                                   as SINGLELEVEL_MFG_OVHD_COST,
        NULL                                                                   as ROLLEDUP_SUBCONTRACTED_COST,
        NULL                                                                   as ROLLEDUP_MFG_OVHD_COST,
        NULL                                                                   as ROLLEDUP_CAP_OVERHEAD_COST,
        NULL                                                                   as INVENTARIO,
        NULL                                                                   as INVENTARIO_VUM,
        NULL                                                                   as IF_RD_TYPE,
        NULL                                                                   as IF_FIXED_WEIGHT,
        NULL                                                                   as IF_MIN_TMP,
        NULL                                                                   as IF_MAX_TMP,
        NULL                                                                   as IF_ERR_WEIGHT,
        NULL                                                                   as IF_PRODUCT_UOM_CONTROL,
        NULL                                                                   as IF_CL_CODE_TYPE,
        NULL                                                                   as IF_CL_CODE_EAN14,
        NULL                                                                   as IF_TRAY_TARE,
        NULL                                                                   as IF_BOX_TARE,
        NULL                                                                   as IF_TRAYS_IN_BOX,
        NULL                                                                   as IF_BOXES_IN_PALLET,
        NULL                                                                   as IF_RET_DAYS,
        NULL                                                                   as IF_BOX_PACK,
        NULL                                                                   as IF_MIN_WEIGHT,
        NULL                                                                   as IF_MAX_WEIGHT,
        NULL                                                                   as IF_ERR_WEIGHT_DOWN,
        NULL                                                                   as RD_INTERNAL,
        NULL                                                                   as IF_GRASA_INFERIOR,
        NULL                                                                   as IF_GRASA_SUPERIOR,
        NULL                                                                   as IF_PD_ID,
        NULL                                                                   as IF_PD_TYPE,
        NULL                                                                   as AIT_DIAS_EN_TIENDA,
        NULL                                                                   as DIMENSIONESBOLSA,
        NULL                                                                   as AIT_OWNER,
        NULL                                                                   as EAN14BOX,
        NULL                                                                   as DL_MACHINECODE,
        NULL                                                                   as HAS_SALES_FORECAST,
        NULL                                                                   as DELAY_DAYS,
        NULL                                                                   as IDPVUM_VARIABLE_UNIT_MEASURE,
        NULL                                                                   as IDPVUM_PRICE_IN_VUM,
        NULL                                                                   as IDPVUM_COST_IN_VUM,
        NULL                                                                   as IDPVUM_AUTOMATIC_DECREASE,
        NULL                                                                   as IDPVUM_DECREASE_OF_DEVIATION,
        NULL                                                                   as IDPVUM_DECREASE_OF_ADJUST,
        NULL                                                                   as IDPVUM_DECREASE_OF_LIQUIDATION,
        NULL                                                                   as IDPVUM_MANUAL_DECREASE,
        NULL                                                                   as IDPVUM_UPD_SALES_DOC_QTY,
        NULL                                                                   as IDPVUM_SALES_ROUNDING_PREC,
        NULL                                                                   as IDPVUM_SALES_ROUNDING_TYPE,
        NULL                                                                   as IDPVUM_UPD_PCH_DOC_QTY,
        NULL                                                                   as IDPVUM_PURCH_ROUNDING_PREC,
        NULL                                                                   as IDPVUM_PURCH_ROUNDING_TYPE,
        NULL                                                                   as AIT_VENDOR_POSTING_GR,
        NULL                                                                   as AIT_CREATION_USER,
        NULL                                                                   as AIT_CREATION_DATETIME,
        NULL                                                                   as PRODUCT_GROUP,
        NULL                                                                   as PRODUCT_CLASS,
        NULL                                                                   as PRODUCT_COMPONENT,
        NULL                                                                   as ALERGENOS,
        NULL                                                                   as ES_CARNE,
        NULL                                                                   as CONGELADO,
        NULL                                                                   as CRITICO,
        NULL                                                                   as DEMORASOLO_CARGA,
        NULL                                                                   as DIAS_EN_TIENDA,
        NULL                                                                   as DET_LUNES,
        NULL                                                                   as DET_MARTES,
        NULL                                                                   as DET_MIERCOLES,
        NULL                                                                   as DET_JUEVES,
        NULL                                                                   as DET_VIERNES,
        NULL                                                                   as DET_SABADO,
        NULL                                                                   as DET_DOMINGO,
        NULL                                                                   as DIAS_VIDA_MAX_USO,
        NULL                                                                   as FECHA_SACRIFICIO,
        NULL                                                                   as GARGANES,
        NULL                                                                   as GERENTE_MDONA,
        NULL                                                                   as CAJA_LOGIFRUIT,
        {{ std_cast('"MARCA"', 'VARCHAR') }}                                   as MARCA,
        NULL                                                                   as MODELO,
        NULL                                                                   as REFERENCIA,
        NULL                                                                   as REPARABILIDAD,
        NULL                                                                   as CERTIFSAE,
        NULL                                                                   as SIN_TRAZAB_VACUNO,
        NULL                                                                   as SIN_VALORACION_STOCK,
        NULL                                                                   as SUMINISTRADOR,
        NULL                                                                   as LOTES_VACUNO,
        NULL                                                                   as IGIC,
        NULL                                                                   as SUBSEMI,
        NULL                                                                   as FECHA_DESPIECE,
        NULL                                                                   as LOTE_10,
        NULL                                                                   as JAPON,
        NULL                                                                   as ENCOLADO_FECHA_PRODUCCION,
        NULL                                                                   as COMEDOR,
        NULL                                                                   as PACKINGLIST_CADUCIDAD,
        NULL                                                                   as FVENTA_ES_FCADUCIDAD,
        NULL                                                                   as HEURA,
        NULL                                                                   as ES_PACK,
        NULL                                                                   as HONGKONG,
        NULL                                                                   as SINGAPUR,
        NULL                                                                   as MUESTRAS,
        NULL                                                                   as COD_FABRICANTE,
        NULL                                                                   as PORPLA,
        NULL                                                                   as PEDIDO_KG_MDONA,
        NULL                                                                   as CANARIAS,
        NULL                                                                   as FRICAFOR,
        NULL                                                                   as CROQUETAS,
        NULL                                                                   as REFRIGERADO,
        {{ std_cast('"MANTENIMIENTO"', 'INTEGER') }}                           as MANTENIMIENTO,
        {{ std_cast('"COD_RAPPEL_VENTAS"', 'VARCHAR') }}                       as COD_RAPPEL_VENTAS,
        {{ std_cast('"COD_RAPPEL_COMPRAS"', 'VARCHAR') }}                      as COD_RAPPEL_COMPRAS,
        {{ std_cast('"NO_PRESENTACION"', 'VARCHAR') }}                         as NO_PRESENTACION,
        {{ std_cast('"CODIGO_EMBALAJE"', 'VARCHAR') }}                         as CODIGO_EMBALAJE,
        {{ std_cast('"CONTROL_DIB"', 'INTEGER') }}                             as CONTROL_DIB,
        {{ std_cast('"PRECIO_PUNTO_VERDE_CDAD_DL"', 'NUMBER(38,5)') }}         as PRECIO_PUNTO_VERDE_CDAD_DL,
        {{ std_cast('"UNIDAD_MEDIDA_PUNTO_VERDE"', 'VARCHAR') }}               as UNIDAD_MEDIDA_PUNTO_VERDE,
        {{ std_cast('"GRUPO_RESIDUOS"', 'VARCHAR') }}                          as GRUPO_RESIDUOS,
        {{ std_cast('"AUTOCOMPLETAR_EMBALAJE"', 'INTEGER') }}                  as AUTOCOMPLETAR_EMBALAJE,
        {{ std_cast('"ANS_CADUCIDAD_RECEP_"', 'VARCHAR') }}                    as ANS_CADUCIDAD_RECEP,
        {{ std_cast('"ANS_CADUCIDAD_EXPED_"', 'VARCHAR') }}                    as ANS_CADUCIDAD_EXPED,
        {{ std_cast('"LIQUIDACION_POR_EMBALAJE"', 'INTEGER') }}                as LIQUIDACION_POR_EMBALAJE,
        {{ std_cast('"PESO_FIJO"', 'INTEGER') }}                               as PESO_FIJO,
        {{ std_cast('"LIQUIDACION_POR_PESADA"', 'INTEGER') }}                  as LIQUIDACION_POR_PESADA,
        {{ std_cast('"NOMBRE_ABREVIADO"', 'VARCHAR') }}                        as NOMBRE_ABREVIADO,
        {{ std_cast('"CANT_ALTERNATIVA_OBLIGATORIA"', 'INTEGER') }}            as CANT_ALTERNATIVA_OBLIGATORIA,
        {{ std_cast('"CODIGO_PLU"', 'VARCHAR') }}                              as CODIGO_PLU,
        {{ std_cast('"REGISTRO_SANITARIO"', 'VARCHAR') }}                      as REGISTRO_SANITARIO,
        {{ std_cast('"COD_EMBALAJE_COMPRA"', 'VARCHAR') }}                     as COD_EMBALAJE_COMPRA,
        {{ std_cast('"COD_PALET_DEFECTO"', 'VARCHAR') }}                       as COD_PALET_DEFECTO,
        {{ std_cast('"TIPO_PALETIZACION"', 'INTEGER') }}                       as TIPO_PALETIZACION,
        {{ std_cast('"PALET_POR_DEFECTO"', 'VARCHAR') }}                       as PALET_POR_DEFECTO,
        {{ std_cast('"PESADA_POR_PRODUCTO_LOTE"', 'INTEGER') }}                as PESADA_POR_PRODUCTO_LOTE,
        {{ std_cast('"PRODUCTO_DE_VENTA"', 'INTEGER') }}                       as PRODUCTO_DE_VENTA,
        {{ std_cast('"PLAZO_CONSUMO_PREFERENTE"', 'VARCHAR') }}                as PLAZO_CONSUMO_PREFERENTE,
        {{ std_cast('"FECHA_ALTA"', 'TIMESTAMP_NTZ') }}                        as FECHA_ALTA,
        {{ std_cast('"USUARIO_ALTA"', 'VARCHAR') }}                            as USUARIO_ALTA,
        {{ std_cast('"PESO_FIJO_EN_VENTA"', 'INTEGER') }}                      as PESO_FIJO_EN_VENTA,
        {{ std_cast('"PRODUCTO_IBERICO"', 'INTEGER') }}                        as PRODUCTO_IBERICO,
        {{ std_cast('"STOCK_SEGURIDAD_PRODUCCION"', 'NUMBER(38,5)') }}         as STOCK_SEGURIDAD_PRODUCCION,
        {{ std_cast('"NATURALEZA_PRODUCTO"', 'VARCHAR') }}                     as NATURALEZA_PRODUCTO,
        {{ std_cast('"TEMPERATURA_MINIMA"', 'NUMBER(38,5)') }}                 as TEMPERATURA_MINIMA,
        {{ std_cast('"TEMPERATURA_MAXIMA"', 'NUMBER(38,5)') }}                 as TEMPERATURA_MAXIMA,
        {{ std_cast('"BLOQUEAR_AJUSTE_AUT_COSTE"', 'INTEGER') }}               as BLOQUEAR_AJUSTE_AUT_COSTE,
        {{ std_cast('"_MERMA_TEORICA"', 'NUMBER(38,5)') }}                     as MERMA_TEORICA,
        {{ std_cast('"PLAZO_OP_FABRIC_"', 'VARCHAR') }}                        as PLAZO_OP_FABRIC,
        {{ std_cast('"PRODUCTO_ORIGEN"', 'VARCHAR') }}                         as PRODUCTO_ORIGEN,
        {{ std_cast('"_COSTES_POR_CANTIDAD"', 'NUMBER(38,5)') }}               as COSTES_POR_CANTIDAD,
        {{ std_cast('"UNIDADES_POR_CAJA"', 'INTEGER') }}                       as UNIDADES_POR_CAJA,
        {{ std_cast('"CAJAS_POR_PALET"', 'INTEGER') }}                         as CAJAS_POR_PALET,
        {{ std_cast('"PESO_MIN_UNIDAD"', 'NUMBER(38,5)') }}                    as PESO_MIN_UNIDAD,
        {{ std_cast('"PESO_MAX_UNIDAD"', 'NUMBER(38,5)') }}                    as PESO_MAX_UNIDAD,
        {{ std_cast('"TOLERANCIA"', 'NUMBER(38,5)') }}                         as TOLERANCIA,
        {{ std_cast('"PRESENCIA_OGM"', 'INTEGER') }}                           as PRESENCIA_OGM,
        {{ std_cast('"PAIS_PROCEDENCIA"', 'VARCHAR') }}                        as PAIS_PROCEDENCIA,
        {{ std_cast('"CERTIFICADO_NO_OGM"', 'VARCHAR') }}                      as CERTIFICADO_NO_OGM,
        {{ std_cast('"TEXTO_ETIQUETA"', 'VARCHAR') }}                          as TEXTO_ETIQUETA,
        {{ std_cast('"ORIGEN"', 'VARCHAR') }}                                  as ORIGEN,
        {{ std_cast('"COD_PLANTILLA"', 'VARCHAR') }}                           as COD_PLANTILLA,
        {{ std_cast('"TIEMPO_REPOSO"', 'TIMESTAMP_NTZ') }}                     as TIEMPO_REPOSO,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"PERMITIR_RECLASIFICACION_OC"', 'INTEGER') }}             as PERMITIR_RECLASIFICACION_OC,
        {{ std_cast('"AVISO_CALIDAD"', 'INTEGER') }}                           as AVISO_CALIDAD,
        {{ std_cast('"EMB_ETIQUETA"', 'VARCHAR') }}                            as EMB_ETIQUETA,
        {{ std_cast('"PRODUCTO_A_CURAR"', 'INTEGER') }}                        as PRODUCTO_A_CURAR,
        {{ std_cast('"PALETIZACION_AUTOMATICA"', 'INTEGER') }}                 as PALETIZACION_AUTOMATICA,
        {{ std_cast('"EDI_CODIGO_EAN"', 'VARCHAR') }}                          as EDI_CODIGO_EAN,
        {{ std_cast('"PRECIO_MATADERO"', 'NUMBER(38,5)') }}                    as PRECIO_MATADERO,
        {{ std_cast('"COD_ESPECIE"', 'VARCHAR') }}                             as COD_ESPECIE,
        {{ std_cast('"CONTROL_POR"', 'INTEGER') }}                             as CONTROL_POR,
        {{ std_cast('"NO_PLANTILLA_OT_MATADERO"', 'VARCHAR') }}                as NO_PLANTILLA_OT_MATADERO,
        {{ std_cast('"NO_PLANTILLA_OT_DESPIECE"', 'VARCHAR') }}                as NO_PLANTILLA_OT_DESPIECE,
        {{ std_cast('"COD_GRUPO_INGREDIENTES"', 'VARCHAR') }}                  as COD_GRUPO_INGREDIENTES,
        {{ std_cast('"CALCULO_FECHA_RETIRADA"', 'VARCHAR') }}                  as CALCULO_FECHA_RETIRADA,
        {{ std_cast('"NO_PRODUCTO_KAIS"', 'VARCHAR') }}                        as NO_PRODUCTO_KAIS,
        {{ std_cast('"CONTROLAR_PESO_MIN_MAX"', 'INTEGER') }}                  as CONTROLAR_PESO_MIN_MAX,
        {{ std_cast('"CONTROL_CADUCIDAD_EXPEDICION"', 'INTEGER') }}            as CONTROL_CADUCIDAD_EXPEDICION,
        {{ std_cast('"DESCRIPCION_INTERNA"', 'VARCHAR') }}                     as DESCRIPCION_INTERNA,
        {{ std_cast('"RECADV_DISABLED"', 'INTEGER') }}                         as RECADV_DISABLED,
        'FRI'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
