{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_NO_PESADA') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_PESADA"', 'VARCHAR') }}                               as NO_PESADA,
        {{ std_cast('"TABLE_ID"', 'INTEGER') }}                                as TABLE_ID,
        {{ std_cast('"DOCUMENT_TYPE"', 'INTEGER') }}                           as DOCUMENT_TYPE,
        {{ std_cast('"DOCUMENT_NO_"', 'VARCHAR') }}                            as DOCUMENT_NO,
        {{ std_cast('"LINE_NO_"', 'INTEGER') }}                                as LINE_NO,
        {{ std_cast('"DESTINATION_TABLE_ID"', 'INTEGER') }}                    as DESTINATION_TABLE_ID,
        {{ std_cast('"DESTINATION_DOCUMENT_TYPE"', 'INTEGER') }}               as DESTINATION_DOCUMENT_TYPE,
        {{ std_cast('"DESTINATION_DOCUMENT_NO_"', 'VARCHAR') }}                as DESTINATION_DOCUMENT_NO,
        {{ std_cast('"DESTINATION_LINE_NO_"', 'INTEGER') }}                    as DESTINATION_LINE_NO,
        {{ std_cast('"REF_EXTERNA"', 'VARCHAR') }}                             as REF_EXTERNA,
        {{ std_cast('"HISTORICO"', 'INTEGER') }}                               as HISTORICO,
        {{ std_cast('"BATCH_NAME"', 'VARCHAR') }}                              as BATCH_NAME,
        {{ std_cast('"DESTINATION_BATCH_NAME"', 'VARCHAR') }}                  as DESTINATION_BATCH_NAME,
        {{ std_cast('"SOURCE_TABLE_ID"', 'INTEGER') }}                         as SOURCE_TABLE_ID,
        {{ std_cast('"SOURCE_DOCUMENT_NO_"', 'VARCHAR') }}                     as SOURCE_DOCUMENT_NO,
        {{ std_cast('"SOURCE_DOCUMENT_TYPE"', 'INTEGER') }}                    as SOURCE_DOCUMENT_TYPE,
        {{ std_cast('"SOURCE_BATCH_NAME"', 'VARCHAR') }}                       as SOURCE_BATCH_NAME,
        {{ std_cast('"SOURCE_DOCUMENT_LINE_NO_"', 'INTEGER') }}                as SOURCE_DOCUMENT_LINE_NO,
        {{ std_cast('"ASSIGN_ENTRY_NO_RELATION"', 'INTEGER') }}                as ASSIGN_ENTRY_NO_RELATION,
        {{ std_cast('"BLOQUEO_FISICO"', 'INTEGER') }}                          as BLOQUEO_FISICO,
        {{ std_cast('"ITEM_NO_"', 'VARCHAR') }}                                as ITEM_NO,
        {{ std_cast('"VARIANT_CODE"', 'VARCHAR') }}                            as VARIANT_CODE,
        {{ std_cast('"CODIGO_EMBALAJE"', 'VARCHAR') }}                         as CODIGO_EMBALAJE,
        {{ std_cast('"NO_PRESENTACION"', 'VARCHAR') }}                         as NO_PRESENTACION,
        {{ std_cast('"LOT_NO_"', 'VARCHAR') }}                                 as LOT_NO,
        {{ std_cast('"CANTIDAD_EMBALAJE"', 'NUMBER(38,5)') }}                  as CANTIDAD_EMBALAJE,
        {{ std_cast('"CANTIDAD_UNIDADES"', 'NUMBER(38,5)') }}                  as CANTIDAD_UNIDADES,
        {{ std_cast('"CANTIDAD_KILOS"', 'NUMBER(38,5)') }}                     as CANTIDAD_KILOS,
        {{ std_cast('"CODIGO_EMBALAJE_DO"', 'VARCHAR') }}                      as CODIGO_EMBALAJE_DO,
        {{ std_cast('"PARAMETRO_1"', 'NUMBER(38,5)') }}                        as PARAMETRO_1,
        {{ std_cast('"PARAMETRO_2"', 'NUMBER(38,5)') }}                        as PARAMETRO_2,
        {{ std_cast('"PARAMETRO_3"', 'INTEGER') }}                             as PARAMETRO_3,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"TIPO_PALET"', 'VARCHAR') }}                              as TIPO_PALET,
        {{ std_cast('"TARA_PALETS"', 'NUMBER(38,5)') }}                        as TARA_PALETS,
        {{ std_cast('"CANTIDAD_PALETS"', 'NUMBER(38,5)') }}                    as CANTIDAD_PALETS,
        {{ std_cast('"TIPO_CAJAS"', 'VARCHAR') }}                              as TIPO_CAJAS,
        {{ std_cast('"TARA_CAJAS"', 'NUMBER(38,5)') }}                         as TARA_CAJAS,
        {{ std_cast('"CANTIDAD_CAJAS"', 'NUMBER(38,5)') }}                     as CANTIDAD_CAJAS,
        {{ std_cast('"TARA_EXTRA"', 'NUMBER(38,5)') }}                         as TARA_EXTRA,
        {{ std_cast('"EXPIRATION_DATE"', 'TIMESTAMP_NTZ') }}                   as EXPIRATION_DATE,
        {{ std_cast('"VENDOR_EXPIRATION_DATE"', 'TIMESTAMP_NTZ') }}            as VENDOR_EXPIRATION_DATE,
        {{ std_cast('"VENDOR_LOT_NO_"', 'VARCHAR') }}                          as VENDOR_LOT_NO,
        {{ std_cast('"PARAMETRO_FECHA_1"', 'TIMESTAMP_NTZ') }}                 as PARAMETRO_FECHA_1,
        {{ std_cast('"PARAMETRO_FECHA_2"', 'TIMESTAMP_NTZ') }}                 as PARAMETRO_FECHA_2,
        {{ std_cast('"PARAMETRO_CODIGO_1"', 'VARCHAR') }}                      as PARAMETRO_CODIGO_1,
        {{ std_cast('"PARAMETRO_DATEFORMULA_1"', 'VARCHAR') }}                 as PARAMETRO_DATEFORMULA_1,
        {{ std_cast('"PARAMETRO_BOOLEAN_1"', 'INTEGER') }}                     as PARAMETRO_BOOLEAN_1,
        {{ std_cast('"BAR_CODE"', 'VARCHAR') }}                                as BAR_CODE,
        {{ std_cast('"REGISTRO_SANITARIO"', 'VARCHAR') }}                      as REGISTRO_SANITARIO,
        {{ std_cast('"PARAMETRO_CODIGO_2"', 'VARCHAR') }}                      as PARAMETRO_CODIGO_2,
        {{ std_cast('"CUSTOMER_NO_"', 'VARCHAR') }}                            as CUSTOMER_NO,
        {{ std_cast('"VENDOR_NO_"', 'VARCHAR') }}                              as VENDOR_NO,
        {{ std_cast('"ESTADO_VALORES"', 'INTEGER') }}                          as ESTADO_VALORES,
        {{ std_cast('"TIPO_EV"', 'INTEGER') }}                                 as TIPO_EV,
        {{ std_cast('"NO_EV"', 'VARCHAR') }}                                   as NO_EV,
        {{ std_cast('"COD_VARIANTE_EV"', 'VARCHAR') }}                         as COD_VARIANTE_EV,
        {{ std_cast('"DESCRIPCION_EV"', 'VARCHAR') }}                          as DESCRIPCION_EV,
        {{ std_cast('"DESCRIPCION_2_EV"', 'VARCHAR') }}                        as DESCRIPCION_2_EV,
        {{ std_cast('"COD_ALMACEN_EV"', 'VARCHAR') }}                          as COD_ALMACEN_EV,
        {{ std_cast('"CANTIDAD_UNIDADES_EV"', 'NUMBER(38,5)') }}               as CANTIDAD_UNIDADES_EV,
        {{ std_cast('"CANTIDAD_KILOS_EV"', 'NUMBER(38,5)') }}                  as CANTIDAD_KILOS_EV,
        {{ std_cast('"NO_LOTE_EV"', 'VARCHAR') }}                              as NO_LOTE_EV,
        {{ std_cast('"FECHA_CADUCIDAD_EV"', 'TIMESTAMP_NTZ') }}                as FECHA_CADUCIDAD_EV,
        {{ std_cast('"TIPO_PALET_EV"', 'VARCHAR') }}                           as TIPO_PALET_EV,
        {{ std_cast('"TARA_PALETS_EV"', 'NUMBER(38,5)') }}                     as TARA_PALETS_EV,
        {{ std_cast('"CANTIDAD_PALETS_EV"', 'NUMBER(38,5)') }}                 as CANTIDAD_PALETS_EV,
        {{ std_cast('"TIPO_CAJAS_EV"', 'VARCHAR') }}                           as TIPO_CAJAS_EV,
        {{ std_cast('"TARA_CAJAS_EV"', 'NUMBER(38,5)') }}                      as TARA_CAJAS_EV,
        {{ std_cast('"CANTIDAD_CAJAS_EV"', 'NUMBER(38,5)') }}                  as CANTIDAD_CAJAS_EV,
        {{ std_cast('"TARA_EXTRA_EV"', 'NUMBER(38,5)') }}                      as TARA_EXTRA_EV,
        {{ std_cast('"CODIGO_EMBALAJE_EV"', 'VARCHAR') }}                      as CODIGO_EMBALAJE_EV,
        {{ std_cast('"CANTIDAD_EMBALAJE_EV"', 'NUMBER(38,5)') }}               as CANTIDAD_EMBALAJE_EV,
        {{ std_cast('"NO_OP_FABR_"', 'VARCHAR') }}                             as NO_OP_FABR,
        {{ std_cast('"NO_OP_CURAC_"', 'VARCHAR') }}                            as NO_OP_CURAC,
        {{ std_cast('"COD_FASE_OC"', 'VARCHAR') }}                             as COD_FASE_OC,
        {{ std_cast('"COD_ALMACEN_OC"', 'VARCHAR') }}                          as COD_ALMACEN_OC,
        {{ std_cast('"PARAMETRO_1_EV"', 'NUMBER(38,5)') }}                     as PARAMETRO_1_EV,
        {{ std_cast('"PARAMETRO_2_EV"', 'NUMBER(38,5)') }}                     as PARAMETRO_2_EV,
        {{ std_cast('"PARAMETRO_3_EV"', 'INTEGER') }}                          as PARAMETRO_3_EV,
        {{ std_cast('"TIPO_ASIGNACION"', 'INTEGER') }}                         as TIPO_ASIGNACION,
        {{ std_cast('"TIPO_AS"', 'INTEGER') }}                                 as TIPO_AS,
        {{ std_cast('"NO_AS"', 'VARCHAR') }}                                   as NO_AS,
        {{ std_cast('"COD_VARIANTE_AS"', 'VARCHAR') }}                         as COD_VARIANTE_AS,
        {{ std_cast('"DESCRIPCION_AS"', 'VARCHAR') }}                          as DESCRIPCION_AS,
        {{ std_cast('"DESCRIPCION_2_AS"', 'VARCHAR') }}                        as DESCRIPCION_2_AS,
        {{ std_cast('"COD_ALMACEN_AS"', 'VARCHAR') }}                          as COD_ALMACEN_AS,
        {{ std_cast('"CANTIDAD_UNIDADES_AS"', 'NUMBER(38,5)') }}               as CANTIDAD_UNIDADES_AS,
        {{ std_cast('"CANTIDAD_KILOS_AS"', 'NUMBER(38,5)') }}                  as CANTIDAD_KILOS_AS,
        {{ std_cast('"NO_LOTE_AS"', 'VARCHAR') }}                              as NO_LOTE_AS,
        {{ std_cast('"FECHA_CADUCIDAD_AS"', 'TIMESTAMP_NTZ') }}                as FECHA_CADUCIDAD_AS,
        {{ std_cast('"TIPO_PALET_AS"', 'VARCHAR') }}                           as TIPO_PALET_AS,
        {{ std_cast('"TARA_PALETS_AS"', 'NUMBER(38,5)') }}                     as TARA_PALETS_AS,
        {{ std_cast('"CANTIDAD_PALETS_AS"', 'NUMBER(38,5)') }}                 as CANTIDAD_PALETS_AS,
        {{ std_cast('"TIPO_CAJAS_AS"', 'VARCHAR') }}                           as TIPO_CAJAS_AS,
        {{ std_cast('"TARA_CAJAS_AS"', 'NUMBER(38,5)') }}                      as TARA_CAJAS_AS,
        {{ std_cast('"CANTIDAD_CAJAS_AS"', 'NUMBER(38,5)') }}                  as CANTIDAD_CAJAS_AS,
        {{ std_cast('"TARA_EXTRA_AS"', 'NUMBER(38,5)') }}                      as TARA_EXTRA_AS,
        {{ std_cast('"CODIGO_EMBALAJE_AS"', 'VARCHAR') }}                      as CODIGO_EMBALAJE_AS,
        {{ std_cast('"CANTIDAD_EMBALAJE_AS"', 'NUMBER(38,5)') }}               as CANTIDAD_EMBALAJE_AS,
        {{ std_cast('"TOTAL_NETO_AS"', 'NUMBER(38,5)') }}                      as TOTAL_NETO_AS,
        {{ std_cast('"NO_PESADA_EMBALAJE"', 'VARCHAR') }}                      as NO_PESADA_EMBALAJE,
        {{ std_cast('"NO_PESADA_PALET"', 'VARCHAR') }}                         as NO_PESADA_PALET,
        {{ std_cast('"TIPO_PESADA"', 'INTEGER') }}                             as TIPO_PESADA,
        {{ std_cast('"INBOUND_ITEM_ENTRY_NO_"', 'INTEGER') }}                  as INBOUND_ITEM_ENTRY_NO,
        {{ std_cast('"OUTBOUND_ITEM_ENTRY_NO_"', 'INTEGER') }}                 as OUTBOUND_ITEM_ENTRY_NO,
        {{ std_cast('"FECHA_CREACION"', 'TIMESTAMP_NTZ') }}                    as FECHA_CREACION,
        {{ std_cast('"SSCC_NO_"', 'VARCHAR') }}                                as SSCC_NO,
        {{ std_cast('"NO_BULTO_ETIQUETA"', 'INTEGER') }}                       as NO_BULTO_ETIQUETA,
        {{ std_cast('"PARAMETRO_1_AS"', 'NUMBER(38,5)') }}                     as PARAMETRO_1_AS,
        {{ std_cast('"PARAMETRO_2_AS"', 'NUMBER(38,5)') }}                     as PARAMETRO_2_AS,
        {{ std_cast('"PARAMETRO_3_AS"', 'INTEGER') }}                          as PARAMETRO_3_AS,
        {{ std_cast('"HORA_CREACION"', 'TIMESTAMP_NTZ') }}                     as HORA_CREACION,
        {{ std_cast('"NO_PESADA_PALET_ORIGEN"', 'VARCHAR') }}                  as NO_PESADA_PALET_ORIGEN,
        {{ std_cast('"APPL_FROM_ITEM_ENTRY"', 'INTEGER') }}                    as APPL_FROM_ITEM_ENTRY,
        {{ std_cast('"ESTADO"', 'INTEGER') }}                                  as ESTADO,
        {{ std_cast('"ESTADO_PALETIZADO"', 'INTEGER') }}                       as ESTADO_PALETIZADO,
        {{ std_cast('"REGISTRADO"', 'INTEGER') }}                              as REGISTRADO,
        {{ std_cast('"NO_DOCUMENTO_TRANSF_"', 'VARCHAR') }}                    as NO_DOCUMENTO_TRANSF,
        {{ std_cast('"NO_LINEA_TRANSF_"', 'INTEGER') }}                        as NO_LINEA_TRANSF,
        {{ std_cast('"NO_MOV_CURACION"', 'INTEGER') }}                         as NO_MOV_CURACION,
        {{ std_cast('"BLOQUEAR_TRANSFORMACION"', 'INTEGER') }}                 as BLOQUEAR_TRANSFORMACION,
        {{ std_cast('"NO_DOCUMENTO_REG_ENTRADA"', 'VARCHAR') }}                as NO_DOCUMENTO_REG_ENTRADA,
        {{ std_cast('"NO_LIN_DOC_REG_ENTRADA"', 'INTEGER') }}                  as NO_LIN_DOC_REG_ENTRADA,
        {{ std_cast('"NO_DOCUMENTO_REG_SALIDA"', 'VARCHAR') }}                 as NO_DOCUMENTO_REG_SALIDA,
        {{ std_cast('"NO_LIN_DOC_REG_SALIDA"', 'INTEGER') }}                   as NO_LIN_DOC_REG_SALIDA,
        {{ std_cast('"NO_DOCUMENTO_DEVOLUCION"', 'VARCHAR') }}                 as NO_DOCUMENTO_DEVOLUCION,
        {{ std_cast('"NO_LIN_DOCUMENTO_DEVOLUCION"', 'INTEGER') }}             as NO_LIN_DOCUMENTO_DEVOLUCION,
        {{ std_cast('"NUMCARRO"', 'VARCHAR') }}                                as NUMCARRO,
        {{ std_cast('"BIN_CODE"', 'VARCHAR') }}                                as BIN_CODE,
        {{ std_cast('"CONGELADO"', 'INTEGER') }}                               as CONGELADO,
        {{ std_cast('"PARAMETRO_4"', 'INTEGER') }}                             as PARAMETRO_4,
        {{ std_cast('"NUMALBPROV"', 'VARCHAR') }}                              as NUMALBPROV,
        {{ std_cast('"UNIDAD_MEDIDA_BASE"', 'VARCHAR') }}                      as UNIDAD_MEDIDA_BASE,
        {{ std_cast('"NUMNOTA"', 'VARCHAR') }}                                 as NUMNOTA,
        {{ std_cast('"NUMGABIA"', 'VARCHAR') }}                                as NUMGABIA,
        {{ std_cast('"OBSQUALITAT"', 'VARCHAR') }}                             as OBSQUALITAT,
        {{ std_cast('"FECHA_SACRIFICIO"', 'TIMESTAMP_NTZ') }}                  as FECHA_SACRIFICIO,
        {{ std_cast('"FECHA_CONGELADO"', 'TIMESTAMP_NTZ') }}                   as FECHA_CONGELADO,
        {{ std_cast('"FECHA_2"', 'TIMESTAMP_NTZ') }}                           as FECHA_2,
        {{ std_cast('"ID_TAG"', 'VARCHAR') }}                                  as ID_TAG,
        {{ std_cast('"HALAL"', 'INTEGER') }}                                   as HALAL,
        {{ std_cast('"ID_INDIVIDUO"', 'VARCHAR') }}                            as ID_INDIVIDUO,
        {{ std_cast('"PARAMETRO_5"', 'INTEGER') }}                             as PARAMETRO_5,
        {{ std_cast('"FECHA_DESPIECE"', 'TIMESTAMP_NTZ') }}                    as FECHA_DESPIECE,
        {{ std_cast('"TARA_UNIDAD"', 'NUMBER(38,5)') }}                        as TARA_UNIDAD,
        {{ std_cast('"PARAMETRO_6"', 'INTEGER') }}                             as PARAMETRO_6,
        {{ std_cast('"TIENE_CERT_"', 'INTEGER') }}                             as TIENE_CERT,
        {{ std_cast('"OBSERVACIONES_PALET"', 'VARCHAR') }}                     as OBSERVACIONES_PALET,
        {{ std_cast('"PRECIO_VALORACION"', 'NUMBER(38,5)') }}                  as PRECIO_VALORACION,
        {{ std_cast('"FECHA_VALORACION"', 'TIMESTAMP_NTZ') }}                  as FECHA_VALORACION,
        {{ std_cast('"VALORADO"', 'INTEGER') }}                                as VALORADO,
        {{ std_cast('"SEXO"', 'INTEGER') }}                                    as SEXO,
        {{ std_cast('"FECHA_NACIMIENTO"', 'TIMESTAMP_NTZ') }}                  as FECHA_NACIMIENTO,
        {{ std_cast('"OBSERVACIONES"', 'VARCHAR') }}                           as OBSERVACIONES,
        {{ std_cast('"COD_CLAS_COMERCIAL"', 'VARCHAR') }}                      as COD_CLAS_COMERCIAL,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'FRI'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no_pesada
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
