{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_SALES_INVOICE_HEADERS') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        NULL                                                                   as TIMESTAMP,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        NULL                                                                   as SELL_TO_CUSTOMER_NO,
        NULL                                                                   as BILL_TO_CUSTOMER_NO,
        NULL                                                                   as BILL_TO_NAME,
        NULL                                                                   as BILL_TO_NAME_2,
        NULL                                                                   as BILL_TO_ADDRESS,
        NULL                                                                   as BILL_TO_ADDRESS_2,
        NULL                                                                   as BILL_TO_CITY,
        NULL                                                                   as BILL_TO_CONTACT,
        {{ std_cast('"Your Reference"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        NULL                                                                   as SHIP_TO_CODE,
        NULL                                                                   as SHIP_TO_NAME,
        NULL                                                                   as SHIP_TO_NAME_2,
        NULL                                                                   as SHIP_TO_ADDRESS,
        NULL                                                                   as SHIP_TO_ADDRESS_2,
        NULL                                                                   as SHIP_TO_CITY,
        NULL                                                                   as SHIP_TO_CONTACT,
        {{ std_cast('"Order Date"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"Posting Date"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"Shipment Date"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"Posting Description"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"Payment Terms Code"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"Due Date"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"Payment Discount _"', 'NUMBER(38,5)') }}                 as PAYMENT_DISCOUNT,
        {{ std_cast('"Pmt_ Discount Date"', 'TIMESTAMP_NTZ') }}                as PMT_DISCOUNT_DATE,
        {{ std_cast('"Shipment Method Code"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Shortcut Dimension 1 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"Shortcut Dimension 2 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"Customer Posting Group"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"Currency Code"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"Currency Factor"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Prices Including VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"Invoice Disc_ Code"', 'VARCHAR') }}                      as INVOICE_DISC_CODE,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        {{ std_cast('"Language Code"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"Salesperson Code"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"Order No_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"No_ Printed"', 'INTEGER') }}                             as NO_PRINTED,
        {{ std_cast('"On Hold"', 'VARCHAR') }}                                 as ON_HOLD,
        NULL                                                                   as APPLIES_TO_DOC_TYPE,
        NULL                                                                   as APPLIES_TO_DOC_NO,
        {{ std_cast('"Bal_ Account No_"', 'VARCHAR') }}                        as BAL_ACCOUNT_NO,
        {{ std_cast('"VAT Registration No_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"Reason Code"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        NULL                                                                   as EU_3_PARTY_TRADE,
        {{ std_cast('"Transaction Type"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"Transport Method"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT Country_Region Code"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        NULL                                                                   as SELL_TO_CUSTOMER_NAME,
        NULL                                                                   as SELL_TO_CUSTOMER_NAME_2,
        NULL                                                                   as SELL_TO_ADDRESS,
        NULL                                                                   as SELL_TO_ADDRESS_2,
        NULL                                                                   as SELL_TO_CITY,
        NULL                                                                   as SELL_TO_CONTACT,
        NULL                                                                   as BILL_TO_POST_CODE,
        NULL                                                                   as BILL_TO_COUNTY,
        NULL                                                                   as BILL_TO_COUNTRY_REGION_CODE,
        NULL                                                                   as SELL_TO_POST_CODE,
        NULL                                                                   as SELL_TO_COUNTY,
        NULL                                                                   as SELL_TO_COUNTRY_REGION_CODE,
        NULL                                                                   as SHIP_TO_POST_CODE,
        NULL                                                                   as SHIP_TO_COUNTY,
        NULL                                                                   as SHIP_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"Bal_ Account Type"', 'INTEGER') }}                       as BAL_ACCOUNT_TYPE,
        {{ std_cast('"Exit Point"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"Correction"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"Document Date"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"External Document No_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"Area"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"Transaction Specification"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"Payment Method Code"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"Shipping Agent Code"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"Package Tracking No_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        NULL                                                                   as PRE_ASSIGNED_NO_SERIES,
        {{ std_cast('"No_ Series"', 'VARCHAR') }}                              as NO_SERIES,
        {{ std_cast('"Order No_ Series"', 'VARCHAR') }}                        as ORDER_NO_SERIES,
        NULL                                                                   as PRE_ASSIGNED_NO,
        {{ std_cast('"User ID"', 'VARCHAR') }}                                 as USER_ID,
        {{ std_cast('"Source Code"', 'VARCHAR') }}                             as SOURCE_CODE,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT Base Discount _"', 'NUMBER(38,5)') }}                as VAT_BASE_DISCOUNT,
        {{ std_cast('"Prepayment No_ Series"', 'VARCHAR') }}                   as PREPAYMENT_NO_SERIES,
        {{ std_cast('"Prepayment Invoice"', 'INTEGER') }}                      as PREPAYMENT_INVOICE,
        {{ std_cast('"Prepayment Order No_"', 'VARCHAR') }}                    as PREPAYMENT_ORDER_NO,
        {{ std_cast('"Quote No_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"Dimension Set ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"Document Exchange Identifier"', 'VARCHAR') }}            as DOCUMENT_EXCHANGE_IDENTIFIER,
        {{ std_cast('"Document Exchange Status"', 'INTEGER') }}                as DOCUMENT_EXCHANGE_STATUS,
        {{ std_cast('"Doc_ Exch_ Original Identifier"', 'VARCHAR') }}          as DOC_EXCH_ORIGINAL_IDENTIFIER,
        {{ std_cast('"Coupled to CRM"', 'INTEGER') }}                          as COUPLED_TO_CRM,
        NULL                                                                   as CREDIT_CARD_NO,
        {{ std_cast('"Direct Debit Mandate ID"', 'VARCHAR') }}                 as DIRECT_DEBIT_MANDATE_ID,
        NULL                                                                   as CANCELED_BY,
        {{ std_cast('"Cust_ Ledger Entry No_"', 'INTEGER') }}                  as CUST_LEDGER_ENTRY_NO,
        {{ std_cast('"Campaign No_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        NULL                                                                   as SELL_TO_CONTACT_NO,
        NULL                                                                   as BILL_TO_CONTACT_NO,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Get Shipment Used"', 'INTEGER') }}                       as GET_SHIPMENT_USED,
        NULL                                                                   as CONTAINER,
        NULL                                                                   as SEAL,
        NULL                                                                   as TRUCK_LICENSE_PLATE,
        NULL                                                                   as DRIVER,
        NULL                                                                   as BANK_ACCOUNT_TO_TRANSFER,
        NULL                                                                   as MOTIVO_DEVOLUCION_EDI,
        NULL                                                                   as DEPARTAMENTO_EDI,
        NULL                                                                   as HEADER_DISCOUNT,
        NULL                                                                   as RAPPEL,
        NULL                                                                   as INVOICE_CANCELATION,
        NULL                                                                   as CORRECTED_INVOICE_TYPE,
        NULL                                                                   as SIMPLIFIED_TYPE,
        NULL                                                                   as FROM_TICKET_NO,
        NULL                                                                   as TO_TICKET_NO,
        NULL                                                                   as APPLIES_TO_BILL_NO,
        {{ std_cast('"Cust_ Bank Acc_ Code"', 'VARCHAR') }}                    as CUST_BANK_ACC_CODE,
        NULL                                                                   as PAY_AT_CODE,
        NULL                                                                   as PESO_NETO,
        NULL                                                                   as PESO_BRUTO,
        NULL                                                                   as FORMA_PAGO_FACTURAPLUS,
        NULL                                                                   as CASH_ENTRY,
        NULL                                                                   as SPETIAL_OPERATION_TYPE,
        NULL                                                                   as SPETIAL_OPERATION_CODE,
        NULL                                                                   as GROUP_SHIPMENT_TYPE,
        NULL                                                                   as SHIPMENT_FREQUENCY,
        NULL                                                                   as INVOICE_DETAIL,
        NULL                                                                   as REVERTIDO_EN_NO_ABONO,
        NULL                                                                   as NO_FACTURA_ANULADA,
        NULL                                                                   as ANULACION_DE_FACTURA,
        NULL                                                                   as REVERTIDA,
        NULL                                                                   as PRINT_BY_CONCEPT,
        NULL                                                                   as ODS_JOB_TEMPLATE_CODE,
        NULL                                                                   as OPERATION_DATE,
        NULL                                                                   as TO_DOCUMENT_NO,
        NULL                                                                   as FROM_DOCUMENT_NO,
        NULL                                                                   as REGIME,
        NULL                                                                   as SII_CORRECTION_TYPE,
        NULL                                                                   as SII_OPERATION_DESCRIPTION,
        NULL                                                                   as SII_INVOICE_TYPE,
        NULL                                                                   as SIMPLIFIED_INVOICE,
        NULL                                                                   as SIMPLIFIED_ART_6_1_D,
        NULL                                                                   as REFEXTERNA,
        NULL                                                                   as TAX_FREE,
        NULL                                                                   as NUM_REGISTRO_ACUERDO_FACT,
        NULL                                                                   as EMITIDA_POR_TERCERO,
        NULL                                                                   as EMITIDA_POR_NORMATIVA_DEL_GAS,
        NULL                                                                   as PAYMENT_DATE,
        NULL                                                                   as PAYMENT_NO_DAYS,
        NULL                                                                   as IPAD_ORDER,
        NULL                                                                   as WITHOUT_PLASTIC_DECLARATION,
        NULL                                                                   as SCRAP_AMOUNT,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        {{ std_cast('"Sell-to Customer No_"', 'VARCHAR') }}                    as SELLTO_CUSTOMER_NO,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"Bill-to Name"', 'VARCHAR') }}                            as BILLTO_NAME,
        {{ std_cast('"Bill-to Name 2"', 'VARCHAR') }}                          as BILLTO_NAME_2,
        {{ std_cast('"Bill-to Address"', 'VARCHAR') }}                         as BILLTO_ADDRESS,
        {{ std_cast('"Bill-to Address 2"', 'VARCHAR') }}                       as BILLTO_ADDRESS_2,
        {{ std_cast('"Bill-to City"', 'VARCHAR') }}                            as BILLTO_CITY,
        {{ std_cast('"Bill-to Contact"', 'VARCHAR') }}                         as BILLTO_CONTACT,
        {{ std_cast('"Ship-to Code"', 'VARCHAR') }}                            as SHIPTO_CODE,
        {{ std_cast('"Ship-to Name"', 'VARCHAR') }}                            as SHIPTO_NAME,
        {{ std_cast('"Ship-to Name 2"', 'VARCHAR') }}                          as SHIPTO_NAME_2,
        {{ std_cast('"Ship-to Address"', 'VARCHAR') }}                         as SHIPTO_ADDRESS,
        {{ std_cast('"Ship-to Address 2"', 'VARCHAR') }}                       as SHIPTO_ADDRESS_2,
        {{ std_cast('"Ship-to City"', 'VARCHAR') }}                            as SHIPTO_CITY,
        {{ std_cast('"Ship-to Contact"', 'VARCHAR') }}                         as SHIPTO_CONTACT,
        {{ std_cast('"Applies-to Doc_ Type"', 'INTEGER') }}                    as APPLIESTO_DOC_TYPE,
        {{ std_cast('"Applies-to Doc_ No_"', 'VARCHAR') }}                     as APPLIESTO_DOC_NO,
        {{ std_cast('"EU 3-Party Trade"', 'INTEGER') }}                        as EU_3PARTY_TRADE,
        {{ std_cast('"Sell-to Customer Name"', 'VARCHAR') }}                   as SELLTO_CUSTOMER_NAME,
        {{ std_cast('"Sell-to Customer Name 2"', 'VARCHAR') }}                 as SELLTO_CUSTOMER_NAME_2,
        {{ std_cast('"Sell-to Address"', 'VARCHAR') }}                         as SELLTO_ADDRESS,
        {{ std_cast('"Sell-to Address 2"', 'VARCHAR') }}                       as SELLTO_ADDRESS_2,
        {{ std_cast('"Sell-to City"', 'VARCHAR') }}                            as SELLTO_CITY,
        {{ std_cast('"Sell-to Contact"', 'VARCHAR') }}                         as SELLTO_CONTACT,
        {{ std_cast('"Bill-to Post Code"', 'VARCHAR') }}                       as BILLTO_POST_CODE,
        {{ std_cast('"Bill-to County"', 'VARCHAR') }}                          as BILLTO_COUNTY,
        {{ std_cast('"Bill-to Country_Region Code"', 'VARCHAR') }}             as BILLTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Sell-to Post Code"', 'VARCHAR') }}                       as SELLTO_POST_CODE,
        {{ std_cast('"Sell-to County"', 'VARCHAR') }}                          as SELLTO_COUNTY,
        {{ std_cast('"Sell-to Country_Region Code"', 'VARCHAR') }}             as SELLTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Ship-to Post Code"', 'VARCHAR') }}                       as SHIPTO_POST_CODE,
        {{ std_cast('"Ship-to County"', 'VARCHAR') }}                          as SHIPTO_COUNTY,
        {{ std_cast('"Ship-to Country_Region Code"', 'VARCHAR') }}             as SHIPTO_COUNTRY_REGION_CODE,
        {{ std_cast('"Pre-Assigned No_ Series"', 'VARCHAR') }}                 as PREASSIGNED_NO_SERIES,
        {{ std_cast('"Pre-Assigned No_"', 'VARCHAR') }}                        as PREASSIGNED_NO,
        {{ std_cast('"Invoice Discount Calculation"', 'INTEGER') }}            as INVOICE_DISCOUNT_CALCULATION,
        {{ std_cast('"Invoice Discount Value"', 'NUMBER(38,5)') }}             as INVOICE_DISCOUNT_VALUE,
        {{ std_cast('"Payment Instructions Name"', 'VARCHAR') }}               as PAYMENT_INSTRUCTIONS_NAME,
        {{ std_cast('"Payment Service Set ID"', 'INTEGER') }}                  as PAYMENT_SERVICE_SET_ID,
        {{ std_cast('"Sell-to Contact No_"', 'VARCHAR') }}                     as SELLTO_CONTACT_NO,
        {{ std_cast('"Bill-to Contact No_"', 'VARCHAR') }}                     as BILLTO_CONTACT_NO,
        {{ std_cast('"Opportunity No_"', 'VARCHAR') }}                         as OPPORTUNITY_NO,
        {{ std_cast('"Id"', 'VARCHAR') }}                                      as ID,
        {{ std_cast('"Invoice Type"', 'INTEGER') }}                            as INVOICE_TYPE,
        {{ std_cast('"Cr_ Memo Type"', 'INTEGER') }}                           as CR_MEMO_TYPE,
        {{ std_cast('"Special Scheme Code"', 'INTEGER') }}                     as SPECIAL_SCHEME_CODE,
        {{ std_cast('"Operation Description"', 'VARCHAR') }}                   as OPERATION_DESCRIPTION,
        {{ std_cast('"Operation Description 2"', 'VARCHAR') }}                 as OPERATION_DESCRIPTION_2,
        {{ std_cast('"Succeeded Company Name"', 'VARCHAR') }}                  as SUCCEEDED_COMPANY_NAME,
        {{ std_cast('"Succeeded VAT Registration No_"', 'VARCHAR') }}          as SUCCEEDED_VAT_REGISTRATION_NO,
        {{ std_cast('"Applies-to Bill No_"', 'VARCHAR') }}                     as APPLIESTO_BILL_NO,
        {{ std_cast('"Pay-at Code"', 'VARCHAR') }}                             as PAYAT_CODE,
        {{ std_cast('"Sell-to Phone No_"', 'VARCHAR') }}                       as SELLTO_PHONE_NO,
        {{ std_cast('"Sell-to E-Mail"', 'VARCHAR') }}                          as SELLTO_EMAIL,
        {{ std_cast('"ID Type"', 'INTEGER') }}                                 as ID_TYPE,
        {{ std_cast('"IDPIRPF IRPF Group"', 'VARCHAR') }}                      as IDPIRPF_IRPF_GROUP,
        {{ std_cast('"Cerrado"', 'INTEGER') }}                                 as CERRADO,
        {{ std_cast('"IDPGND Ship-to Excl_ SIG Rate"', 'INTEGER') }}           as IDPGND_SHIPTO_EXCL_SIG_RATE,
        {{ std_cast('"IF_OR_TYPE"', 'VARCHAR') }}                              as IF_OR_TYPE,
        {{ std_cast('"IF_DATA_1"', 'VARCHAR') }}                               as IF_DATA_1,
        {{ std_cast('"IF_DATA_2"', 'VARCHAR') }}                               as IF_DATA_2,
        {{ std_cast('"IF_DATA_3"', 'VARCHAR') }}                               as IF_DATA_3,
        {{ std_cast('"IF_DATA_4"', 'VARCHAR') }}                               as IF_DATA_4,
        {{ std_cast('"IF_DATA_5"', 'VARCHAR') }}                               as IF_DATA_5,
        {{ std_cast('"IF_ML_TIME"', 'TIMESTAMP_NTZ') }}                        as IF_ML_TIME,
        {{ std_cast('"IF_SAE_CERTIFICATION"', 'VARCHAR') }}                    as IF_SAE_CERTIFICATION,
        {{ std_cast('"CO_ID_CONT"', 'VARCHAR') }}                              as CO_ID_CONT,
        {{ std_cast('"CO_ID_PREC"', 'VARCHAR') }}                              as CO_ID_PREC,
        {{ std_cast('"TotalNetWeight"', 'NUMBER(38,5)') }}                     as TOTALNETWEIGHT,
        {{ std_cast('"TotalGrossWeight"', 'NUMBER(38,5)') }}                   as TOTALGROSSWEIGHT,
        {{ std_cast('"PackagesPalletNumber"', 'INTEGER') }}                    as PACKAGESPALLETNUMBER,
        {{ std_cast('"PackagesNumber"', 'INTEGER') }}                          as PACKAGESNUMBER,
        {{ std_cast('"AIT Billing Address Code"', 'VARCHAR') }}                as AIT_BILLING_ADDRESS_CODE,
        {{ std_cast('"IDPEDI INVOIC"', 'INTEGER') }}                           as IDPEDI_INVOIC,
        {{ std_cast('"IDPEDI INVOIC Sent"', 'INTEGER') }}                      as IDPEDI_INVOIC_SENT,
        {{ std_cast('"AIT Creation User"', 'VARCHAR') }}                       as AIT_CREATION_USER,
        {{ std_cast('"AIT Creation Datetime"', 'TIMESTAMP_NTZ') }}             as AIT_CREATION_DATETIME,
        NULL                                                                   as NO_MENSAJE_EDI,
        NULL                                                                   as COD_CADENA,
        NULL                                                                   as PROMOCIONES_POR,
        NULL                                                                   as COD_DTO_LINEA,
        NULL                                                                   as TIPO_PEDIDO,
        NULL                                                                   as TIPO_PUNTO_VERDE,
        NULL                                                                   as TIPO_RESIDUOS,
        NULL                                                                   as EDI_NO_EXPORTACIONES,
        NULL                                                                   as DTO_FACTURA,
        NULL                                                                   as COD_BANCO,
        NULL                                                                   as COMMISSION_SALESPERSON,
        NULL                                                                   as 2ND_SALESPERSON_CODE,
        NULL                                                                   as COMMISSION_2ND_SALESPERSON,
        NULL                                                                   as INCOME_TAX_RETENTION_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION,
        NULL                                                                   as INCOME_TAX_RETENTION_KEY,
        NULL                                                                   as INCOME_TAX_RETENTION_SUBKEY,
        NULL                                                                   as TEXTO_SUBVENCION,
        NULL                                                                   as TAX_FREE_VENDOR_NO,
        NULL                                                                   as CUSTOMER_SALES_DEPARTMENT,
        NULL                                                                   as EDI_BLOCKED,
        NULL                                                                   as DESADV_NO,
        NULL                                                                   as PLANNING_DELIVERY_DATE,
        NULL                                                                   as INVOICE_BLOCKED,
        NULL                                                                   as INTERCOMPANY_INVOICE,
        NULL                                                                   as CUSTOMER_RECEPTION_NO,
        NULL                                                                   as EDI_ORDER_NO,
        NULL                                                                   as SALES_SHIPMENT_NO,
        NULL                                                                   as FIX_SALES_PRICE,
        'DLS'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, tec_ts_staging DESC
) = 1
