{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_SALES_INVOICE_HEADER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_NAME"', 'VARCHAR') }}                            as BILL_TO_NAME,
        {{ std_cast('"BILL_TO_NAME_2"', 'VARCHAR') }}                          as BILL_TO_NAME_2,
        {{ std_cast('"BILL_TO_ADDRESS"', 'VARCHAR') }}                         as BILL_TO_ADDRESS,
        {{ std_cast('"BILL_TO_ADDRESS_2"', 'VARCHAR') }}                       as BILL_TO_ADDRESS_2,
        {{ std_cast('"BILL_TO_CITY"', 'VARCHAR') }}                            as BILL_TO_CITY,
        {{ std_cast('"BILL_TO_CONTACT"', 'VARCHAR') }}                         as BILL_TO_CONTACT,
        {{ std_cast('"YOUR_REFERENCE"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        {{ std_cast('"SHIP_TO_CODE"', 'VARCHAR') }}                            as SHIP_TO_CODE,
        {{ std_cast('"SHIP_TO_NAME"', 'VARCHAR') }}                            as SHIP_TO_NAME,
        {{ std_cast('"SHIP_TO_NAME_2"', 'VARCHAR') }}                          as SHIP_TO_NAME_2,
        {{ std_cast('"SHIP_TO_ADDRESS"', 'VARCHAR') }}                         as SHIP_TO_ADDRESS,
        {{ std_cast('"SHIP_TO_ADDRESS_2"', 'VARCHAR') }}                       as SHIP_TO_ADDRESS_2,
        {{ std_cast('"SHIP_TO_CITY"', 'VARCHAR') }}                            as SHIP_TO_CITY,
        {{ std_cast('"SHIP_TO_CONTACT"', 'VARCHAR') }}                         as SHIP_TO_CONTACT,
        {{ std_cast('"ORDER_DATE"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"POSTING_DESCRIPTION"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"DUE_DATE"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}                  as PAYMENT_DISCOUNT,
        {{ std_cast('"PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}                 as PMT_DISCOUNT_DATE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CURRENCY_FACTOR"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"ORDER_NO_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"NO_PRINTED"', 'INTEGER') }}                              as NO_PRINTED,
        {{ std_cast('"ON_HOLD"', 'VARCHAR') }}                                 as ON_HOLD,
        {{ std_cast('"APPLIES_TO_DOC_TYPE"', 'INTEGER') }}                     as APPLIES_TO_DOC_TYPE,
        {{ std_cast('"APPLIES_TO_DOC_NO_"', 'VARCHAR') }}                      as APPLIES_TO_DOC_NO,
        {{ std_cast('"BAL_ACCOUNT_NO_"', 'VARCHAR') }}                         as BAL_ACCOUNT_NO,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"REASON_CODE"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"EU_3_PARTY_TRADE"', 'INTEGER') }}                        as EU_3_PARTY_TRADE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT_COUNTRY_REGION_CODE"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME"', 'VARCHAR') }}                   as SELL_TO_CUSTOMER_NAME,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME_2"', 'VARCHAR') }}                 as SELL_TO_CUSTOMER_NAME_2,
        {{ std_cast('"SELL_TO_ADDRESS"', 'VARCHAR') }}                         as SELL_TO_ADDRESS,
        {{ std_cast('"SELL_TO_ADDRESS_2"', 'VARCHAR') }}                       as SELL_TO_ADDRESS_2,
        {{ std_cast('"SELL_TO_CITY"', 'VARCHAR') }}                            as SELL_TO_CITY,
        {{ std_cast('"SELL_TO_CONTACT"', 'VARCHAR') }}                         as SELL_TO_CONTACT,
        {{ std_cast('"BILL_TO_POST_CODE"', 'VARCHAR') }}                       as BILL_TO_POST_CODE,
        {{ std_cast('"BILL_TO_COUNTY"', 'VARCHAR') }}                          as BILL_TO_COUNTY,
        {{ std_cast('"BILL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as BILL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_POST_CODE"', 'VARCHAR') }}                       as SELL_TO_POST_CODE,
        {{ std_cast('"SELL_TO_COUNTY"', 'VARCHAR') }}                          as SELL_TO_COUNTY,
        {{ std_cast('"SELL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SELL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SHIP_TO_POST_CODE"', 'VARCHAR') }}                       as SHIP_TO_POST_CODE,
        {{ std_cast('"SHIP_TO_COUNTY"', 'VARCHAR') }}                          as SHIP_TO_COUNTY,
        {{ std_cast('"SHIP_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SHIP_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"BAL_ACCOUNT_TYPE"', 'INTEGER') }}                        as BAL_ACCOUNT_TYPE,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"CORRECTION"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"DOCUMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"EXTERNAL_DOCUMENT_NO_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PACKAGE_TRACKING_NO_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        {{ std_cast('"PRE_ASSIGNED_NO_SERIES"', 'VARCHAR') }}                  as PRE_ASSIGNED_NO_SERIES,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"ORDER_NO_SERIES"', 'VARCHAR') }}                         as ORDER_NO_SERIES,
        {{ std_cast('"PRE_ASSIGNED_NO_"', 'VARCHAR') }}                        as PRE_ASSIGNED_NO,
        {{ std_cast('"USER_ID"', 'VARCHAR') }}                                 as USER_ID,
        {{ std_cast('"SOURCE_CODE"', 'VARCHAR') }}                             as SOURCE_CODE,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT_BASE_DISCOUNT_"', 'NUMBER(38,5)') }}                 as VAT_BASE_DISCOUNT,
        {{ std_cast('"PREPAYMENT_NO_SERIES"', 'VARCHAR') }}                    as PREPAYMENT_NO_SERIES,
        {{ std_cast('"PREPAYMENT_INVOICE"', 'INTEGER') }}                      as PREPAYMENT_INVOICE,
        {{ std_cast('"PREPAYMENT_ORDER_NO_"', 'VARCHAR') }}                    as PREPAYMENT_ORDER_NO,
        {{ std_cast('"QUOTE_NO_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"DOCUMENT_EXCHANGE_IDENTIFIER"', 'VARCHAR') }}            as DOCUMENT_EXCHANGE_IDENTIFIER,
        {{ std_cast('"DOCUMENT_EXCHANGE_STATUS"', 'INTEGER') }}                as DOCUMENT_EXCHANGE_STATUS,
        {{ std_cast('"DOC_EXCH_ORIGINAL_IDENTIFIER"', 'VARCHAR') }}            as DOC_EXCH_ORIGINAL_IDENTIFIER,
        {{ std_cast('"COUPLED_TO_CRM"', 'INTEGER') }}                          as COUPLED_TO_CRM,
        {{ std_cast('"CREDIT_CARD_NO_"', 'VARCHAR') }}                         as CREDIT_CARD_NO,
        {{ std_cast('"DIRECT_DEBIT_MANDATE_ID"', 'VARCHAR') }}                 as DIRECT_DEBIT_MANDATE_ID,
        {{ std_cast('"CANCELED_BY"', 'VARCHAR') }}                             as CANCELED_BY,
        {{ std_cast('"CUST_LEDGER_ENTRY_NO_"', 'INTEGER') }}                   as CUST_LEDGER_ENTRY_NO,
        {{ std_cast('"CAMPAIGN_NO_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        {{ std_cast('"SELL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as SELL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as BILL_TO_CONTACT_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"GET_SHIPMENT_USED"', 'INTEGER') }}                       as GET_SHIPMENT_USED,
        {{ std_cast('"CONTAINER"', 'VARCHAR') }}                               as CONTAINER,
        {{ std_cast('"SEAL"', 'VARCHAR') }}                                    as SEAL,
        {{ std_cast('"TRUCK_LICENSE_PLATE"', 'VARCHAR') }}                     as TRUCK_LICENSE_PLATE,
        {{ std_cast('"DRIVER"', 'VARCHAR') }}                                  as DRIVER,
        {{ std_cast('"BANK_ACCOUNT_TO_TRANSFER"', 'VARCHAR') }}                as BANK_ACCOUNT_TO_TRANSFER,
        {{ std_cast('"MOTIVO_DEVOLUCION_EDI"', 'INTEGER') }}                   as MOTIVO_DEVOLUCION_EDI,
        {{ std_cast('"DEPARTAMENTO_EDI"', 'VARCHAR') }}                        as DEPARTAMENTO_EDI,
        {{ std_cast('"HEADER_DISCOUNT_"', 'NUMBER(38,5)') }}                   as HEADER_DISCOUNT,
        {{ std_cast('"RAPPEL_"', 'NUMBER(38,5)') }}                            as RAPPEL,
        {{ std_cast('"INVOICE_CANCELATION"', 'INTEGER') }}                     as INVOICE_CANCELATION,
        {{ std_cast('"CORRECTED_INVOICE_TYPE"', 'INTEGER') }}                  as CORRECTED_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_TYPE"', 'INTEGER') }}                         as SIMPLIFIED_TYPE,
        {{ std_cast('"FROM_TICKET_NO_"', 'VARCHAR') }}                         as FROM_TICKET_NO,
        {{ std_cast('"TO_TICKET_NO_"', 'VARCHAR') }}                           as TO_TICKET_NO,
        {{ std_cast('"APPLIES_TO_BILL_NO_"', 'VARCHAR') }}                     as APPLIES_TO_BILL_NO,
        {{ std_cast('"CUST_BANK_ACC_CODE"', 'VARCHAR') }}                      as CUST_BANK_ACC_CODE,
        {{ std_cast('"PAY_AT_CODE"', 'VARCHAR') }}                             as PAY_AT_CODE,
        {{ std_cast('"PESO_NETO"', 'NUMBER(38,5)') }}                          as PESO_NETO,
        {{ std_cast('"PESO_BRUTO"', 'NUMBER(38,5)') }}                         as PESO_BRUTO,
        {{ std_cast('"FORMA_PAGO_FACTURAPLUS"', 'VARCHAR') }}                  as FORMA_PAGO_FACTURAPLUS,
        {{ std_cast('"CASH_ENTRY"', 'INTEGER') }}                              as CASH_ENTRY,
        {{ std_cast('"SPETIAL_OPERATION_TYPE"', 'INTEGER') }}                  as SPETIAL_OPERATION_TYPE,
        {{ std_cast('"SPETIAL_OPERATION_CODE"', 'VARCHAR') }}                  as SPETIAL_OPERATION_CODE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        {{ std_cast('"INVOICE_DETAIL"', 'INTEGER') }}                          as INVOICE_DETAIL,
        {{ std_cast('"REVERTIDO_EN_NO_ABONO"', 'VARCHAR') }}                   as REVERTIDO_EN_NO_ABONO,
        {{ std_cast('"NO_FACTURA_ANULADA"', 'VARCHAR') }}                      as NO_FACTURA_ANULADA,
        {{ std_cast('"ANULACION_DE_FACTURA"', 'INTEGER') }}                    as ANULACION_DE_FACTURA,
        {{ std_cast('"REVERTIDA"', 'INTEGER') }}                               as REVERTIDA,
        {{ std_cast('"PRINT_BY_CONCEPT"', 'INTEGER') }}                        as PRINT_BY_CONCEPT,
        {{ std_cast('"ODS_JOB_TEMPLATE_CODE"', 'VARCHAR') }}                   as ODS_JOB_TEMPLATE_CODE,
        {{ std_cast('"OPERATION_DATE"', 'TIMESTAMP_NTZ') }}                    as OPERATION_DATE,
        {{ std_cast('"TO_DOCUMENT_NO_"', 'VARCHAR') }}                         as TO_DOCUMENT_NO,
        {{ std_cast('"FROM_DOCUMENT_NO_"', 'VARCHAR') }}                       as FROM_DOCUMENT_NO,
        {{ std_cast('"REGIME"', 'VARCHAR') }}                                  as REGIME,
        {{ std_cast('"SII_CORRECTION_TYPE"', 'VARCHAR') }}                     as SII_CORRECTION_TYPE,
        {{ std_cast('"SII_OPERATION_DESCRIPTION"', 'VARCHAR') }}               as SII_OPERATION_DESCRIPTION,
        {{ std_cast('"SII_INVOICE_TYPE"', 'VARCHAR') }}                        as SII_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_INVOICE"', 'INTEGER') }}                      as SIMPLIFIED_INVOICE,
        {{ std_cast('"SIMPLIFIED_ART_6_1_D"', 'INTEGER') }}                    as SIMPLIFIED_ART_6_1_D,
        {{ std_cast('"REFEXTERNA"', 'VARCHAR') }}                              as REFEXTERNA,
        {{ std_cast('"TAX_FREE"', 'INTEGER') }}                                as TAX_FREE,
        {{ std_cast('"NUM_REGISTRO_ACUERDO_FACT_"', 'VARCHAR') }}              as NUM_REGISTRO_ACUERDO_FACT,
        {{ std_cast('"EMITIDA_POR_TERCERO"', 'INTEGER') }}                     as EMITIDA_POR_TERCERO,
        {{ std_cast('"EMITIDA_POR_NORMATIVA_DEL_GAS"', 'INTEGER') }}           as EMITIDA_POR_NORMATIVA_DEL_GAS,
        {{ std_cast('"PAYMENT_DATE"', 'TIMESTAMP_NTZ') }}                      as PAYMENT_DATE,
        {{ std_cast('"PAYMENT_NO_DAYS"', 'NUMBER(38,5)') }}                    as PAYMENT_NO_DAYS,
        {{ std_cast('"IPAD_ORDER"', 'INTEGER') }}                              as IPAD_ORDER,
        {{ std_cast('"WITHOUT_PLASTIC_DECLARATION"', 'INTEGER') }}             as WITHOUT_PLASTIC_DECLARATION,
        {{ std_cast('"SCRAP_AMOUNT"', 'NUMBER(38,5)') }}                       as SCRAP_AMOUNT,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        NULL                                                                   as SELLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_NAME,
        NULL                                                                   as BILLTO_NAME_2,
        NULL                                                                   as BILLTO_ADDRESS,
        NULL                                                                   as BILLTO_ADDRESS_2,
        NULL                                                                   as BILLTO_CITY,
        NULL                                                                   as BILLTO_CONTACT,
        NULL                                                                   as SHIPTO_CODE,
        NULL                                                                   as SHIPTO_NAME,
        NULL                                                                   as SHIPTO_NAME_2,
        NULL                                                                   as SHIPTO_ADDRESS,
        NULL                                                                   as SHIPTO_ADDRESS_2,
        NULL                                                                   as SHIPTO_CITY,
        NULL                                                                   as SHIPTO_CONTACT,
        NULL                                                                   as APPLIESTO_DOC_TYPE,
        NULL                                                                   as APPLIESTO_DOC_NO,
        NULL                                                                   as EU_3PARTY_TRADE,
        NULL                                                                   as SELLTO_CUSTOMER_NAME,
        NULL                                                                   as SELLTO_CUSTOMER_NAME_2,
        NULL                                                                   as SELLTO_ADDRESS,
        NULL                                                                   as SELLTO_ADDRESS_2,
        NULL                                                                   as SELLTO_CITY,
        NULL                                                                   as SELLTO_CONTACT,
        NULL                                                                   as BILLTO_POST_CODE,
        NULL                                                                   as BILLTO_COUNTY,
        NULL                                                                   as BILLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SELLTO_POST_CODE,
        NULL                                                                   as SELLTO_COUNTY,
        NULL                                                                   as SELLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SHIPTO_POST_CODE,
        NULL                                                                   as SHIPTO_COUNTY,
        NULL                                                                   as SHIPTO_COUNTRY_REGION_CODE,
        NULL                                                                   as PREASSIGNED_NO_SERIES,
        NULL                                                                   as PREASSIGNED_NO,
        NULL                                                                   as INVOICE_DISCOUNT_CALCULATION,
        NULL                                                                   as INVOICE_DISCOUNT_VALUE,
        NULL                                                                   as PAYMENT_INSTRUCTIONS_NAME,
        NULL                                                                   as PAYMENT_SERVICE_SET_ID,
        NULL                                                                   as SELLTO_CONTACT_NO,
        NULL                                                                   as BILLTO_CONTACT_NO,
        NULL                                                                   as OPPORTUNITY_NO,
        NULL                                                                   as ID,
        NULL                                                                   as INVOICE_TYPE,
        NULL                                                                   as CR_MEMO_TYPE,
        NULL                                                                   as SPECIAL_SCHEME_CODE,
        NULL                                                                   as OPERATION_DESCRIPTION,
        NULL                                                                   as OPERATION_DESCRIPTION_2,
        NULL                                                                   as SUCCEEDED_COMPANY_NAME,
        NULL                                                                   as SUCCEEDED_VAT_REGISTRATION_NO,
        NULL                                                                   as APPLIESTO_BILL_NO,
        NULL                                                                   as PAYAT_CODE,
        NULL                                                                   as SELLTO_PHONE_NO,
        NULL                                                                   as SELLTO_EMAIL,
        NULL                                                                   as ID_TYPE,
        NULL                                                                   as IDPIRPF_IRPF_GROUP,
        NULL                                                                   as CERRADO,
        NULL                                                                   as IDPGND_SHIPTO_EXCL_SIG_RATE,
        NULL                                                                   as IF_OR_TYPE,
        NULL                                                                   as IF_DATA_1,
        NULL                                                                   as IF_DATA_2,
        NULL                                                                   as IF_DATA_3,
        NULL                                                                   as IF_DATA_4,
        NULL                                                                   as IF_DATA_5,
        NULL                                                                   as IF_ML_TIME,
        NULL                                                                   as IF_SAE_CERTIFICATION,
        NULL                                                                   as CO_ID_CONT,
        NULL                                                                   as CO_ID_PREC,
        NULL                                                                   as TOTALNETWEIGHT,
        NULL                                                                   as TOTALGROSSWEIGHT,
        NULL                                                                   as PACKAGESPALLETNUMBER,
        NULL                                                                   as PACKAGESNUMBER,
        NULL                                                                   as AIT_BILLING_ADDRESS_CODE,
        NULL                                                                   as IDPEDI_INVOIC,
        NULL                                                                   as IDPEDI_INVOIC_SENT,
        NULL                                                                   as AIT_CREATION_USER,
        NULL                                                                   as AIT_CREATION_DATETIME,
        NULL                                                                   as NO_MENSAJE_EDI,
        NULL                                                                   as COD_CADENA,
        NULL                                                                   as PROMOCIONES_POR,
        NULL                                                                   as COD_DTO_LINEA,
        NULL                                                                   as TIPO_PEDIDO,
        NULL                                                                   as TIPO_PUNTO_VERDE,
        NULL                                                                   as TIPO_RESIDUOS,
        NULL                                                                   as EDI_NO_EXPORTACIONES,
        NULL                                                                   as DTO_FACTURA,
        NULL                                                                   as COD_BANCO,
        NULL                                                                   as COMMISSION_SALESPERSON,
        NULL                                                                   as 2ND_SALESPERSON_CODE,
        NULL                                                                   as COMMISSION_2ND_SALESPERSON,
        NULL                                                                   as INCOME_TAX_RETENTION_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION,
        NULL                                                                   as INCOME_TAX_RETENTION_KEY,
        NULL                                                                   as INCOME_TAX_RETENTION_SUBKEY,
        NULL                                                                   as TEXTO_SUBVENCION,
        NULL                                                                   as TAX_FREE_VENDOR_NO,
        NULL                                                                   as CUSTOMER_SALES_DEPARTMENT,
        NULL                                                                   as EDI_BLOCKED,
        NULL                                                                   as DESADV_NO,
        NULL                                                                   as PLANNING_DELIVERY_DATE,
        NULL                                                                   as INVOICE_BLOCKED,
        NULL                                                                   as INTERCOMPANY_INVOICE,
        NULL                                                                   as CUSTOMER_RECEPTION_NO,
        NULL                                                                   as EDI_ORDER_NO,
        NULL                                                                   as SALES_SHIPMENT_NO,
        NULL                                                                   as FIX_SALES_PRICE,
        'COO'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
