{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_SALES_INVOICE_HEADER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_NAME"', 'VARCHAR') }}                            as BILL_TO_NAME,
        {{ std_cast('"BILL_TO_NAME_2"', 'VARCHAR') }}                          as BILL_TO_NAME_2,
        {{ std_cast('"BILL_TO_ADDRESS"', 'VARCHAR') }}                         as BILL_TO_ADDRESS,
        {{ std_cast('"BILL_TO_ADDRESS_2"', 'VARCHAR') }}                       as BILL_TO_ADDRESS_2,
        {{ std_cast('"BILL_TO_CITY"', 'VARCHAR') }}                            as BILL_TO_CITY,
        {{ std_cast('"BILL_TO_CONTACT"', 'VARCHAR') }}                         as BILL_TO_CONTACT,
        {{ std_cast('"YOUR_REFERENCE"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        {{ std_cast('"SHIP_TO_CODE"', 'VARCHAR') }}                            as SHIP_TO_CODE,
        {{ std_cast('"SHIP_TO_NAME"', 'VARCHAR') }}                            as SHIP_TO_NAME,
        {{ std_cast('"SHIP_TO_NAME_2"', 'VARCHAR') }}                          as SHIP_TO_NAME_2,
        {{ std_cast('"SHIP_TO_ADDRESS"', 'VARCHAR') }}                         as SHIP_TO_ADDRESS,
        {{ std_cast('"SHIP_TO_ADDRESS_2"', 'VARCHAR') }}                       as SHIP_TO_ADDRESS_2,
        {{ std_cast('"SHIP_TO_CITY"', 'VARCHAR') }}                            as SHIP_TO_CITY,
        {{ std_cast('"SHIP_TO_CONTACT"', 'VARCHAR') }}                         as SHIP_TO_CONTACT,
        {{ std_cast('"ORDER_DATE"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"POSTING_DESCRIPTION"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"DUE_DATE"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}                  as PAYMENT_DISCOUNT,
        {{ std_cast('"PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}                 as PMT_DISCOUNT_DATE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CURRENCY_FACTOR"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"ORDER_NO_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"NO_PRINTED"', 'INTEGER') }}                              as NO_PRINTED,
        {{ std_cast('"ON_HOLD"', 'VARCHAR') }}                                 as ON_HOLD,
        {{ std_cast('"APPLIES_TO_DOC_TYPE"', 'INTEGER') }}                     as APPLIES_TO_DOC_TYPE,
        {{ std_cast('"APPLIES_TO_DOC_NO_"', 'VARCHAR') }}                      as APPLIES_TO_DOC_NO,
        {{ std_cast('"BAL_ACCOUNT_NO_"', 'VARCHAR') }}                         as BAL_ACCOUNT_NO,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"REASON_CODE"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"EU_3_PARTY_TRADE"', 'INTEGER') }}                        as EU_3_PARTY_TRADE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT_COUNTRY_REGION_CODE"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME"', 'VARCHAR') }}                   as SELL_TO_CUSTOMER_NAME,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME_2"', 'VARCHAR') }}                 as SELL_TO_CUSTOMER_NAME_2,
        {{ std_cast('"SELL_TO_ADDRESS"', 'VARCHAR') }}                         as SELL_TO_ADDRESS,
        {{ std_cast('"SELL_TO_ADDRESS_2"', 'VARCHAR') }}                       as SELL_TO_ADDRESS_2,
        {{ std_cast('"SELL_TO_CITY"', 'VARCHAR') }}                            as SELL_TO_CITY,
        {{ std_cast('"SELL_TO_CONTACT"', 'VARCHAR') }}                         as SELL_TO_CONTACT,
        {{ std_cast('"BILL_TO_POST_CODE"', 'VARCHAR') }}                       as BILL_TO_POST_CODE,
        {{ std_cast('"BILL_TO_COUNTY"', 'VARCHAR') }}                          as BILL_TO_COUNTY,
        {{ std_cast('"BILL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as BILL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_POST_CODE"', 'VARCHAR') }}                       as SELL_TO_POST_CODE,
        {{ std_cast('"SELL_TO_COUNTY"', 'VARCHAR') }}                          as SELL_TO_COUNTY,
        {{ std_cast('"SELL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SELL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SHIP_TO_POST_CODE"', 'VARCHAR') }}                       as SHIP_TO_POST_CODE,
        {{ std_cast('"SHIP_TO_COUNTY"', 'VARCHAR') }}                          as SHIP_TO_COUNTY,
        {{ std_cast('"SHIP_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SHIP_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"BAL_ACCOUNT_TYPE"', 'INTEGER') }}                        as BAL_ACCOUNT_TYPE,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"CORRECTION"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"DOCUMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"EXTERNAL_DOCUMENT_NO_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PACKAGE_TRACKING_NO_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        {{ std_cast('"PRE_ASSIGNED_NO_SERIES"', 'VARCHAR') }}                  as PRE_ASSIGNED_NO_SERIES,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"ORDER_NO_SERIES"', 'VARCHAR') }}                         as ORDER_NO_SERIES,
        {{ std_cast('"PRE_ASSIGNED_NO_"', 'VARCHAR') }}                        as PRE_ASSIGNED_NO,
        {{ std_cast('"USER_ID"', 'VARCHAR') }}                                 as USER_ID,
        {{ std_cast('"SOURCE_CODE"', 'VARCHAR') }}                             as SOURCE_CODE,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT_BASE_DISCOUNT_"', 'NUMBER(38,5)') }}                 as VAT_BASE_DISCOUNT,
        {{ std_cast('"PREPAYMENT_NO_SERIES"', 'VARCHAR') }}                    as PREPAYMENT_NO_SERIES,
        {{ std_cast('"PREPAYMENT_INVOICE"', 'INTEGER') }}                      as PREPAYMENT_INVOICE,
        {{ std_cast('"PREPAYMENT_ORDER_NO_"', 'VARCHAR') }}                    as PREPAYMENT_ORDER_NO,
        {{ std_cast('"QUOTE_NO_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"PAYMENT_SERVICE_SET_ID"', 'INTEGER') }}                  as PAYMENT_SERVICE_SET_ID,
        {{ std_cast('"DOCUMENT_EXCHANGE_IDENTIFIER"', 'VARCHAR') }}            as DOCUMENT_EXCHANGE_IDENTIFIER,
        {{ std_cast('"DOCUMENT_EXCHANGE_STATUS"', 'INTEGER') }}                as DOCUMENT_EXCHANGE_STATUS,
        {{ std_cast('"DOC_EXCH_ORIGINAL_IDENTIFIER"', 'VARCHAR') }}            as DOC_EXCH_ORIGINAL_IDENTIFIER,
        {{ std_cast('"COUPLED_TO_CRM"', 'INTEGER') }}                          as COUPLED_TO_CRM,
        {{ std_cast('"DIRECT_DEBIT_MANDATE_ID"', 'VARCHAR') }}                 as DIRECT_DEBIT_MANDATE_ID,
        {{ std_cast('"CUST_LEDGER_ENTRY_NO_"', 'INTEGER') }}                   as CUST_LEDGER_ENTRY_NO,
        {{ std_cast('"CAMPAIGN_NO_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        {{ std_cast('"SELL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as SELL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as BILL_TO_CONTACT_NO,
        {{ std_cast('"OPPORTUNITY_NO_"', 'VARCHAR') }}                         as OPPORTUNITY_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"GET_SHIPMENT_USED"', 'INTEGER') }}                       as GET_SHIPMENT_USED,
        {{ std_cast('"INVOICE_TYPE"', 'INTEGER') }}                            as INVOICE_TYPE,
        {{ std_cast('"CR_MEMO_TYPE"', 'INTEGER') }}                            as CR_MEMO_TYPE,
        {{ std_cast('"SPECIAL_SCHEME_CODE"', 'INTEGER') }}                     as SPECIAL_SCHEME_CODE,
        {{ std_cast('"OPERATION_DESCRIPTION"', 'VARCHAR') }}                   as OPERATION_DESCRIPTION,
        {{ std_cast('"OPERATION_DESCRIPTION_2"', 'VARCHAR') }}                 as OPERATION_DESCRIPTION_2,
        {{ std_cast('"SUCCEEDED_COMPANY_NAME"', 'VARCHAR') }}                  as SUCCEEDED_COMPANY_NAME,
        {{ std_cast('"SUCCEEDED_VAT_REGISTRATION_NO_"', 'VARCHAR') }}          as SUCCEEDED_VAT_REGISTRATION_NO,
        {{ std_cast('"NO_MENSAJE_EDI"', 'VARCHAR') }}                          as NO_MENSAJE_EDI,
        {{ std_cast('"COD_CADENA"', 'VARCHAR') }}                              as COD_CADENA,
        {{ std_cast('"PROMOCIONES_POR"', 'INTEGER') }}                         as PROMOCIONES_POR,
        {{ std_cast('"COD_DTO_LINEA"', 'VARCHAR') }}                           as COD_DTO_LINEA,
        {{ std_cast('"TIPO_PEDIDO"', 'INTEGER') }}                             as TIPO_PEDIDO,
        {{ std_cast('"TIPO_PUNTO_VERDE"', 'INTEGER') }}                        as TIPO_PUNTO_VERDE,
        {{ std_cast('"TIPO_RESIDUOS"', 'INTEGER') }}                           as TIPO_RESIDUOS,
        {{ std_cast('"EDI_NO_EXPORTACIONES"', 'INTEGER') }}                    as EDI_NO_EXPORTACIONES,
        {{ std_cast('"APPLIES_TO_BILL_NO_"', 'VARCHAR') }}                     as APPLIES_TO_BILL_NO,
        {{ std_cast('"CUST_BANK_ACC_CODE"', 'VARCHAR') }}                      as CUST_BANK_ACC_CODE,
        {{ std_cast('"PAY_AT_CODE"', 'VARCHAR') }}                             as PAY_AT_CODE,
        {{ std_cast('"_DTO_FACTURA"', 'NUMBER(38,5)') }}                       as DTO_FACTURA,
        {{ std_cast('"COD_BANCO"', 'VARCHAR') }}                               as COD_BANCO,
        {{ std_cast('"_COMMISSION_SALESPERSON"', 'NUMBER(38,5)') }}            as COMMISSION_SALESPERSON,
        {{ std_cast('"_2ND_SALESPERSON_CODE"', 'VARCHAR') }}                   as "2nd_salesperson_code",
        {{ std_cast('"_COMMISSION_2ND_SALESPERSON"', 'NUMBER(38,5)') }}        as COMMISSION_2ND_SALESPERSON,
        {{ std_cast('"INCOME_TAX_RETENTION_CODE"', 'VARCHAR') }}               as INCOME_TAX_RETENTION_CODE,
        {{ std_cast('"INCOME_TAX_RETENTION_"', 'NUMBER(38,5)') }}              as INCOME_TAX_RETENTION,
        {{ std_cast('"INCOME_TAX_RETENTION_KEY"', 'VARCHAR') }}                as INCOME_TAX_RETENTION_KEY,
        {{ std_cast('"INCOME_TAX_RETENTION_SUBKEY"', 'VARCHAR') }}             as INCOME_TAX_RETENTION_SUBKEY,
        {{ std_cast('"TEXTO_SUBVENCION"', 'VARCHAR') }}                        as TEXTO_SUBVENCION,
        {{ std_cast('"SPETIAL_OPERATION_CODE"', 'VARCHAR') }}                  as SPETIAL_OPERATION_CODE,
        {{ std_cast('"SPETIAL_OPERATION_TYPE"', 'INTEGER') }}                  as SPETIAL_OPERATION_TYPE,
        {{ std_cast('"INVOICE_CANCELATION"', 'INTEGER') }}                     as INVOICE_CANCELATION,
        {{ std_cast('"SIMPLIFIED_INVOICE"', 'INTEGER') }}                      as SIMPLIFIED_INVOICE,
        {{ std_cast('"CORRECTED_INVOICE_TYPE"', 'INTEGER') }}                  as CORRECTED_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_TYPE"', 'INTEGER') }}                         as SIMPLIFIED_TYPE,
        {{ std_cast('"FROM_TICKET_NO_"', 'VARCHAR') }}                         as FROM_TICKET_NO,
        {{ std_cast('"TO_TICKET_NO_"', 'VARCHAR') }}                           as TO_TICKET_NO,
        {{ std_cast('"TAX_FREE"', 'INTEGER') }}                                as TAX_FREE,
        {{ std_cast('"TAX_FREE_VENDOR_NO_"', 'VARCHAR') }}                     as TAX_FREE_VENDOR_NO,
        {{ std_cast('"CUSTOMER_SALES_DEPARTMENT"', 'VARCHAR') }}               as CUSTOMER_SALES_DEPARTMENT,
        {{ std_cast('"EDI_BLOCKED"', 'INTEGER') }}                             as EDI_BLOCKED,
        {{ std_cast('"DESADV_NO_"', 'VARCHAR') }}                              as DESADV_NO,
        {{ std_cast('"PLANNING_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}            as PLANNING_DELIVERY_DATE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        {{ std_cast('"INVOICE_BLOCKED"', 'INTEGER') }}                         as INVOICE_BLOCKED,
        {{ std_cast('"INTERCOMPANY_INVOICE"', 'INTEGER') }}                    as INTERCOMPANY_INVOICE,
        {{ std_cast('"CUSTOMER_RECEPTION_NO_"', 'VARCHAR') }}                  as CUSTOMER_RECEPTION_NO,
        {{ std_cast('"EDI_ORDER_NO_"', 'VARCHAR') }}                           as EDI_ORDER_NO,
        {{ std_cast('"SALES_SHIPMENT_NO_"', 'VARCHAR') }}                      as SALES_SHIPMENT_NO,
        {{ std_cast('"FIX_SALES_PRICE"', 'INTEGER') }}                         as FIX_SALES_PRICE,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'FRI'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
