{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_DELISANO', materialized='view', tags=['bronze','batch','DELISANO']) }}

{% set src_ref = source('bronze_delisano', 'V_DL_SALES_INVOICE_LINES') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"timestamp"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"Document No_"', 'VARCHAR') }}                            as DOCUMENT_NO,
        {{ std_cast('"Line No_"', 'INTEGER') }}                                as LINE_NO,
        NULL                                                                   as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"Type"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"No_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"Location Code"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"Posting Group"', 'VARCHAR') }}                           as POSTING_GROUP,
        {{ std_cast('"Shipment Date"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"Description"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"Description 2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"Unit of Measure"', 'VARCHAR') }}                         as UNIT_OF_MEASURE,
        {{ std_cast('"Quantity"', 'NUMBER(38,5)') }}                           as QUANTITY,
        {{ std_cast('"Unit Price"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"Unit Cost (LCY)"', 'NUMBER(38,5)') }}                    as UNIT_COST_LCY,
        {{ std_cast('"VAT _"', 'NUMBER(38,5)') }}                              as VAT,
        {{ std_cast('"Line Discount _"', 'NUMBER(38,5)') }}                    as LINE_DISCOUNT,
        {{ std_cast('"Line Discount Amount"', 'NUMBER(38,5)') }}               as LINE_DISCOUNT_AMOUNT,
        {{ std_cast('"Amount"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"Amount Including VAT"', 'NUMBER(38,5)') }}               as AMOUNT_INCLUDING_VAT,
        {{ std_cast('"Allow Invoice Disc_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"Gross Weight"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"Net Weight"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"Units per Parcel"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"Unit Volume"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"Appl_-to Item Entry"', 'INTEGER') }}                     as APPL_TO_ITEM_ENTRY,
        {{ std_cast('"Shortcut Dimension 1 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"Shortcut Dimension 2 Code"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"Customer Price Group"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"Job No_"', 'VARCHAR') }}                                 as JOB_NO,
        {{ std_cast('"Work Type Code"', 'VARCHAR') }}                          as WORK_TYPE_CODE,
        {{ std_cast('"Shipment No_"', 'VARCHAR') }}                            as SHIPMENT_NO,
        {{ std_cast('"Shipment Line No_"', 'INTEGER') }}                       as SHIPMENT_LINE_NO,
        NULL                                                                   as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"Inv_ Discount Amount"', 'NUMBER(38,5)') }}               as INV_DISCOUNT_AMOUNT,
        {{ std_cast('"Drop Shipment"', 'INTEGER') }}                           as DROP_SHIPMENT,
        {{ std_cast('"Gen_ Bus_ Posting Group"', 'VARCHAR') }}                 as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"Gen_ Prod_ Posting Group"', 'VARCHAR') }}                as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"VAT Calculation Type"', 'INTEGER') }}                    as VAT_CALCULATION_TYPE,
        {{ std_cast('"Transaction Type"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"Transport Method"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"Attached to Line No_"', 'INTEGER') }}                    as ATTACHED_TO_LINE_NO,
        {{ std_cast('"Exit Point"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"Area"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"Transaction Specification"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"Tax Category"', 'VARCHAR') }}                            as TAX_CATEGORY,
        {{ std_cast('"Tax Area Code"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"Tax Liable"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"Tax Group Code"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT Clause Code"', 'VARCHAR') }}                         as VAT_CLAUSE_CODE,
        {{ std_cast('"VAT Bus_ Posting Group"', 'VARCHAR') }}                  as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT Prod_ Posting Group"', 'VARCHAR') }}                 as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"Blanket Order No_"', 'VARCHAR') }}                       as BLANKET_ORDER_NO,
        {{ std_cast('"Blanket Order Line No_"', 'INTEGER') }}                  as BLANKET_ORDER_LINE_NO,
        {{ std_cast('"VAT Base Amount"', 'NUMBER(38,5)') }}                    as VAT_BASE_AMOUNT,
        {{ std_cast('"Unit Cost"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        NULL                                                                   as SYSTEM_CREATED_ENTRY,
        {{ std_cast('"Line Amount"', 'NUMBER(38,5)') }}                        as LINE_AMOUNT,
        {{ std_cast('"VAT Difference"', 'NUMBER(38,5)') }}                     as VAT_DIFFERENCE,
        {{ std_cast('"VAT Identifier"', 'VARCHAR') }}                          as VAT_IDENTIFIER,
        {{ std_cast('"IC Partner Ref_ Type"', 'INTEGER') }}                    as IC_PARTNER_REF_TYPE,
        {{ std_cast('"IC Partner Reference"', 'VARCHAR') }}                    as IC_PARTNER_REFERENCE,
        {{ std_cast('"Prepayment Line"', 'INTEGER') }}                         as PREPAYMENT_LINE,
        {{ std_cast('"IC Partner Code"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"Posting Date"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"Dimension Set ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"Job Task No_"', 'VARCHAR') }}                            as JOB_TASK_NO,
        {{ std_cast('"Job Contract Entry No_"', 'INTEGER') }}                  as JOB_CONTRACT_ENTRY_NO,
        {{ std_cast('"Deferral Code"', 'VARCHAR') }}                           as DEFERRAL_CODE,
        {{ std_cast('"Variant Code"', 'VARCHAR') }}                            as VARIANT_CODE,
        {{ std_cast('"Bin Code"', 'VARCHAR') }}                                as BIN_CODE,
        {{ std_cast('"Qty_ per Unit of Measure"', 'NUMBER(38,5)') }}           as QTY_PER_UNIT_OF_MEASURE,
        {{ std_cast('"Unit of Measure Code"', 'VARCHAR') }}                    as UNIT_OF_MEASURE_CODE,
        {{ std_cast('"Quantity (Base)"', 'NUMBER(38,5)') }}                    as QUANTITY_BASE,
        {{ std_cast('"FA Posting Date"', 'TIMESTAMP_NTZ') }}                   as FA_POSTING_DATE,
        {{ std_cast('"Depreciation Book Code"', 'VARCHAR') }}                  as DEPRECIATION_BOOK_CODE,
        {{ std_cast('"Depr_ until FA Posting Date"', 'INTEGER') }}             as DEPR_UNTIL_FA_POSTING_DATE,
        {{ std_cast('"Duplicate in Depreciation Book"', 'VARCHAR') }}          as DUPLICATE_IN_DEPRECIATION_BOOK,
        {{ std_cast('"Use Duplication List"', 'INTEGER') }}                    as USE_DUPLICATION_LIST,
        {{ std_cast('"Responsibility Center"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        NULL                                                                   as CROSS_REFERENCE_NO,
        {{ std_cast('"Unit of Measure (Cross Ref_)"', 'VARCHAR') }}            as UNIT_OF_MEASURE_CROSS_REF,
        NULL                                                                   as CROSS_REFERENCE_TYPE,
        NULL                                                                   as CROSS_REFERENCE_TYPE_NO,
        {{ std_cast('"Item Category Code"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"Nonstock"', 'INTEGER') }}                                as NONSTOCK,
        {{ std_cast('"Purchasing Code"', 'VARCHAR') }}                         as PURCHASING_CODE,
        {{ std_cast('"Product Group Code"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"Appl_-from Item Entry"', 'INTEGER') }}                   as APPL_FROM_ITEM_ENTRY,
        {{ std_cast('"Return Reason Code"', 'VARCHAR') }}                      as RETURN_REASON_CODE,
        {{ std_cast('"Allow Line Disc_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"Customer Disc_ Group"', 'VARCHAR') }}                    as CUSTOMER_DISC_GROUP,
        NULL                                                                   as PMT_DISC_GIVEN_AMOUNT,
        {{ std_cast('"EC _"', 'NUMBER(38,5)') }}                               as EC,
        {{ std_cast('"EC Difference"', 'NUMBER(38,5)') }}                      as EC_DIFFERENCE,
        NULL                                                                   as MURANO_CODE,
        NULL                                                                   as MIGRATION_LOT_NO,
        NULL                                                                   as NO_ALBARAN_VENTA,
        NULL                                                                   as NO_LINEA_ALBARAN_VENTA,
        NULL                                                                   as COD_VENDEDOR_1,
        NULL                                                                   as COD_VENDEDOR_2,
        NULL                                                                   as COD_VENDEDOR_3,
        NULL                                                                   as COM_1,
        NULL                                                                   as COM_2,
        NULL                                                                   as COM_3,
        NULL                                                                   as DTO_1,
        NULL                                                                   as TIPO_DTO_2,
        NULL                                                                   as DTO_2,
        NULL                                                                   as TIPO_DTO_3,
        NULL                                                                   as DTO_3,
        NULL                                                                   as TIPO_DTO_4,
        NULL                                                                   as DTO_4,
        NULL                                                                   as TIPO_DTO_5,
        NULL                                                                   as DTO_5,
        NULL                                                                   as NEGRILLA,
        NULL                                                                   as BASE_RAPPEL,
        NULL                                                                   as IMPORTE_PROVISIONADO,
        NULL                                                                   as IMPORTE_DESPROVISIONADO,
        NULL                                                                   as NO_CUENTA_PROVISION_VENTA,
        NULL                                                                   as NO_CUENTA_PROVISION_CLIENTE,
        NULL                                                                   as CLAIM_CODE,
        NULL                                                                   as W_ITEM_ENTRIES,
        NULL                                                                   as REAL_SHIPMENT_DATE,
        NULL                                                                   as CREATION_DATE,
        NULL                                                                   as PLATES_SHIPPED,
        NULL                                                                   as VAT_BREAKDOWN,
        NULL                                                                   as TYPE_BREAKDOWN,
        NULL                                                                   as CADASTRAL_REFERENCE,
        NULL                                                                   as PROPERTY_SITUATION,
        NULL                                                                   as Q_CONFIRMADA_RECADV,
        NULL                                                                   as PLASTIC_LINE,
        NULL                                                                   as TARIFF_NO,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        {{ std_cast('"Sell-to Customer No_"', 'VARCHAR') }}                    as SELLTO_CUSTOMER_NO,
        {{ std_cast('"Order No_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"Order Line No_"', 'INTEGER') }}                          as ORDER_LINE_NO,
        {{ std_cast('"Bill-to Customer No_"', 'VARCHAR') }}                    as BILLTO_CUSTOMER_NO,
        {{ std_cast('"System-Created Entry"', 'INTEGER') }}                    as SYSTEMCREATED_ENTRY,
        {{ std_cast('"Pmt_ Discount Amount"', 'NUMBER(38,5)') }}               as PMT_DISCOUNT_AMOUNT,
        {{ std_cast('"Line Discount Calculation"', 'INTEGER') }}               as LINE_DISCOUNT_CALCULATION,
        {{ std_cast('"Cross-Reference No_"', 'VARCHAR') }}                     as CROSSREFERENCE_NO,
        {{ std_cast('"Cross-Reference Type"', 'INTEGER') }}                    as CROSSREFERENCE_TYPE,
        {{ std_cast('"Cross-Reference Type No_"', 'VARCHAR') }}                as CROSSREFERENCE_TYPE_NO,
        {{ std_cast('"Price description"', 'VARCHAR') }}                       as PRICE_DESCRIPTION,
        {{ std_cast('"Pmt_ Disc_ Given Amount (Old)"', 'NUMBER(38,5)') }}      as PMT_DISC_GIVEN_AMOUNT_OLD,
        {{ std_cast('"IDPIRPF IRPF Group"', 'VARCHAR') }}                      as IDPIRPF_IRPF_GROUP,
        {{ std_cast('"IDPIRPF IRPF Amount"', 'NUMBER(38,5)') }}                as IDPIRPF_IRPF_AMOUNT,
        {{ std_cast('"IDPIRPF IRPF _"', 'NUMBER(38,5)') }}                     as IDPIRPF_IRPF,
        {{ std_cast('"IDPIRPF IRPF Base Amount"', 'NUMBER(38,5)') }}           as IDPIRPF_IRPF_BASE_AMOUNT,
        {{ std_cast('"IDPVUM Quantity"', 'NUMBER(38,5)') }}                    as IDPVUM_QUANTITY,
        {{ std_cast('"IDPVUM Unit of Measure Code"', 'VARCHAR') }}             as IDPVUM_UNIT_OF_MEASURE_CODE,
        {{ std_cast('"IDPVUM Unit Price"', 'NUMBER(38,5)') }}                  as IDPVUM_UNIT_PRICE,
        {{ std_cast('"IDPVUM Price in VUM"', 'INTEGER') }}                     as IDPVUM_PRICE_IN_VUM,
        {{ std_cast('"IDPVUM VUM Per Unit"', 'NUMBER(38,5)') }}                as IDPVUM_VUM_PER_UNIT,
        {{ std_cast('"Cerrado"', 'INTEGER') }}                                 as CERRADO,
        {{ std_cast('"TempQty"', 'NUMBER(38,5)') }}                            as TEMPQTY,
        {{ std_cast('"Original Quantity"', 'NUMBER(38,5)') }}                  as ORIGINAL_QUANTITY,
        {{ std_cast('"Original Quantity UMV"', 'NUMBER(38,5)') }}              as ORIGINAL_QUANTITY_UMV,
        {{ std_cast('"IDPGND SIG Amount"', 'NUMBER(38,5)') }}                  as IDPGND_SIG_AMOUNT,
        {{ std_cast('"IDPGND SIG Rate"', 'NUMBER(38,5)') }}                    as IDPGND_SIG_RATE,
        {{ std_cast('"IDPGND SIG"', 'INTEGER') }}                              as IDPGND_SIG,
        {{ std_cast('"IDPGND Posting Date Shipment"', 'TIMESTAMP_NTZ') }}      as IDPGND_POSTING_DATE_SHIPMENT,
        {{ std_cast('"IDPGND Shipment Date Shipment"', 'TIMESTAMP_NTZ') }}     as IDPGND_SHIPMENT_DATE_SHIPMENT,
        {{ std_cast('"IDPGND Req_ Del_ Date Shipment"', 'TIMESTAMP_NTZ') }}    as IDPGND_REQ_DEL_DATE_SHIPMENT,
        {{ std_cast('"IDPGND Packaging Format No_"', 'VARCHAR') }}             as IDPGND_PACKAGING_FORMAT_NO,
        {{ std_cast('"IF_OR_TYPE"', 'VARCHAR') }}                              as IF_OR_TYPE,
        {{ std_cast('"IF_UNIT_PRICE_CODE"', 'VARCHAR') }}                      as IF_UNIT_PRICE_CODE,
        {{ std_cast('"IF_NUM_BOXES_NEEDED"', 'NUMBER(38,5)') }}                as IF_NUM_BOXES_NEEDED,
        {{ std_cast('"IF_NUM_CONT_NEEDED"', 'NUMBER(38,5)') }}                 as IF_NUM_CONT_NEEDED,
        {{ std_cast('"IF_DUN14"', 'VARCHAR') }}                                as IF_DUN14,
        NULL                                                                   as COD_CADENA,
        NULL                                                                   as PROMOCIONES_POR,
        NULL                                                                   as COMISIONES_POR,
        NULL                                                                   as CODIGO_EMBALAJE,
        NULL                                                                   as CANTIDAD_EMBALAJE,
        NULL                                                                   as CANTIDAD_UNIDADES,
        NULL                                                                   as CANTIDAD_KILOS,
        NULL                                                                   as NO_PRESENTACION,
        NULL                                                                   as DESCRIPCION_PRESENTACION,
        NULL                                                                   as OBSERVACIONES,
        NULL                                                                   as MOTIVO_DEVOLUCION,
        NULL                                                                   as SERVICIO,
        NULL                                                                   as PRECIO_PUNTO_VERDE_CDAD,
        NULL                                                                   as UNIDAD_MEDIDA_PUNTO_VERDE,
        NULL                                                                   as IMPORTE_PUNTO_VERDE,
        NULL                                                                   as GRUPO_RESIDUOS,
        NULL                                                                   as PRECIO_RESIDUOS_CDAD,
        NULL                                                                   as UNIDAD_MEDIDA_RESIDUOS,
        NULL                                                                   as IMPORTE_RESIDUOS,
        NULL                                                                   as INCOME_TAX_RETENTION_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION,
        NULL                                                                   as INCOME_TAX_BASE,
        NULL                                                                   as SALESPERSON_CODE,
        NULL                                                                   as COMMISSION_SALESPERSON,
        NULL                                                                   as 2ND_SALESPERSON_CODE,
        NULL                                                                   as COMMISSION_2ND_SALESPERSON,
        NULL                                                                   as SPECIAL_LINE_TYPE,
        NULL                                                                   as SALES_SHIPMENT_NO,
        NULL                                                                   as SALES_SHIPMENT_LINE_NO,
        NULL                                                                   as EDI_POSITION,
        NULL                                                                   as RECADCV_QUANTITY,
        NULL                                                                   as EDI_POSITION_SUBLINE,
        NULL                                                                   as GLN,
        NULL                                                                   as EDI_PRICE,
        NULL                                                                   as EDI_DISCOUNT,
        'DLS'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY document_no, line_no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
