{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_SALES_SHIPMENT_LINE') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"DOCUMENT_NO_"', 'VARCHAR') }}                            as DOCUMENT_NO,
        {{ std_cast('"LINE_NO_"', 'INTEGER') }}                                as LINE_NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"TYPE"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"POSTING_GROUP"', 'VARCHAR') }}                           as POSTING_GROUP,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"DESCRIPTION"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"DESCRIPTION_2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"UNIT_OF_MEASURE"', 'VARCHAR') }}                         as UNIT_OF_MEASURE,
        {{ std_cast('"QUANTITY"', 'NUMBER(38,5)') }}                           as QUANTITY,
        {{ std_cast('"UNIT_PRICE"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"UNIT_COST_LCY"', 'NUMBER(38,5)') }}                      as UNIT_COST_LCY,
        {{ std_cast('"VAT_"', 'NUMBER(38,5)') }}                               as VAT,
        {{ std_cast('"LINE_DISCOUNT_"', 'NUMBER(38,5)') }}                     as LINE_DISCOUNT,
        {{ std_cast('"ALLOW_INVOICE_DISC_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"GROSS_WEIGHT"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"NET_WEIGHT"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"UNITS_PER_PARCEL"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"UNIT_VOLUME"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"APPL_TO_ITEM_ENTRY"', 'INTEGER') }}                      as APPL_TO_ITEM_ENTRY,
        {{ std_cast('"ITEM_SHPT_ENTRY_NO_"', 'INTEGER') }}                     as ITEM_SHPT_ENTRY_NO,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"JOB_NO_"', 'VARCHAR') }}                                 as JOB_NO,
        {{ std_cast('"WORK_TYPE_CODE"', 'VARCHAR') }}                          as WORK_TYPE_CODE,
        {{ std_cast('"QTY_SHIPPED_NOT_INVOICED"', 'NUMBER(38,5)') }}           as QTY_SHIPPED_NOT_INVOICED,
        {{ std_cast('"QUANTITY_INVOICED"', 'NUMBER(38,5)') }}                  as QUANTITY_INVOICED,
        {{ std_cast('"ORDER_NO_"', 'VARCHAR') }}                               as ORDER_NO,
        {{ std_cast('"ORDER_LINE_NO_"', 'INTEGER') }}                          as ORDER_LINE_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"PURCHASE_ORDER_NO_"', 'VARCHAR') }}                      as PURCHASE_ORDER_NO,
        {{ std_cast('"PURCH_ORDER_LINE_NO_"', 'INTEGER') }}                    as PURCH_ORDER_LINE_NO,
        {{ std_cast('"DROP_SHIPMENT"', 'INTEGER') }}                           as DROP_SHIPMENT,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GEN_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"VAT_CALCULATION_TYPE"', 'INTEGER') }}                    as VAT_CALCULATION_TYPE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"ATTACHED_TO_LINE_NO_"', 'INTEGER') }}                    as ATTACHED_TO_LINE_NO,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"TAX_GROUP_CODE"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"BLANKET_ORDER_NO_"', 'VARCHAR') }}                       as BLANKET_ORDER_NO,
        {{ std_cast('"BLANKET_ORDER_LINE_NO_"', 'INTEGER') }}                  as BLANKET_ORDER_LINE_NO,
        {{ std_cast('"VAT_BASE_AMOUNT"', 'NUMBER(38,5)') }}                    as VAT_BASE_AMOUNT,
        {{ std_cast('"UNIT_COST"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"AUTHORIZED_FOR_CREDIT_CARD"', 'INTEGER') }}              as AUTHORIZED_FOR_CREDIT_CARD,
        {{ std_cast('"JOB_TASK_NO_"', 'VARCHAR') }}                            as JOB_TASK_NO,
        {{ std_cast('"JOB_CONTRACT_ENTRY_NO_"', 'INTEGER') }}                  as JOB_CONTRACT_ENTRY_NO,
        {{ std_cast('"VARIANT_CODE"', 'VARCHAR') }}                            as VARIANT_CODE,
        {{ std_cast('"BIN_CODE"', 'VARCHAR') }}                                as BIN_CODE,
        {{ std_cast('"QTY_PER_UNIT_OF_MEASURE"', 'NUMBER(38,5)') }}            as QTY_PER_UNIT_OF_MEASURE,
        {{ std_cast('"UNIT_OF_MEASURE_CODE"', 'VARCHAR') }}                    as UNIT_OF_MEASURE_CODE,
        {{ std_cast('"QUANTITY_BASE"', 'NUMBER(38,5)') }}                      as QUANTITY_BASE,
        {{ std_cast('"QTY_INVOICED_BASE"', 'NUMBER(38,5)') }}                  as QTY_INVOICED_BASE,
        {{ std_cast('"FA_POSTING_DATE"', 'TIMESTAMP_NTZ') }}                   as FA_POSTING_DATE,
        {{ std_cast('"DEPRECIATION_BOOK_CODE"', 'VARCHAR') }}                  as DEPRECIATION_BOOK_CODE,
        {{ std_cast('"DEPR_UNTIL_FA_POSTING_DATE"', 'INTEGER') }}              as DEPR_UNTIL_FA_POSTING_DATE,
        {{ std_cast('"DUPLICATE_IN_DEPRECIATION_BOOK"', 'VARCHAR') }}          as DUPLICATE_IN_DEPRECIATION_BOOK,
        {{ std_cast('"USE_DUPLICATION_LIST"', 'INTEGER') }}                    as USE_DUPLICATION_LIST,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"CROSS_REFERENCE_NO_"', 'VARCHAR') }}                     as CROSS_REFERENCE_NO,
        {{ std_cast('"UNIT_OF_MEASURE_CROSS_REF_"', 'VARCHAR') }}              as UNIT_OF_MEASURE_CROSS_REF,
        {{ std_cast('"CROSS_REFERENCE_TYPE"', 'INTEGER') }}                    as CROSS_REFERENCE_TYPE,
        {{ std_cast('"CROSS_REFERENCE_TYPE_NO_"', 'VARCHAR') }}                as CROSS_REFERENCE_TYPE_NO,
        {{ std_cast('"ITEM_CATEGORY_CODE"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"NONSTOCK"', 'INTEGER') }}                                as NONSTOCK,
        {{ std_cast('"PURCHASING_CODE"', 'VARCHAR') }}                         as PURCHASING_CODE,
        {{ std_cast('"PRODUCT_GROUP_CODE"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"REQUESTED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}           as REQUESTED_DELIVERY_DATE,
        {{ std_cast('"PROMISED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}            as PROMISED_DELIVERY_DATE,
        {{ std_cast('"SHIPPING_TIME"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"OUTBOUND_WHSE_HANDLING_TIME"', 'VARCHAR') }}             as OUTBOUND_WHSE_HANDLING_TIME,
        {{ std_cast('"PLANNED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}             as PLANNED_DELIVERY_DATE,
        {{ std_cast('"PLANNED_SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}             as PLANNED_SHIPMENT_DATE,
        {{ std_cast('"APPL_FROM_ITEM_ENTRY"', 'INTEGER') }}                    as APPL_FROM_ITEM_ENTRY,
        {{ std_cast('"ITEM_CHARGE_BASE_AMOUNT"', 'NUMBER(38,5)') }}            as ITEM_CHARGE_BASE_AMOUNT,
        {{ std_cast('"CORRECTION"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"RETURN_REASON_CODE"', 'VARCHAR') }}                      as RETURN_REASON_CODE,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"MURANO_CODE"', 'VARCHAR') }}                             as MURANO_CODE,
        {{ std_cast('"KG"', 'NUMBER(38,5)') }}                                 as KG,
        {{ std_cast('"BOXES"', 'NUMBER(38,5)') }}                              as BOXES,
        {{ std_cast('"PALLETS"', 'NUMBER(38,5)') }}                            as PALLETS,
        {{ std_cast('"ROWS_PALET"', 'NUMBER(38,5)') }}                         as ROWS_PALET,
        {{ std_cast('"SELECTED_UNIT_TYPE"', 'INTEGER') }}                      as SELECTED_UNIT_TYPE,
        {{ std_cast('"_COM_1"', 'NUMBER(38,5)') }}                             as COM_1,
        {{ std_cast('"_COM_2"', 'NUMBER(38,5)') }}                             as COM_2,
        {{ std_cast('"_COM_3"', 'NUMBER(38,5)') }}                             as COM_3,
        {{ std_cast('"AMOUNT"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"AMOUNT_INCLUDING_VAT"', 'NUMBER(38,5)') }}               as AMOUNT_INCLUDING_VAT,
        {{ std_cast('"LINE_DISC_AMOUNT"', 'NUMBER(38,5)') }}                   as LINE_DISC_AMOUNT,
        {{ std_cast('"PMT_DISC_GIVEN_AMOUNT"', 'NUMBER(38,5)') }}              as PMT_DISC_GIVEN_AMOUNT,
        {{ std_cast('"INV_DISCOUNT_AMOUNT"', 'NUMBER(38,5)') }}                as INV_DISCOUNT_AMOUNT,
        {{ std_cast('"LINE_AMOUNT"', 'NUMBER(38,5)') }}                        as LINE_AMOUNT,
        {{ std_cast('"_DTO_1"', 'NUMBER(38,5)') }}                             as DTO_1,
        {{ std_cast('"TIPO_DTO_2"', 'INTEGER') }}                              as TIPO_DTO_2,
        {{ std_cast('"_DTO_2"', 'NUMBER(38,5)') }}                             as DTO_2,
        {{ std_cast('"TIPO_DTO_3"', 'INTEGER') }}                              as TIPO_DTO_3,
        {{ std_cast('"_DTO_3"', 'NUMBER(38,5)') }}                             as DTO_3,
        {{ std_cast('"TIPO_DTO_4"', 'INTEGER') }}                              as TIPO_DTO_4,
        {{ std_cast('"_DTO_4"', 'NUMBER(38,5)') }}                             as DTO_4,
        {{ std_cast('"TIPO_DTO_5"', 'INTEGER') }}                              as TIPO_DTO_5,
        {{ std_cast('"_DTO_5"', 'NUMBER(38,5)') }}                             as DTO_5,
        {{ std_cast('"FACTURADO_COMPLETAMENTE"', 'INTEGER') }}                 as FACTURADO_COMPLETAMENTE,
        {{ std_cast('"PRECIO_ORIGEN"', 'NUMBER(38,5)') }}                      as PRECIO_ORIGEN,
        {{ std_cast('"_DTO_ORIGEN"', 'NUMBER(38,5)') }}                        as DTO_ORIGEN,
        {{ std_cast('"IMPORTE_PROVISIONADO"', 'NUMBER(38,5)') }}               as IMPORTE_PROVISIONADO,
        {{ std_cast('"IMPORTE_DESPROVISIONADO"', 'NUMBER(38,5)') }}            as IMPORTE_DESPROVISIONADO,
        {{ std_cast('"NO_CUENTA_PROVISION_VENTA"', 'VARCHAR') }}               as NO_CUENTA_PROVISION_VENTA,
        {{ std_cast('"NO_CUENTA_PROVISION_CLIENTE"', 'VARCHAR') }}             as NO_CUENTA_PROVISION_CLIENTE,
        {{ std_cast('"CLAIM_CODE"', 'VARCHAR') }}                              as CLAIM_CODE,
        {{ std_cast('"EDI_POSITION"', 'VARCHAR') }}                            as EDI_POSITION,
        {{ std_cast('"CREATION_DATE"', 'TIMESTAMP_NTZ') }}                     as CREATION_DATE,
        {{ std_cast('"PLATE_SHIPPED"', 'NUMBER(38,5)') }}                      as PLATE_SHIPPED,
        {{ std_cast('"PLATE_CONFIRMED"', 'NUMBER(38,5)') }}                    as PLATE_CONFIRMED,
        {{ std_cast('"FCP"', 'INTEGER') }}                                     as FCP,
        {{ std_cast('"PROD_ORDER_NO_"', 'VARCHAR') }}                          as PROD_ORDER_NO,
        {{ std_cast('"PROD_ORDER_LINE_NO_"', 'INTEGER') }}                     as PROD_ORDER_LINE_NO,
        {{ std_cast('"MANUFACTURING_DATE"', 'TIMESTAMP_NTZ') }}                as MANUFACTURING_DATE,
        {{ std_cast('"Q_CONFIRMADA_RECADV"', 'NUMBER(38,5)') }}                as Q_CONFIRMADA_RECADV,
        {{ std_cast('"LINEA_CONFIRMADA"', 'INTEGER') }}                        as LINEA_CONFIRMADA,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'COO'                                                                     as tec_des_cod_siglas,
        'COOPECARN'                                                            as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY document_no, line_no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
