{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_SALES_INVOICE_LINE') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"DOCUMENT_NO_"', 'VARCHAR') }}                            as DOCUMENT_NO,
        {{ std_cast('"LINE_NO_"', 'INTEGER') }}                                as LINE_NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"TYPE"', 'INTEGER') }}                                    as TYPE,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"POSTING_GROUP"', 'VARCHAR') }}                           as POSTING_GROUP,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"DESCRIPTION"', 'VARCHAR') }}                             as DESCRIPTION,
        {{ std_cast('"DESCRIPTION_2"', 'VARCHAR') }}                           as DESCRIPTION_2,
        {{ std_cast('"UNIT_OF_MEASURE"', 'VARCHAR') }}                         as UNIT_OF_MEASURE,
        {{ std_cast('"QUANTITY"', 'NUMBER(38,5)') }}                           as QUANTITY,
        {{ std_cast('"UNIT_PRICE"', 'NUMBER(38,5)') }}                         as UNIT_PRICE,
        {{ std_cast('"UNIT_COST_LCY"', 'NUMBER(38,5)') }}                      as UNIT_COST_LCY,
        {{ std_cast('"VAT_"', 'NUMBER(38,5)') }}                               as VAT,
        {{ std_cast('"LINE_DISCOUNT_"', 'NUMBER(38,5)') }}                     as LINE_DISCOUNT,
        {{ std_cast('"LINE_DISCOUNT_AMOUNT"', 'NUMBER(38,5)') }}               as LINE_DISCOUNT_AMOUNT,
        {{ std_cast('"AMOUNT"', 'NUMBER(38,5)') }}                             as AMOUNT,
        {{ std_cast('"AMOUNT_INCLUDING_VAT"', 'NUMBER(38,5)') }}               as AMOUNT_INCLUDING_VAT,
        {{ std_cast('"ALLOW_INVOICE_DISC_"', 'INTEGER') }}                     as ALLOW_INVOICE_DISC,
        {{ std_cast('"GROSS_WEIGHT"', 'NUMBER(38,5)') }}                       as GROSS_WEIGHT,
        {{ std_cast('"NET_WEIGHT"', 'NUMBER(38,5)') }}                         as NET_WEIGHT,
        {{ std_cast('"UNITS_PER_PARCEL"', 'NUMBER(38,5)') }}                   as UNITS_PER_PARCEL,
        {{ std_cast('"UNIT_VOLUME"', 'NUMBER(38,5)') }}                        as UNIT_VOLUME,
        {{ std_cast('"APPL_TO_ITEM_ENTRY"', 'INTEGER') }}                      as APPL_TO_ITEM_ENTRY,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"JOB_NO_"', 'VARCHAR') }}                                 as JOB_NO,
        {{ std_cast('"WORK_TYPE_CODE"', 'VARCHAR') }}                          as WORK_TYPE_CODE,
        {{ std_cast('"SHIPMENT_NO_"', 'VARCHAR') }}                            as SHIPMENT_NO,
        {{ std_cast('"SHIPMENT_LINE_NO_"', 'INTEGER') }}                       as SHIPMENT_LINE_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"INV_DISCOUNT_AMOUNT"', 'NUMBER(38,5)') }}                as INV_DISCOUNT_AMOUNT,
        {{ std_cast('"DROP_SHIPMENT"', 'INTEGER') }}                           as DROP_SHIPMENT,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"GEN_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as GEN_PROD_POSTING_GROUP,
        {{ std_cast('"VAT_CALCULATION_TYPE"', 'INTEGER') }}                    as VAT_CALCULATION_TYPE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"ATTACHED_TO_LINE_NO_"', 'INTEGER') }}                    as ATTACHED_TO_LINE_NO,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"TAX_CATEGORY"', 'VARCHAR') }}                            as TAX_CATEGORY,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"TAX_GROUP_CODE"', 'VARCHAR') }}                          as TAX_GROUP_CODE,
        {{ std_cast('"VAT_CLAUSE_CODE"', 'VARCHAR') }}                         as VAT_CLAUSE_CODE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"VAT_PROD_POSTING_GROUP"', 'VARCHAR') }}                  as VAT_PROD_POSTING_GROUP,
        {{ std_cast('"BLANKET_ORDER_NO_"', 'VARCHAR') }}                       as BLANKET_ORDER_NO,
        {{ std_cast('"BLANKET_ORDER_LINE_NO_"', 'INTEGER') }}                  as BLANKET_ORDER_LINE_NO,
        {{ std_cast('"VAT_BASE_AMOUNT"', 'NUMBER(38,5)') }}                    as VAT_BASE_AMOUNT,
        {{ std_cast('"UNIT_COST"', 'NUMBER(38,5)') }}                          as UNIT_COST,
        {{ std_cast('"SYSTEM_CREATED_ENTRY"', 'INTEGER') }}                    as SYSTEM_CREATED_ENTRY,
        {{ std_cast('"LINE_AMOUNT"', 'NUMBER(38,5)') }}                        as LINE_AMOUNT,
        {{ std_cast('"VAT_DIFFERENCE"', 'NUMBER(38,5)') }}                     as VAT_DIFFERENCE,
        {{ std_cast('"VAT_IDENTIFIER"', 'VARCHAR') }}                          as VAT_IDENTIFIER,
        {{ std_cast('"IC_PARTNER_REF_TYPE"', 'INTEGER') }}                     as IC_PARTNER_REF_TYPE,
        {{ std_cast('"IC_PARTNER_REFERENCE"', 'VARCHAR') }}                    as IC_PARTNER_REFERENCE,
        {{ std_cast('"PREPAYMENT_LINE"', 'INTEGER') }}                         as PREPAYMENT_LINE,
        {{ std_cast('"IC_PARTNER_CODE"', 'VARCHAR') }}                         as IC_PARTNER_CODE,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"JOB_TASK_NO_"', 'VARCHAR') }}                            as JOB_TASK_NO,
        {{ std_cast('"JOB_CONTRACT_ENTRY_NO_"', 'INTEGER') }}                  as JOB_CONTRACT_ENTRY_NO,
        {{ std_cast('"DEFERRAL_CODE"', 'VARCHAR') }}                           as DEFERRAL_CODE,
        {{ std_cast('"VARIANT_CODE"', 'VARCHAR') }}                            as VARIANT_CODE,
        {{ std_cast('"BIN_CODE"', 'VARCHAR') }}                                as BIN_CODE,
        {{ std_cast('"QTY_PER_UNIT_OF_MEASURE"', 'NUMBER(38,5)') }}            as QTY_PER_UNIT_OF_MEASURE,
        {{ std_cast('"UNIT_OF_MEASURE_CODE"', 'VARCHAR') }}                    as UNIT_OF_MEASURE_CODE,
        {{ std_cast('"QUANTITY_BASE"', 'NUMBER(38,5)') }}                      as QUANTITY_BASE,
        {{ std_cast('"FA_POSTING_DATE"', 'TIMESTAMP_NTZ') }}                   as FA_POSTING_DATE,
        {{ std_cast('"DEPRECIATION_BOOK_CODE"', 'VARCHAR') }}                  as DEPRECIATION_BOOK_CODE,
        {{ std_cast('"DEPR_UNTIL_FA_POSTING_DATE"', 'INTEGER') }}              as DEPR_UNTIL_FA_POSTING_DATE,
        {{ std_cast('"DUPLICATE_IN_DEPRECIATION_BOOK"', 'VARCHAR') }}          as DUPLICATE_IN_DEPRECIATION_BOOK,
        {{ std_cast('"USE_DUPLICATION_LIST"', 'INTEGER') }}                    as USE_DUPLICATION_LIST,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"CROSS_REFERENCE_NO_"', 'VARCHAR') }}                     as CROSS_REFERENCE_NO,
        {{ std_cast('"UNIT_OF_MEASURE_CROSS_REF_"', 'VARCHAR') }}              as UNIT_OF_MEASURE_CROSS_REF,
        {{ std_cast('"CROSS_REFERENCE_TYPE"', 'INTEGER') }}                    as CROSS_REFERENCE_TYPE,
        {{ std_cast('"CROSS_REFERENCE_TYPE_NO_"', 'VARCHAR') }}                as CROSS_REFERENCE_TYPE_NO,
        {{ std_cast('"ITEM_CATEGORY_CODE"', 'VARCHAR') }}                      as ITEM_CATEGORY_CODE,
        {{ std_cast('"NONSTOCK"', 'INTEGER') }}                                as NONSTOCK,
        {{ std_cast('"PURCHASING_CODE"', 'VARCHAR') }}                         as PURCHASING_CODE,
        {{ std_cast('"PRODUCT_GROUP_CODE"', 'VARCHAR') }}                      as PRODUCT_GROUP_CODE,
        {{ std_cast('"APPL_FROM_ITEM_ENTRY"', 'INTEGER') }}                    as APPL_FROM_ITEM_ENTRY,
        {{ std_cast('"RETURN_REASON_CODE"', 'VARCHAR') }}                      as RETURN_REASON_CODE,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"PMT_DISC_GIVEN_AMOUNT"', 'NUMBER(38,5)') }}              as PMT_DISC_GIVEN_AMOUNT,
        {{ std_cast('"EC_"', 'NUMBER(38,5)') }}                                as EC,
        {{ std_cast('"EC_DIFFERENCE"', 'NUMBER(38,5)') }}                      as EC_DIFFERENCE,
        {{ std_cast('"COD_CADENA"', 'VARCHAR') }}                              as COD_CADENA,
        {{ std_cast('"PROMOCIONES_POR"', 'INTEGER') }}                         as PROMOCIONES_POR,
        {{ std_cast('"COMISIONES_POR"', 'INTEGER') }}                          as COMISIONES_POR,
        {{ std_cast('"CODIGO_EMBALAJE"', 'VARCHAR') }}                         as CODIGO_EMBALAJE,
        {{ std_cast('"CANTIDAD_EMBALAJE"', 'NUMBER(38,5)') }}                  as CANTIDAD_EMBALAJE,
        {{ std_cast('"CANTIDAD_UNIDADES"', 'NUMBER(38,5)') }}                  as CANTIDAD_UNIDADES,
        {{ std_cast('"CANTIDAD_KILOS"', 'NUMBER(38,5)') }}                     as CANTIDAD_KILOS,
        {{ std_cast('"NO_PRESENTACION"', 'VARCHAR') }}                         as NO_PRESENTACION,
        {{ std_cast('"DESCRIPCION_PRESENTACION"', 'VARCHAR') }}                as DESCRIPCION_PRESENTACION,
        {{ std_cast('"OBSERVACIONES"', 'VARCHAR') }}                           as OBSERVACIONES,
        {{ std_cast('"MOTIVO_DEVOLUCION"', 'VARCHAR') }}                       as MOTIVO_DEVOLUCION,
        {{ std_cast('"SERVICIO"', 'INTEGER') }}                                as SERVICIO,
        {{ std_cast('"PRECIO_PUNTO_VERDE_CDAD_"', 'NUMBER(38,5)') }}           as PRECIO_PUNTO_VERDE_CDAD,
        {{ std_cast('"UNIDAD_MEDIDA_PUNTO_VERDE"', 'VARCHAR') }}               as UNIDAD_MEDIDA_PUNTO_VERDE,
        {{ std_cast('"IMPORTE_PUNTO_VERDE"', 'NUMBER(38,5)') }}                as IMPORTE_PUNTO_VERDE,
        {{ std_cast('"GRUPO_RESIDUOS"', 'VARCHAR') }}                          as GRUPO_RESIDUOS,
        {{ std_cast('"PRECIO_RESIDUOS_CDAD_"', 'NUMBER(38,5)') }}              as PRECIO_RESIDUOS_CDAD,
        {{ std_cast('"UNIDAD_MEDIDA_RESIDUOS"', 'VARCHAR') }}                  as UNIDAD_MEDIDA_RESIDUOS,
        {{ std_cast('"IMPORTE_RESIDUOS"', 'NUMBER(38,5)') }}                   as IMPORTE_RESIDUOS,
        {{ std_cast('"INCOME_TAX_RETENTION_CODE"', 'VARCHAR') }}               as INCOME_TAX_RETENTION_CODE,
        {{ std_cast('"INCOME_TAX_RETENTION_"', 'NUMBER(38,5)') }}              as INCOME_TAX_RETENTION,
        {{ std_cast('"INCOME_TAX_BASE"', 'NUMBER(38,5)') }}                    as INCOME_TAX_BASE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"_COMMISSION_SALESPERSON"', 'NUMBER(38,5)') }}            as COMMISSION_SALESPERSON,
        {{ std_cast('"_2ND_SALESPERSON_CODE"', 'VARCHAR') }}                   as "2nd_salesperson_code",
        {{ std_cast('"_COMMISSION_2ND_SALESPERSON"', 'NUMBER(38,5)') }}        as COMMISSION_2ND_SALESPERSON,
        {{ std_cast('"SPECIAL_LINE_TYPE"', 'INTEGER') }}                       as SPECIAL_LINE_TYPE,
        {{ std_cast('"SALES_SHIPMENT_NO_"', 'VARCHAR') }}                      as SALES_SHIPMENT_NO,
        {{ std_cast('"SALES_SHIPMENT_LINE_NO_"', 'INTEGER') }}                 as SALES_SHIPMENT_LINE_NO,
        {{ std_cast('"TARIFF_NO_"', 'VARCHAR') }}                              as TARIFF_NO,
        {{ std_cast('"EDI_POSITION"', 'INTEGER') }}                            as EDI_POSITION,
        {{ std_cast('"Q_CONFIRMADA_RECADV"', 'NUMBER(38,5)') }}                as Q_CONFIRMADA_RECADV,
        {{ std_cast('"RECADCV_QUANTITY"', 'NUMBER(38,5)') }}                   as RECADCV_QUANTITY,
        {{ std_cast('"EDI_POSITION_SUBLINE"', 'INTEGER') }}                    as EDI_POSITION_SUBLINE,
        {{ std_cast('"GLN"', 'VARCHAR') }}                                     as GLN,
        {{ std_cast('"EDI_PRICE"', 'NUMBER(38,5)') }}                          as EDI_PRICE,
        {{ std_cast('"EDI_DISCOUNT_"', 'NUMBER(38,5)') }}                      as EDI_DISCOUNT,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        'FRI'                                                                     as tec_des_cod_siglas,
        'FRICAFOR'                                                             as tec_des_empresa,
        tec_id_ingesta,
        tec_ts_ingesta,
        tec_ts_staging,
        tec_ts_integracion_b
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY document_no, line_no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
