{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_COOPECARN', materialized='view', tags=['bronze','batch','COOPECARN']) }}

{% set src_ref = source('bronze_coopecarn', 'COOPECARN_SALES_HEADER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"DOCUMENT_TYPE"', 'INTEGER') }}                           as DOCUMENT_TYPE,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_NAME"', 'VARCHAR') }}                            as BILL_TO_NAME,
        {{ std_cast('"BILL_TO_NAME_2"', 'VARCHAR') }}                          as BILL_TO_NAME_2,
        {{ std_cast('"BILL_TO_ADDRESS"', 'VARCHAR') }}                         as BILL_TO_ADDRESS,
        {{ std_cast('"BILL_TO_ADDRESS_2"', 'VARCHAR') }}                       as BILL_TO_ADDRESS_2,
        {{ std_cast('"BILL_TO_CITY"', 'VARCHAR') }}                            as BILL_TO_CITY,
        {{ std_cast('"BILL_TO_CONTACT"', 'VARCHAR') }}                         as BILL_TO_CONTACT,
        {{ std_cast('"YOUR_REFERENCE"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        {{ std_cast('"SHIP_TO_CODE"', 'VARCHAR') }}                            as SHIP_TO_CODE,
        {{ std_cast('"SHIP_TO_NAME"', 'VARCHAR') }}                            as SHIP_TO_NAME,
        {{ std_cast('"SHIP_TO_NAME_2"', 'VARCHAR') }}                          as SHIP_TO_NAME_2,
        {{ std_cast('"SHIP_TO_ADDRESS"', 'VARCHAR') }}                         as SHIP_TO_ADDRESS,
        {{ std_cast('"SHIP_TO_ADDRESS_2"', 'VARCHAR') }}                       as SHIP_TO_ADDRESS_2,
        {{ std_cast('"SHIP_TO_CITY"', 'VARCHAR') }}                            as SHIP_TO_CITY,
        {{ std_cast('"SHIP_TO_CONTACT"', 'VARCHAR') }}                         as SHIP_TO_CONTACT,
        {{ std_cast('"ORDER_DATE"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"POSTING_DESCRIPTION"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"DUE_DATE"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}                  as PAYMENT_DISCOUNT,
        {{ std_cast('"PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}                 as PMT_DISCOUNT_DATE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CURRENCY_FACTOR"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"ORDER_CLASS"', 'VARCHAR') }}                             as ORDER_CLASS,
        {{ std_cast('"NO_PRINTED"', 'INTEGER') }}                              as NO_PRINTED,
        {{ std_cast('"ON_HOLD"', 'VARCHAR') }}                                 as ON_HOLD,
        {{ std_cast('"APPLIES_TO_DOC_TYPE"', 'INTEGER') }}                     as APPLIES_TO_DOC_TYPE,
        {{ std_cast('"APPLIES_TO_DOC_NO_"', 'VARCHAR') }}                      as APPLIES_TO_DOC_NO,
        {{ std_cast('"BAL_ACCOUNT_NO_"', 'VARCHAR') }}                         as BAL_ACCOUNT_NO,
        {{ std_cast('"SHIP"', 'INTEGER') }}                                    as SHIP,
        {{ std_cast('"INVOICE"', 'INTEGER') }}                                 as INVOICE,
        {{ std_cast('"PRINT_POSTED_DOCUMENTS"', 'INTEGER') }}                  as PRINT_POSTED_DOCUMENTS,
        {{ std_cast('"SHIPPING_NO_"', 'VARCHAR') }}                            as SHIPPING_NO,
        {{ std_cast('"POSTING_NO_"', 'VARCHAR') }}                             as POSTING_NO,
        {{ std_cast('"LAST_SHIPPING_NO_"', 'VARCHAR') }}                       as LAST_SHIPPING_NO,
        {{ std_cast('"LAST_POSTING_NO_"', 'VARCHAR') }}                        as LAST_POSTING_NO,
        {{ std_cast('"PREPAYMENT_NO_"', 'VARCHAR') }}                          as PREPAYMENT_NO,
        {{ std_cast('"LAST_PREPAYMENT_NO_"', 'VARCHAR') }}                     as LAST_PREPAYMENT_NO,
        {{ std_cast('"PREPMT_CR_MEMO_NO_"', 'VARCHAR') }}                      as PREPMT_CR_MEMO_NO,
        {{ std_cast('"LAST_PREPMT_CR_MEMO_NO_"', 'VARCHAR') }}                 as LAST_PREPMT_CR_MEMO_NO,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"COMBINE_SHIPMENTS"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"REASON_CODE"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"EU_3_PARTY_TRADE"', 'INTEGER') }}                        as EU_3_PARTY_TRADE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT_COUNTRY_REGION_CODE"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME"', 'VARCHAR') }}                   as SELL_TO_CUSTOMER_NAME,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME_2"', 'VARCHAR') }}                 as SELL_TO_CUSTOMER_NAME_2,
        {{ std_cast('"SELL_TO_ADDRESS"', 'VARCHAR') }}                         as SELL_TO_ADDRESS,
        {{ std_cast('"SELL_TO_ADDRESS_2"', 'VARCHAR') }}                       as SELL_TO_ADDRESS_2,
        {{ std_cast('"SELL_TO_CITY"', 'VARCHAR') }}                            as SELL_TO_CITY,
        {{ std_cast('"SELL_TO_CONTACT"', 'VARCHAR') }}                         as SELL_TO_CONTACT,
        {{ std_cast('"BILL_TO_POST_CODE"', 'VARCHAR') }}                       as BILL_TO_POST_CODE,
        {{ std_cast('"BILL_TO_COUNTY"', 'VARCHAR') }}                          as BILL_TO_COUNTY,
        {{ std_cast('"BILL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as BILL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_POST_CODE"', 'VARCHAR') }}                       as SELL_TO_POST_CODE,
        {{ std_cast('"SELL_TO_COUNTY"', 'VARCHAR') }}                          as SELL_TO_COUNTY,
        {{ std_cast('"SELL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SELL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SHIP_TO_POST_CODE"', 'VARCHAR') }}                       as SHIP_TO_POST_CODE,
        {{ std_cast('"SHIP_TO_COUNTY"', 'VARCHAR') }}                          as SHIP_TO_COUNTY,
        {{ std_cast('"SHIP_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SHIP_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"BAL_ACCOUNT_TYPE"', 'INTEGER') }}                        as BAL_ACCOUNT_TYPE,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"CORRECTION"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"DOCUMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"EXTERNAL_DOCUMENT_NO_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PACKAGE_TRACKING_NO_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"POSTING_NO_SERIES"', 'VARCHAR') }}                       as POSTING_NO_SERIES,
        {{ std_cast('"SHIPPING_NO_SERIES"', 'VARCHAR') }}                      as SHIPPING_NO_SERIES,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"APPLIES_TO_ID"', 'VARCHAR') }}                           as APPLIES_TO_ID,
        {{ std_cast('"VAT_BASE_DISCOUNT_"', 'NUMBER(38,5)') }}                 as VAT_BASE_DISCOUNT,
        {{ std_cast('"STATUS"', 'INTEGER') }}                                  as STATUS,
        {{ std_cast('"INVOICE_DISCOUNT_CALCULATION"', 'INTEGER') }}            as INVOICE_DISCOUNT_CALCULATION,
        {{ std_cast('"INVOICE_DISCOUNT_VALUE"', 'NUMBER(38,5)') }}             as INVOICE_DISCOUNT_VALUE,
        {{ std_cast('"SEND_IC_DOCUMENT"', 'INTEGER') }}                        as SEND_IC_DOCUMENT,
        {{ std_cast('"IC_STATUS"', 'INTEGER') }}                               as IC_STATUS,
        {{ std_cast('"SELL_TO_IC_PARTNER_CODE"', 'VARCHAR') }}                 as SELL_TO_IC_PARTNER_CODE,
        {{ std_cast('"BILL_TO_IC_PARTNER_CODE"', 'VARCHAR') }}                 as BILL_TO_IC_PARTNER_CODE,
        {{ std_cast('"IC_DIRECTION"', 'INTEGER') }}                            as IC_DIRECTION,
        {{ std_cast('"PREPAYMENT_"', 'NUMBER(38,5)') }}                        as PREPAYMENT,
        {{ std_cast('"PREPAYMENT_NO_SERIES"', 'VARCHAR') }}                    as PREPAYMENT_NO_SERIES,
        {{ std_cast('"COMPRESS_PREPAYMENT"', 'INTEGER') }}                     as COMPRESS_PREPAYMENT,
        {{ std_cast('"PREPAYMENT_DUE_DATE"', 'TIMESTAMP_NTZ') }}               as PREPAYMENT_DUE_DATE,
        {{ std_cast('"PREPMT_CR_MEMO_NO_SERIES"', 'VARCHAR') }}                as PREPMT_CR_MEMO_NO_SERIES,
        {{ std_cast('"PREPMT_POSTING_DESCRIPTION"', 'VARCHAR') }}              as PREPMT_POSTING_DESCRIPTION,
        {{ std_cast('"PREPMT_PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}          as PREPMT_PMT_DISCOUNT_DATE,
        {{ std_cast('"PREPMT_PAYMENT_TERMS_CODE"', 'VARCHAR') }}               as PREPMT_PAYMENT_TERMS_CODE,
        {{ std_cast('"PREPMT_PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}           as PREPMT_PAYMENT_DISCOUNT,
        {{ std_cast('"QUOTE_NO_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"JOB_QUEUE_STATUS"', 'INTEGER') }}                        as JOB_QUEUE_STATUS,
        {{ std_cast('"JOB_QUEUE_ENTRY_ID"', 'VARCHAR') }}                      as JOB_QUEUE_ENTRY_ID,
        {{ std_cast('"INCOMING_DOCUMENT_ENTRY_NO_"', 'INTEGER') }}             as INCOMING_DOCUMENT_ENTRY_NO,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        {{ std_cast('"AUTHORIZATION_REQUIRED"', 'INTEGER') }}                  as AUTHORIZATION_REQUIRED,
        {{ std_cast('"CREDIT_CARD_NO_"', 'VARCHAR') }}                         as CREDIT_CARD_NO,
        {{ std_cast('"DIRECT_DEBIT_MANDATE_ID"', 'VARCHAR') }}                 as DIRECT_DEBIT_MANDATE_ID,
        {{ std_cast('"DOC_NO_OCCURRENCE"', 'INTEGER') }}                       as DOC_NO_OCCURRENCE,
        {{ std_cast('"CAMPAIGN_NO_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        {{ std_cast('"SELL_TO_CUSTOMER_TEMPLATE_CODE"', 'VARCHAR') }}          as SELL_TO_CUSTOMER_TEMPLATE_CODE,
        {{ std_cast('"SELL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as SELL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as BILL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_TEMPLATE_CODE"', 'VARCHAR') }}          as BILL_TO_CUSTOMER_TEMPLATE_CODE,
        {{ std_cast('"OPPORTUNITY_NO_"', 'VARCHAR') }}                         as OPPORTUNITY_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"SHIPPING_ADVICE"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"POSTING_FROM_WHSE_REF_"', 'INTEGER') }}                  as POSTING_FROM_WHSE_REF,
        {{ std_cast('"REQUESTED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}           as REQUESTED_DELIVERY_DATE,
        {{ std_cast('"PROMISED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}            as PROMISED_DELIVERY_DATE,
        {{ std_cast('"SHIPPING_TIME"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"OUTBOUND_WHSE_HANDLING_TIME"', 'VARCHAR') }}             as OUTBOUND_WHSE_HANDLING_TIME,
        {{ std_cast('"SHIPPING_AGENT_SERVICE_CODE"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"RECEIVE"', 'INTEGER') }}                                 as RECEIVE,
        {{ std_cast('"RETURN_RECEIPT_NO_"', 'VARCHAR') }}                      as RETURN_RECEIPT_NO,
        {{ std_cast('"RETURN_RECEIPT_NO_SERIES"', 'VARCHAR') }}                as RETURN_RECEIPT_NO_SERIES,
        {{ std_cast('"LAST_RETURN_RECEIPT_NO_"', 'VARCHAR') }}                 as LAST_RETURN_RECEIPT_NO,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"GET_SHIPMENT_USED"', 'INTEGER') }}                       as GET_SHIPMENT_USED,
        {{ std_cast('"ASSIGNED_USER_ID"', 'VARCHAR') }}                        as ASSIGNED_USER_ID,
        {{ std_cast('"CORRECTED_INVOICE_NO_"', 'VARCHAR') }}                   as CORRECTED_INVOICE_NO,
        {{ std_cast('"DUE_DATE_MODIFIED"', 'INTEGER') }}                       as DUE_DATE_MODIFIED,
        {{ std_cast('"QUOTE_END_DATE"', 'TIMESTAMP_NTZ') }}                    as QUOTE_END_DATE,
        {{ std_cast('"UPLOAD_DATE"', 'TIMESTAMP_NTZ') }}                       as UPLOAD_DATE,
        {{ std_cast('"SAMPLE_ORDER"', 'INTEGER') }}                            as SAMPLE_ORDER,
        {{ std_cast('"CONTAINER"', 'VARCHAR') }}                               as CONTAINER,
        {{ std_cast('"SEAL"', 'VARCHAR') }}                                    as SEAL,
        {{ std_cast('"TRUCK_LICENSE_PLATE"', 'VARCHAR') }}                     as TRUCK_LICENSE_PLATE,
        {{ std_cast('"DRIVER"', 'VARCHAR') }}                                  as DRIVER,
        {{ std_cast('"AUTHORIZE_ORDER"', 'INTEGER') }}                         as AUTHORIZE_ORDER,
        {{ std_cast('"TRAILER_LICENSE_PLATE"', 'VARCHAR') }}                   as TRAILER_LICENSE_PLATE,
        {{ std_cast('"PENDING_AUTHORIZE_ORDER"', 'INTEGER') }}                 as PENDING_AUTHORIZE_ORDER,
        {{ std_cast('"RISK_EXCEEDED"', 'INTEGER') }}                           as RISK_EXCEEDED,
        {{ std_cast('"BANK_ACCOUNT_TO_TRANSFER"', 'VARCHAR') }}                as BANK_ACCOUNT_TO_TRANSFER,
        {{ std_cast('"TRIP_NO_"', 'VARCHAR') }}                                as TRIP_NO,
        {{ std_cast('"FILE_GENERATED"', 'INTEGER') }}                          as FILE_GENERATED,
        {{ std_cast('"ESTADO_EDI"', 'INTEGER') }}                              as ESTADO_EDI,
        {{ std_cast('"MOTIVO_DEVOLUCION_EDI"', 'INTEGER') }}                   as MOTIVO_DEVOLUCION_EDI,
        {{ std_cast('"DEPARTAMENTO_EDI"', 'VARCHAR') }}                        as DEPARTAMENTO_EDI,
        {{ std_cast('"SHIPMENT_LANGUAGE_CODE"', 'VARCHAR') }}                  as SHIPMENT_LANGUAGE_CODE,
        {{ std_cast('"HEADER_DISCOUNT_"', 'NUMBER(38,5)') }}                   as HEADER_DISCOUNT,
        {{ std_cast('"SALES_RETURN"', 'INTEGER') }}                            as SALES_RETURN,
        {{ std_cast('"RAPPEL_"', 'NUMBER(38,5)') }}                            as RAPPEL,
        {{ std_cast('"LOAD_TIME"', 'VARCHAR') }}                               as LOAD_TIME,
        {{ std_cast('"LOAD_HR_"', 'TIMESTAMP_NTZ') }}                          as LOAD_HR,
        {{ std_cast('"SALES_INV_PROFORMA"', 'INTEGER') }}                      as SALES_INV_PROFORMA,
        {{ std_cast('"SHIPMENT_ZONE_CODE"', 'VARCHAR') }}                      as SHIPMENT_ZONE_CODE,
        {{ std_cast('"INVOICE_CANCELATION"', 'INTEGER') }}                     as INVOICE_CANCELATION,
        {{ std_cast('"CORRECTED_INVOICE_TYPE"', 'INTEGER') }}                  as CORRECTED_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_TYPE"', 'INTEGER') }}                         as SIMPLIFIED_TYPE,
        {{ std_cast('"FROM_TICKET_NO_"', 'VARCHAR') }}                         as FROM_TICKET_NO,
        {{ std_cast('"TO_TICKET_NO_"', 'VARCHAR') }}                           as TO_TICKET_NO,
        {{ std_cast('"APPLIES_TO_BILL_NO_"', 'VARCHAR') }}                     as APPLIES_TO_BILL_NO,
        {{ std_cast('"CUST_BANK_ACC_CODE"', 'VARCHAR') }}                      as CUST_BANK_ACC_CODE,
        {{ std_cast('"PAY_AT_CODE"', 'VARCHAR') }}                             as PAY_AT_CODE,
        {{ std_cast('"NO_TELEFONO_ENVIO"', 'VARCHAR') }}                       as NO_TELEFONO_ENVIO,
        {{ std_cast('"OBSERVACIONES_ENVIO"', 'VARCHAR') }}                     as OBSERVACIONES_ENVIO,
        {{ std_cast('"PESO_NETO"', 'NUMBER(38,5)') }}                          as PESO_NETO,
        {{ std_cast('"PESO_BRUTO"', 'NUMBER(38,5)') }}                         as PESO_BRUTO,
        {{ std_cast('"FORMA_PAGO_FACTURAPLUS"', 'VARCHAR') }}                  as FORMA_PAGO_FACTURAPLUS,
        {{ std_cast('"VALUED_SHIPMENT"', 'INTEGER') }}                         as VALUED_SHIPMENT,
        {{ std_cast('"DROP_SHIPMENT"', 'INTEGER') }}                           as DROP_SHIPMENT,
        {{ std_cast('"SIN_MOVS_ALMACEN"', 'INTEGER') }}                        as SIN_MOVS_ALMACEN,
        {{ std_cast('"EN_FACTURACION_AUTOMATICA"', 'INTEGER') }}               as EN_FACTURACION_AUTOMATICA,
        {{ std_cast('"FECHA_CONFIRMACION_PACKING"', 'TIMESTAMP_NTZ') }}        as FECHA_CONFIRMACION_PACKING,
        {{ std_cast('"ANULACION_AUTOMATICA"', 'INTEGER') }}                    as ANULACION_AUTOMATICA,
        {{ std_cast('"USUARIO_ALTA"', 'VARCHAR') }}                            as USUARIO_ALTA,
        {{ std_cast('"JEFE_DE_VENTAS"', 'VARCHAR') }}                          as JEFE_DE_VENTAS,
        {{ std_cast('"JEFE_DE_ZONA"', 'VARCHAR') }}                            as JEFE_DE_ZONA,
        {{ std_cast('"HEREDA_COND_GRUPO"', 'INTEGER') }}                       as HEREDA_COND_GRUPO,
        {{ std_cast('"NO_EXPEDICION"', 'VARCHAR') }}                           as NO_EXPEDICION,
        {{ std_cast('"NO_ALBARAN_AGENCIA"', 'VARCHAR') }}                      as NO_ALBARAN_AGENCIA,
        {{ std_cast('"CASH_ENTRY"', 'INTEGER') }}                              as CASH_ENTRY,
        {{ std_cast('"SPETIAL_OPERATION_TYPE"', 'INTEGER') }}                  as SPETIAL_OPERATION_TYPE,
        {{ std_cast('"SPETIAL_OPERATION_CODE"', 'VARCHAR') }}                  as SPETIAL_OPERATION_CODE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        {{ std_cast('"INVOICE_DETAIL"', 'INTEGER') }}                          as INVOICE_DETAIL,
        {{ std_cast('"RETENER_FACTURACION"', 'INTEGER') }}                     as RETENER_FACTURACION,
        {{ std_cast('"NO_FACTURA_ANULADA"', 'VARCHAR') }}                      as NO_FACTURA_ANULADA,
        {{ std_cast('"ANULACION_DE_FACTURA"', 'INTEGER') }}                    as ANULACION_DE_FACTURA,
        {{ std_cast('"PRINT_BY_CONCEPT"', 'INTEGER') }}                        as PRINT_BY_CONCEPT,
        {{ std_cast('"PEDIDO_SINCRON_AUTOMATICA"', 'INTEGER') }}               as PEDIDO_SINCRON_AUTOMATICA,
        {{ std_cast('"EMPRESA_ORIGEN"', 'VARCHAR') }}                          as EMPRESA_ORIGEN,
        {{ std_cast('"NO_PROV_EN_CLIENTE"', 'VARCHAR') }}                      as NO_PROV_EN_CLIENTE,
        {{ std_cast('"ANULADO"', 'INTEGER') }}                                 as ANULADO,
        {{ std_cast('"ODS_JOB_TEMPLATE_CODE"', 'VARCHAR') }}                   as ODS_JOB_TEMPLATE_CODE,
        {{ std_cast('"OPERATION_DATE"', 'TIMESTAMP_NTZ') }}                    as OPERATION_DATE,
        {{ std_cast('"TO_DOCUMENT_NO_"', 'VARCHAR') }}                         as TO_DOCUMENT_NO,
        {{ std_cast('"FROM_DOCUMENT_NO_"', 'VARCHAR') }}                       as FROM_DOCUMENT_NO,
        {{ std_cast('"REGIMEN"', 'VARCHAR') }}                                 as REGIMEN,
        {{ std_cast('"SII_CORRECTION_TYPE"', 'VARCHAR') }}                     as SII_CORRECTION_TYPE,
        {{ std_cast('"SII_OPERATION_DESCRIPTION"', 'VARCHAR') }}               as SII_OPERATION_DESCRIPTION,
        {{ std_cast('"SII_INVOICE_TYPE"', 'VARCHAR') }}                        as SII_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_INVOICE"', 'INTEGER') }}                      as SIMPLIFIED_INVOICE,
        {{ std_cast('"SIMPLIFIED_ART_6_1_D"', 'INTEGER') }}                    as SIMPLIFIED_ART_6_1_D,
        {{ std_cast('"REFEXTERNA"', 'VARCHAR') }}                              as REFEXTERNA,
        {{ std_cast('"TAX_FREE"', 'INTEGER') }}                                as TAX_FREE,
        {{ std_cast('"NUM_REGISTRO_ACUERDO_FACT_"', 'VARCHAR') }}              as NUM_REGISTRO_ACUERDO_FACT,
        {{ std_cast('"EMITIDA_POR_TERCERO"', 'INTEGER') }}                     as EMITIDA_POR_TERCERO,
        {{ std_cast('"EMITIDA_POR_NORMATIVA_DEL_GAS"', 'INTEGER') }}           as EMITIDA_POR_NORMATIVA_DEL_GAS,
        {{ std_cast('"COMPLETELY_INVOICED"', 'INTEGER') }}                     as COMPLETELY_INVOICED,
        {{ std_cast('"IPAD_ORDER"', 'INTEGER') }}                              as IPAD_ORDER,
        {{ std_cast('"WITHOUT_PLASTIC_DECLARATION"', 'INTEGER') }}             as WITHOUT_PLASTIC_DECLARATION,
        {{ std_cast('"FECHAEPRDT"', 'TIMESTAMP_NTZ') }}                        as FECHAEPRDT,
        {{ std_cast('"FECHATODT"', 'TIMESTAMP_NTZ') }}                         as FECHATODT,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        NULL                                                                   as SELLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_NAME,
        NULL                                                                   as BILLTO_NAME_2,
        NULL                                                                   as BILLTO_ADDRESS,
        NULL                                                                   as BILLTO_ADDRESS_2,
        NULL                                                                   as BILLTO_CITY,
        NULL                                                                   as BILLTO_CONTACT,
        NULL                                                                   as SHIPTO_CODE,
        NULL                                                                   as SHIPTO_NAME,
        NULL                                                                   as SHIPTO_NAME_2,
        NULL                                                                   as SHIPTO_ADDRESS,
        NULL                                                                   as SHIPTO_ADDRESS_2,
        NULL                                                                   as SHIPTO_CITY,
        NULL                                                                   as SHIPTO_CONTACT,
        NULL                                                                   as APPLIESTO_DOC_TYPE,
        NULL                                                                   as APPLIESTO_DOC_NO,
        NULL                                                                   as EU_3PARTY_TRADE,
        NULL                                                                   as SELLTO_CUSTOMER_NAME,
        NULL                                                                   as SELLTO_CUSTOMER_NAME_2,
        NULL                                                                   as SELLTO_ADDRESS,
        NULL                                                                   as SELLTO_ADDRESS_2,
        NULL                                                                   as SELLTO_CITY,
        NULL                                                                   as SELLTO_CONTACT,
        NULL                                                                   as BILLTO_POST_CODE,
        NULL                                                                   as BILLTO_COUNTY,
        NULL                                                                   as BILLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SELLTO_POST_CODE,
        NULL                                                                   as SELLTO_COUNTY,
        NULL                                                                   as SELLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SHIPTO_POST_CODE,
        NULL                                                                   as SHIPTO_COUNTY,
        NULL                                                                   as SHIPTO_COUNTRY_REGION_CODE,
        NULL                                                                   as APPLIESTO_ID,
        NULL                                                                   as ESTADO,
        NULL                                                                   as SELLTO_IC_PARTNER_CODE,
        NULL                                                                   as BILLTO_IC_PARTNER_CODE,
        NULL                                                                   as QUOTE_VALID_UNTIL_DATE,
        NULL                                                                   as QUOTE_SENT_TO_CUSTOMER,
        NULL                                                                   as QUOTE_ACCEPTED,
        NULL                                                                   as QUOTE_ACCEPTED_DATE,
        NULL                                                                   as ISTEST,
        NULL                                                                   as PAYMENT_INSTRUCTIONS_ID,
        NULL                                                                   as PAYMENT_SERVICE_SET_ID,
        NULL                                                                   as SELLTO_CUSTOMER_TEMPLATE_CODE,
        NULL                                                                   as SELLTO_CONTACT_NO,
        NULL                                                                   as BILLTO_CONTACT_NO,
        NULL                                                                   as BILLTO_CUSTOMER_TEMPLATE_CODE,
        NULL                                                                   as ID,
        NULL                                                                   as INVOICE_TYPE,
        NULL                                                                   as CR_MEMO_TYPE,
        NULL                                                                   as SPECIAL_SCHEME_CODE,
        NULL                                                                   as OPERATION_DESCRIPTION,
        NULL                                                                   as CORRECTION_TYPE,
        NULL                                                                   as OPERATION_DESCRIPTION_2,
        NULL                                                                   as SUCCEEDED_COMPANY_NAME,
        NULL                                                                   as SUCCEEDED_VAT_REGISTRATION_NO,
        NULL                                                                   as APPLIESTO_BILL_NO,
        NULL                                                                   as PAYAT_CODE,
        NULL                                                                   as IDPIRPF_IRPF_GROUP,
        NULL                                                                   as IDPGND_SHIPTO_EXCL_SIG_RATE,
        NULL                                                                   as IF_OR_TYPE,
        NULL                                                                   as IF_DATA_1,
        NULL                                                                   as IF_DATA_2,
        NULL                                                                   as IF_DATA_3,
        NULL                                                                   as IF_DATA_4,
        NULL                                                                   as IF_DATA_5,
        NULL                                                                   as IF_ML_TIME,
        NULL                                                                   as IF_SAE_CERTIFICATION,
        NULL                                                                   as CO_ID_CONT,
        NULL                                                                   as CO_ID_PREC,
        NULL                                                                   as TOTALNETWEIGHT,
        NULL                                                                   as TOTALGROSSWEIGHT,
        NULL                                                                   as PACKAGESPALLETNUMBER,
        NULL                                                                   as PACKAGESNUMBER,
        NULL                                                                   as SII_NUMDESDE,
        NULL                                                                   as SII_NUMHASTA,
        NULL                                                                   as SII_FACARRENDAMIENTO,
        NULL                                                                   as SII_UBICACIONPROPIEDAD,
        NULL                                                                   as SII_INMUEBLESADICIONALES,
        NULL                                                                   as SII_NUMCUENTAIMPUESTO,
        NULL                                                                   as SALES_DATE,
        NULL                                                                   as SYSTEM_DATE,
        NULL                                                                   as CERRADO,
        NULL                                                                   as AIT_BILLING_ADDRESS_CODE,
        NULL                                                                   as IDPCIN_ALLOW_CREDIT_EXCEEDED,
        NULL                                                                   as IDPEDI_DOCUMENT,
        NULL                                                                   as IDPEDI_ORDRSP,
        NULL                                                                   as IDPEDI_ORDRSP_SENT,
        NULL                                                                   as IDPEDI_INTERLOCUTOR_CODE,
        NULL                                                                   as IDPEDI_ORDRSP_RESPONSE_CODE,
        NULL                                                                   as IDPEDI_INVOIC,
        NULL                                                                   as IDPEDI_ORDRSP_REVIEWED,
        NULL                                                                   as IDPEDI_DESADV,
        NULL                                                                   as IDPEDI_RECADV,
        NULL                                                                   as IDPVUM_UPDATE_SOURCE,
        NULL                                                                   as AIT_CREATION_USER,
        NULL                                                                   as AIT_CREATION_DATETIME,
        NULL                                                                   as AIT_RIESGOSUPERADO,
        NULL                                                                   as BLOQUEAR_PROMOCIONES,
        NULL                                                                   as COD_CADENA,
        NULL                                                                   as PROMOCIONES_POR,
        NULL                                                                   as COD_DTO_LINEA,
        NULL                                                                   as CALCULAR_RAPPEL,
        NULL                                                                   as TIPO_PEDIDO,
        NULL                                                                   as TIPO_PUNTO_VERDE,
        NULL                                                                   as COD_RUTA,
        NULL                                                                   as PREFACTURAR_SERVICIO,
        NULL                                                                   as ZONA_TRANSPORTE,
        NULL                                                                   as TEMPERATURA_EXP,
        NULL                                                                   as ESTADO_LIMPIEZA,
        NULL                                                                   as ESTADO_PALETIZADO,
        NULL                                                                   as ORIGEN,
        NULL                                                                   as OBSERVACIONES_PICKING,
        NULL                                                                   as OBSERVACIONES_RECOGIDA,
        NULL                                                                   as OBSERVACIONES_CARTA_PORTES,
        NULL                                                                   as NATURALEZA_PRODUCTO,
        NULL                                                                   as DOC_TRANSPORTE,
        NULL                                                                   as NO_ENVIO,
        NULL                                                                   as COD_PALET,
        NULL                                                                   as TIPO_RESIDUOS,
        NULL                                                                   as COD_IDIOMA_ETIQUETAJE,
        NULL                                                                   as HORARIO_ENTREGA,
        NULL                                                                   as NO_CAJAS_POR_PALET,
        NULL                                                                   as MATRICULA_VEHICULO,
        NULL                                                                   as CONDUCTOR,
        NULL                                                                   as NIF_CONDUCTOR,
        NULL                                                                   as MATRICULA_REMOLQUE,
        NULL                                                                   as CAPACIDAD_MAX_PALETS,
        NULL                                                                   as NO_PEDIDO_ORIGEN,
        NULL                                                                   as RECUPERACION_EDI,
        NULL                                                                   as ALBARAN_VALORADO,
        NULL                                                                   as TIPO_FACTURACION,
        NULL                                                                   as FACTURA_POR_ALBARAN,
        NULL                                                                   as PREINVOICE,
        NULL                                                                   as SPLIT_SHIP_TO_ADD,
        NULL                                                                   as DTO_FACTURA,
        NULL                                                                   as COD_BANCO,
        NULL                                                                   as COMMISSION_SALESPERSON,
        NULL                                                                   as 2ND_SALESPERSON_CODE,
        NULL                                                                   as COMMISSION_2ND_SALESPERSON,
        NULL                                                                   as INCOME_TAX_RETENTION_CODE,
        NULL                                                                   as INCOME_TAX_RETENTION,
        NULL                                                                   as INCOME_TAX_RETENTION_KEY,
        NULL                                                                   as INCOME_TAX_RETENTION_SUBKEY,
        NULL                                                                   as POSTING_STATUS,
        NULL                                                                   as SHIP_POSTING,
        NULL                                                                   as INVOICE_POSTING,
        NULL                                                                   as POSTING_IN_ERROR,
        NULL                                                                   as EDI_HORA_ENTREGA,
        NULL                                                                   as CONTROLAR_PR_MIN,
        NULL                                                                   as ESTADO_CALIDAD,
        NULL                                                                   as CODIGO_CALIDAD,
        NULL                                                                   as TAX_FREE_VENDOR_NO,
        NULL                                                                   as CUSTOMER_SALES_DEPARTMENT,
        NULL                                                                   as EDI_BLOCKED,
        NULL                                                                   as DESADV_NO,
        NULL                                                                   as PLANNING_DELIVERY_DATE,
        NULL                                                                   as INVOICE_BLOCKED,
        NULL                                                                   as INTERCOMPANY_INVOICE,
        NULL                                                                   as HIDE_DIALOGUE,
        NULL                                                                   as CUSTOMER_RECEPTION_NO,
        NULL                                                                   as EDI_ORDER_NO,
        NULL                                                                   as SALES_SHIPMENT_NO,
        NULL                                                                   as FIX_SALES_PRICE,
        'COO'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
