{{ config(database='PROD_BRONZE' if target.name == 'prod' else 'DEV_BRONZE', schema='BRONZE_FRICAFOR', materialized='view', tags=['bronze','batch','FRICAFOR']) }}

{% set src_ref = source('bronze_fricafor', 'FRICAFOR_SALES_HEADER') %}
{% set log_ref = source('support_param', 'INSERT_LOGS') %}

with next_log as (
    select tec_id_ingesta
    from {{ log_ref }}
    where upper(database)   = upper('{{ src_ref.database }}')
      and upper(schema)     = upper('{{ src_ref.schema }}')
      and upper(table_name) = upper('{{ src_ref.identifier }}')
      and start_watermark <> end_watermark
      and tec_ts_integracion_b is null
    qualify row_number() over(order by tec_ts_ingesta) = 1
),
src as (
    select
        {{ std_cast('"TIMESTAMP"', 'INTEGER') }}                               as TIMESTAMP,
        {{ std_cast('"DOCUMENT_TYPE"', 'INTEGER') }}                           as DOCUMENT_TYPE,
        {{ std_cast('"NO_"', 'VARCHAR') }}                                     as NO,
        {{ std_cast('"SELL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as SELL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_NO_"', 'VARCHAR') }}                    as BILL_TO_CUSTOMER_NO,
        {{ std_cast('"BILL_TO_NAME"', 'VARCHAR') }}                            as BILL_TO_NAME,
        {{ std_cast('"BILL_TO_NAME_2"', 'VARCHAR') }}                          as BILL_TO_NAME_2,
        {{ std_cast('"BILL_TO_ADDRESS"', 'VARCHAR') }}                         as BILL_TO_ADDRESS,
        {{ std_cast('"BILL_TO_ADDRESS_2"', 'VARCHAR') }}                       as BILL_TO_ADDRESS_2,
        {{ std_cast('"BILL_TO_CITY"', 'VARCHAR') }}                            as BILL_TO_CITY,
        {{ std_cast('"BILL_TO_CONTACT"', 'VARCHAR') }}                         as BILL_TO_CONTACT,
        {{ std_cast('"YOUR_REFERENCE"', 'VARCHAR') }}                          as YOUR_REFERENCE,
        {{ std_cast('"SHIP_TO_CODE"', 'VARCHAR') }}                            as SHIP_TO_CODE,
        {{ std_cast('"SHIP_TO_NAME"', 'VARCHAR') }}                            as SHIP_TO_NAME,
        {{ std_cast('"SHIP_TO_NAME_2"', 'VARCHAR') }}                          as SHIP_TO_NAME_2,
        {{ std_cast('"SHIP_TO_ADDRESS"', 'VARCHAR') }}                         as SHIP_TO_ADDRESS,
        {{ std_cast('"SHIP_TO_ADDRESS_2"', 'VARCHAR') }}                       as SHIP_TO_ADDRESS_2,
        {{ std_cast('"SHIP_TO_CITY"', 'VARCHAR') }}                            as SHIP_TO_CITY,
        {{ std_cast('"SHIP_TO_CONTACT"', 'VARCHAR') }}                         as SHIP_TO_CONTACT,
        {{ std_cast('"ORDER_DATE"', 'TIMESTAMP_NTZ') }}                        as ORDER_DATE,
        {{ std_cast('"POSTING_DATE"', 'TIMESTAMP_NTZ') }}                      as POSTING_DATE,
        {{ std_cast('"SHIPMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as SHIPMENT_DATE,
        {{ std_cast('"POSTING_DESCRIPTION"', 'VARCHAR') }}                     as POSTING_DESCRIPTION,
        {{ std_cast('"PAYMENT_TERMS_CODE"', 'VARCHAR') }}                      as PAYMENT_TERMS_CODE,
        {{ std_cast('"DUE_DATE"', 'TIMESTAMP_NTZ') }}                          as DUE_DATE,
        {{ std_cast('"PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}                  as PAYMENT_DISCOUNT,
        {{ std_cast('"PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}                 as PMT_DISCOUNT_DATE,
        {{ std_cast('"SHIPMENT_METHOD_CODE"', 'VARCHAR') }}                    as SHIPMENT_METHOD_CODE,
        {{ std_cast('"LOCATION_CODE"', 'VARCHAR') }}                           as LOCATION_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_1_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_1_CODE,
        {{ std_cast('"SHORTCUT_DIMENSION_2_CODE"', 'VARCHAR') }}               as SHORTCUT_DIMENSION_2_CODE,
        {{ std_cast('"CUSTOMER_POSTING_GROUP"', 'VARCHAR') }}                  as CUSTOMER_POSTING_GROUP,
        {{ std_cast('"CURRENCY_CODE"', 'VARCHAR') }}                           as CURRENCY_CODE,
        {{ std_cast('"CURRENCY_FACTOR"', 'NUMBER(38,5)') }}                    as CURRENCY_FACTOR,
        {{ std_cast('"CUSTOMER_PRICE_GROUP"', 'VARCHAR') }}                    as CUSTOMER_PRICE_GROUP,
        {{ std_cast('"PRICES_INCLUDING_VAT"', 'INTEGER') }}                    as PRICES_INCLUDING_VAT,
        {{ std_cast('"INVOICE_DISC_CODE"', 'VARCHAR') }}                       as INVOICE_DISC_CODE,
        {{ std_cast('"CUSTOMER_DISC_GROUP"', 'VARCHAR') }}                     as CUSTOMER_DISC_GROUP,
        {{ std_cast('"LANGUAGE_CODE"', 'VARCHAR') }}                           as LANGUAGE_CODE,
        {{ std_cast('"SALESPERSON_CODE"', 'VARCHAR') }}                        as SALESPERSON_CODE,
        {{ std_cast('"ORDER_CLASS"', 'VARCHAR') }}                             as ORDER_CLASS,
        {{ std_cast('"NO_PRINTED"', 'INTEGER') }}                              as NO_PRINTED,
        {{ std_cast('"ON_HOLD"', 'VARCHAR') }}                                 as ON_HOLD,
        {{ std_cast('"APPLIES_TO_DOC_TYPE"', 'INTEGER') }}                     as APPLIES_TO_DOC_TYPE,
        {{ std_cast('"APPLIES_TO_DOC_NO_"', 'VARCHAR') }}                      as APPLIES_TO_DOC_NO,
        {{ std_cast('"BAL_ACCOUNT_NO_"', 'VARCHAR') }}                         as BAL_ACCOUNT_NO,
        {{ std_cast('"SHIP"', 'INTEGER') }}                                    as SHIP,
        {{ std_cast('"INVOICE"', 'INTEGER') }}                                 as INVOICE,
        {{ std_cast('"PRINT_POSTED_DOCUMENTS"', 'INTEGER') }}                  as PRINT_POSTED_DOCUMENTS,
        {{ std_cast('"SHIPPING_NO_"', 'VARCHAR') }}                            as SHIPPING_NO,
        {{ std_cast('"POSTING_NO_"', 'VARCHAR') }}                             as POSTING_NO,
        {{ std_cast('"LAST_SHIPPING_NO_"', 'VARCHAR') }}                       as LAST_SHIPPING_NO,
        {{ std_cast('"LAST_POSTING_NO_"', 'VARCHAR') }}                        as LAST_POSTING_NO,
        {{ std_cast('"PREPAYMENT_NO_"', 'VARCHAR') }}                          as PREPAYMENT_NO,
        {{ std_cast('"LAST_PREPAYMENT_NO_"', 'VARCHAR') }}                     as LAST_PREPAYMENT_NO,
        {{ std_cast('"PREPMT_CR_MEMO_NO_"', 'VARCHAR') }}                      as PREPMT_CR_MEMO_NO,
        {{ std_cast('"LAST_PREPMT_CR_MEMO_NO_"', 'VARCHAR') }}                 as LAST_PREPMT_CR_MEMO_NO,
        {{ std_cast('"VAT_REGISTRATION_NO_"', 'VARCHAR') }}                    as VAT_REGISTRATION_NO,
        {{ std_cast('"COMBINE_SHIPMENTS"', 'INTEGER') }}                       as COMBINE_SHIPMENTS,
        {{ std_cast('"REASON_CODE"', 'VARCHAR') }}                             as REASON_CODE,
        {{ std_cast('"GEN_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as GEN_BUS_POSTING_GROUP,
        {{ std_cast('"EU_3_PARTY_TRADE"', 'INTEGER') }}                        as EU_3_PARTY_TRADE,
        {{ std_cast('"TRANSACTION_TYPE"', 'VARCHAR') }}                        as TRANSACTION_TYPE,
        {{ std_cast('"TRANSPORT_METHOD"', 'VARCHAR') }}                        as TRANSPORT_METHOD,
        {{ std_cast('"VAT_COUNTRY_REGION_CODE"', 'VARCHAR') }}                 as VAT_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME"', 'VARCHAR') }}                   as SELL_TO_CUSTOMER_NAME,
        {{ std_cast('"SELL_TO_CUSTOMER_NAME_2"', 'VARCHAR') }}                 as SELL_TO_CUSTOMER_NAME_2,
        {{ std_cast('"SELL_TO_ADDRESS"', 'VARCHAR') }}                         as SELL_TO_ADDRESS,
        {{ std_cast('"SELL_TO_ADDRESS_2"', 'VARCHAR') }}                       as SELL_TO_ADDRESS_2,
        {{ std_cast('"SELL_TO_CITY"', 'VARCHAR') }}                            as SELL_TO_CITY,
        {{ std_cast('"SELL_TO_CONTACT"', 'VARCHAR') }}                         as SELL_TO_CONTACT,
        {{ std_cast('"BILL_TO_POST_CODE"', 'VARCHAR') }}                       as BILL_TO_POST_CODE,
        {{ std_cast('"BILL_TO_COUNTY"', 'VARCHAR') }}                          as BILL_TO_COUNTY,
        {{ std_cast('"BILL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as BILL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SELL_TO_POST_CODE"', 'VARCHAR') }}                       as SELL_TO_POST_CODE,
        {{ std_cast('"SELL_TO_COUNTY"', 'VARCHAR') }}                          as SELL_TO_COUNTY,
        {{ std_cast('"SELL_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SELL_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"SHIP_TO_POST_CODE"', 'VARCHAR') }}                       as SHIP_TO_POST_CODE,
        {{ std_cast('"SHIP_TO_COUNTY"', 'VARCHAR') }}                          as SHIP_TO_COUNTY,
        {{ std_cast('"SHIP_TO_COUNTRY_REGION_CODE"', 'VARCHAR') }}             as SHIP_TO_COUNTRY_REGION_CODE,
        {{ std_cast('"BAL_ACCOUNT_TYPE"', 'INTEGER') }}                        as BAL_ACCOUNT_TYPE,
        {{ std_cast('"EXIT_POINT"', 'VARCHAR') }}                              as EXIT_POINT,
        {{ std_cast('"CORRECTION"', 'INTEGER') }}                              as CORRECTION,
        {{ std_cast('"DOCUMENT_DATE"', 'TIMESTAMP_NTZ') }}                     as DOCUMENT_DATE,
        {{ std_cast('"EXTERNAL_DOCUMENT_NO_"', 'VARCHAR') }}                   as EXTERNAL_DOCUMENT_NO,
        {{ std_cast('"AREA"', 'VARCHAR') }}                                    as AREA,
        {{ std_cast('"TRANSACTION_SPECIFICATION"', 'VARCHAR') }}               as TRANSACTION_SPECIFICATION,
        {{ std_cast('"PAYMENT_METHOD_CODE"', 'VARCHAR') }}                     as PAYMENT_METHOD_CODE,
        {{ std_cast('"SHIPPING_AGENT_CODE"', 'VARCHAR') }}                     as SHIPPING_AGENT_CODE,
        {{ std_cast('"PACKAGE_TRACKING_NO_"', 'VARCHAR') }}                    as PACKAGE_TRACKING_NO,
        {{ std_cast('"NO_SERIES"', 'VARCHAR') }}                               as NO_SERIES,
        {{ std_cast('"POSTING_NO_SERIES"', 'VARCHAR') }}                       as POSTING_NO_SERIES,
        {{ std_cast('"SHIPPING_NO_SERIES"', 'VARCHAR') }}                      as SHIPPING_NO_SERIES,
        {{ std_cast('"TAX_AREA_CODE"', 'VARCHAR') }}                           as TAX_AREA_CODE,
        {{ std_cast('"TAX_LIABLE"', 'INTEGER') }}                              as TAX_LIABLE,
        {{ std_cast('"VAT_BUS_POSTING_GROUP"', 'VARCHAR') }}                   as VAT_BUS_POSTING_GROUP,
        {{ std_cast('"RESERVE"', 'INTEGER') }}                                 as RESERVE,
        {{ std_cast('"APPLIES_TO_ID"', 'VARCHAR') }}                           as APPLIES_TO_ID,
        {{ std_cast('"VAT_BASE_DISCOUNT_"', 'NUMBER(38,5)') }}                 as VAT_BASE_DISCOUNT,
        {{ std_cast('"STATUS"', 'INTEGER') }}                                  as STATUS,
        {{ std_cast('"INVOICE_DISCOUNT_CALCULATION"', 'INTEGER') }}            as INVOICE_DISCOUNT_CALCULATION,
        {{ std_cast('"INVOICE_DISCOUNT_VALUE"', 'NUMBER(38,5)') }}             as INVOICE_DISCOUNT_VALUE,
        {{ std_cast('"SEND_IC_DOCUMENT"', 'INTEGER') }}                        as SEND_IC_DOCUMENT,
        {{ std_cast('"IC_STATUS"', 'INTEGER') }}                               as IC_STATUS,
        {{ std_cast('"SELL_TO_IC_PARTNER_CODE"', 'VARCHAR') }}                 as SELL_TO_IC_PARTNER_CODE,
        {{ std_cast('"BILL_TO_IC_PARTNER_CODE"', 'VARCHAR') }}                 as BILL_TO_IC_PARTNER_CODE,
        {{ std_cast('"IC_DIRECTION"', 'INTEGER') }}                            as IC_DIRECTION,
        {{ std_cast('"PREPAYMENT_"', 'NUMBER(38,5)') }}                        as PREPAYMENT,
        {{ std_cast('"PREPAYMENT_NO_SERIES"', 'VARCHAR') }}                    as PREPAYMENT_NO_SERIES,
        {{ std_cast('"COMPRESS_PREPAYMENT"', 'INTEGER') }}                     as COMPRESS_PREPAYMENT,
        {{ std_cast('"PREPAYMENT_DUE_DATE"', 'TIMESTAMP_NTZ') }}               as PREPAYMENT_DUE_DATE,
        {{ std_cast('"PREPMT_CR_MEMO_NO_SERIES"', 'VARCHAR') }}                as PREPMT_CR_MEMO_NO_SERIES,
        {{ std_cast('"PREPMT_POSTING_DESCRIPTION"', 'VARCHAR') }}              as PREPMT_POSTING_DESCRIPTION,
        {{ std_cast('"PREPMT_PMT_DISCOUNT_DATE"', 'TIMESTAMP_NTZ') }}          as PREPMT_PMT_DISCOUNT_DATE,
        {{ std_cast('"PREPMT_PAYMENT_TERMS_CODE"', 'VARCHAR') }}               as PREPMT_PAYMENT_TERMS_CODE,
        {{ std_cast('"PREPMT_PAYMENT_DISCOUNT_"', 'NUMBER(38,5)') }}           as PREPMT_PAYMENT_DISCOUNT,
        {{ std_cast('"QUOTE_NO_"', 'VARCHAR') }}                               as QUOTE_NO,
        {{ std_cast('"JOB_QUEUE_STATUS"', 'INTEGER') }}                        as JOB_QUEUE_STATUS,
        {{ std_cast('"JOB_QUEUE_ENTRY_ID"', 'VARCHAR') }}                      as JOB_QUEUE_ENTRY_ID,
        {{ std_cast('"INCOMING_DOCUMENT_ENTRY_NO_"', 'INTEGER') }}             as INCOMING_DOCUMENT_ENTRY_NO,
        {{ std_cast('"DIMENSION_SET_ID"', 'INTEGER') }}                        as DIMENSION_SET_ID,
        NULL                                                                   as AUTHORIZATION_REQUIRED,
        NULL                                                                   as CREDIT_CARD_NO,
        {{ std_cast('"DIRECT_DEBIT_MANDATE_ID"', 'VARCHAR') }}                 as DIRECT_DEBIT_MANDATE_ID,
        {{ std_cast('"DOC_NO_OCCURRENCE"', 'INTEGER') }}                       as DOC_NO_OCCURRENCE,
        {{ std_cast('"CAMPAIGN_NO_"', 'VARCHAR') }}                            as CAMPAIGN_NO,
        {{ std_cast('"SELL_TO_CUSTOMER_TEMPLATE_CODE"', 'VARCHAR') }}          as SELL_TO_CUSTOMER_TEMPLATE_CODE,
        {{ std_cast('"SELL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as SELL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CONTACT_NO_"', 'VARCHAR') }}                     as BILL_TO_CONTACT_NO,
        {{ std_cast('"BILL_TO_CUSTOMER_TEMPLATE_CODE"', 'VARCHAR') }}          as BILL_TO_CUSTOMER_TEMPLATE_CODE,
        {{ std_cast('"OPPORTUNITY_NO_"', 'VARCHAR') }}                         as OPPORTUNITY_NO,
        {{ std_cast('"RESPONSIBILITY_CENTER"', 'VARCHAR') }}                   as RESPONSIBILITY_CENTER,
        {{ std_cast('"SHIPPING_ADVICE"', 'INTEGER') }}                         as SHIPPING_ADVICE,
        {{ std_cast('"POSTING_FROM_WHSE_REF_"', 'INTEGER') }}                  as POSTING_FROM_WHSE_REF,
        {{ std_cast('"REQUESTED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}           as REQUESTED_DELIVERY_DATE,
        {{ std_cast('"PROMISED_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}            as PROMISED_DELIVERY_DATE,
        {{ std_cast('"SHIPPING_TIME"', 'VARCHAR') }}                           as SHIPPING_TIME,
        {{ std_cast('"OUTBOUND_WHSE_HANDLING_TIME"', 'VARCHAR') }}             as OUTBOUND_WHSE_HANDLING_TIME,
        {{ std_cast('"SHIPPING_AGENT_SERVICE_CODE"', 'VARCHAR') }}             as SHIPPING_AGENT_SERVICE_CODE,
        {{ std_cast('"RECEIVE"', 'INTEGER') }}                                 as RECEIVE,
        {{ std_cast('"RETURN_RECEIPT_NO_"', 'VARCHAR') }}                      as RETURN_RECEIPT_NO,
        {{ std_cast('"RETURN_RECEIPT_NO_SERIES"', 'VARCHAR') }}                as RETURN_RECEIPT_NO_SERIES,
        {{ std_cast('"LAST_RETURN_RECEIPT_NO_"', 'VARCHAR') }}                 as LAST_RETURN_RECEIPT_NO,
        {{ std_cast('"ALLOW_LINE_DISC_"', 'INTEGER') }}                        as ALLOW_LINE_DISC,
        {{ std_cast('"GET_SHIPMENT_USED"', 'INTEGER') }}                       as GET_SHIPMENT_USED,
        {{ std_cast('"ASSIGNED_USER_ID"', 'VARCHAR') }}                        as ASSIGNED_USER_ID,
        {{ std_cast('"CORRECTED_INVOICE_NO_"', 'VARCHAR') }}                   as CORRECTED_INVOICE_NO,
        {{ std_cast('"DUE_DATE_MODIFIED"', 'INTEGER') }}                       as DUE_DATE_MODIFIED,
        NULL                                                                   as QUOTE_END_DATE,
        NULL                                                                   as UPLOAD_DATE,
        NULL                                                                   as SAMPLE_ORDER,
        NULL                                                                   as CONTAINER,
        NULL                                                                   as SEAL,
        NULL                                                                   as TRUCK_LICENSE_PLATE,
        NULL                                                                   as DRIVER,
        NULL                                                                   as AUTHORIZE_ORDER,
        NULL                                                                   as TRAILER_LICENSE_PLATE,
        NULL                                                                   as PENDING_AUTHORIZE_ORDER,
        NULL                                                                   as RISK_EXCEEDED,
        NULL                                                                   as BANK_ACCOUNT_TO_TRANSFER,
        NULL                                                                   as TRIP_NO,
        NULL                                                                   as FILE_GENERATED,
        NULL                                                                   as ESTADO_EDI,
        NULL                                                                   as MOTIVO_DEVOLUCION_EDI,
        NULL                                                                   as DEPARTAMENTO_EDI,
        NULL                                                                   as SHIPMENT_LANGUAGE_CODE,
        NULL                                                                   as HEADER_DISCOUNT,
        NULL                                                                   as SALES_RETURN,
        NULL                                                                   as RAPPEL,
        NULL                                                                   as LOAD_TIME,
        NULL                                                                   as LOAD_HR,
        NULL                                                                   as SALES_INV_PROFORMA,
        NULL                                                                   as SHIPMENT_ZONE_CODE,
        {{ std_cast('"INVOICE_CANCELATION"', 'INTEGER') }}                     as INVOICE_CANCELATION,
        {{ std_cast('"CORRECTED_INVOICE_TYPE"', 'INTEGER') }}                  as CORRECTED_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_TYPE"', 'INTEGER') }}                         as SIMPLIFIED_TYPE,
        {{ std_cast('"FROM_TICKET_NO_"', 'VARCHAR') }}                         as FROM_TICKET_NO,
        {{ std_cast('"TO_TICKET_NO_"', 'VARCHAR') }}                           as TO_TICKET_NO,
        {{ std_cast('"APPLIES_TO_BILL_NO_"', 'VARCHAR') }}                     as APPLIES_TO_BILL_NO,
        {{ std_cast('"CUST_BANK_ACC_CODE"', 'VARCHAR') }}                      as CUST_BANK_ACC_CODE,
        {{ std_cast('"PAY_AT_CODE"', 'VARCHAR') }}                             as PAY_AT_CODE,
        NULL                                                                   as NO_TELEFONO_ENVIO,
        NULL                                                                   as OBSERVACIONES_ENVIO,
        NULL                                                                   as PESO_NETO,
        NULL                                                                   as PESO_BRUTO,
        NULL                                                                   as FORMA_PAGO_FACTURAPLUS,
        NULL                                                                   as VALUED_SHIPMENT,
        NULL                                                                   as DROP_SHIPMENT,
        NULL                                                                   as SIN_MOVS_ALMACEN,
        NULL                                                                   as EN_FACTURACION_AUTOMATICA,
        NULL                                                                   as FECHA_CONFIRMACION_PACKING,
        NULL                                                                   as ANULACION_AUTOMATICA,
        NULL                                                                   as USUARIO_ALTA,
        NULL                                                                   as JEFE_DE_VENTAS,
        NULL                                                                   as JEFE_DE_ZONA,
        NULL                                                                   as HEREDA_COND_GRUPO,
        NULL                                                                   as NO_EXPEDICION,
        NULL                                                                   as NO_ALBARAN_AGENCIA,
        NULL                                                                   as CASH_ENTRY,
        {{ std_cast('"SPETIAL_OPERATION_TYPE"', 'INTEGER') }}                  as SPETIAL_OPERATION_TYPE,
        {{ std_cast('"SPETIAL_OPERATION_CODE"', 'VARCHAR') }}                  as SPETIAL_OPERATION_CODE,
        {{ std_cast('"GROUP_SHIPMENT_TYPE"', 'INTEGER') }}                     as GROUP_SHIPMENT_TYPE,
        {{ std_cast('"SHIPMENT_FREQUENCY"', 'INTEGER') }}                      as SHIPMENT_FREQUENCY,
        NULL                                                                   as INVOICE_DETAIL,
        NULL                                                                   as RETENER_FACTURACION,
        NULL                                                                   as NO_FACTURA_ANULADA,
        NULL                                                                   as ANULACION_DE_FACTURA,
        NULL                                                                   as PRINT_BY_CONCEPT,
        NULL                                                                   as PEDIDO_SINCRON_AUTOMATICA,
        NULL                                                                   as EMPRESA_ORIGEN,
        NULL                                                                   as NO_PROV_EN_CLIENTE,
        NULL                                                                   as ANULADO,
        NULL                                                                   as ODS_JOB_TEMPLATE_CODE,
        NULL                                                                   as OPERATION_DATE,
        NULL                                                                   as TO_DOCUMENT_NO,
        NULL                                                                   as FROM_DOCUMENT_NO,
        NULL                                                                   as REGIMEN,
        NULL                                                                   as SII_CORRECTION_TYPE,
        NULL                                                                   as SII_OPERATION_DESCRIPTION,
        NULL                                                                   as SII_INVOICE_TYPE,
        {{ std_cast('"SIMPLIFIED_INVOICE"', 'INTEGER') }}                      as SIMPLIFIED_INVOICE,
        NULL                                                                   as SIMPLIFIED_ART_6_1_D,
        NULL                                                                   as REFEXTERNA,
        {{ std_cast('"TAX_FREE"', 'INTEGER') }}                                as TAX_FREE,
        NULL                                                                   as NUM_REGISTRO_ACUERDO_FACT,
        NULL                                                                   as EMITIDA_POR_TERCERO,
        NULL                                                                   as EMITIDA_POR_NORMATIVA_DEL_GAS,
        NULL                                                                   as COMPLETELY_INVOICED,
        NULL                                                                   as IPAD_ORDER,
        NULL                                                                   as WITHOUT_PLASTIC_DECLARATION,
        NULL                                                                   as FECHAEPRDT,
        NULL                                                                   as FECHATODT,
        {{ std_cast('"TEC_DES_EMPRESA"', 'VARCHAR') }}                         as TEC_DES_EMPRESA,
        {{ std_cast('"TEC_ID_INGESTA"', 'VARCHAR') }}                          as TEC_ID_INGESTA,
        {{ std_cast('"TEC_TS_INGESTA"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_INGESTA,
        {{ std_cast('"TEC_TS_STAGING"', 'TIMESTAMP_NTZ') }}                    as TEC_TS_STAGING,
        {{ std_cast('"TEC_TS_INTEGRACION_B"', 'TIMESTAMP_NTZ') }}              as TEC_TS_INTEGRACION_B,
        NULL                                                                   as SELLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_CUSTOMER_NO,
        NULL                                                                   as BILLTO_NAME,
        NULL                                                                   as BILLTO_NAME_2,
        NULL                                                                   as BILLTO_ADDRESS,
        NULL                                                                   as BILLTO_ADDRESS_2,
        NULL                                                                   as BILLTO_CITY,
        NULL                                                                   as BILLTO_CONTACT,
        NULL                                                                   as SHIPTO_CODE,
        NULL                                                                   as SHIPTO_NAME,
        NULL                                                                   as SHIPTO_NAME_2,
        NULL                                                                   as SHIPTO_ADDRESS,
        NULL                                                                   as SHIPTO_ADDRESS_2,
        NULL                                                                   as SHIPTO_CITY,
        NULL                                                                   as SHIPTO_CONTACT,
        NULL                                                                   as APPLIESTO_DOC_TYPE,
        NULL                                                                   as APPLIESTO_DOC_NO,
        NULL                                                                   as EU_3PARTY_TRADE,
        NULL                                                                   as SELLTO_CUSTOMER_NAME,
        NULL                                                                   as SELLTO_CUSTOMER_NAME_2,
        NULL                                                                   as SELLTO_ADDRESS,
        NULL                                                                   as SELLTO_ADDRESS_2,
        NULL                                                                   as SELLTO_CITY,
        NULL                                                                   as SELLTO_CONTACT,
        NULL                                                                   as BILLTO_POST_CODE,
        NULL                                                                   as BILLTO_COUNTY,
        NULL                                                                   as BILLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SELLTO_POST_CODE,
        NULL                                                                   as SELLTO_COUNTY,
        NULL                                                                   as SELLTO_COUNTRY_REGION_CODE,
        NULL                                                                   as SHIPTO_POST_CODE,
        NULL                                                                   as SHIPTO_COUNTY,
        NULL                                                                   as SHIPTO_COUNTRY_REGION_CODE,
        NULL                                                                   as APPLIESTO_ID,
        NULL                                                                   as ESTADO,
        NULL                                                                   as SELLTO_IC_PARTNER_CODE,
        NULL                                                                   as BILLTO_IC_PARTNER_CODE,
        NULL                                                                   as QUOTE_VALID_UNTIL_DATE,
        NULL                                                                   as QUOTE_SENT_TO_CUSTOMER,
        NULL                                                                   as QUOTE_ACCEPTED,
        NULL                                                                   as QUOTE_ACCEPTED_DATE,
        NULL                                                                   as ISTEST,
        NULL                                                                   as PAYMENT_INSTRUCTIONS_ID,
        {{ std_cast('"PAYMENT_SERVICE_SET_ID"', 'INTEGER') }}                  as PAYMENT_SERVICE_SET_ID,
        NULL                                                                   as SELLTO_CUSTOMER_TEMPLATE_CODE,
        NULL                                                                   as SELLTO_CONTACT_NO,
        NULL                                                                   as BILLTO_CONTACT_NO,
        NULL                                                                   as BILLTO_CUSTOMER_TEMPLATE_CODE,
        NULL                                                                   as ID,
        {{ std_cast('"INVOICE_TYPE"', 'INTEGER') }}                            as INVOICE_TYPE,
        {{ std_cast('"CR_MEMO_TYPE"', 'INTEGER') }}                            as CR_MEMO_TYPE,
        {{ std_cast('"SPECIAL_SCHEME_CODE"', 'INTEGER') }}                     as SPECIAL_SCHEME_CODE,
        {{ std_cast('"OPERATION_DESCRIPTION"', 'VARCHAR') }}                   as OPERATION_DESCRIPTION,
        {{ std_cast('"CORRECTION_TYPE"', 'INTEGER') }}                         as CORRECTION_TYPE,
        {{ std_cast('"OPERATION_DESCRIPTION_2"', 'VARCHAR') }}                 as OPERATION_DESCRIPTION_2,
        {{ std_cast('"SUCCEEDED_COMPANY_NAME"', 'VARCHAR') }}                  as SUCCEEDED_COMPANY_NAME,
        {{ std_cast('"SUCCEEDED_VAT_REGISTRATION_NO_"', 'VARCHAR') }}          as SUCCEEDED_VAT_REGISTRATION_NO,
        NULL                                                                   as APPLIESTO_BILL_NO,
        NULL                                                                   as PAYAT_CODE,
        NULL                                                                   as IDPIRPF_IRPF_GROUP,
        NULL                                                                   as IDPGND_SHIPTO_EXCL_SIG_RATE,
        NULL                                                                   as IF_OR_TYPE,
        NULL                                                                   as IF_DATA_1,
        NULL                                                                   as IF_DATA_2,
        NULL                                                                   as IF_DATA_3,
        NULL                                                                   as IF_DATA_4,
        NULL                                                                   as IF_DATA_5,
        NULL                                                                   as IF_ML_TIME,
        NULL                                                                   as IF_SAE_CERTIFICATION,
        NULL                                                                   as CO_ID_CONT,
        NULL                                                                   as CO_ID_PREC,
        NULL                                                                   as TOTALNETWEIGHT,
        NULL                                                                   as TOTALGROSSWEIGHT,
        NULL                                                                   as PACKAGESPALLETNUMBER,
        NULL                                                                   as PACKAGESNUMBER,
        NULL                                                                   as SII_NUMDESDE,
        NULL                                                                   as SII_NUMHASTA,
        NULL                                                                   as SII_FACARRENDAMIENTO,
        NULL                                                                   as SII_UBICACIONPROPIEDAD,
        NULL                                                                   as SII_INMUEBLESADICIONALES,
        NULL                                                                   as SII_NUMCUENTAIMPUESTO,
        NULL                                                                   as SALES_DATE,
        NULL                                                                   as SYSTEM_DATE,
        NULL                                                                   as CERRADO,
        NULL                                                                   as AIT_BILLING_ADDRESS_CODE,
        NULL                                                                   as IDPCIN_ALLOW_CREDIT_EXCEEDED,
        NULL                                                                   as IDPEDI_DOCUMENT,
        NULL                                                                   as IDPEDI_ORDRSP,
        NULL                                                                   as IDPEDI_ORDRSP_SENT,
        NULL                                                                   as IDPEDI_INTERLOCUTOR_CODE,
        NULL                                                                   as IDPEDI_ORDRSP_RESPONSE_CODE,
        NULL                                                                   as IDPEDI_INVOIC,
        NULL                                                                   as IDPEDI_ORDRSP_REVIEWED,
        NULL                                                                   as IDPEDI_DESADV,
        NULL                                                                   as IDPEDI_RECADV,
        NULL                                                                   as IDPVUM_UPDATE_SOURCE,
        NULL                                                                   as AIT_CREATION_USER,
        NULL                                                                   as AIT_CREATION_DATETIME,
        NULL                                                                   as AIT_RIESGOSUPERADO,
        {{ std_cast('"BLOQUEAR_PROMOCIONES"', 'INTEGER') }}                    as BLOQUEAR_PROMOCIONES,
        {{ std_cast('"COD_CADENA"', 'VARCHAR') }}                              as COD_CADENA,
        {{ std_cast('"PROMOCIONES_POR"', 'INTEGER') }}                         as PROMOCIONES_POR,
        {{ std_cast('"COD_DTO_LINEA"', 'VARCHAR') }}                           as COD_DTO_LINEA,
        {{ std_cast('"CALCULAR_RAPPEL"', 'INTEGER') }}                         as CALCULAR_RAPPEL,
        {{ std_cast('"TIPO_PEDIDO"', 'INTEGER') }}                             as TIPO_PEDIDO,
        {{ std_cast('"TIPO_PUNTO_VERDE"', 'INTEGER') }}                        as TIPO_PUNTO_VERDE,
        {{ std_cast('"COD_RUTA"', 'VARCHAR') }}                                as COD_RUTA,
        {{ std_cast('"PREFACTURAR_SERVICIO"', 'INTEGER') }}                    as PREFACTURAR_SERVICIO,
        {{ std_cast('"ZONA_TRANSPORTE"', 'VARCHAR') }}                         as ZONA_TRANSPORTE,
        {{ std_cast('"TEMPERATURA_EXP_"', 'NUMBER(38,5)') }}                   as TEMPERATURA_EXP,
        {{ std_cast('"ESTADO_LIMPIEZA"', 'INTEGER') }}                         as ESTADO_LIMPIEZA,
        {{ std_cast('"ESTADO_PALETIZADO"', 'INTEGER') }}                       as ESTADO_PALETIZADO,
        {{ std_cast('"ORIGEN"', 'INTEGER') }}                                  as ORIGEN,
        {{ std_cast('"OBSERVACIONES_PICKING"', 'VARCHAR') }}                   as OBSERVACIONES_PICKING,
        {{ std_cast('"OBSERVACIONES_RECOGIDA"', 'VARCHAR') }}                  as OBSERVACIONES_RECOGIDA,
        {{ std_cast('"OBSERVACIONES_CARTA_PORTES"', 'VARCHAR') }}              as OBSERVACIONES_CARTA_PORTES,
        {{ std_cast('"NATURALEZA_PRODUCTO"', 'VARCHAR') }}                     as NATURALEZA_PRODUCTO,
        {{ std_cast('"DOC_TRANSPORTE"', 'INTEGER') }}                          as DOC_TRANSPORTE,
        {{ std_cast('"NO_ENVIO"', 'VARCHAR') }}                                as NO_ENVIO,
        {{ std_cast('"COD_PALET"', 'VARCHAR') }}                               as COD_PALET,
        {{ std_cast('"TIPO_RESIDUOS"', 'INTEGER') }}                           as TIPO_RESIDUOS,
        {{ std_cast('"COD_IDIOMA_ETIQUETAJE"', 'VARCHAR') }}                   as COD_IDIOMA_ETIQUETAJE,
        {{ std_cast('"HORARIO_ENTREGA"', 'VARCHAR') }}                         as HORARIO_ENTREGA,
        {{ std_cast('"NO_CAJAS_POR_PALET"', 'INTEGER') }}                      as NO_CAJAS_POR_PALET,
        {{ std_cast('"MATRICULA_VEHICULO"', 'VARCHAR') }}                      as MATRICULA_VEHICULO,
        {{ std_cast('"CONDUCTOR"', 'VARCHAR') }}                               as CONDUCTOR,
        {{ std_cast('"NIF_CONDUCTOR"', 'VARCHAR') }}                           as NIF_CONDUCTOR,
        {{ std_cast('"MATRICULA_REMOLQUE"', 'VARCHAR') }}                      as MATRICULA_REMOLQUE,
        {{ std_cast('"CAPACIDAD_MAX_PALETS"', 'INTEGER') }}                    as CAPACIDAD_MAX_PALETS,
        {{ std_cast('"NO_PEDIDO_ORIGEN"', 'VARCHAR') }}                        as NO_PEDIDO_ORIGEN,
        {{ std_cast('"RECUPERACION_EDI"', 'INTEGER') }}                        as RECUPERACION_EDI,
        {{ std_cast('"ALBARAN_VALORADO"', 'INTEGER') }}                        as ALBARAN_VALORADO,
        {{ std_cast('"TIPO_FACTURACION"', 'INTEGER') }}                        as TIPO_FACTURACION,
        {{ std_cast('"FACTURA_POR_ALBARAN"', 'INTEGER') }}                     as FACTURA_POR_ALBARAN,
        {{ std_cast('"PREINVOICE"', 'INTEGER') }}                              as PREINVOICE,
        {{ std_cast('"SPLIT_SHIP_TO_ADD_"', 'INTEGER') }}                      as SPLIT_SHIP_TO_ADD,
        {{ std_cast('"_DTO_FACTURA"', 'NUMBER(38,5)') }}                       as DTO_FACTURA,
        {{ std_cast('"COD_BANCO"', 'VARCHAR') }}                               as COD_BANCO,
        {{ std_cast('"_COMMISSION_SALESPERSON"', 'NUMBER(38,5)') }}            as COMMISSION_SALESPERSON,
        {{ std_cast('"_2ND_SALESPERSON_CODE"', 'VARCHAR') }}                   as "2nd_salesperson_code",
        {{ std_cast('"_COMMISSION_2ND_SALESPERSON"', 'NUMBER(38,5)') }}        as COMMISSION_2ND_SALESPERSON,
        {{ std_cast('"INCOME_TAX_RETENTION_CODE"', 'VARCHAR') }}               as INCOME_TAX_RETENTION_CODE,
        {{ std_cast('"INCOME_TAX_RETENTION_"', 'NUMBER(38,5)') }}              as INCOME_TAX_RETENTION,
        {{ std_cast('"INCOME_TAX_RETENTION_KEY"', 'VARCHAR') }}                as INCOME_TAX_RETENTION_KEY,
        {{ std_cast('"INCOME_TAX_RETENTION_SUBKEY"', 'VARCHAR') }}             as INCOME_TAX_RETENTION_SUBKEY,
        {{ std_cast('"POSTING_STATUS"', 'INTEGER') }}                          as POSTING_STATUS,
        {{ std_cast('"SHIP_POSTING"', 'INTEGER') }}                            as SHIP_POSTING,
        {{ std_cast('"INVOICE_POSTING"', 'INTEGER') }}                         as INVOICE_POSTING,
        {{ std_cast('"POSTING_IN_ERROR"', 'INTEGER') }}                        as POSTING_IN_ERROR,
        {{ std_cast('"EDI_HORA_ENTREGA"', 'TIMESTAMP_NTZ') }}                  as EDI_HORA_ENTREGA,
        {{ std_cast('"CONTROLAR_PR_MIN_"', 'INTEGER') }}                       as CONTROLAR_PR_MIN,
        {{ std_cast('"ESTADO_CALIDAD"', 'INTEGER') }}                          as ESTADO_CALIDAD,
        {{ std_cast('"CODIGO_CALIDAD"', 'VARCHAR') }}                          as CODIGO_CALIDAD,
        {{ std_cast('"TAX_FREE_VENDOR_NO_"', 'VARCHAR') }}                     as TAX_FREE_VENDOR_NO,
        {{ std_cast('"CUSTOMER_SALES_DEPARTMENT"', 'VARCHAR') }}               as CUSTOMER_SALES_DEPARTMENT,
        {{ std_cast('"EDI_BLOCKED"', 'INTEGER') }}                             as EDI_BLOCKED,
        {{ std_cast('"DESADV_NO_"', 'VARCHAR') }}                              as DESADV_NO,
        {{ std_cast('"PLANNING_DELIVERY_DATE"', 'TIMESTAMP_NTZ') }}            as PLANNING_DELIVERY_DATE,
        {{ std_cast('"INVOICE_BLOCKED"', 'INTEGER') }}                         as INVOICE_BLOCKED,
        {{ std_cast('"INTERCOMPANY_INVOICE"', 'INTEGER') }}                    as INTERCOMPANY_INVOICE,
        {{ std_cast('"HIDE_DIALOGUE"', 'INTEGER') }}                           as HIDE_DIALOGUE,
        {{ std_cast('"CUSTOMER_RECEPTION_NO_"', 'VARCHAR') }}                  as CUSTOMER_RECEPTION_NO,
        {{ std_cast('"EDI_ORDER_NO_"', 'VARCHAR') }}                           as EDI_ORDER_NO,
        {{ std_cast('"SALES_SHIPMENT_NO_"', 'VARCHAR') }}                      as SALES_SHIPMENT_NO,
        {{ std_cast('"FIX_SALES_PRICE"', 'INTEGER') }}                         as FIX_SALES_PRICE,
        'FRI'                                                                     as tec_des_cod_siglas
    from {{ src_ref }}
    where tec_id_ingesta = (select tec_id_ingesta from next_log)
)
select *
from src
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY no
    ORDER BY tec_ts_ingesta DESC, TIMESTAMP DESC
) = 1
