{{ config(
    materialized='incremental',
    database='PROD_SILVER' if target.name == 'prod' else 'DEV_SILVER', schema='SILVER_GC_GRUPO',
    incremental_strategy='append',
    tags=['silver','integ'],
    pre_hook=[
        "{% if is_incremental() %}
        -- (tec_cod_vigencia = 1 --> 0) Marcar como no vigentes registros con match y alguna diferencia. fec_negocio - 1 día (o mismo día si coincide inicio)
        merge into {{ this }} t
        using (
            select
                tec_des_empresa,
                HASH(TIMESTAMP, DOCUMENT_NO, LINE_NO, SELL_TO_CUSTOMER_NO, SELLTO_CUSTOMER_NO, TYPE, NO, LOCATION_CODE, POSTING_GROUP, SHIPMENT_DATE, DESCRIPTION, DESCRIPTION_2, UNIT_OF_MEASURE, QUANTITY, UNIT_PRICE, UNIT_COST_LCY, VAT, LINE_DISCOUNT, LINE_DISCOUNT_AMOUNT, AMOUNT, AMOUNT_INCLUDING_VAT, ALLOW_INVOICE_DISC, GROSS_WEIGHT, NET_WEIGHT, UNITS_PER_PARCEL, UNIT_VOLUME, APPL_TO_ITEM_ENTRY, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_PRICE_GROUP, JOB_NO, WORK_TYPE_CODE, SHIPMENT_NO, SHIPMENT_LINE_NO, BILL_TO_CUSTOMER_NO, ORDER_NO, INV_DISCOUNT_AMOUNT, ORDER_LINE_NO, DROP_SHIPMENT, BILLTO_CUSTOMER_NO, GEN_BUS_POSTING_GROUP, GEN_PROD_POSTING_GROUP, VAT_CALCULATION_TYPE, TRANSACTION_TYPE, TRANSPORT_METHOD, ATTACHED_TO_LINE_NO, EXIT_POINT, AREA, TRANSACTION_SPECIFICATION, TAX_CATEGORY, TAX_AREA_CODE, TAX_LIABLE, TAX_GROUP_CODE, VAT_CLAUSE_CODE, VAT_BUS_POSTING_GROUP, VAT_PROD_POSTING_GROUP, BLANKET_ORDER_NO, BLANKET_ORDER_LINE_NO, VAT_BASE_AMOUNT, UNIT_COST, SYSTEM_CREATED_ENTRY, LINE_AMOUNT, VAT_DIFFERENCE, SYSTEMCREATED_ENTRY, VAT_IDENTIFIER, IC_PARTNER_REF_TYPE, IC_PARTNER_REFERENCE, PREPAYMENT_LINE, IC_PARTNER_CODE, POSTING_DATE, DIMENSION_SET_ID, JOB_TASK_NO, JOB_CONTRACT_ENTRY_NO, PMT_DISCOUNT_AMOUNT, DEFERRAL_CODE, LINE_DISCOUNT_CALCULATION, VARIANT_CODE, BIN_CODE, QTY_PER_UNIT_OF_MEASURE, UNIT_OF_MEASURE_CODE, QUANTITY_BASE, FA_POSTING_DATE, DEPRECIATION_BOOK_CODE, DEPR_UNTIL_FA_POSTING_DATE, DUPLICATE_IN_DEPRECIATION_BOOK, USE_DUPLICATION_LIST, RESPONSIBILITY_CENTER, CROSS_REFERENCE_NO, UNIT_OF_MEASURE_CROSS_REF, CROSS_REFERENCE_TYPE, CROSS_REFERENCE_TYPE_NO, CROSSREFERENCE_NO, ITEM_CATEGORY_CODE, NONSTOCK, PURCHASING_CODE, CROSSREFERENCE_TYPE, PRODUCT_GROUP_CODE, CROSSREFERENCE_TYPE_NO, APPL_FROM_ITEM_ENTRY, RETURN_REASON_CODE, ALLOW_LINE_DISC, CUSTOMER_DISC_GROUP, PMT_DISC_GIVEN_AMOUNT, EC, EC_DIFFERENCE, COD_CADENA, MURANO_CODE, PROMOCIONES_POR, PRICE_DESCRIPTION, MIGRATION_LOT_NO, NO_ALBARAN_VENTA, PMT_DISC_GIVEN_AMOUNT_OLD, COMISIONES_POR, CODIGO_EMBALAJE, NO_LINEA_ALBARAN_VENTA, CANTIDAD_EMBALAJE, COD_VENDEDOR_1, CANTIDAD_UNIDADES, COD_VENDEDOR_2, IDPIRPF_IRPF_GROUP, COD_VENDEDOR_3, CANTIDAD_KILOS, IDPIRPF_IRPF_AMOUNT, IDPIRPF_IRPF, NO_PRESENTACION, COM_1, IDPIRPF_IRPF_BASE_AMOUNT, COM_2, DESCRIPCION_PRESENTACION, COM_3, IDPVUM_QUANTITY, OBSERVACIONES, MOTIVO_DEVOLUCION, IDPVUM_UNIT_OF_MEASURE_CODE, DTO_1, SERVICIO, TIPO_DTO_2, IDPVUM_UNIT_PRICE, IDPVUM_PRICE_IN_VUM, DTO_2, PRECIO_PUNTO_VERDE_CDAD, UNIDAD_MEDIDA_PUNTO_VERDE, IDPVUM_VUM_PER_UNIT, TIPO_DTO_3, CERRADO, IMPORTE_PUNTO_VERDE, DTO_3, GRUPO_RESIDUOS, TIPO_DTO_4, TEMPQTY, PRECIO_RESIDUOS_CDAD, DTO_4, ORIGINAL_QUANTITY, UNIDAD_MEDIDA_RESIDUOS, TIPO_DTO_5, ORIGINAL_QUANTITY_UMV, IMPORTE_RESIDUOS, IDPGND_SIG_AMOUNT, DTO_5, IDPGND_SIG_RATE, NEGRILLA, INCOME_TAX_RETENTION_CODE, IDPGND_SIG, BASE_RAPPEL, INCOME_TAX_RETENTION, IDPGND_POSTING_DATE_SHIPMENT, IMPORTE_PROVISIONADO, INCOME_TAX_BASE, IDPGND_SHIPMENT_DATE_SHIPMENT, IMPORTE_DESPROVISIONADO, SALESPERSON_CODE, COMMISSION_SALESPERSON, IDPGND_REQ_DEL_DATE_SHIPMENT, NO_CUENTA_PROVISION_VENTA, 2ND_SALESPERSON_CODE, NO_CUENTA_PROVISION_CLIENTE, IDPGND_PACKAGING_FORMAT_NO, CLAIM_CODE, COMMISSION_2ND_SALESPERSON, IF_OR_TYPE, SPECIAL_LINE_TYPE, W_ITEM_ENTRIES, IF_UNIT_PRICE_CODE, SALES_SHIPMENT_NO, IF_NUM_BOXES_NEEDED, REAL_SHIPMENT_DATE, SALES_SHIPMENT_LINE_NO, IF_NUM_CONT_NEEDED, CREATION_DATE, TARIFF_NO, IF_DUN14, PLATES_SHIPPED, VAT_BREAKDOWN, TEC_DES_EMPRESA, EDI_POSITION, TEC_ID_INGESTA, Q_CONFIRMADA_RECADV, TYPE_BREAKDOWN, CADASTRAL_REFERENCE, RECADCV_QUANTITY, TEC_TS_INGESTA, TEC_TS_STAGING, EDI_POSITION_SUBLINE, PROPERTY_SITUATION, GLN, TEC_TS_INTEGRACION_B, PLASTIC_LINE, EDI_PRICE, EDI_DISCOUNT) AS tec_hash,
                date(tec_ts_ingesta) as tec_fec_inicio
            from {{ ref('sales_invoice_line_batch') }}
        ) s
        on t.tec_cod_vigencia = 1
            and 1=1
        when matched and t.tec_hash <> s.tec_hash then
            update set
                tec_cod_vigencia = 0,
                tec_fec_fin = case
                    when s.tec_fec_inicio = t.tec_fec_inicio then s.tec_fec_inicio
                    else dateadd(day, -1, s.tec_fec_inicio)
                end;
        {% endif %}"
    ],
    post_hook=[
        "{% set log_ref = source('support_param', 'INSERT_LOGS') %}{% set asociados = var('empresas', []) %}{% for a in asociados %}
            {% set src_ref = source('bronze_' ~ a, 'COOPECARN_SALES_INVOICE_LINE') %}
            -- Sella ÚNICAMENTE el batch (tec_id_ingesta) que está procesando la view {{ ref('sales_invoice_line_batch_' ~ a) }}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref.database }}')
              and upper(l.schema)     = upper('{{ src_ref.schema }}')
              and upper(l.table_name) = upper('{{ src_ref.identifier }}')
              and exists (
                  select 1
                  from {{ ref('sales_invoice_line_batch_' ~ a) }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );
        {% endfor %}"
    ]
) }}

with source as (
    select
        timestamp, 
        document_no, 
        line_no, 
        sell_to_customer_no, 
        sellto_customer_no, 
        type, 
        no, 
        location_code, 
        posting_group, 
        shipment_date, 
        description, 
        description_2, 
        unit_of_measure, 
        quantity, 
        unit_price, 
        unit_cost_lcy, 
        vat, 
        line_discount, 
        line_discount_amount, 
        amount, 
        amount_including_vat, 
        allow_invoice_disc, 
        gross_weight, 
        net_weight, 
        units_per_parcel, 
        unit_volume, 
        appl_to_item_entry, 
        shortcut_dimension_1_code, 
        shortcut_dimension_2_code, 
        customer_price_group, 
        job_no, 
        work_type_code, 
        shipment_no, 
        shipment_line_no, 
        bill_to_customer_no, 
        order_no, 
        inv_discount_amount, 
        order_line_no, 
        drop_shipment, 
        billto_customer_no, 
        gen_bus_posting_group, 
        gen_prod_posting_group, 
        vat_calculation_type, 
        transaction_type, 
        transport_method, 
        attached_to_line_no, 
        exit_point, 
        area, 
        transaction_specification, 
        tax_category, 
        tax_area_code, 
        tax_liable, 
        tax_group_code, 
        vat_clause_code, 
        vat_bus_posting_group, 
        vat_prod_posting_group, 
        blanket_order_no, 
        blanket_order_line_no, 
        vat_base_amount, 
        unit_cost, 
        system_created_entry, 
        line_amount, 
        vat_difference, 
        systemcreated_entry, 
        vat_identifier, 
        ic_partner_ref_type, 
        ic_partner_reference, 
        prepayment_line, 
        ic_partner_code, 
        posting_date, 
        dimension_set_id, 
        job_task_no, 
        job_contract_entry_no, 
        pmt_discount_amount, 
        deferral_code, 
        line_discount_calculation, 
        variant_code, 
        bin_code, 
        qty_per_unit_of_measure, 
        unit_of_measure_code, 
        quantity_base, 
        fa_posting_date, 
        depreciation_book_code, 
        depr_until_fa_posting_date, 
        duplicate_in_depreciation_book, 
        use_duplication_list, 
        responsibility_center, 
        cross_reference_no, 
        unit_of_measure_cross_ref, 
        cross_reference_type, 
        cross_reference_type_no, 
        crossreference_no, 
        item_category_code, 
        nonstock, 
        purchasing_code, 
        crossreference_type, 
        product_group_code, 
        crossreference_type_no, 
        appl_from_item_entry, 
        return_reason_code, 
        allow_line_disc, 
        customer_disc_group, 
        pmt_disc_given_amount, 
        ec, 
        ec_difference, 
        cod_cadena, 
        murano_code, 
        promociones_por, 
        price_description, 
        migration_lot_no, 
        no_albaran_venta, 
        pmt_disc_given_amount_old, 
        comisiones_por, 
        codigo_embalaje, 
        no_linea_albaran_venta, 
        cantidad_embalaje, 
        cod_vendedor_1, 
        cantidad_unidades, 
        cod_vendedor_2, 
        idpirpf_irpf_group, 
        cod_vendedor_3, 
        cantidad_kilos, 
        idpirpf_irpf_amount, 
        idpirpf_irpf, 
        no_presentacion, 
        com_1, 
        idpirpf_irpf_base_amount, 
        com_2, 
        descripcion_presentacion, 
        com_3, 
        idpvum_quantity, 
        observaciones, 
        motivo_devolucion, 
        idpvum_unit_of_measure_code, 
        dto_1, 
        servicio, 
        tipo_dto_2, 
        idpvum_unit_price, 
        idpvum_price_in_vum, 
        dto_2, 
        precio_punto_verde_cdad, 
        unidad_medida_punto_verde, 
        idpvum_vum_per_unit, 
        tipo_dto_3, 
        cerrado, 
        importe_punto_verde, 
        dto_3, 
        grupo_residuos, 
        tipo_dto_4, 
        tempqty, 
        precio_residuos_cdad, 
        dto_4, 
        original_quantity, 
        unidad_medida_residuos, 
        tipo_dto_5, 
        original_quantity_umv, 
        importe_residuos, 
        idpgnd_sig_amount, 
        dto_5, 
        idpgnd_sig_rate, 
        negrilla, 
        income_tax_retention_code, 
        idpgnd_sig, 
        base_rappel, 
        income_tax_retention, 
        idpgnd_posting_date_shipment, 
        importe_provisionado, 
        income_tax_base, 
        idpgnd_shipment_date_shipment, 
        importe_desprovisionado, 
        salesperson_code, 
        commission_salesperson, 
        idpgnd_req_del_date_shipment, 
        no_cuenta_provision_venta, 
        2nd_salesperson_code, 
        no_cuenta_provision_cliente, 
        idpgnd_packaging_format_no, 
        claim_code, 
        commission_2nd_salesperson, 
        if_or_type, 
        special_line_type, 
        w_item_entries, 
        if_unit_price_code, 
        sales_shipment_no, 
        if_num_boxes_needed, 
        real_shipment_date, 
        sales_shipment_line_no, 
        if_num_cont_needed, 
        creation_date, 
        tariff_no, 
        if_dun14, 
        plates_shipped, 
        vat_breakdown, 
        tec_des_empresa, 
        edi_position, 
        tec_id_ingesta, 
        q_confirmada_recadv, 
        type_breakdown, 
        cadastral_reference, 
        recadcv_quantity, 
        tec_ts_ingesta, 
        tec_ts_staging, 
        edi_position_subline, 
        property_situation, 
        gln, 
        tec_ts_integracion_b, 
        plastic_line, 
        edi_price, 
        edi_discount, 
        tec_des_cod_siglas, 
        tec_des_empresa, 
        tec_id_ingesta, 
        tec_ts_ingesta, 
        HASH(TIMESTAMP, DOCUMENT_NO, LINE_NO, SELL_TO_CUSTOMER_NO, SELLTO_CUSTOMER_NO, TYPE, NO, LOCATION_CODE, POSTING_GROUP, SHIPMENT_DATE, DESCRIPTION, DESCRIPTION_2, UNIT_OF_MEASURE, QUANTITY, UNIT_PRICE, UNIT_COST_LCY, VAT, LINE_DISCOUNT, LINE_DISCOUNT_AMOUNT, AMOUNT, AMOUNT_INCLUDING_VAT, ALLOW_INVOICE_DISC, GROSS_WEIGHT, NET_WEIGHT, UNITS_PER_PARCEL, UNIT_VOLUME, APPL_TO_ITEM_ENTRY, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_PRICE_GROUP, JOB_NO, WORK_TYPE_CODE, SHIPMENT_NO, SHIPMENT_LINE_NO, BILL_TO_CUSTOMER_NO, ORDER_NO, INV_DISCOUNT_AMOUNT, ORDER_LINE_NO, DROP_SHIPMENT, BILLTO_CUSTOMER_NO, GEN_BUS_POSTING_GROUP, GEN_PROD_POSTING_GROUP, VAT_CALCULATION_TYPE, TRANSACTION_TYPE, TRANSPORT_METHOD, ATTACHED_TO_LINE_NO, EXIT_POINT, AREA, TRANSACTION_SPECIFICATION, TAX_CATEGORY, TAX_AREA_CODE, TAX_LIABLE, TAX_GROUP_CODE, VAT_CLAUSE_CODE, VAT_BUS_POSTING_GROUP, VAT_PROD_POSTING_GROUP, BLANKET_ORDER_NO, BLANKET_ORDER_LINE_NO, VAT_BASE_AMOUNT, UNIT_COST, SYSTEM_CREATED_ENTRY, LINE_AMOUNT, VAT_DIFFERENCE, SYSTEMCREATED_ENTRY, VAT_IDENTIFIER, IC_PARTNER_REF_TYPE, IC_PARTNER_REFERENCE, PREPAYMENT_LINE, IC_PARTNER_CODE, POSTING_DATE, DIMENSION_SET_ID, JOB_TASK_NO, JOB_CONTRACT_ENTRY_NO, PMT_DISCOUNT_AMOUNT, DEFERRAL_CODE, LINE_DISCOUNT_CALCULATION, VARIANT_CODE, BIN_CODE, QTY_PER_UNIT_OF_MEASURE, UNIT_OF_MEASURE_CODE, QUANTITY_BASE, FA_POSTING_DATE, DEPRECIATION_BOOK_CODE, DEPR_UNTIL_FA_POSTING_DATE, DUPLICATE_IN_DEPRECIATION_BOOK, USE_DUPLICATION_LIST, RESPONSIBILITY_CENTER, CROSS_REFERENCE_NO, UNIT_OF_MEASURE_CROSS_REF, CROSS_REFERENCE_TYPE, CROSS_REFERENCE_TYPE_NO, CROSSREFERENCE_NO, ITEM_CATEGORY_CODE, NONSTOCK, PURCHASING_CODE, CROSSREFERENCE_TYPE, PRODUCT_GROUP_CODE, CROSSREFERENCE_TYPE_NO, APPL_FROM_ITEM_ENTRY, RETURN_REASON_CODE, ALLOW_LINE_DISC, CUSTOMER_DISC_GROUP, PMT_DISC_GIVEN_AMOUNT, EC, EC_DIFFERENCE, COD_CADENA, MURANO_CODE, PROMOCIONES_POR, PRICE_DESCRIPTION, MIGRATION_LOT_NO, NO_ALBARAN_VENTA, PMT_DISC_GIVEN_AMOUNT_OLD, COMISIONES_POR, CODIGO_EMBALAJE, NO_LINEA_ALBARAN_VENTA, CANTIDAD_EMBALAJE, COD_VENDEDOR_1, CANTIDAD_UNIDADES, COD_VENDEDOR_2, IDPIRPF_IRPF_GROUP, COD_VENDEDOR_3, CANTIDAD_KILOS, IDPIRPF_IRPF_AMOUNT, IDPIRPF_IRPF, NO_PRESENTACION, COM_1, IDPIRPF_IRPF_BASE_AMOUNT, COM_2, DESCRIPCION_PRESENTACION, COM_3, IDPVUM_QUANTITY, OBSERVACIONES, MOTIVO_DEVOLUCION, IDPVUM_UNIT_OF_MEASURE_CODE, DTO_1, SERVICIO, TIPO_DTO_2, IDPVUM_UNIT_PRICE, IDPVUM_PRICE_IN_VUM, DTO_2, PRECIO_PUNTO_VERDE_CDAD, UNIDAD_MEDIDA_PUNTO_VERDE, IDPVUM_VUM_PER_UNIT, TIPO_DTO_3, CERRADO, IMPORTE_PUNTO_VERDE, DTO_3, GRUPO_RESIDUOS, TIPO_DTO_4, TEMPQTY, PRECIO_RESIDUOS_CDAD, DTO_4, ORIGINAL_QUANTITY, UNIDAD_MEDIDA_RESIDUOS, TIPO_DTO_5, ORIGINAL_QUANTITY_UMV, IMPORTE_RESIDUOS, IDPGND_SIG_AMOUNT, DTO_5, IDPGND_SIG_RATE, NEGRILLA, INCOME_TAX_RETENTION_CODE, IDPGND_SIG, BASE_RAPPEL, INCOME_TAX_RETENTION, IDPGND_POSTING_DATE_SHIPMENT, IMPORTE_PROVISIONADO, INCOME_TAX_BASE, IDPGND_SHIPMENT_DATE_SHIPMENT, IMPORTE_DESPROVISIONADO, SALESPERSON_CODE, COMMISSION_SALESPERSON, IDPGND_REQ_DEL_DATE_SHIPMENT, NO_CUENTA_PROVISION_VENTA, 2ND_SALESPERSON_CODE, NO_CUENTA_PROVISION_CLIENTE, IDPGND_PACKAGING_FORMAT_NO, CLAIM_CODE, COMMISSION_2ND_SALESPERSON, IF_OR_TYPE, SPECIAL_LINE_TYPE, W_ITEM_ENTRIES, IF_UNIT_PRICE_CODE, SALES_SHIPMENT_NO, IF_NUM_BOXES_NEEDED, REAL_SHIPMENT_DATE, SALES_SHIPMENT_LINE_NO, IF_NUM_CONT_NEEDED, CREATION_DATE, TARIFF_NO, IF_DUN14, PLATES_SHIPPED, VAT_BREAKDOWN, TEC_DES_EMPRESA, EDI_POSITION, TEC_ID_INGESTA, Q_CONFIRMADA_RECADV, TYPE_BREAKDOWN, CADASTRAL_REFERENCE, RECADCV_QUANTITY, TEC_TS_INGESTA, TEC_TS_STAGING, EDI_POSITION_SUBLINE, PROPERTY_SITUATION, GLN, TEC_TS_INTEGRACION_B, PLASTIC_LINE, EDI_PRICE, EDI_DISCOUNT) AS tec_hash, 
        date(tec_ts_ingesta) as tec_fec_inicio
    from {{ ref('sales_invoice_line_batch') }}
)
select
    s.*,
    to_date('2999-12-31')             as tec_fec_fin,
    1                                 as tec_cod_vigencia,
    current_timestamp()               as tec_ts_integracion_s
from source s
{% if is_incremental() %}
left join {{ this }} t
    on  1=1
    and t.tec_cod_vigencia    = 1
where 1=1
    or t.tec_hash <> s.tec_hash
{% endif %}
