{{ config(
    materialized='incremental',
    database='PROD_SILVER' if target.name == 'prod' else 'DEV_SILVER', schema='SILVER_GC_GRUPO',
    incremental_strategy='append',
    tags=['silver','integ'],
    pre_hook=[
        "{% if is_incremental() %}
        -- (tec_cod_vigencia = 1 --> 0) Marcar como no vigentes registros con match y alguna diferencia. fec_negocio - 1 día (o mismo día si coincide inicio)
        merge into {{ this }} t
        using (
            select
                tec_des_empresa,
                HASH(TIMESTAMP, DOCUMENT_TYPE, NO, SELL_TO_CUSTOMER_NO, SELLTO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, BILL_TO_CUSTOMER_NO, BILL_TO_NAME, BILLTO_NAME, BILL_TO_NAME_2, BILLTO_NAME_2, BILL_TO_ADDRESS, BILLTO_ADDRESS, BILLTO_ADDRESS_2, BILL_TO_ADDRESS_2, BILLTO_CITY, BILL_TO_CITY, BILLTO_CONTACT, BILL_TO_CONTACT, YOUR_REFERENCE, SHIP_TO_CODE, SHIPTO_CODE, SHIP_TO_NAME, SHIPTO_NAME, SHIPTO_NAME_2, SHIP_TO_NAME_2, SHIP_TO_ADDRESS, SHIPTO_ADDRESS, SHIP_TO_ADDRESS_2, SHIPTO_ADDRESS_2, SHIP_TO_CITY, SHIPTO_CITY, SHIP_TO_CONTACT, SHIPTO_CONTACT, ORDER_DATE, POSTING_DATE, SHIPMENT_DATE, POSTING_DESCRIPTION, PAYMENT_TERMS_CODE, DUE_DATE, PAYMENT_DISCOUNT, PMT_DISCOUNT_DATE, SHIPMENT_METHOD_CODE, LOCATION_CODE, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_POSTING_GROUP, CURRENCY_CODE, CURRENCY_FACTOR, CUSTOMER_PRICE_GROUP, PRICES_INCLUDING_VAT, INVOICE_DISC_CODE, CUSTOMER_DISC_GROUP, LANGUAGE_CODE, SALESPERSON_CODE, ORDER_CLASS, NO_PRINTED, ON_HOLD, APPLIES_TO_DOC_TYPE, APPLIESTO_DOC_TYPE, APPLIESTO_DOC_NO, APPLIES_TO_DOC_NO, BAL_ACCOUNT_NO, SHIP, INVOICE, PRINT_POSTED_DOCUMENTS, SHIPPING_NO, POSTING_NO, LAST_SHIPPING_NO, LAST_POSTING_NO, PREPAYMENT_NO, LAST_PREPAYMENT_NO, PREPMT_CR_MEMO_NO, LAST_PREPMT_CR_MEMO_NO, VAT_REGISTRATION_NO, COMBINE_SHIPMENTS, REASON_CODE, GEN_BUS_POSTING_GROUP, EU_3_PARTY_TRADE, EU_3PARTY_TRADE, TRANSACTION_TYPE, TRANSPORT_METHOD, VAT_COUNTRY_REGION_CODE, SELL_TO_CUSTOMER_NAME, SELLTO_CUSTOMER_NAME, SELLTO_CUSTOMER_NAME_2, SELL_TO_CUSTOMER_NAME_2, SELLTO_ADDRESS, SELL_TO_ADDRESS, SELL_TO_ADDRESS_2, SELLTO_ADDRESS_2, SELLTO_CITY, SELL_TO_CITY, SELLTO_CONTACT, SELL_TO_CONTACT, BILL_TO_POST_CODE, BILLTO_POST_CODE, BILL_TO_COUNTY, BILLTO_COUNTY, BILL_TO_COUNTRY_REGION_CODE, BILLTO_COUNTRY_REGION_CODE, SELLTO_POST_CODE, SELL_TO_POST_CODE, SELL_TO_COUNTY, SELLTO_COUNTY, SELL_TO_COUNTRY_REGION_CODE, SELLTO_COUNTRY_REGION_CODE, SHIPTO_POST_CODE, SHIP_TO_POST_CODE, SHIPTO_COUNTY, SHIP_TO_COUNTY, SHIPTO_COUNTRY_REGION_CODE, SHIP_TO_COUNTRY_REGION_CODE, BAL_ACCOUNT_TYPE, EXIT_POINT, CORRECTION, DOCUMENT_DATE, EXTERNAL_DOCUMENT_NO, AREA, TRANSACTION_SPECIFICATION, PAYMENT_METHOD_CODE, SHIPPING_AGENT_CODE, PACKAGE_TRACKING_NO, NO_SERIES, POSTING_NO_SERIES, SHIPPING_NO_SERIES, TAX_AREA_CODE, TAX_LIABLE, VAT_BUS_POSTING_GROUP, RESERVE, APPLIES_TO_ID, APPLIESTO_ID, VAT_BASE_DISCOUNT, STATUS, ESTADO, INVOICE_DISCOUNT_CALCULATION, INVOICE_DISCOUNT_VALUE, SEND_IC_DOCUMENT, IC_STATUS, SELL_TO_IC_PARTNER_CODE, SELLTO_IC_PARTNER_CODE, BILL_TO_IC_PARTNER_CODE, IC_DIRECTION, BILLTO_IC_PARTNER_CODE, PREPAYMENT, PREPAYMENT_NO_SERIES, COMPRESS_PREPAYMENT, PREPAYMENT_DUE_DATE, PREPMT_CR_MEMO_NO_SERIES, PREPMT_POSTING_DESCRIPTION, PREPMT_PMT_DISCOUNT_DATE, PREPMT_PAYMENT_TERMS_CODE, PREPMT_PAYMENT_DISCOUNT, QUOTE_NO, JOB_QUEUE_STATUS, JOB_QUEUE_ENTRY_ID, QUOTE_VALID_UNTIL_DATE, INCOMING_DOCUMENT_ENTRY_NO, QUOTE_SENT_TO_CUSTOMER, QUOTE_ACCEPTED, DIMENSION_SET_ID, PAYMENT_SERVICE_SET_ID, AUTHORIZATION_REQUIRED, QUOTE_ACCEPTED_DATE, DIRECT_DEBIT_MANDATE_ID, CREDIT_CARD_NO, DOC_NO_OCCURRENCE, CAMPAIGN_NO, SELL_TO_CUSTOMER_TEMPLATE_CODE, ISTEST, PAYMENT_INSTRUCTIONS_ID, SELL_TO_CONTACT_NO, BILL_TO_CONTACT_NO, BILL_TO_CUSTOMER_TEMPLATE_CODE, OPPORTUNITY_NO, RESPONSIBILITY_CENTER, SHIPPING_ADVICE, POSTING_FROM_WHSE_REF, SELLTO_CUSTOMER_TEMPLATE_CODE, SELLTO_CONTACT_NO, REQUESTED_DELIVERY_DATE, PROMISED_DELIVERY_DATE, BILLTO_CONTACT_NO, SHIPPING_TIME, BILLTO_CUSTOMER_TEMPLATE_CODE, OUTBOUND_WHSE_HANDLING_TIME, SHIPPING_AGENT_SERVICE_CODE, RECEIVE, RETURN_RECEIPT_NO, RETURN_RECEIPT_NO_SERIES, LAST_RETURN_RECEIPT_NO, ALLOW_LINE_DISC, GET_SHIPMENT_USED, ASSIGNED_USER_ID, CORRECTED_INVOICE_NO, DUE_DATE_MODIFIED, INVOICE_TYPE, QUOTE_END_DATE, CR_MEMO_TYPE, SPECIAL_SCHEME_CODE, UPLOAD_DATE, OPERATION_DESCRIPTION, SAMPLE_ORDER, CONTAINER, ID, CORRECTION_TYPE, SUCCEEDED_VAT_REGISTRATION_NO, SEAL, TRUCK_LICENSE_PLATE, BLOQUEAR_PROMOCIONES, COD_CADENA, DRIVER, PROMOCIONES_POR, AUTHORIZE_ORDER, COD_DTO_LINEA, TRAILER_LICENSE_PLATE, PENDING_AUTHORIZE_ORDER, CALCULAR_RAPPEL, TIPO_PEDIDO, RISK_EXCEEDED, TIPO_PUNTO_VERDE, BANK_ACCOUNT_TO_TRANSFER, COD_RUTA, TRIP_NO, OPERATION_DESCRIPTION_2, PREFACTURAR_SERVICIO, SUCCEEDED_COMPANY_NAME, FILE_GENERATED, ZONA_TRANSPORTE, ESTADO_EDI, TEMPERATURA_EXP, APPLIESTO_BILL_NO, MOTIVO_DEVOLUCION_EDI, CUST_BANK_ACC_CODE, ESTADO_LIMPIEZA, DEPARTAMENTO_EDI, SHIPMENT_LANGUAGE_CODE, PAYAT_CODE, ESTADO_PALETIZADO, IDPIRPF_IRPF_GROUP, ORIGEN, HEADER_DISCOUNT, SALES_RETURN, IDPGND_SHIPTO_EXCL_SIG_RATE, OBSERVACIONES_PICKING, RAPPEL, IF_OR_TYPE, OBSERVACIONES_RECOGIDA, OBSERVACIONES_CARTA_PORTES, LOAD_TIME, IF_DATA_1, IF_DATA_2, NATURALEZA_PRODUCTO, LOAD_HR, DOC_TRANSPORTE, IF_DATA_3, SALES_INV_PROFORMA, NO_ENVIO, IF_DATA_4, SHIPMENT_ZONE_CODE, IF_DATA_5, INVOICE_CANCELATION, COD_PALET, CORRECTED_INVOICE_TYPE, TIPO_RESIDUOS, IF_ML_TIME, SIMPLIFIED_TYPE, COD_IDIOMA_ETIQUETAJE, IF_SAE_CERTIFICATION, HORARIO_ENTREGA, FROM_TICKET_NO, CO_ID_CONT, NO_CAJAS_POR_PALET, CO_ID_PREC, TO_TICKET_NO, MATRICULA_VEHICULO, TOTALNETWEIGHT, APPLIES_TO_BILL_NO, CONDUCTOR, TOTALGROSSWEIGHT, PAY_AT_CODE, NIF_CONDUCTOR, PACKAGESPALLETNUMBER, NO_TELEFONO_ENVIO, MATRICULA_REMOLQUE, PACKAGESNUMBER, OBSERVACIONES_ENVIO, CAPACIDAD_MAX_PALETS, SII_NUMDESDE, PESO_NETO, NO_PEDIDO_ORIGEN, SII_NUMHASTA, RECUPERACION_EDI, SII_FACARRENDAMIENTO, PESO_BRUTO, ALBARAN_VALORADO, SII_UBICACIONPROPIEDAD, FORMA_PAGO_FACTURAPLUS, SII_INMUEBLESADICIONALES, VALUED_SHIPMENT, TIPO_FACTURACION, DROP_SHIPMENT, SII_NUMCUENTAIMPUESTO, FACTURA_POR_ALBARAN, SIN_MOVS_ALMACEN, SALES_DATE, EN_FACTURACION_AUTOMATICA, SYSTEM_DATE, FECHA_CONFIRMACION_PACKING, CERRADO, PREINVOICE, AIT_BILLING_ADDRESS_CODE, ANULACION_AUTOMATICA, USUARIO_ALTA, SPLIT_SHIP_TO_ADD, IDPCIN_ALLOW_CREDIT_EXCEEDED, JEFE_DE_VENTAS, IDPEDI_DOCUMENT, DTO_FACTURA, JEFE_DE_ZONA, IDPEDI_ORDRSP, COD_BANCO, COMMISSION_SALESPERSON, HEREDA_COND_GRUPO, IDPEDI_ORDRSP_SENT, IDPEDI_INTERLOCUTOR_CODE, 2ND_SALESPERSON_CODE, NO_EXPEDICION, IDPEDI_ORDRSP_RESPONSE_CODE, COMMISSION_2ND_SALESPERSON, NO_ALBARAN_AGENCIA, IDPEDI_INVOIC, CASH_ENTRY, INCOME_TAX_RETENTION_CODE, SPETIAL_OPERATION_TYPE, IDPEDI_ORDRSP_REVIEWED, INCOME_TAX_RETENTION, IDPEDI_DESADV, INCOME_TAX_RETENTION_KEY, SPETIAL_OPERATION_CODE, IDPEDI_RECADV, INCOME_TAX_RETENTION_SUBKEY, GROUP_SHIPMENT_TYPE, POSTING_STATUS, IDPVUM_UPDATE_SOURCE, SHIPMENT_FREQUENCY, AIT_CREATION_USER, SHIP_POSTING, INVOICE_DETAIL, RETENER_FACTURACION, AIT_CREATION_DATETIME, INVOICE_POSTING, NO_FACTURA_ANULADA, POSTING_IN_ERROR, AIT_RIESGOSUPERADO, EDI_HORA_ENTREGA, TEC_DES_EMPRESA, ANULACION_DE_FACTURA, PRINT_BY_CONCEPT, CONTROLAR_PR_MIN, TEC_ID_INGESTA, ESTADO_CALIDAD, TEC_TS_INGESTA, PEDIDO_SINCRON_AUTOMATICA, TEC_TS_STAGING, CODIGO_CALIDAD, EMPRESA_ORIGEN, NO_PROV_EN_CLIENTE, TEC_TS_INTEGRACION_B, ANULADO, ODS_JOB_TEMPLATE_CODE, OPERATION_DATE, SIMPLIFIED_INVOICE, TO_DOCUMENT_NO, FROM_DOCUMENT_NO, REGIMEN, SII_CORRECTION_TYPE, TAX_FREE, SII_OPERATION_DESCRIPTION, SII_INVOICE_TYPE, TAX_FREE_VENDOR_NO, CUSTOMER_SALES_DEPARTMENT, EDI_BLOCKED, SIMPLIFIED_ART_6_1_D, REFEXTERNA, DESADV_NO, PLANNING_DELIVERY_DATE, NUM_REGISTRO_ACUERDO_FACT, EMITIDA_POR_TERCERO, INVOICE_BLOCKED, EMITIDA_POR_NORMATIVA_DEL_GAS, COMPLETELY_INVOICED, INTERCOMPANY_INVOICE, IPAD_ORDER, HIDE_DIALOGUE, WITHOUT_PLASTIC_DECLARATION, CUSTOMER_RECEPTION_NO, FECHAEPRDT, EDI_ORDER_NO, FECHATODT, SALES_SHIPMENT_NO, FIX_SALES_PRICE) AS tec_hash,
                date(tec_ts_ingesta) as tec_fec_inicio
            from {{ ref('sales_header_batch') }}
        ) s
        on t.tec_cod_vigencia = 1
            and 1=1
        when matched and t.tec_hash <> s.tec_hash then
            update set
                tec_cod_vigencia = 0,
                tec_fec_fin = case
                    when s.tec_fec_inicio = t.tec_fec_inicio then s.tec_fec_inicio
                    else dateadd(day, -1, s.tec_fec_inicio)
                end;
        {% endif %}"
    ],
    post_hook=[
        "{% set log_ref = source('support_param', 'INSERT_LOGS') %}{% set asociados = var('empresas', []) %}{% for a in asociados %}
            {% set src_ref = source('bronze_' ~ a, 'COOPECARN_SALES_HEADER') %}
            -- Sella ÚNICAMENTE el batch (tec_id_ingesta) que está procesando la view {{ ref('sales_header_batch_' ~ a) }}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref.database }}')
              and upper(l.schema)     = upper('{{ src_ref.schema }}')
              and upper(l.table_name) = upper('{{ src_ref.identifier }}')
              and exists (
                  select 1
                  from {{ ref('sales_header_batch_' ~ a) }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );
        {% endfor %}"
    ]
) }}

with source as (
    select
        timestamp, 
        document_type, 
        no, 
        sell_to_customer_no, 
        sellto_customer_no, 
        billto_customer_no, 
        bill_to_customer_no, 
        bill_to_name, 
        billto_name, 
        bill_to_name_2, 
        billto_name_2, 
        bill_to_address, 
        billto_address, 
        billto_address_2, 
        bill_to_address_2, 
        billto_city, 
        bill_to_city, 
        billto_contact, 
        bill_to_contact, 
        your_reference, 
        ship_to_code, 
        shipto_code, 
        ship_to_name, 
        shipto_name, 
        shipto_name_2, 
        ship_to_name_2, 
        ship_to_address, 
        shipto_address, 
        ship_to_address_2, 
        shipto_address_2, 
        ship_to_city, 
        shipto_city, 
        ship_to_contact, 
        shipto_contact, 
        order_date, 
        posting_date, 
        shipment_date, 
        posting_description, 
        payment_terms_code, 
        due_date, 
        payment_discount, 
        pmt_discount_date, 
        shipment_method_code, 
        location_code, 
        shortcut_dimension_1_code, 
        shortcut_dimension_2_code, 
        customer_posting_group, 
        currency_code, 
        currency_factor, 
        customer_price_group, 
        prices_including_vat, 
        invoice_disc_code, 
        customer_disc_group, 
        language_code, 
        salesperson_code, 
        order_class, 
        no_printed, 
        on_hold, 
        applies_to_doc_type, 
        appliesto_doc_type, 
        appliesto_doc_no, 
        applies_to_doc_no, 
        bal_account_no, 
        ship, 
        invoice, 
        print_posted_documents, 
        shipping_no, 
        posting_no, 
        last_shipping_no, 
        last_posting_no, 
        prepayment_no, 
        last_prepayment_no, 
        prepmt_cr_memo_no, 
        last_prepmt_cr_memo_no, 
        vat_registration_no, 
        combine_shipments, 
        reason_code, 
        gen_bus_posting_group, 
        eu_3_party_trade, 
        eu_3party_trade, 
        transaction_type, 
        transport_method, 
        vat_country_region_code, 
        sell_to_customer_name, 
        sellto_customer_name, 
        sellto_customer_name_2, 
        sell_to_customer_name_2, 
        sellto_address, 
        sell_to_address, 
        sell_to_address_2, 
        sellto_address_2, 
        sellto_city, 
        sell_to_city, 
        sellto_contact, 
        sell_to_contact, 
        bill_to_post_code, 
        billto_post_code, 
        bill_to_county, 
        billto_county, 
        bill_to_country_region_code, 
        billto_country_region_code, 
        sellto_post_code, 
        sell_to_post_code, 
        sell_to_county, 
        sellto_county, 
        sell_to_country_region_code, 
        sellto_country_region_code, 
        shipto_post_code, 
        ship_to_post_code, 
        shipto_county, 
        ship_to_county, 
        shipto_country_region_code, 
        ship_to_country_region_code, 
        bal_account_type, 
        exit_point, 
        correction, 
        document_date, 
        external_document_no, 
        area, 
        transaction_specification, 
        payment_method_code, 
        shipping_agent_code, 
        package_tracking_no, 
        no_series, 
        posting_no_series, 
        shipping_no_series, 
        tax_area_code, 
        tax_liable, 
        vat_bus_posting_group, 
        reserve, 
        applies_to_id, 
        appliesto_id, 
        vat_base_discount, 
        status, 
        estado, 
        invoice_discount_calculation, 
        invoice_discount_value, 
        send_ic_document, 
        ic_status, 
        sell_to_ic_partner_code, 
        sellto_ic_partner_code, 
        bill_to_ic_partner_code, 
        ic_direction, 
        billto_ic_partner_code, 
        prepayment, 
        prepayment_no_series, 
        compress_prepayment, 
        prepayment_due_date, 
        prepmt_cr_memo_no_series, 
        prepmt_posting_description, 
        prepmt_pmt_discount_date, 
        prepmt_payment_terms_code, 
        prepmt_payment_discount, 
        quote_no, 
        job_queue_status, 
        job_queue_entry_id, 
        quote_valid_until_date, 
        incoming_document_entry_no, 
        quote_sent_to_customer, 
        quote_accepted, 
        dimension_set_id, 
        payment_service_set_id, 
        authorization_required, 
        quote_accepted_date, 
        direct_debit_mandate_id, 
        credit_card_no, 
        doc_no_occurrence, 
        campaign_no, 
        sell_to_customer_template_code, 
        istest, 
        payment_instructions_id, 
        sell_to_contact_no, 
        bill_to_contact_no, 
        bill_to_customer_template_code, 
        opportunity_no, 
        responsibility_center, 
        shipping_advice, 
        posting_from_whse_ref, 
        sellto_customer_template_code, 
        sellto_contact_no, 
        requested_delivery_date, 
        promised_delivery_date, 
        billto_contact_no, 
        shipping_time, 
        billto_customer_template_code, 
        outbound_whse_handling_time, 
        shipping_agent_service_code, 
        receive, 
        return_receipt_no, 
        return_receipt_no_series, 
        last_return_receipt_no, 
        allow_line_disc, 
        get_shipment_used, 
        assigned_user_id, 
        corrected_invoice_no, 
        due_date_modified, 
        invoice_type, 
        quote_end_date, 
        cr_memo_type, 
        special_scheme_code, 
        upload_date, 
        operation_description, 
        sample_order, 
        container, 
        id, 
        correction_type, 
        succeeded_vat_registration_no, 
        seal, 
        truck_license_plate, 
        bloquear_promociones, 
        cod_cadena, 
        driver, 
        promociones_por, 
        authorize_order, 
        cod_dto_linea, 
        trailer_license_plate, 
        pending_authorize_order, 
        calcular_rappel, 
        tipo_pedido, 
        risk_exceeded, 
        tipo_punto_verde, 
        bank_account_to_transfer, 
        cod_ruta, 
        trip_no, 
        operation_description_2, 
        prefacturar_servicio, 
        succeeded_company_name, 
        file_generated, 
        zona_transporte, 
        estado_edi, 
        temperatura_exp, 
        appliesto_bill_no, 
        motivo_devolucion_edi, 
        cust_bank_acc_code, 
        estado_limpieza, 
        departamento_edi, 
        shipment_language_code, 
        payat_code, 
        estado_paletizado, 
        idpirpf_irpf_group, 
        origen, 
        header_discount, 
        sales_return, 
        idpgnd_shipto_excl_sig_rate, 
        observaciones_picking, 
        rappel, 
        if_or_type, 
        observaciones_recogida, 
        observaciones_carta_portes, 
        load_time, 
        if_data_1, 
        if_data_2, 
        naturaleza_producto, 
        load_hr, 
        doc_transporte, 
        if_data_3, 
        sales_inv_proforma, 
        no_envio, 
        if_data_4, 
        shipment_zone_code, 
        if_data_5, 
        invoice_cancelation, 
        cod_palet, 
        corrected_invoice_type, 
        tipo_residuos, 
        if_ml_time, 
        simplified_type, 
        cod_idioma_etiquetaje, 
        if_sae_certification, 
        horario_entrega, 
        from_ticket_no, 
        co_id_cont, 
        no_cajas_por_palet, 
        co_id_prec, 
        to_ticket_no, 
        matricula_vehiculo, 
        totalnetweight, 
        applies_to_bill_no, 
        conductor, 
        totalgrossweight, 
        pay_at_code, 
        nif_conductor, 
        packagespalletnumber, 
        no_telefono_envio, 
        matricula_remolque, 
        packagesnumber, 
        observaciones_envio, 
        capacidad_max_palets, 
        sii_numdesde, 
        peso_neto, 
        no_pedido_origen, 
        sii_numhasta, 
        recuperacion_edi, 
        sii_facarrendamiento, 
        peso_bruto, 
        albaran_valorado, 
        sii_ubicacionpropiedad, 
        forma_pago_facturaplus, 
        sii_inmueblesadicionales, 
        valued_shipment, 
        tipo_facturacion, 
        drop_shipment, 
        sii_numcuentaimpuesto, 
        factura_por_albaran, 
        sin_movs_almacen, 
        sales_date, 
        en_facturacion_automatica, 
        system_date, 
        fecha_confirmacion_packing, 
        cerrado, 
        preinvoice, 
        ait_billing_address_code, 
        anulacion_automatica, 
        usuario_alta, 
        split_ship_to_add, 
        idpcin_allow_credit_exceeded, 
        jefe_de_ventas, 
        idpedi_document, 
        dto_factura, 
        jefe_de_zona, 
        idpedi_ordrsp, 
        cod_banco, 
        commission_salesperson, 
        hereda_cond_grupo, 
        idpedi_ordrsp_sent, 
        idpedi_interlocutor_code, 
        2nd_salesperson_code, 
        no_expedicion, 
        idpedi_ordrsp_response_code, 
        commission_2nd_salesperson, 
        no_albaran_agencia, 
        idpedi_invoic, 
        cash_entry, 
        income_tax_retention_code, 
        spetial_operation_type, 
        idpedi_ordrsp_reviewed, 
        income_tax_retention, 
        idpedi_desadv, 
        income_tax_retention_key, 
        spetial_operation_code, 
        idpedi_recadv, 
        income_tax_retention_subkey, 
        group_shipment_type, 
        posting_status, 
        idpvum_update_source, 
        shipment_frequency, 
        ait_creation_user, 
        ship_posting, 
        invoice_detail, 
        retener_facturacion, 
        ait_creation_datetime, 
        invoice_posting, 
        no_factura_anulada, 
        posting_in_error, 
        ait_riesgosuperado, 
        edi_hora_entrega, 
        tec_des_empresa, 
        anulacion_de_factura, 
        print_by_concept, 
        controlar_pr_min, 
        tec_id_ingesta, 
        estado_calidad, 
        tec_ts_ingesta, 
        pedido_sincron_automatica, 
        tec_ts_staging, 
        codigo_calidad, 
        empresa_origen, 
        no_prov_en_cliente, 
        tec_ts_integracion_b, 
        anulado, 
        ods_job_template_code, 
        operation_date, 
        simplified_invoice, 
        to_document_no, 
        from_document_no, 
        regimen, 
        sii_correction_type, 
        tax_free, 
        sii_operation_description, 
        sii_invoice_type, 
        tax_free_vendor_no, 
        customer_sales_department, 
        edi_blocked, 
        simplified_art_6_1_d, 
        refexterna, 
        desadv_no, 
        planning_delivery_date, 
        num_registro_acuerdo_fact, 
        emitida_por_tercero, 
        invoice_blocked, 
        emitida_por_normativa_del_gas, 
        completely_invoiced, 
        intercompany_invoice, 
        ipad_order, 
        hide_dialogue, 
        without_plastic_declaration, 
        customer_reception_no, 
        fechaeprdt, 
        edi_order_no, 
        fechatodt, 
        sales_shipment_no, 
        fix_sales_price, 
        tec_des_cod_siglas, 
        tec_des_empresa, 
        tec_id_ingesta, 
        tec_ts_ingesta, 
        HASH(TIMESTAMP, DOCUMENT_TYPE, NO, SELL_TO_CUSTOMER_NO, SELLTO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, BILL_TO_CUSTOMER_NO, BILL_TO_NAME, BILLTO_NAME, BILL_TO_NAME_2, BILLTO_NAME_2, BILL_TO_ADDRESS, BILLTO_ADDRESS, BILLTO_ADDRESS_2, BILL_TO_ADDRESS_2, BILLTO_CITY, BILL_TO_CITY, BILLTO_CONTACT, BILL_TO_CONTACT, YOUR_REFERENCE, SHIP_TO_CODE, SHIPTO_CODE, SHIP_TO_NAME, SHIPTO_NAME, SHIPTO_NAME_2, SHIP_TO_NAME_2, SHIP_TO_ADDRESS, SHIPTO_ADDRESS, SHIP_TO_ADDRESS_2, SHIPTO_ADDRESS_2, SHIP_TO_CITY, SHIPTO_CITY, SHIP_TO_CONTACT, SHIPTO_CONTACT, ORDER_DATE, POSTING_DATE, SHIPMENT_DATE, POSTING_DESCRIPTION, PAYMENT_TERMS_CODE, DUE_DATE, PAYMENT_DISCOUNT, PMT_DISCOUNT_DATE, SHIPMENT_METHOD_CODE, LOCATION_CODE, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_POSTING_GROUP, CURRENCY_CODE, CURRENCY_FACTOR, CUSTOMER_PRICE_GROUP, PRICES_INCLUDING_VAT, INVOICE_DISC_CODE, CUSTOMER_DISC_GROUP, LANGUAGE_CODE, SALESPERSON_CODE, ORDER_CLASS, NO_PRINTED, ON_HOLD, APPLIES_TO_DOC_TYPE, APPLIESTO_DOC_TYPE, APPLIESTO_DOC_NO, APPLIES_TO_DOC_NO, BAL_ACCOUNT_NO, SHIP, INVOICE, PRINT_POSTED_DOCUMENTS, SHIPPING_NO, POSTING_NO, LAST_SHIPPING_NO, LAST_POSTING_NO, PREPAYMENT_NO, LAST_PREPAYMENT_NO, PREPMT_CR_MEMO_NO, LAST_PREPMT_CR_MEMO_NO, VAT_REGISTRATION_NO, COMBINE_SHIPMENTS, REASON_CODE, GEN_BUS_POSTING_GROUP, EU_3_PARTY_TRADE, EU_3PARTY_TRADE, TRANSACTION_TYPE, TRANSPORT_METHOD, VAT_COUNTRY_REGION_CODE, SELL_TO_CUSTOMER_NAME, SELLTO_CUSTOMER_NAME, SELLTO_CUSTOMER_NAME_2, SELL_TO_CUSTOMER_NAME_2, SELLTO_ADDRESS, SELL_TO_ADDRESS, SELL_TO_ADDRESS_2, SELLTO_ADDRESS_2, SELLTO_CITY, SELL_TO_CITY, SELLTO_CONTACT, SELL_TO_CONTACT, BILL_TO_POST_CODE, BILLTO_POST_CODE, BILL_TO_COUNTY, BILLTO_COUNTY, BILL_TO_COUNTRY_REGION_CODE, BILLTO_COUNTRY_REGION_CODE, SELLTO_POST_CODE, SELL_TO_POST_CODE, SELL_TO_COUNTY, SELLTO_COUNTY, SELL_TO_COUNTRY_REGION_CODE, SELLTO_COUNTRY_REGION_CODE, SHIPTO_POST_CODE, SHIP_TO_POST_CODE, SHIPTO_COUNTY, SHIP_TO_COUNTY, SHIPTO_COUNTRY_REGION_CODE, SHIP_TO_COUNTRY_REGION_CODE, BAL_ACCOUNT_TYPE, EXIT_POINT, CORRECTION, DOCUMENT_DATE, EXTERNAL_DOCUMENT_NO, AREA, TRANSACTION_SPECIFICATION, PAYMENT_METHOD_CODE, SHIPPING_AGENT_CODE, PACKAGE_TRACKING_NO, NO_SERIES, POSTING_NO_SERIES, SHIPPING_NO_SERIES, TAX_AREA_CODE, TAX_LIABLE, VAT_BUS_POSTING_GROUP, RESERVE, APPLIES_TO_ID, APPLIESTO_ID, VAT_BASE_DISCOUNT, STATUS, ESTADO, INVOICE_DISCOUNT_CALCULATION, INVOICE_DISCOUNT_VALUE, SEND_IC_DOCUMENT, IC_STATUS, SELL_TO_IC_PARTNER_CODE, SELLTO_IC_PARTNER_CODE, BILL_TO_IC_PARTNER_CODE, IC_DIRECTION, BILLTO_IC_PARTNER_CODE, PREPAYMENT, PREPAYMENT_NO_SERIES, COMPRESS_PREPAYMENT, PREPAYMENT_DUE_DATE, PREPMT_CR_MEMO_NO_SERIES, PREPMT_POSTING_DESCRIPTION, PREPMT_PMT_DISCOUNT_DATE, PREPMT_PAYMENT_TERMS_CODE, PREPMT_PAYMENT_DISCOUNT, QUOTE_NO, JOB_QUEUE_STATUS, JOB_QUEUE_ENTRY_ID, QUOTE_VALID_UNTIL_DATE, INCOMING_DOCUMENT_ENTRY_NO, QUOTE_SENT_TO_CUSTOMER, QUOTE_ACCEPTED, DIMENSION_SET_ID, PAYMENT_SERVICE_SET_ID, AUTHORIZATION_REQUIRED, QUOTE_ACCEPTED_DATE, DIRECT_DEBIT_MANDATE_ID, CREDIT_CARD_NO, DOC_NO_OCCURRENCE, CAMPAIGN_NO, SELL_TO_CUSTOMER_TEMPLATE_CODE, ISTEST, PAYMENT_INSTRUCTIONS_ID, SELL_TO_CONTACT_NO, BILL_TO_CONTACT_NO, BILL_TO_CUSTOMER_TEMPLATE_CODE, OPPORTUNITY_NO, RESPONSIBILITY_CENTER, SHIPPING_ADVICE, POSTING_FROM_WHSE_REF, SELLTO_CUSTOMER_TEMPLATE_CODE, SELLTO_CONTACT_NO, REQUESTED_DELIVERY_DATE, PROMISED_DELIVERY_DATE, BILLTO_CONTACT_NO, SHIPPING_TIME, BILLTO_CUSTOMER_TEMPLATE_CODE, OUTBOUND_WHSE_HANDLING_TIME, SHIPPING_AGENT_SERVICE_CODE, RECEIVE, RETURN_RECEIPT_NO, RETURN_RECEIPT_NO_SERIES, LAST_RETURN_RECEIPT_NO, ALLOW_LINE_DISC, GET_SHIPMENT_USED, ASSIGNED_USER_ID, CORRECTED_INVOICE_NO, DUE_DATE_MODIFIED, INVOICE_TYPE, QUOTE_END_DATE, CR_MEMO_TYPE, SPECIAL_SCHEME_CODE, UPLOAD_DATE, OPERATION_DESCRIPTION, SAMPLE_ORDER, CONTAINER, ID, CORRECTION_TYPE, SUCCEEDED_VAT_REGISTRATION_NO, SEAL, TRUCK_LICENSE_PLATE, BLOQUEAR_PROMOCIONES, COD_CADENA, DRIVER, PROMOCIONES_POR, AUTHORIZE_ORDER, COD_DTO_LINEA, TRAILER_LICENSE_PLATE, PENDING_AUTHORIZE_ORDER, CALCULAR_RAPPEL, TIPO_PEDIDO, RISK_EXCEEDED, TIPO_PUNTO_VERDE, BANK_ACCOUNT_TO_TRANSFER, COD_RUTA, TRIP_NO, OPERATION_DESCRIPTION_2, PREFACTURAR_SERVICIO, SUCCEEDED_COMPANY_NAME, FILE_GENERATED, ZONA_TRANSPORTE, ESTADO_EDI, TEMPERATURA_EXP, APPLIESTO_BILL_NO, MOTIVO_DEVOLUCION_EDI, CUST_BANK_ACC_CODE, ESTADO_LIMPIEZA, DEPARTAMENTO_EDI, SHIPMENT_LANGUAGE_CODE, PAYAT_CODE, ESTADO_PALETIZADO, IDPIRPF_IRPF_GROUP, ORIGEN, HEADER_DISCOUNT, SALES_RETURN, IDPGND_SHIPTO_EXCL_SIG_RATE, OBSERVACIONES_PICKING, RAPPEL, IF_OR_TYPE, OBSERVACIONES_RECOGIDA, OBSERVACIONES_CARTA_PORTES, LOAD_TIME, IF_DATA_1, IF_DATA_2, NATURALEZA_PRODUCTO, LOAD_HR, DOC_TRANSPORTE, IF_DATA_3, SALES_INV_PROFORMA, NO_ENVIO, IF_DATA_4, SHIPMENT_ZONE_CODE, IF_DATA_5, INVOICE_CANCELATION, COD_PALET, CORRECTED_INVOICE_TYPE, TIPO_RESIDUOS, IF_ML_TIME, SIMPLIFIED_TYPE, COD_IDIOMA_ETIQUETAJE, IF_SAE_CERTIFICATION, HORARIO_ENTREGA, FROM_TICKET_NO, CO_ID_CONT, NO_CAJAS_POR_PALET, CO_ID_PREC, TO_TICKET_NO, MATRICULA_VEHICULO, TOTALNETWEIGHT, APPLIES_TO_BILL_NO, CONDUCTOR, TOTALGROSSWEIGHT, PAY_AT_CODE, NIF_CONDUCTOR, PACKAGESPALLETNUMBER, NO_TELEFONO_ENVIO, MATRICULA_REMOLQUE, PACKAGESNUMBER, OBSERVACIONES_ENVIO, CAPACIDAD_MAX_PALETS, SII_NUMDESDE, PESO_NETO, NO_PEDIDO_ORIGEN, SII_NUMHASTA, RECUPERACION_EDI, SII_FACARRENDAMIENTO, PESO_BRUTO, ALBARAN_VALORADO, SII_UBICACIONPROPIEDAD, FORMA_PAGO_FACTURAPLUS, SII_INMUEBLESADICIONALES, VALUED_SHIPMENT, TIPO_FACTURACION, DROP_SHIPMENT, SII_NUMCUENTAIMPUESTO, FACTURA_POR_ALBARAN, SIN_MOVS_ALMACEN, SALES_DATE, EN_FACTURACION_AUTOMATICA, SYSTEM_DATE, FECHA_CONFIRMACION_PACKING, CERRADO, PREINVOICE, AIT_BILLING_ADDRESS_CODE, ANULACION_AUTOMATICA, USUARIO_ALTA, SPLIT_SHIP_TO_ADD, IDPCIN_ALLOW_CREDIT_EXCEEDED, JEFE_DE_VENTAS, IDPEDI_DOCUMENT, DTO_FACTURA, JEFE_DE_ZONA, IDPEDI_ORDRSP, COD_BANCO, COMMISSION_SALESPERSON, HEREDA_COND_GRUPO, IDPEDI_ORDRSP_SENT, IDPEDI_INTERLOCUTOR_CODE, 2ND_SALESPERSON_CODE, NO_EXPEDICION, IDPEDI_ORDRSP_RESPONSE_CODE, COMMISSION_2ND_SALESPERSON, NO_ALBARAN_AGENCIA, IDPEDI_INVOIC, CASH_ENTRY, INCOME_TAX_RETENTION_CODE, SPETIAL_OPERATION_TYPE, IDPEDI_ORDRSP_REVIEWED, INCOME_TAX_RETENTION, IDPEDI_DESADV, INCOME_TAX_RETENTION_KEY, SPETIAL_OPERATION_CODE, IDPEDI_RECADV, INCOME_TAX_RETENTION_SUBKEY, GROUP_SHIPMENT_TYPE, POSTING_STATUS, IDPVUM_UPDATE_SOURCE, SHIPMENT_FREQUENCY, AIT_CREATION_USER, SHIP_POSTING, INVOICE_DETAIL, RETENER_FACTURACION, AIT_CREATION_DATETIME, INVOICE_POSTING, NO_FACTURA_ANULADA, POSTING_IN_ERROR, AIT_RIESGOSUPERADO, EDI_HORA_ENTREGA, TEC_DES_EMPRESA, ANULACION_DE_FACTURA, PRINT_BY_CONCEPT, CONTROLAR_PR_MIN, TEC_ID_INGESTA, ESTADO_CALIDAD, TEC_TS_INGESTA, PEDIDO_SINCRON_AUTOMATICA, TEC_TS_STAGING, CODIGO_CALIDAD, EMPRESA_ORIGEN, NO_PROV_EN_CLIENTE, TEC_TS_INTEGRACION_B, ANULADO, ODS_JOB_TEMPLATE_CODE, OPERATION_DATE, SIMPLIFIED_INVOICE, TO_DOCUMENT_NO, FROM_DOCUMENT_NO, REGIMEN, SII_CORRECTION_TYPE, TAX_FREE, SII_OPERATION_DESCRIPTION, SII_INVOICE_TYPE, TAX_FREE_VENDOR_NO, CUSTOMER_SALES_DEPARTMENT, EDI_BLOCKED, SIMPLIFIED_ART_6_1_D, REFEXTERNA, DESADV_NO, PLANNING_DELIVERY_DATE, NUM_REGISTRO_ACUERDO_FACT, EMITIDA_POR_TERCERO, INVOICE_BLOCKED, EMITIDA_POR_NORMATIVA_DEL_GAS, COMPLETELY_INVOICED, INTERCOMPANY_INVOICE, IPAD_ORDER, HIDE_DIALOGUE, WITHOUT_PLASTIC_DECLARATION, CUSTOMER_RECEPTION_NO, FECHAEPRDT, EDI_ORDER_NO, FECHATODT, SALES_SHIPMENT_NO, FIX_SALES_PRICE) AS tec_hash, 
        date(tec_ts_ingesta) as tec_fec_inicio
    from {{ ref('sales_header_batch') }}
)
select
    s.*,
    to_date('2999-12-31')             as tec_fec_fin,
    1                                 as tec_cod_vigencia,
    current_timestamp()               as tec_ts_integracion_s
from source s
{% if is_incremental() %}
left join {{ this }} t
    on  1=1
    and t.tec_cod_vigencia    = 1
where 1=1
    or t.tec_hash <> s.tec_hash
{% endif %}
