{{ config(
    materialized='incremental',
    database='PROD_SILVER' if target.name == 'prod' else 'DEV_SILVER', schema='SILVER_GC_GRUPO',
    incremental_strategy='append',
    tags=['silver','integ'],
    pre_hook=[
        "{% if is_incremental() %}
        -- (tec_cod_vigencia = 1 --> 0) Marcar como no vigentes registros con match y alguna diferencia. fec_negocio - 1 día (o mismo día si coincide inicio)
        merge into {{ this }} t
        using (
            select
                tec_des_empresa,
                HASH(TIMESTAMP, DOCUMENT_TYPE, DOCUMENT_NO, LINE_NO, SELLTO_CUSTOMER_NO, SELL_TO_CUSTOMER_NO, TYPE, NO, LOCATION_CODE, POSTING_GROUP, SHIPMENT_DATE, DESCRIPTION, DESCRIPTION_2, UNIT_OF_MEASURE, QUANTITY, OUTSTANDING_QUANTITY, QTY_TO_INVOICE, QTY_TO_SHIP, UNIT_PRICE, UNIT_COST_LCY, VAT, LINE_DISCOUNT, LINE_DISCOUNT_AMOUNT, AMOUNT, AMOUNT_INCLUDING_VAT, ALLOW_INVOICE_DISC, GROSS_WEIGHT, NET_WEIGHT, UNITS_PER_PARCEL, UNIT_VOLUME, APPL_TO_ITEM_ENTRY, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_PRICE_GROUP, JOB_NO, WORK_TYPE_CODE, RECALCULATE_INVOICE_DISC, OUTSTANDING_AMOUNT, QTY_SHIPPED_NOT_INVOICED, SHIPPED_NOT_INVOICED, QUANTITY_SHIPPED, QUANTITY_INVOICED, SHIPMENT_NO, SHIPMENT_LINE_NO, PROFIT, BILL_TO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, INV_DISCOUNT_AMOUNT, PURCHASE_ORDER_NO, PURCH_ORDER_LINE_NO, DROP_SHIPMENT, GEN_BUS_POSTING_GROUP, GEN_PROD_POSTING_GROUP, VAT_CALCULATION_TYPE, TRANSACTION_TYPE, TRANSPORT_METHOD, ATTACHED_TO_LINE_NO, EXIT_POINT, AREA, TRANSACTION_SPECIFICATION, TAX_CATEGORY, TAX_AREA_CODE, TAX_LIABLE, TAX_GROUP_CODE, VAT_CLAUSE_CODE, VAT_BUS_POSTING_GROUP, VAT_PROD_POSTING_GROUP, CURRENCY_CODE, OUTSTANDING_AMOUNT_LCY, SHIPPED_NOT_INVOICED_LCY, RESERVE, SHIPPED_NOT_INV_LCY_NO_VAT, BLANKET_ORDER_NO, BLANKET_ORDER_LINE_NO, VAT_BASE_AMOUNT, UNIT_COST, SYSTEM_CREATED_ENTRY, LINE_AMOUNT, SYSTEMCREATED_ENTRY, VAT_DIFFERENCE, INV_DISC_AMOUNT_TO_INVOICE, VAT_IDENTIFIER, IC_PARTNER_REF_TYPE, IC_PARTNER_REFERENCE, PREPAYMENT, PREPMT_LINE_AMOUNT, PREPMT_AMT_INV, PREPMT_AMT_INCL_VAT, PREPAYMENT_AMOUNT, PREPMT_VAT_BASE_AMT, PREPAYMENT_VAT, PREPMT_VAT_CALC_TYPE, PREPAYMENT_VAT_IDENTIFIER, PREPAYMENT_TAX_AREA_CODE, PREPAYMENT_TAX_LIABLE, PREPAYMENT_TAX_GROUP_CODE, PREPMT_AMT_TO_DEDUCT, PREPMT_AMT_DEDUCTED, PREPAYMENT_LINE, PREPMT_AMOUNT_INV_INCL_VAT, PREPMT_AMOUNT_INV_LCY, IC_PARTNER_CODE, PREPMT_VAT_AMOUNT_INV_LCY, PREPAYMENT_VAT_DIFFERENCE, PREPMT_VAT_DIFF_TO_DEDUCT, PREPMT_VAT_DIFF_DEDUCTED, DIMENSION_SET_ID, QTY_TO_ASSEMBLE_TO_ORDER, PMT_DISCOUNT_AMOUNT, LINE_DISCOUNT_CALCULATION, QTY_TO_ASM_TO_ORDER_BASE, JOB_TASK_NO, JOB_CONTRACT_ENTRY_NO, DEFERRAL_CODE, RETURNS_DEFERRAL_START_DATE, VARIANT_CODE, BIN_CODE, QTY_PER_UNIT_OF_MEASURE, PLANNED, UNIT_OF_MEASURE_CODE, QUANTITY_BASE, OUTSTANDING_QTY_BASE, QTY_TO_INVOICE_BASE, QTY_TO_SHIP_BASE, QTY_SHIPPED_NOT_INVD_BASE, QTY_SHIPPED_BASE, QTY_INVOICED_BASE, FA_POSTING_DATE, DEPRECIATION_BOOK_CODE, DEPR_UNTIL_FA_POSTING_DATE, DUPLICATE_IN_DEPRECIATION_BOOK, USE_DUPLICATION_LIST, RESPONSIBILITY_CENTER, OUT_OF_STOCK_SUBSTITUTION, ORIGINALLY_ORDERED_NO, ORIGINALLY_ORDERED_VAR_CODE, CROSS_REFERENCE_NO, OUTOFSTOCK_SUBSTITUTION, UNIT_OF_MEASURE_CROSS_REF, CROSS_REFERENCE_TYPE, CROSS_REFERENCE_TYPE_NO, CROSSREFERENCE_NO, ITEM_CATEGORY_CODE, NONSTOCK, CROSSREFERENCE_TYPE, PURCHASING_CODE, CROSSREFERENCE_TYPE_NO, PRODUCT_GROUP_CODE, SPECIAL_ORDER, SPECIAL_ORDER_PURCHASE_NO, SPECIAL_ORDER_PURCH_LINE_NO, COMPLETELY_SHIPPED, REQUESTED_DELIVERY_DATE, PROMISED_DELIVERY_DATE, SHIPPING_TIME, OUTBOUND_WHSE_HANDLING_TIME, PLANNED_DELIVERY_DATE, PLANNED_SHIPMENT_DATE, SHIPPING_AGENT_CODE, SHIPPING_AGENT_SERVICE_CODE, ALLOW_ITEM_CHARGE_ASSIGNMENT, RETURN_QTY_TO_RECEIVE, RETURN_QTY_TO_RECEIVE_BASE, RETURN_QTY_RCD_NOT_INVD, RET_QTY_RCD_NOT_INVD_BASE, RETURN_RCD_NOT_INVD, RETURN_RCD_NOT_INVD_LCY, RETURN_QTY_RECEIVED, RETURN_QTY_RECEIVED_BASE, APPL_FROM_ITEM_ENTRY, BOM_ITEM_NO, RETURN_RECEIPT_NO, RETURN_RECEIPT_LINE_NO, RETURN_REASON_CODE, ALLOW_LINE_DISC, CUSTOMER_DISC_GROUP, PMT_DISC_GIVEN_AMOUNT, COPIED_FROM_POSTED_DOC, EC, EC_DIFFERENCE, PREPAYMENT_EC, SUBTYPE, NO_PEDIDO_ORIGEN, MANUFACTURING_COMMENTS, NO_LINEA_PEDIDO_ORIGEN, PRICE_DESCRIPTION, MURANO_CODE, BLOQUEAR_PROMOCIONES, PMT_DISC_GIVEN_AMOUNT_OLD, KG, BOXES, COD_CADENA, PALLETS, PROMOCIONES_POR, KG_TO_SHIP, COMISIONES_POR, BOXES_TO_SHIP, IDPIRPF_IRPF_GROUP, CODIGO_EMBALAJE, IDPIRPF_IRPF_AMOUNT, PALLETS_TO_SHIP, CANTIDAD_EMBALAJE, CANTIDAD_UNIDADES, IDPIRPF_IRPF, COMMENT_LINE, CANTIDAD_KILOS, IDPIRPF_IRPF_BASE_AMOUNT, ROWS_PALET, IDPIRPF_AMOUNT_INCL_IRPF, CANTIDAD_EMBALAJE_TEORICO, ROWS_PALET_TO_SHIP, CANTIDAD_UNIDADES_TEORICO, SELECTED_UNIT_TYPE, HEIGHT_PALLET_TO_SHIP, IDPVUM_QUANTITY, CANTIDAD_KILOS_TEORICO, ENTIRE_PALLETS_TO_SHIP, IDPVUM_UNIT_OF_MEASURE_CODE, CANTIDAD_EMBALAJE_A_ENVIAR, IDPVUM_UNIT_PRICE, CANTIDAD_UNIDADES_A_ENVIAR, BOXES_ALONE_TO_SHIP, CANTIDAD_KILOS_A_ENVIAR, SHIPMENT_COMMENTS, IDPVUM_PRICE_IN_VUM, CANTIDAD_EMBALAJE_ENVIADO, IDPVUM_VUM_PER_UNIT, PREPARATION_STATUS, PALLET_NO, IDPVUM_OUTSTANDING_QTY, CANTIDAD_UNIDADES_ENVIADA, IDPVUM_QTY_TO_INVOICE, MIGRATION_LOT_NO, CANTIDAD_KILOS_ENVIADO, IDPVUM_QTY_TO_SHIP, NO_ALBARAN_VENTA, NO_PRESENTACION, IDPVUM_QTY_SHIPPED_NOT_INV, NO_LINEA_ALBARAN_VENTA, DESCRIPCION_PRESENTACION, IDPVUM_QUANTITY_SHIPPED, COD_VENDEDOR_1, OBSERVACIONES, ESTADO_PLANIFICACION, IDPVUM_QUANTITY_INVOICED, COD_VENDEDOR_2, MOTIVO_DEVOLUCION, IDPVUM_QTY_TO_ASSBLE_ORDER, COD_VENDEDOR_3, IDPVUM_RETURN_QTY_TO_RECEIVE, COM_1, SERVICIO, COM_2, IDPVUM_RETN_QTY_RD_NOT_INV, CANTIDAD_EMBALAJE_OP_TRANSF, COM_3, IDPVUM_RETURN_QTY_RECEIVED, CANTIDAD_UNIDADES_OP_TRANSF, DTO_1, CANTIDAD_KILOS_OP_TRANSF, IDPVUM_UPDATE_SOURCE, IDPGND_SIG_AMOUNT, TIPO_DTO_2, PRECIO_PUNTO_VERDE_CDAD, IDPGND_SIG_RATE, UNIDAD_MEDIDA_PUNTO_VERDE, DTO_2, TIPO_DTO_3, IMPORTE_PUNTO_VERDE, IDPGND_SIG, IDPGND_POSTING_DATE_SHIPMENT, DTO_3, GRUPO_RESIDUOS, IDPGND_SHIPMENT_DATE_SHIPMENT, PRECIO_RESIDUOS_CDAD, TIPO_DTO_4, DTO_4, UNIDAD_MEDIDA_RESIDUOS, IDPGND_REQ_DEL_DATE_SHIPMENT, TIPO_DTO_5, IMPORTE_RESIDUOS, IF_OR_TYPE, ANS_FECHA_CADUCIDAD, IF_UNIT_PRICE_CODE, DTO_5, IF_NUM_BOXES_NEEDED, ITEM_CROSS_REFERENCE_CODE, NUEVO_CODIGO_EMBALAJE, CONFIGURADOR, IF_NUM_CONT_NEEDED, LINEA_EMBALAJE, NEGRILLA, IF_DUN14, CODIGO_PALET, SALES_DATE, BASE_RAPPEL, CANTIDAD_PALETS, DESCRIPCION_EDI, CERRADO, MANTENER_PRECIOS, FECHA_REGISTRO, TEMPQTY, NO_PEDIDO_COMPRA_BACKUP, ORIGINAL_QUANTITY, PRECIO_ORIGEN, NO_ALBARAN_TRAIDO, DTO_ORIGEN, NO_LINEA_ALBARAN_TRAIDO, ORIGINAL_QUANTITY_UMV, TEC_DES_EMPRESA, LAST_INVOICE_UNIT_PRICE, NO_ALBARAN_ORIGEN, TEC_ID_INGESTA, LAST_INVOICE_DATE_UNIT_PRICE, NO_LINEA_ALBARAN_ORIGEN, TEC_TS_INGESTA, CLAIM_CODE, COMENTARIO_GENERAL, W_ITEM_ENTRIES, TEC_TS_STAGING, COMENTARIO_ASOCIADO, REAL_SHIPMENT_DATE, TEC_TS_INTEGRACION_B, FECHA_DE_PEDIDO, ORIGINAL_QTY, COMMISSION_BLOCKED, SAMPLE, INCOME_TAX_RETENTION_CODE, INCOME_TAX_RETENCION, EDI_POSITION, CREATION_DATE, INCOME_TAX_BASE, SALESPERSON_CODE, MIN_PRICE, COMMISSION_SALESPERSON, PLATE_QTY, PLATES_TO_SHIP, 2ND_SALESPERSON_CODE, COMMISSION_2ND_SALESPERSON, PLATES_SHIPPED, CANTIDAD_EMBALAJE_CLI, VAT_BREAKDOWN, CANTIDAD_UNIDADES_CLI, TYPE_BREAKDOWN, FCP, CANTIDAD_KILOS_CLI, PROD_ORDER_NO, POSTING_STATUS, PROD_ORDER_LINE_NO, EDI_SHIPMENT_NO, EDI_SHIPMENT_DATE, MANUFACTURING_DATE, PRECIO_VENTA_MIN, CADASTRAL_REFERENCE, PRECIO_CONFIRMADO, PROPERTY_SITUATION, Q_CONFIRMADA_RECADV, USUARIO_CONFIRMACION_PRECIO, FECHA_HORA_CONFIRMACION_PRECIO, PLASTIC_LINE, SPECIAL_LINE_TYPE, TARIFF_NO, SALES_SHIPMENT_NO, SALES_SHIPMENT_LINE_NO, RECADCV_QUANTITY, EDI_POSITION_SUBLINE, GLN, EDI_PRICE, EDI_DISCOUNT, ENVIO_VALIDADO, FECHA_ENVIO_CABECERA) AS tec_hash,
                date(tec_ts_ingesta) as tec_fec_inicio
            from {{ ref('sales_line_batch') }}
        ) s
        on t.tec_cod_vigencia = 1
            and 1=1
        when matched and t.tec_hash <> s.tec_hash then
            update set
                tec_cod_vigencia = 0,
                tec_fec_fin = case
                    when s.tec_fec_inicio = t.tec_fec_inicio then s.tec_fec_inicio
                    else dateadd(day, -1, s.tec_fec_inicio)
                end;
        {% endif %}"
    ],
    post_hook=[
        "{% set log_ref = source('support_param', 'INSERT_LOGS') %}{% set asociados = var('empresas', []) %}{% for a in asociados %}
            {% set src_ref = source('bronze_' ~ a, 'COOPECARN_SALES_LINE') %}
            -- Sella ÚNICAMENTE el batch (tec_id_ingesta) que está procesando la view {{ ref('sales_line_batch_' ~ a) }}
            update {{ log_ref }} l
            set tec_ts_integracion_b = current_timestamp()
            where l.tec_ts_integracion_b is null
              and l.start_watermark <> l.end_watermark
              and upper(l.database)   = upper('{{ src_ref.database }}')
              and upper(l.schema)     = upper('{{ src_ref.schema }}')
              and upper(l.table_name) = upper('{{ src_ref.identifier }}')
              and exists (
                  select 1
                  from {{ ref('sales_line_batch_' ~ a) }} v
                  where v.tec_id_ingesta = l.tec_id_ingesta
              );
        {% endfor %}"
    ]
) }}

with source as (
    select
        timestamp, 
        document_type, 
        document_no, 
        line_no, 
        sellto_customer_no, 
        sell_to_customer_no, 
        type, 
        no, 
        location_code, 
        posting_group, 
        shipment_date, 
        description, 
        description_2, 
        unit_of_measure, 
        quantity, 
        outstanding_quantity, 
        qty_to_invoice, 
        qty_to_ship, 
        unit_price, 
        unit_cost_lcy, 
        vat, 
        line_discount, 
        line_discount_amount, 
        amount, 
        amount_including_vat, 
        allow_invoice_disc, 
        gross_weight, 
        net_weight, 
        units_per_parcel, 
        unit_volume, 
        appl_to_item_entry, 
        shortcut_dimension_1_code, 
        shortcut_dimension_2_code, 
        customer_price_group, 
        job_no, 
        work_type_code, 
        recalculate_invoice_disc, 
        outstanding_amount, 
        qty_shipped_not_invoiced, 
        shipped_not_invoiced, 
        quantity_shipped, 
        quantity_invoiced, 
        shipment_no, 
        shipment_line_no, 
        profit, 
        bill_to_customer_no, 
        billto_customer_no, 
        inv_discount_amount, 
        purchase_order_no, 
        purch_order_line_no, 
        drop_shipment, 
        gen_bus_posting_group, 
        gen_prod_posting_group, 
        vat_calculation_type, 
        transaction_type, 
        transport_method, 
        attached_to_line_no, 
        exit_point, 
        area, 
        transaction_specification, 
        tax_category, 
        tax_area_code, 
        tax_liable, 
        tax_group_code, 
        vat_clause_code, 
        vat_bus_posting_group, 
        vat_prod_posting_group, 
        currency_code, 
        outstanding_amount_lcy, 
        shipped_not_invoiced_lcy, 
        reserve, 
        shipped_not_inv_lcy_no_vat, 
        blanket_order_no, 
        blanket_order_line_no, 
        vat_base_amount, 
        unit_cost, 
        system_created_entry, 
        line_amount, 
        systemcreated_entry, 
        vat_difference, 
        inv_disc_amount_to_invoice, 
        vat_identifier, 
        ic_partner_ref_type, 
        ic_partner_reference, 
        prepayment, 
        prepmt_line_amount, 
        prepmt_amt_inv, 
        prepmt_amt_incl_vat, 
        prepayment_amount, 
        prepmt_vat_base_amt, 
        prepayment_vat, 
        prepmt_vat_calc_type, 
        prepayment_vat_identifier, 
        prepayment_tax_area_code, 
        prepayment_tax_liable, 
        prepayment_tax_group_code, 
        prepmt_amt_to_deduct, 
        prepmt_amt_deducted, 
        prepayment_line, 
        prepmt_amount_inv_incl_vat, 
        prepmt_amount_inv_lcy, 
        ic_partner_code, 
        prepmt_vat_amount_inv_lcy, 
        prepayment_vat_difference, 
        prepmt_vat_diff_to_deduct, 
        prepmt_vat_diff_deducted, 
        dimension_set_id, 
        qty_to_assemble_to_order, 
        pmt_discount_amount, 
        line_discount_calculation, 
        qty_to_asm_to_order_base, 
        job_task_no, 
        job_contract_entry_no, 
        deferral_code, 
        returns_deferral_start_date, 
        variant_code, 
        bin_code, 
        qty_per_unit_of_measure, 
        planned, 
        unit_of_measure_code, 
        quantity_base, 
        outstanding_qty_base, 
        qty_to_invoice_base, 
        qty_to_ship_base, 
        qty_shipped_not_invd_base, 
        qty_shipped_base, 
        qty_invoiced_base, 
        fa_posting_date, 
        depreciation_book_code, 
        depr_until_fa_posting_date, 
        duplicate_in_depreciation_book, 
        use_duplication_list, 
        responsibility_center, 
        out_of_stock_substitution, 
        originally_ordered_no, 
        originally_ordered_var_code, 
        cross_reference_no, 
        outofstock_substitution, 
        unit_of_measure_cross_ref, 
        cross_reference_type, 
        cross_reference_type_no, 
        crossreference_no, 
        item_category_code, 
        nonstock, 
        crossreference_type, 
        purchasing_code, 
        crossreference_type_no, 
        product_group_code, 
        special_order, 
        special_order_purchase_no, 
        special_order_purch_line_no, 
        completely_shipped, 
        requested_delivery_date, 
        promised_delivery_date, 
        shipping_time, 
        outbound_whse_handling_time, 
        planned_delivery_date, 
        planned_shipment_date, 
        shipping_agent_code, 
        shipping_agent_service_code, 
        allow_item_charge_assignment, 
        return_qty_to_receive, 
        return_qty_to_receive_base, 
        return_qty_rcd_not_invd, 
        ret_qty_rcd_not_invd_base, 
        return_rcd_not_invd, 
        return_rcd_not_invd_lcy, 
        return_qty_received, 
        return_qty_received_base, 
        appl_from_item_entry, 
        bom_item_no, 
        return_receipt_no, 
        return_receipt_line_no, 
        return_reason_code, 
        allow_line_disc, 
        customer_disc_group, 
        pmt_disc_given_amount, 
        copied_from_posted_doc, 
        ec, 
        ec_difference, 
        prepayment_ec, 
        subtype, 
        no_pedido_origen, 
        manufacturing_comments, 
        no_linea_pedido_origen, 
        price_description, 
        murano_code, 
        bloquear_promociones, 
        pmt_disc_given_amount_old, 
        kg, 
        boxes, 
        cod_cadena, 
        pallets, 
        promociones_por, 
        kg_to_ship, 
        comisiones_por, 
        boxes_to_ship, 
        idpirpf_irpf_group, 
        codigo_embalaje, 
        idpirpf_irpf_amount, 
        pallets_to_ship, 
        cantidad_embalaje, 
        cantidad_unidades, 
        idpirpf_irpf, 
        comment_line, 
        cantidad_kilos, 
        idpirpf_irpf_base_amount, 
        rows_palet, 
        idpirpf_amount_incl_irpf, 
        cantidad_embalaje_teorico, 
        rows_palet_to_ship, 
        cantidad_unidades_teorico, 
        selected_unit_type, 
        height_pallet_to_ship, 
        idpvum_quantity, 
        cantidad_kilos_teorico, 
        entire_pallets_to_ship, 
        idpvum_unit_of_measure_code, 
        cantidad_embalaje_a_enviar, 
        idpvum_unit_price, 
        cantidad_unidades_a_enviar, 
        boxes_alone_to_ship, 
        cantidad_kilos_a_enviar, 
        shipment_comments, 
        idpvum_price_in_vum, 
        cantidad_embalaje_enviado, 
        idpvum_vum_per_unit, 
        preparation_status, 
        pallet_no, 
        idpvum_outstanding_qty, 
        cantidad_unidades_enviada, 
        idpvum_qty_to_invoice, 
        migration_lot_no, 
        cantidad_kilos_enviado, 
        idpvum_qty_to_ship, 
        no_albaran_venta, 
        no_presentacion, 
        idpvum_qty_shipped_not_inv, 
        no_linea_albaran_venta, 
        descripcion_presentacion, 
        idpvum_quantity_shipped, 
        cod_vendedor_1, 
        observaciones, 
        estado_planificacion, 
        idpvum_quantity_invoiced, 
        cod_vendedor_2, 
        motivo_devolucion, 
        idpvum_qty_to_assble_order, 
        cod_vendedor_3, 
        idpvum_return_qty_to_receive, 
        com_1, 
        servicio, 
        com_2, 
        idpvum_retn_qty_rd_not_inv, 
        cantidad_embalaje_op_transf, 
        com_3, 
        idpvum_return_qty_received, 
        cantidad_unidades_op_transf, 
        dto_1, 
        cantidad_kilos_op_transf, 
        idpvum_update_source, 
        idpgnd_sig_amount, 
        tipo_dto_2, 
        precio_punto_verde_cdad, 
        idpgnd_sig_rate, 
        unidad_medida_punto_verde, 
        dto_2, 
        tipo_dto_3, 
        importe_punto_verde, 
        idpgnd_sig, 
        idpgnd_posting_date_shipment, 
        dto_3, 
        grupo_residuos, 
        idpgnd_shipment_date_shipment, 
        precio_residuos_cdad, 
        tipo_dto_4, 
        dto_4, 
        unidad_medida_residuos, 
        idpgnd_req_del_date_shipment, 
        tipo_dto_5, 
        importe_residuos, 
        if_or_type, 
        ans_fecha_caducidad, 
        if_unit_price_code, 
        dto_5, 
        if_num_boxes_needed, 
        item_cross_reference_code, 
        nuevo_codigo_embalaje, 
        configurador, 
        if_num_cont_needed, 
        linea_embalaje, 
        negrilla, 
        if_dun14, 
        codigo_palet, 
        sales_date, 
        base_rappel, 
        cantidad_palets, 
        descripcion_edi, 
        cerrado, 
        mantener_precios, 
        fecha_registro, 
        tempqty, 
        no_pedido_compra_backup, 
        original_quantity, 
        precio_origen, 
        no_albaran_traido, 
        dto_origen, 
        no_linea_albaran_traido, 
        original_quantity_umv, 
        tec_des_empresa, 
        last_invoice_unit_price, 
        no_albaran_origen, 
        tec_id_ingesta, 
        last_invoice_date_unit_price, 
        no_linea_albaran_origen, 
        tec_ts_ingesta, 
        claim_code, 
        comentario_general, 
        w_item_entries, 
        tec_ts_staging, 
        comentario_asociado, 
        real_shipment_date, 
        tec_ts_integracion_b, 
        fecha_de_pedido, 
        original_qty, 
        commission_blocked, 
        sample, 
        income_tax_retention_code, 
        income_tax_retencion, 
        edi_position, 
        creation_date, 
        income_tax_base, 
        salesperson_code, 
        min_price, 
        commission_salesperson, 
        plate_qty, 
        plates_to_ship, 
        2nd_salesperson_code, 
        commission_2nd_salesperson, 
        plates_shipped, 
        cantidad_embalaje_cli, 
        vat_breakdown, 
        cantidad_unidades_cli, 
        type_breakdown, 
        fcp, 
        cantidad_kilos_cli, 
        prod_order_no, 
        posting_status, 
        prod_order_line_no, 
        edi_shipment_no, 
        edi_shipment_date, 
        manufacturing_date, 
        precio_venta_min, 
        cadastral_reference, 
        precio_confirmado, 
        property_situation, 
        q_confirmada_recadv, 
        usuario_confirmacion_precio, 
        fecha_hora_confirmacion_precio, 
        plastic_line, 
        special_line_type, 
        tariff_no, 
        sales_shipment_no, 
        sales_shipment_line_no, 
        recadcv_quantity, 
        edi_position_subline, 
        gln, 
        edi_price, 
        edi_discount, 
        envio_validado, 
        fecha_envio_cabecera, 
        tec_des_cod_siglas, 
        tec_des_empresa, 
        tec_id_ingesta, 
        tec_ts_ingesta, 
        HASH(TIMESTAMP, DOCUMENT_TYPE, DOCUMENT_NO, LINE_NO, SELLTO_CUSTOMER_NO, SELL_TO_CUSTOMER_NO, TYPE, NO, LOCATION_CODE, POSTING_GROUP, SHIPMENT_DATE, DESCRIPTION, DESCRIPTION_2, UNIT_OF_MEASURE, QUANTITY, OUTSTANDING_QUANTITY, QTY_TO_INVOICE, QTY_TO_SHIP, UNIT_PRICE, UNIT_COST_LCY, VAT, LINE_DISCOUNT, LINE_DISCOUNT_AMOUNT, AMOUNT, AMOUNT_INCLUDING_VAT, ALLOW_INVOICE_DISC, GROSS_WEIGHT, NET_WEIGHT, UNITS_PER_PARCEL, UNIT_VOLUME, APPL_TO_ITEM_ENTRY, SHORTCUT_DIMENSION_1_CODE, SHORTCUT_DIMENSION_2_CODE, CUSTOMER_PRICE_GROUP, JOB_NO, WORK_TYPE_CODE, RECALCULATE_INVOICE_DISC, OUTSTANDING_AMOUNT, QTY_SHIPPED_NOT_INVOICED, SHIPPED_NOT_INVOICED, QUANTITY_SHIPPED, QUANTITY_INVOICED, SHIPMENT_NO, SHIPMENT_LINE_NO, PROFIT, BILL_TO_CUSTOMER_NO, BILLTO_CUSTOMER_NO, INV_DISCOUNT_AMOUNT, PURCHASE_ORDER_NO, PURCH_ORDER_LINE_NO, DROP_SHIPMENT, GEN_BUS_POSTING_GROUP, GEN_PROD_POSTING_GROUP, VAT_CALCULATION_TYPE, TRANSACTION_TYPE, TRANSPORT_METHOD, ATTACHED_TO_LINE_NO, EXIT_POINT, AREA, TRANSACTION_SPECIFICATION, TAX_CATEGORY, TAX_AREA_CODE, TAX_LIABLE, TAX_GROUP_CODE, VAT_CLAUSE_CODE, VAT_BUS_POSTING_GROUP, VAT_PROD_POSTING_GROUP, CURRENCY_CODE, OUTSTANDING_AMOUNT_LCY, SHIPPED_NOT_INVOICED_LCY, RESERVE, SHIPPED_NOT_INV_LCY_NO_VAT, BLANKET_ORDER_NO, BLANKET_ORDER_LINE_NO, VAT_BASE_AMOUNT, UNIT_COST, SYSTEM_CREATED_ENTRY, LINE_AMOUNT, SYSTEMCREATED_ENTRY, VAT_DIFFERENCE, INV_DISC_AMOUNT_TO_INVOICE, VAT_IDENTIFIER, IC_PARTNER_REF_TYPE, IC_PARTNER_REFERENCE, PREPAYMENT, PREPMT_LINE_AMOUNT, PREPMT_AMT_INV, PREPMT_AMT_INCL_VAT, PREPAYMENT_AMOUNT, PREPMT_VAT_BASE_AMT, PREPAYMENT_VAT, PREPMT_VAT_CALC_TYPE, PREPAYMENT_VAT_IDENTIFIER, PREPAYMENT_TAX_AREA_CODE, PREPAYMENT_TAX_LIABLE, PREPAYMENT_TAX_GROUP_CODE, PREPMT_AMT_TO_DEDUCT, PREPMT_AMT_DEDUCTED, PREPAYMENT_LINE, PREPMT_AMOUNT_INV_INCL_VAT, PREPMT_AMOUNT_INV_LCY, IC_PARTNER_CODE, PREPMT_VAT_AMOUNT_INV_LCY, PREPAYMENT_VAT_DIFFERENCE, PREPMT_VAT_DIFF_TO_DEDUCT, PREPMT_VAT_DIFF_DEDUCTED, DIMENSION_SET_ID, QTY_TO_ASSEMBLE_TO_ORDER, PMT_DISCOUNT_AMOUNT, LINE_DISCOUNT_CALCULATION, QTY_TO_ASM_TO_ORDER_BASE, JOB_TASK_NO, JOB_CONTRACT_ENTRY_NO, DEFERRAL_CODE, RETURNS_DEFERRAL_START_DATE, VARIANT_CODE, BIN_CODE, QTY_PER_UNIT_OF_MEASURE, PLANNED, UNIT_OF_MEASURE_CODE, QUANTITY_BASE, OUTSTANDING_QTY_BASE, QTY_TO_INVOICE_BASE, QTY_TO_SHIP_BASE, QTY_SHIPPED_NOT_INVD_BASE, QTY_SHIPPED_BASE, QTY_INVOICED_BASE, FA_POSTING_DATE, DEPRECIATION_BOOK_CODE, DEPR_UNTIL_FA_POSTING_DATE, DUPLICATE_IN_DEPRECIATION_BOOK, USE_DUPLICATION_LIST, RESPONSIBILITY_CENTER, OUT_OF_STOCK_SUBSTITUTION, ORIGINALLY_ORDERED_NO, ORIGINALLY_ORDERED_VAR_CODE, CROSS_REFERENCE_NO, OUTOFSTOCK_SUBSTITUTION, UNIT_OF_MEASURE_CROSS_REF, CROSS_REFERENCE_TYPE, CROSS_REFERENCE_TYPE_NO, CROSSREFERENCE_NO, ITEM_CATEGORY_CODE, NONSTOCK, CROSSREFERENCE_TYPE, PURCHASING_CODE, CROSSREFERENCE_TYPE_NO, PRODUCT_GROUP_CODE, SPECIAL_ORDER, SPECIAL_ORDER_PURCHASE_NO, SPECIAL_ORDER_PURCH_LINE_NO, COMPLETELY_SHIPPED, REQUESTED_DELIVERY_DATE, PROMISED_DELIVERY_DATE, SHIPPING_TIME, OUTBOUND_WHSE_HANDLING_TIME, PLANNED_DELIVERY_DATE, PLANNED_SHIPMENT_DATE, SHIPPING_AGENT_CODE, SHIPPING_AGENT_SERVICE_CODE, ALLOW_ITEM_CHARGE_ASSIGNMENT, RETURN_QTY_TO_RECEIVE, RETURN_QTY_TO_RECEIVE_BASE, RETURN_QTY_RCD_NOT_INVD, RET_QTY_RCD_NOT_INVD_BASE, RETURN_RCD_NOT_INVD, RETURN_RCD_NOT_INVD_LCY, RETURN_QTY_RECEIVED, RETURN_QTY_RECEIVED_BASE, APPL_FROM_ITEM_ENTRY, BOM_ITEM_NO, RETURN_RECEIPT_NO, RETURN_RECEIPT_LINE_NO, RETURN_REASON_CODE, ALLOW_LINE_DISC, CUSTOMER_DISC_GROUP, PMT_DISC_GIVEN_AMOUNT, COPIED_FROM_POSTED_DOC, EC, EC_DIFFERENCE, PREPAYMENT_EC, SUBTYPE, NO_PEDIDO_ORIGEN, MANUFACTURING_COMMENTS, NO_LINEA_PEDIDO_ORIGEN, PRICE_DESCRIPTION, MURANO_CODE, BLOQUEAR_PROMOCIONES, PMT_DISC_GIVEN_AMOUNT_OLD, KG, BOXES, COD_CADENA, PALLETS, PROMOCIONES_POR, KG_TO_SHIP, COMISIONES_POR, BOXES_TO_SHIP, IDPIRPF_IRPF_GROUP, CODIGO_EMBALAJE, IDPIRPF_IRPF_AMOUNT, PALLETS_TO_SHIP, CANTIDAD_EMBALAJE, CANTIDAD_UNIDADES, IDPIRPF_IRPF, COMMENT_LINE, CANTIDAD_KILOS, IDPIRPF_IRPF_BASE_AMOUNT, ROWS_PALET, IDPIRPF_AMOUNT_INCL_IRPF, CANTIDAD_EMBALAJE_TEORICO, ROWS_PALET_TO_SHIP, CANTIDAD_UNIDADES_TEORICO, SELECTED_UNIT_TYPE, HEIGHT_PALLET_TO_SHIP, IDPVUM_QUANTITY, CANTIDAD_KILOS_TEORICO, ENTIRE_PALLETS_TO_SHIP, IDPVUM_UNIT_OF_MEASURE_CODE, CANTIDAD_EMBALAJE_A_ENVIAR, IDPVUM_UNIT_PRICE, CANTIDAD_UNIDADES_A_ENVIAR, BOXES_ALONE_TO_SHIP, CANTIDAD_KILOS_A_ENVIAR, SHIPMENT_COMMENTS, IDPVUM_PRICE_IN_VUM, CANTIDAD_EMBALAJE_ENVIADO, IDPVUM_VUM_PER_UNIT, PREPARATION_STATUS, PALLET_NO, IDPVUM_OUTSTANDING_QTY, CANTIDAD_UNIDADES_ENVIADA, IDPVUM_QTY_TO_INVOICE, MIGRATION_LOT_NO, CANTIDAD_KILOS_ENVIADO, IDPVUM_QTY_TO_SHIP, NO_ALBARAN_VENTA, NO_PRESENTACION, IDPVUM_QTY_SHIPPED_NOT_INV, NO_LINEA_ALBARAN_VENTA, DESCRIPCION_PRESENTACION, IDPVUM_QUANTITY_SHIPPED, COD_VENDEDOR_1, OBSERVACIONES, ESTADO_PLANIFICACION, IDPVUM_QUANTITY_INVOICED, COD_VENDEDOR_2, MOTIVO_DEVOLUCION, IDPVUM_QTY_TO_ASSBLE_ORDER, COD_VENDEDOR_3, IDPVUM_RETURN_QTY_TO_RECEIVE, COM_1, SERVICIO, COM_2, IDPVUM_RETN_QTY_RD_NOT_INV, CANTIDAD_EMBALAJE_OP_TRANSF, COM_3, IDPVUM_RETURN_QTY_RECEIVED, CANTIDAD_UNIDADES_OP_TRANSF, DTO_1, CANTIDAD_KILOS_OP_TRANSF, IDPVUM_UPDATE_SOURCE, IDPGND_SIG_AMOUNT, TIPO_DTO_2, PRECIO_PUNTO_VERDE_CDAD, IDPGND_SIG_RATE, UNIDAD_MEDIDA_PUNTO_VERDE, DTO_2, TIPO_DTO_3, IMPORTE_PUNTO_VERDE, IDPGND_SIG, IDPGND_POSTING_DATE_SHIPMENT, DTO_3, GRUPO_RESIDUOS, IDPGND_SHIPMENT_DATE_SHIPMENT, PRECIO_RESIDUOS_CDAD, TIPO_DTO_4, DTO_4, UNIDAD_MEDIDA_RESIDUOS, IDPGND_REQ_DEL_DATE_SHIPMENT, TIPO_DTO_5, IMPORTE_RESIDUOS, IF_OR_TYPE, ANS_FECHA_CADUCIDAD, IF_UNIT_PRICE_CODE, DTO_5, IF_NUM_BOXES_NEEDED, ITEM_CROSS_REFERENCE_CODE, NUEVO_CODIGO_EMBALAJE, CONFIGURADOR, IF_NUM_CONT_NEEDED, LINEA_EMBALAJE, NEGRILLA, IF_DUN14, CODIGO_PALET, SALES_DATE, BASE_RAPPEL, CANTIDAD_PALETS, DESCRIPCION_EDI, CERRADO, MANTENER_PRECIOS, FECHA_REGISTRO, TEMPQTY, NO_PEDIDO_COMPRA_BACKUP, ORIGINAL_QUANTITY, PRECIO_ORIGEN, NO_ALBARAN_TRAIDO, DTO_ORIGEN, NO_LINEA_ALBARAN_TRAIDO, ORIGINAL_QUANTITY_UMV, TEC_DES_EMPRESA, LAST_INVOICE_UNIT_PRICE, NO_ALBARAN_ORIGEN, TEC_ID_INGESTA, LAST_INVOICE_DATE_UNIT_PRICE, NO_LINEA_ALBARAN_ORIGEN, TEC_TS_INGESTA, CLAIM_CODE, COMENTARIO_GENERAL, W_ITEM_ENTRIES, TEC_TS_STAGING, COMENTARIO_ASOCIADO, REAL_SHIPMENT_DATE, TEC_TS_INTEGRACION_B, FECHA_DE_PEDIDO, ORIGINAL_QTY, COMMISSION_BLOCKED, SAMPLE, INCOME_TAX_RETENTION_CODE, INCOME_TAX_RETENCION, EDI_POSITION, CREATION_DATE, INCOME_TAX_BASE, SALESPERSON_CODE, MIN_PRICE, COMMISSION_SALESPERSON, PLATE_QTY, PLATES_TO_SHIP, 2ND_SALESPERSON_CODE, COMMISSION_2ND_SALESPERSON, PLATES_SHIPPED, CANTIDAD_EMBALAJE_CLI, VAT_BREAKDOWN, CANTIDAD_UNIDADES_CLI, TYPE_BREAKDOWN, FCP, CANTIDAD_KILOS_CLI, PROD_ORDER_NO, POSTING_STATUS, PROD_ORDER_LINE_NO, EDI_SHIPMENT_NO, EDI_SHIPMENT_DATE, MANUFACTURING_DATE, PRECIO_VENTA_MIN, CADASTRAL_REFERENCE, PRECIO_CONFIRMADO, PROPERTY_SITUATION, Q_CONFIRMADA_RECADV, USUARIO_CONFIRMACION_PRECIO, FECHA_HORA_CONFIRMACION_PRECIO, PLASTIC_LINE, SPECIAL_LINE_TYPE, TARIFF_NO, SALES_SHIPMENT_NO, SALES_SHIPMENT_LINE_NO, RECADCV_QUANTITY, EDI_POSITION_SUBLINE, GLN, EDI_PRICE, EDI_DISCOUNT, ENVIO_VALIDADO, FECHA_ENVIO_CABECERA) AS tec_hash, 
        date(tec_ts_ingesta) as tec_fec_inicio
    from {{ ref('sales_line_batch') }}
)
select
    s.*,
    to_date('2999-12-31')             as tec_fec_fin,
    1                                 as tec_cod_vigencia,
    current_timestamp()               as tec_ts_integracion_s
from source s
{% if is_incremental() %}
left join {{ this }} t
    on  1=1
    and t.tec_cod_vigencia    = 1
where 1=1
    or t.tec_hash <> s.tec_hash
{% endif %}
